### ISSUE TITLE
[not our bug] MinIO hosted on a glusterFS is so slow. 

### ISSUE THREAD

**Issue by hosnas** [minio/minio#10169]
## Expected Behavior
It shouldt have this much impact on data transfer.

## Current Behavior

I tried to transfer a set of likely small data in 3 ways to a glusterfs server. 
1- hosted minio in a gluster shared mountpoint and transfered data with rclone. The transfer speed was 17MB/S and about 500 files per minutes.

2- Directly transfered files with rclone to a folder inside glusterfs shared mountpoint.  This way I achieved speed of 41MB/s and around 1400 files per minutes. 

3- directly transfered files with rclone to glusterfs server (this time not inside the shared mount). This way I achieved 44MB/S and about 1500 files per minutes. 

So to me, according to the test, glusterfs itself has negligible impact on transfer speed. And minio does somthing that makes the speed very much less. 

Maybe there is a special configuration that I dont know?

**Comment by harshavardhana** [comment]
GlusterFS is not recommended use direct JBODs / disks with MinIO - look at how to use a Direct drive CSI https://github.com/minio/direct-csi 

GlusterFS will be slow since it does synchronous replication and MinIO writes with O_DIRECT / sync model and we need to be crash consistent. This will make all GlusterFS optimizations turned off. 

There is nothing we can do here.
