### ISSUE TITLE
HTTPS notification setup with Elasticsearch

### ISSUE THREAD

**Issue by keelezibel** [minio/minio#10262]
## Expected Behavior

Setup of notifications with Elasticsearch using HTTP works according to the documentation [here](https://docs.min.io/docs/minio-bucket-notification-guide.html#Elasticsearch). However, we wanted to change to HTTPS instead and encounter errors.

## Current Behavior
During startup of Minio server, we ran the following command:
`minio server :<port> <ip_addresses>`

> 
> The SSL certificate is recognised for Minio side:
> Signature Algorithm SHA256-RSA
> Issuer: C=<>, ST=<>, UnknownID=<ip_address>, O=<>, CN=<server_name>
> Validity:
> Not before:
> Not after:
> 

Upon startup of the server, there is an error:
> API system()
> Time: <Time>
> DeploymentID: <ID>
> Error: Unable to initialize notification targets: unexpected scheme found
> 7: github.com\minio\minio@\cmd\config-current.go:487:cmd.lookupConfig()
> 6: github.com\minio\minio@\cmd\config-current.go:607:and.

When we tried to access Minio via the web application, another error periodically appeared on the command prompt.
> Error: http: TLS handshake error from <ip_address:port> remote error:tls : bad certificate
> 1. github.com\minio\minio@\cmd\server-main.go:459:cmd.serverMain.func2()

Also, we tried to check the configuration for the server.
`mc.exe admin config get <servername>/ `

> mc.exe: <ERROR> Cannot get help for the sub-system. Get https://<ip_address>/minio/admin/v3/help-config-kv?key=&subSys=: x509:certificate signed by unknown authority

## Possible Solution
1. Is it misconfigured SSL certs? 
2. Is the error due to certificate signed by unknown authority? How do we ask Minio to accept the CA?
3. Configuration values for the server is wrong?

## Context
We are trying to setup with HTTPS connection between Minio and Elasticsearch for Minio to publish notifications to Elasticsearch.

## Regression
No 

## Your Environment

* Version used (`minio --version`): 2020-06-26T19-56-55Z
* Server setup and configuration: Windows Server 2016 VMs. We have two seperate VMs hosting Minio with Elasticsearch running in one of the VMs.
* Operating System and version: Windows Server 2016

**Comment by Praveenrajmani** [comment]
@keelezibel SSL support is not yet implemented for Elastic search targets. Will be sending a PR adding this.

**Comment by keelezibel** [comment]
@Praveenrajmani do we have a timeline for the implementation? What's the reason for not being able to support SSL? Is there any workaround we can try?

Thanks

**Comment by Praveenrajmani** [comment]
> @Praveenrajmani do we have a timeline for the implementation? What's the reason for not being able to support SSL? Is there any workaround we can try?
> 
> Thanks

I will be sending a PR within 2/3 days @keelezibel

**Comment by mshankr** [comment]
@harshavardhana @Praveenrajmani We updated to the fixed Minio version RELEASE.2020-08-26T00-00-49Z, but still faced the same error 😢 

## Current Behaviour

During startup of Minio server, we ran the following command:
`minio server :<port> <ip_addresses>`

```
API system()
Time:
DeploymentID:
Error: Unable to initialize notification target(s): unexpected scheme found
7: cmd\config-current.go:494:cmd.lookupConfig()
6: cmd\config-current.go:606:cmd.loadConfig()
5: cmd\config.go:233:cmd.initConfig()
4: cmd\config.go:193:cmd.(*ConfigSys).Init()
3: cmd\server-main.go:341:cmd.initAllSubsystems()
2: cmd\server-main.go:266:cmd.initSafeMode()
1: cmd\server-main.go:526:cmd.serverMain()
```

## Possible Solution
Is it misconfigured SSL certs?
Is the error due to certificate signed by unknown authority? How do we ask Minio to accept the CA?
Configuration values for the server is wrong?

## Context
We are trying to setup with HTTPS connection between Minio and Elasticsearch for Minio to publish notifications to Elasticsearch.

We have followed the steps in #10332 :

- Start elasticsearch with SSL enabled.
- Put ES ca.cert in ~/.minio/certs/CAs in both VMs hosting Minio.
- Set elasticsearch config
`mc admin config set <instance_name> notify_elasticsearch ... url="https://<ES_username>:<ES_password>@<ES_ip_address>:<ES_port>"`
ref: https://docs.min.io/docs/minio-bucket-notification-guide.html#Elasticsearch

## Regression
No

## Your Environment
Version used (`minio --version`):  RELEASE.2020-08-26T00-00-49Z
Server setup and configuration: Windows Server 2016 VMs. We have two seperate VMs hosting Minio with Elasticsearch running in one of the VMs.
Operating System and version: Windows Server 2016

**Comment by Praveenrajmani** [comment]
>  Unable to initialize notification target

I just tried it locally here with the same version `RELEASE.2020-08-26T00-00-49Z`. It worked fine.

```
➜  mc git:(master) ✗ ./mc admin config set myminio/ notify_elasticsearch:1 url="https://<username>:<pass>@node1.elastic.test.com:9200" index="minio_events"
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio/`.

➜  mc git:(master) ✗ ./mc admin service restart myminio
Restart command successfully sent to `myminio`.
Restarted `myminio` successfully.

```
The error reported is because of an invalid URL being set. Can you fix your setup and retry.

And also two things i have to point out here 

- The config setting `mc admin config set <instance_name> notify_elasticsearch ... url="https://<ES_username>:<ES_password>@<ES_ip_address>:<ES_port>` is wrong, You have to use the domain name here instead of the ip address. 
The ca.crt that you place in ~/.minio/certs/CAs should be for the corresponding domain name. 
- Make sure you restart the server after placing the certs in ~/.minio/certs/CAs

You can check the health of the ES cluster through curl. Eg, `curl --cacert <ca_cert_path> -u <username> 'https://node1.elastic.test.com:9200/_cat/nodes?v'`

You can follow the documentation here - https://www.elastic.co/blog/configuring-ssl-tls-and-https-to-secure-elasticsearch-kibana-beats-and-logstash which worked for me.

**Comment by mshankr** [comment]
@Praveenrajmani You're right, I'm able to connect HTTPS Minio-HTTPS ES now! Thank you so much !: :blush:
