### ISSUE TITLE
AWS S3 SDK Incompatibilities

### ISSUE THREAD

**Issue by notnoopci** [minio/minio#1059]
I'm having a tough time with using AWS S3 Java SDK against minio server, particularly around object metadata and presigned urls.  I created a sample project with some unit tests exposing the issues I've seen: https://github.com/notnoopci/minio-java-test/blob/master/src/test/java/MinioTest.java  .  What can I do to fix them?

You can see the failures in CircleCI builds, e.g. https://circleci.com/gh/notnoopci/minio-java-test/4 with test reports being https://circle-artifacts.com/gh/notnoopci/minio-java-test/4/artifacts/0/tmp/circle-artifacts.ps0AHnx/index.html .

I also tried against HEAD without much luck.

**Comment by harshavardhana** [comment]
> I'm having a tough time with using AWS S3 Java SDK against minio server, particularly around object metadata and presigned urls. I created a sample project with some unit tests exposing the issues I've seen: https://github.com/notnoopci/minio-java-test/blob/master/src/test/java/MinioTest.java . What can I do to fix them?

@notnoopci - looks like presigned URLs generated by AWS Java SDK are a little different. 

https://circle-artifacts.com/gh/notnoopci/minio-java-test/4/artifacts/0/tmp/circle-artifacts.ps0AHnx/classes/MinioTest.html#uploadWithCurlWorks

https://circle-artifacts.com/gh/notnoopci/minio-java-test/4/artifacts/0/tmp/circle-artifacts.ps0AHnx/classes/MinioTest.html#authenticatedURLWorks

https://circle-artifacts.com/gh/notnoopci/minio-java-test/4/artifacts/0/tmp/circle-artifacts.ps0AHnx/classes/MinioTest.html#getWorks - this is limitation right now since the server does not remember the 'content-type' that was set since there is no metadata saved on the server side, we are introducing a transparent translation for this so that the content-Type is set automatically based on the extension. 

I will test them locally, i will keep you updated - thanks for testing minio server.

**Comment by harshavardhana** [comment]
From what i can see 

Minio libraries are generating URL of this form

`http://localhost:9000/asdf/authenticatedURLWorksTest?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=WLGDGYAQYIGI833EV05A%2F20160128%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160128T193943Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=3af801aee4e49090360864c7c630c2fd26cf9688f589fe04a7f6e66cf184f459`

AWS SDK of this form.
`http://localhost:9000/asdf/authenticatedURLWorksTest?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20160128T193826Z&X-Amz-SignedHeaders=host&X-Amz-Expires=420&X-Amz-Credential=WLGDGYAQYIGI833EV05A%2F20160128%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=6acf162adaf92458be582da07b33e486fa95727498f2ab6977d481aa2abf7ee5`

The only difference is order of query params.

**Comment by harshavardhana** [comment]
> The only difference is order of query params.

This would lead to signature mismatch error, fixing it.

**Comment by notnoopci** [comment]
Thanks for looking into this!

> this is limitation right now since the server does not remember the 'content-type' that was set since there is no metadata saved on the server side

Any pointers for known limitations?  I'd be happy to contribute to get metadata and user-defined metadata as well.  A PR next week is coming up :).

**Comment by harshavardhana** [comment]
> Any pointers for known limitations? I'd be happy to contribute to get metadata and user-defined metadata as well. A PR next week is coming up :).

We haven't documented few things which we should, i will write a comprehensive markdown on incompatibilities or basically omitted features. 

We need to decide on where to put this metadata since it has to be a portable implementation to work even on windows. Additionally object metadata can grow big so we need to be careful about that as well :-).

**Comment by harshavardhana** [comment]
> A PR next week is coming up :).

This would be great!
