### ISSUE TITLE
Default Healtcheck missing in Dockerfile(s)

### ISSUE THREAD

**Issue by vanthome** [minio/minio#11040]
In this ticket https://github.com/minio/minio/issues/3800 a default healthcheck was proposed and obviously implemented but as of now I cannot see such a healthcheck in the Dockerfiles.

Thanks

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/tree/master/docs/metrics/healthcheck

**Comment by vanthome** [comment]
This allows one to implement health checks, I understand that but why are they not used in the default docker images using the `HEALTCHECK` statement https://docs.docker.com/engine/reference/builder/#healthcheck.

**Comment by harshavardhana** [comment]
> This allows one to implement health checks, I understand that but why are they not used in the default docker images using the `HEALTCHECK` statement https://docs.docker.com/engine/reference/builder/#healthcheck.

Because we don't want it to be default behavior. These healthchecks we have seen are quite bogus for us in practice and deployments - come in the way of our startup scripts and at the more mere annoyance since the lack is extensibility to provide context to the entity checking for health of a system.
