### ISSUE TITLE
Disk space usage for small files

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#11101]
### Context

We use a MinIO federation for each environment (dev and prod), 3 clusters of 3 MinIO nodes.

### Problem

The disk space usage varies **A LOT** depending on the file size and thus we cannot predict how much we can still upload.
This is a big issue for production.

### Benchmark
We made a benchmark about disk space usage in relation to the size of the file:

To get the disk usage of a file (193 KB in this example), inside a MinIO node run:

```
du -scb data{0..3}/{bucket}

34090	data0/{bucket}/{file}
34090	data1/{bucket}/{file}
34090	data2/{bucket}/{file}
34090	data3/{bucket}/{file}
136360	total
```

In this example the file takes **136,36 KB** on one MinIO.

Since we have 3 MinIO nodes / cluster and each object is replicated in every nodes, we multiply it by **3**.
So the total disk usage of the file **409,08 KB**.

Usage factor: 409,08 (disk storage) / 193 (file size) = **2.119** 

I tested with different file size:

**Object size** | **Disk usage** | **Usage factor**
--- | --- | -- |
1 B | 5,17 KB | **5170**
101 B | 5,2 KB | **51,485**
256 B | 5,7 KB | **22,265**
29 KB | 144 KB | **4,965**
38 KB | 83 KB | **2,184**
47,5 KB | 102 KB | **2,147**
92 KB | 195 KB | **2,119**
194 KB | 408 KB | **2,103**
461,3 KB | 945 KB | **2,048**
1,89 MB | 3,96 MB | **2,098**
13,82 MB | 31 MB | **2,248**
1 GB | 2,13 GB | **2,13**

### Conclusion

File sizes beyond 50 KB begin to have ~2,1 usage factor. It gets closer and closer to 2x and disappear into fractions for higher file sizes.

The usage factor varies a lot depending on users' files size. We cannot predict precisely how much we can upload to our storage even if we know the remaining disk space. This is a big issue for production.

An user can upload 10 files but depending on their size we have a completely different disk usage factor.

### Solution

Reduce the disk usage factor for small files.

### Related Issue

https://github.com/minio/minio/issues/7395

Thanks.

**Comment by klauspost** [comment]
@ToLToL For small files the metadata and FS block will take up the bulk of the space.

Metadata is placed on every disk for fault tolerance. For a 1 byte file that takes about 300 bytes, more if the data is encrypted. The actual size isn't that important since your FS will probably allocate a bigger block anyway.

Each part of the file is 33 bytes on disk. 32 bytes are bitrot protection. Encryption will add  a similar amount. Not important since it will take a block, usually 4KiB anyway.

This fixed overhead will decrease percentage-wise as you increase the payload size.

Instead of thinking of thinking of it in terms of percentages of the input size, consider the number of blocks it uses. Until you reach `4KiB * data-drives` they will take 2 blocks per disk. One for metadata and one for payload divided across data disks.

You specify `-b` to ignore the block size. Use `-B` with your FS block size instead.

**Comment by klauspost** [comment]
For reference, the metadata contains 

* combined size, 
* modified date.
* erasure distribution
* `content-type`.
* etag
* Parts (if multipart)
* Directory with data.
* Bitrot algoithm to verify.

... for each version of your object.

**Comment by harshavardhana** [comment]
Closing this issue

**Comment by ToLToL** [comment]
@klauspost Thanks for your reply.

How can I predict how much storage I can really store when some files took up to 5200x their real size ?

**Comment by klauspost** [comment]
@ToLToL See my post above, it has the information.  If you need more help than that take a look at out professional support services: https://min.io/pricing
