### ISSUE TITLE
S3 gateway - Backblaze b2

### ISSUE THREAD

**Issue by dragon2611** [minio/minio#11172]
Is the S3 gateway mode currently broken with backblaze B2?

## Expected Behavior
Upload/Download Files

## Current Behavior
Files upload, but downloading doesn't seem to work, Nextcloud returns 0 byte files, minio browser returns error

ERR_INVALID_RESPONSE

Also Seafile cannot access it's repository files, at first I thought there was something wrong with the cache/ or I'd corrupted the repo, in the case of seafile the errors are 412 at least one of the pre-conditions you specified did not hold (Different instance and different bucket)

## Context
Cannot download files

## Regression
Yes 

## Your Environment
minio version RELEASE.2020-12-26T01-35-54Z

**Comment by dragon2611** [comment]
I walked back through the docker tags it seems RELEASE.2020-12-16T05-05-17Z is the latest version that works in S3 gateway mode with Backblaze.

**Comment by harshavardhana** [comment]
This is most probably because B2 S3 implementation doesn't honor etags properly as expected.

Our S3 gateway works with AWS S3 and MinIO so nothing actionable at the moment on our end.

If you figure out a fix please do send us a patch, but we don't have access to B2 and no current needs to fix any incompatibly that may come with their S3 implementation.

So closing the issue.
