### ISSUE TITLE
incorrect errors reported from toObjectErr: ObjectExistsAsDirectory / ObjectNotFound

### ISSUE THREAD

**Issue by OriHoch** [minio/minio#11479]
I encountered a couple of cases where the errors reported from [toObjectErr](https://github.com/minio/minio/blob/master/cmd/object-api-errors.go#L31) are incorrect.

These cases occured when using nas gateway with an underlying storage system under stress conditions.

These are the relevant codes:

```
	case errIsNotRegular:
		if len(params) >= 2 {
			err = ObjectExistsAsDirectory{
				Bucket: params[0],
				Object: params[1],
			}
		}
```

```
	case errFileNotFound:
		switch len(params) {
		case 2:
			err = ObjectNotFound{
				Bucket: params[0],
				Object: params[1],
			}
```

## Expected Behavior
* error is `errIsNotRegular` / `errFileNotFound` - report the storage error message as-is, adding a message indicating the possible cause (object exist as a directory / object not found)

## Current Behavior
* error is `errIsNotRegular` / `errFileNotFound` - reported as object exist as a directory / object is not found, but this is not the case, in my investigation I found the root cause was due to underlying storage being under stress conditions
* errIsNotRegular - caused by invalid response from filesystem
* errFileNotFound - caused by rename operation in fs-v1-helpers during putObject

## Possible Solution
While I understand that minio shouldn't have to work correctly when underlying storage system has problems, I expect the errors reported to be indicative of the actual error to help in debugging and understanding the cause of the problems. 

## Steps to Reproduce (for bugs)
While it may be hard to reproduce the exact conditions I encountered, I suspect it should be easy to fake such error conditions (create a "not regular" file / delete an underlying file)

## Context
Running minio nas gateway with a specific underlying storage under stress conditions, and wanting to understand the root cause of errors from minio.

## Regression
No

## Your Environment
* Recent minio version (from 2021)
* Linux / NFS / Ceph

**Comment by harshavardhana** [comment]
> While I understand that minio shouldn't have to work correctly when underlying storage system has problems, I expect the errors reported to be indicative of the actual error to help in debugging and understanding the cause of the problems.

We are returning what underlying code is returning `errIsNotRegular` means the underlying type of the file has changed from being a regular file type to something expected at that location.

**Comment by harshavardhana** [comment]
MinIO NAS gateway requires `fcntl` lock support on the backend NAS if backend NAS doesn't support fcntl POSIX locks here NAS Gateway will not function correctly.

**Comment by OriHoch** [comment]
thanks, perhaps my error report was not clear enough

the problem is with the error reported to end-user:

* `An error occurred (NoSuchKey) when calling the PutObject operation: The specified key does not exist.`
* `An error occurred (XMinioObjectExistsAsDirectory) when calling the PutObject operation: Object name already exists as a directory.`

in these cases the error messages are incorrect and they are not the actual errors

**Comment by harshavardhana** [comment]
> * `An error occurred (NoSuchKey) when calling the PutObject operation: The specified key does not exist.`

This is happening because of underlying storage returns `NoSuchKey` for some files that we expect to exist in the entirety of PutObject such as `fs.json` - where we hold the locks. NFSv3 especially is known to return ESTALE (such as invalid file handle errors) - this is because of the wonky NFSv3 dentry caching logic.  The only improvement in this area is seen with NFSv4 implementation. 

> * `An error occurred (XMinioObjectExistsAsDirectory) when calling the PutObject operation: Object name already exists as a directory.`

This is perhaps another remnant of the same problem - unfortunately we can't really do anything on our end. NFS backends are notorious for throwing these errors. The protocol itself is not well designed for concurrent I/O so if you have stressed your backend then it would be misbehaving. 

MinIO is simply relying on filesystem operations such as POSIX operations to succeed the way we expect, if the underlying system returns an error we simply translate that and return it to the end-user.  There may be situations we can patch things to circumvent underlying shortcomings of the POSIX API but we can only go so far.

**Comment by OriHoch** [comment]
thanks!

**Comment by harshavardhana** [comment]
> thanks!

If you have the choice use NFSv4 instead of NFSv3 (in case you are using NFSv3 right now) and it shall handle the concurrency well.

**Comment by OriHoch** [comment]
thanks, we are using NFSv4 but have some complex storage and usage which probably complicates it
