### ISSUE TITLE
http: TLS handshake error

### ISSUE THREAD

**Issue by zapto2600** [minio/minio#11815]
We are seeing a high volume of errors in the logs that are masking other issues. 

http: TLS handshake error from 10.*.*.*:41212: write tcp 10.*.*.*:443->10.*.*.*:41212: write: broken pipe

This is repeated for all IP's within the cluster. 

## Expected Behavior
More verbose error pointing to where the issue is. 

## Current Behavior
Log spew. 

## Context

We followed the MinIO Docs to implement the TLS. 
All Certs are correct 
NTP is running on all servers and time is in-sync.

## Your Environment
* Version used 2021-03-12T00:00:47Z
* Operating System: 4.15.0-129-generic

**Comment by klauspost** [comment]
Upstream closes the connection, we don't know more than that. If you need more detailed assistance look into our [subscription options](https://min.io/pricing).

**Comment by zapto2600** [comment]
The "upstream" is being closed by the other MinIO nodes as per thread. Not an upstream application.

**Comment by klauspost** [comment]
@zapto2600 If it is inter-server connections that are producing this error something is definitely fishy in the setup. These should rarely, if ever, happen.

You should check your network setup and investigate for packet loss or other problems. Maybe do TCP captures and see if you can identify the problems.

**Comment by csbarry** [comment]
@klauspost It seems that these errors only ramp up during a healing process where the nodes communicate to each other, is there a way of putting minio into debug mode so that we can look at more information?.
Networking looks fine, we've done some tcpdump and there are no packet drops, all minio servers are on the same vlan so theres no firewall issues.
