### ISSUE TITLE
Vulnerability warning for unmaintained module "github.com/dgrijalva/jwt-go v3.2.0+incompatible"

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#11836]
I noticed there is a vulnerability warning for `github.com/dgrijalva/jwt-go v3.2.0+incompatible` module.

![Selection_038](https://user-images.githubusercontent.com/24552332/111760842-68b51a00-885c-11eb-919e-247fec52e09f.jpg)

It needs to be upgraded or replaced.

There is a communication about this subject and what can be done at `https://github.com/datawire/ambassador/issues/3122` with some advices:
```
1. Upgrade to github.com/square/go-jose, since dgrijalva/jwt-go seems to be unmaintained.
2. Upgrade to github.com/dgrijalva/jwt-go 4.0.0-preview1. The breaking changes you mentioned were negligible for us. I remember just having to change jwt.StandardClaims#IssuedAt from int to jwtgo.Time.
3. Upgrade to github.com/form3tech-oss/jwt-go v3.2.2 which is supposed to be a fork to just address the CVE while you work on one of the other two fixes.
```

**Comment by harshavardhana** [comment]
Moved to server since this is a server dependency issue

**Comment by harshavardhana** [comment]
Okay so I looked at it, it's not a vulnerability that we are worried about. 

Since we handle the validation part of audience manually as a custom code that circumvents the bugs in jwt-go library - so we have no reason to move to another dependency.

So we are good - this is a harmless warning we can ignore.
