### ISSUE TITLE
Readiness should take IAM initialization into account

### ISSUE THREAD

**Issue by sgandon** [minio/minio#11862]
## Expected Behavior

1/ When starting Minio with many user/policies, all of those are loaded at startup and some API like listing users or policies are not usable during that phase.
So the readiness endpoint should not report OK in that case and report an error.
2/ The readiness api does not return an error code but a special header (x-minio-server-status: unavailable). In Kuberentes it is not possible to create a readiness probe on an header value, it is expecting return code in a 200-400 range for success.

## Current Behavior
1/ The readiness api ( /minio/health/ready ) returns OK even when the IAM initialization phase is not over.
2/ it returns an error header when not ready instead of a error code not compatible with K8s

## Possible Solution

1/ update the readiness probe implementation to check on the `sys.configLoaded` channel to see if the IAM has finished it's intialization phase
2/ return a `StatusServiceUnavailable` if the initialization has not finished.

## Steps to Reproduce (for bugs)
1/ create 1000 users 
2/ start minio
3/ curl -v http://localhost:9000/minio/health/ready <- should not return a 200 while initializing

**Comment by klauspost** [comment]
What do you mean "some API like listing users or policies are not usable during that phase."?

 Aren't they simply blocking until the data is available?

**Comment by sgandon** [comment]
indeed it is blocking until data is available (although I don't know the timeout).
Do you consider those API still usable even in a blocking mode ?

**Comment by klauspost** [comment]
@sgandon There are no timeouts unless you configured them or set them on the client.

Yes, APIs are usable as long as they return a reply.  You never have any guarantees about how fast.

**Comment by sgandon** [comment]
@klauspost you are right and my first point is not legitimate for updating the readiness probe.
What do you think about the second point ?

**Comment by harshavardhana** [comment]
There is no way for us to do this - readiness in k8s parlance is poorly thought out and can lead to catch-22 like scenarios where networking is turned off while the server is booting up etc.

We specifically didn't want k8s to see failure and turn-off networking to pods due to failure in readiness probes. The current design is what is expected as we cannot easily co-existing with k8s readiness requirements. 

You are only looking at this from a gateway point of view @sgandon but our primary requirement is to satisfy scale-out - distributed setups

Anything specific to a gateway and its future work will go here https://github.com/minio/ming - closing this issue.

**Comment by sgandon** [comment]
Indeed readiness probe can be challenging to setup and may not be appropriate if you cannot know the responsivness status of your pod at runtime. 
But for doing rolling upgrade you need to have your pod not taking any request if they are not "ready" and for this the *startup probe* would be more appropriate and was build for this purpose.
I believe that Minio should offer such a probe to make sure the initialization phase is over (not talking about IAM initialization here but the **globalObjectAPI** object set).
