### ISSUE TITLE
Please clarify licensing on website

### ISSUE THREAD

**Issue by candlerb** [minio/minio#11886]
**Is your feature request related to a problem? Please describe.**
It's unclear from reading the website what license(s) MinIO may be used under.

* The [pricing](https://min.io/pricing) page mentions only AGPLv3 for the Community edition in the comparison table:
    ![image](https://user-images.githubusercontent.com/44789/112348534-d4194480-8cbf-11eb-9a98-7ed66bea3838.png)
* Lower in the page it says "Our entire software stack is licensed under two Open Source licenses, the Apache License Version 2 and the Affero General Public License Version 3 (AGPLv3)"
    ![image](https://user-images.githubusercontent.com/44789/112348757-07f46a00-8cc0-11eb-92d8-5c86ec8ca3e0.png)
    "To understand more, we recommend visiting our Compliance Page."
* The [compliance](https://min.io/compliance) page refers *only* to AGPLv3.  No mention of Apache 2 at all.  Lower down that page, it says that to comply with FOSS, you *must* comply with AGPLv3 terms.
    ![image](https://user-images.githubusercontent.com/44789/112348580-dda2ac80-8cbf-11eb-8110-ed1e933c8a69.png)
* The [LICENSE](https://github.com/minio/minio/blob/master/LICENSE) file in the minio/minio source repo, master branch, is Apache 2 (only).  None of the source files mention (A)GPL.
* The [LICENSE](https://github.com/minio/operator/blob/master/LICENSE) file in the minio/operator repository is AGPLv3 (only), and was last changed on [7 Oct 2019](https://github.com/minio/operator/commit/bdea7aa7032fdbb09f6327086fc52f39a508be5f).

**Describe the solution you'd like**
A clear and consistent description of the license terms of minio.

If it's the case that some parts are Apache 2 and other parts are AGPLv3, then please make this clear.  For example, you could change

"Our entire software stack is licensed under two Open Source licenses, the Apache License Version 2 and the Affero General Public License Version 3 (AGPLv3)"

to:

"Our entire software stack is licensed under two Open Source licenses: some parts are under the Apache License Version 2 and other parts under the Affero General Public License Version 3 (AGPLv3)"

Otherwise it could be read that the *entire* stack is licensed under *both* licenses.

Similarly, update the pricing table to say "Apache 2 (minio server); AGPLv3 (minio operator)" - or whatever is the case.

**Describe alternatives you've considered**
N/A

**Additional context**
Investigation triggered from [this medium post](https://wubaoqi.medium.com/be-warned-minio-popular-open-source-object-storage-may-change-its-license-from-apache-to-agpl-1856b0a29845).

I came back to the minio pricing and compliance pages to get an authoritative answer, and was surprised not to find it there.

**Comment by collimarco** [comment]
Yes, the writing on their website is misleading... Why AGPL? 

This Github repo is clearly under the more permissive Apache license.

**Comment by harshavardhana** [comment]
> Yes, the writing on their website is misleading... Why AGPL?

## Not a legal advice

MinIO is 100% open-source and released under the FOSS licenses.  MinIO for multi-tenancy which is based on K8s operator is available under AGPL along with other services like sidekick (sidecar load-balancer), Key management store to manage your encrypted objects (kes), etc. 

MinIO server for bare-metal or single-tenant is released under Apache v2.0. 

AGPLv3 is used by all our new projects, even gateway is moving away from MinIO core and moving https://github.com/minio/ming .

The website talks about licenses for projects you may end up using primarily during a production deployment.  You should always seek a lawyer to clarify your usage and make sure to avoid any violation of licensing terms when using these projects. 

MinIO umbrella is not just one project it is a collection of all these projects. https://min.io simply expands and guides the users correctly to avoid such violations so AGPLv3 is listed predominantly on the website. 

We are bringing some more clarification on the website this shall roll out soon, will close this issue since this not related to this project. 

PS: @colinmarco it's not misleading - please seek legal advice to avoid any AGPL violations.
