### ISSUE TITLE
Verify Distributed Erasure Coding Setup

### ISSUE THREAD

**Issue by champds** [minio/minio#11954]
**Is your feature request related to a problem? Please describe.**
When setting up a new instance, we were playing around with different syntax for various nodes (eg, they were non-incrementing hostnames, etc).  So we did not use the ellipses notation.  There were three hosts with two disks each.

Of course this was due to incorrect syntax on our part, but we had no indication that the erasure coding was not optimal until we tried our read operation(s).  

Write operations showed correct distributed network activity, but read operations only showed activity on two of the hosts.   When we consulted the JSON output from `mc admin info minio --json` we noted no material difference in the two setups.

That is, everything "looked fine" from a configuration standpoint.

**Describe the solution you'd like**
Did we miss something in the --json output, or is there another way to determine the distribution in the erasure set?  

**Describe alternatives you've considered**
Simply doing a read and write operation while watching traffic would suffice for initial verification.  However it would be interesting if there were a way to get the data from the system as it "sees" it.  

**Additional context**
Here's a cap from grafana illustrating the bandwidth as observed:
https://d.pr/i/grVQI7
First is the write (seems all good), then on read (from GV4) only two participants.

Thanks for the consideration and/or any help here!

**Comment by harshavardhana** [comment]
> Of course this was due to incorrect syntax on our part, but we had no indication that the erasure coding was not optimal until we tried our read operation(s).

Architecture advise is kept for paying customers, software by itself tries to warn you on the console if the setup is suboptimal to an extent but it's not possible beyond certain limits to automatically guide users and we have no way of knowing. As sometimes it's intentional to use it certain way.

In such a scenario if this a production setup or planning to go production you are advised to get a subscription from us where we provide reviews on a regular basis.

https://min.io/pricing

**Comment by champds** [comment]
@harshavardhana thanks again for the help.  

Makes sense - thanks for the clarification.
