### ISSUE TITLE
SSE-C not working in gateway mode

### ISSUE THREAD

**Issue by uhinze** [minio/minio#12177]
SSE-C does not seem to be working in gateway mode if the gateway backend does not support SSE-C.

If I read the docs at https://docs.min.io/docs/minio-gateway-for-s3.html correctly, SSE-C is never in pass-through mode, but will always be processed in the gateway. 

## Expected Behavior
PutObject operations with an SSE-C key should successful.

## Current Behavior
```
mc cp --insecure --encrypt-key "minios/mybucket=AdAZlxRL4NARRBGPyYC2SpXUAwjHeIfMAC8Y6Cf+uMI="  testencryption.txt minios/mybucket
mc: <ERROR> Failed to copy `testencryption.txt`. A header you provided implies functionality that is not implemented
```

## Steps to Reproduce (for bugs)

1. Set up a backend without SSE-C enabled (e.g. an old Minio version?)
2. Start gateway
3. Put files to the gateway with SSE-C key

## Context
I'm using Minio as a gateway because the service I need to use does not offer some important things...e.g. user management (which works fine with the gateway now) or encryption (which unfortunately doesn't seem to work)

## Your Environment

docker tag RELEASE.2021-04-22T15-44-28Z

**Comment by ebozduman** [comment]
Reproduced the issue

**Comment by ebozduman** [comment]
Working on a higher priority task. I'll come back to this one as soon as I am done with my current task.

**Comment by llarsson** [comment]
Has there been any progress on this? 

The ability to have the gateway encrypt objects and then just store an encrypted object on some backend would be very valuable. In particular, because the [European Data Protection Board considers it a lawful transfer of personally identifiable data if one stores an encrypted backup such that the cloud provider never has access to encryption keys](https://edpb.europa.eu/our-work-tools/our-documents/recommendations/recommendations-012020-measures-supplement-transfer_en). 

If the gateway is the only component that ever sees the client encryption key and performs encryption, all that would wind up in the backend, say AWS S3, would be a bunch of indecipherable junk that the cloud provider (or authorities they are under) could not decrypt.

**Comment by klauspost** [comment]
@llarsson You should use SSE-S3 with a KMS.

Contact us via our [subscription offer](https://min.io/pricing) or write `hello@minio.io` to discuss options.

**Comment by ghost** [comment]
We have been fighting (perhaps in vain  :)  ) for few day with getting error regarding headers

minio.error.S3Error: S3 operation failed; code: InvalidArgument, message: Server Side Encryption with AWS KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms

minio.error.S3Error: S3 operation failed; code: NotImplemented, message: A header you provided implies functionality that is not implemented,

when we use the minioClient.copy_object with a Minio gateway using an s3 bucket with encryption with customer managed key and perhaps we didn't ask ourself the major question.

@klauspost  Does Minio gateway for S3 support Server-side encryption with KMS key stored in AWS Key Management Service (SSE-KMS) ?

Thanks in advance for any information you can provide.

**Comment by llarsson** [comment]
@klauspost, does what you posted to me about subscription and/or writing to the company email mean SSE-S3 with Minio cannot be done with only open source?

**Comment by harshavardhana** [comment]
> @klauspost, does what you posted to me about subscription and/or writing to the company email mean SSE-S3 with Minio cannot be done with only open source?

There are no plans to support SSE-C with S3 Gateway @llarsson - Gateway implementations are in code-freeze are not taking any more feature requests.  Our main focus is MinIO server and things around it.

**Comment by ebozduman** [comment]
Closed as `wont fix`.
