### ISSUE TITLE
ILM: make Expire inactive without working Transition

### ISSUE THREAD

**Issue by NMi-ru** [minio/minio#12392]
**Is your feature request related to a problem? Please describe.**
Minio Instance deletes files that have not been transitioned to another Tier.

Steps to reproduce:
1. Create Cluster A
2. Create Cluster B
3. Configure Cluster A with ILM to Cluster B: --transition-days 1, --expiry-days 2
4. Upload test file to Cluster A
5. Shutdown Cluster B (simulating failure)
6. Wait 3 days [error messages from Cluster A show that it is unable to execute transition of file to Cluster B]
7. See that file has been removed from Cluster A

**Describe the solution you'd like**
Ability to disable "expiry-days" for ILM if objects have not been transitioned to another tier.

**Describe alternatives you've considered**
mcli ilm edit --id c2hv26ejf3es3n9pt7h0 --disable instancename/bucketname
mcli ilm edit --id c2hv26ejf3es3n9pt7h0 --expiry-days 9999 instancename/bucketname

**Comment by krisis** [comment]
@NMi-ru per S3 API bucket lifecycle [semantics](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html#lifecycle-config-conceptual-ex5), an object with conflicting rules, i.e when both transition and expiration actions are in effect based on the lifecycle rules, expiration action applies. In the above example, transition action is delayed due to a temporary outage of the configured tier up to a point where expiration action is in effect too. In this case expiration action will prevail, as expected.

Providing an option to disable expiry rules on those objects that have failed to transition would be an S3 **API incompatible** extension.

**Comment by harshavardhana** [comment]
> @NMi-ru per S3 API bucket lifecycle [semantics](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html#lifecycle-config-conceptual-ex5), an object with conflicting rules, i.e when both transition and expiration actions are in effect based on the lifecycle rules, expiration action applies. In the above example, transition action is delayed due to a temporary outage of the configured tier up to a point where expiration action is in effect too. In this case expiration action will prevail, as expected.
> 
> Providing an option to disable expiry rules on those objects that have failed to transition would be an S3 **API incompatible** extension.

Closing as this doesn't make sense.
