### ISSUE TITLE
health check readiness on IAM initialization complete

### ISSUE THREAD

**Issue by christophemorio** [minio/minio#12404]
**Is your feature request related to a problem? Please describe.**
At startup as a Kubernetes pod, MinIO health check readiness is UP too early in process.
Later during the boot, log `IAM initialization complete` indicates boot is completely done.

**Describe the solution you'd like**
Have another health path (eg. `/minio/health/iam-ready`) that proves IAM is ready.

**Describe alternatives you've considered**
Redirect stdout to a text file, and grep for line "IAM initialization complete" as an pod exec probe.

**Additional context**
K8s HorizontalPodAutoscaler checks CPU usage as soon as the readiness is UP.
Having readiness probe UP after IAM loaded will help, as IAM is CPU intensive task and HPA triggers others undesired pods.

**Comment by harshavardhana** [comment]
There is no point in doing this @christophemorio 

- IAM is not initialized and other servers are up the request is proxied (redirected)
- If users themselves are not yet loaded they are loaded from the drives and subsequent requests serve the creds based on memory. 

We don't need to do anything special that requires another `/iam-ready`  

> **Additional context**
> K8s HorizontalPodAutoscaler checks CPU usage as soon as the readiness is UP.
> Having readiness probe UP after IAM loaded will help, as IAM is CPU intensive task and HPA triggers others undesired pods.

There is no CPU activity anymore we have moved the way we reload and initialize IAM.

**Comment by harshavardhana** [comment]
I don't think this makes sense.. if you have an actual issue please explain. 

Please reopen with a reproducer in a separate issue.

**Comment by studna** [comment]
@harshavardhana We've experienced same issue. We run minio in custom gateway mode with 15k+ buckets (keys and policies stored in etcd). During the bootstrap period minio was ready to handle connections, however it takes like 5-15 mins until IAM config is fully loaded (during this period it's not possible to access API with user keys).

Another issue we had (still have actually) is that the init sometimes fails due:
```txt
Error: Unable to initialize IAM sub-system, some users may not be available readObjectStart: 
expect { or n, but found �, error found in #1 byte of ...|��~[3Pogt�+|..., bigger context ...|��~[3Pogt�+�%�;����$�$����wX�r�� �W���?�\|... (*fmt.wrapError)
```

And since there's no IAM check in readiness handler, even partially initialized nodes were considered as healthy (only some users were able to access API). To prevent that, I've modified `ReadinessCheckHandler` so it waits until config is loaded:

```go
func ReadinessCheckHandler(w http.ResponseWriter, r *http.Request) {
	if shouldProxy() {
		// Service not initialized yet
		w.Header().Set(xhttp.MinIOServerStatus, unavailable)
	}

	// wait until config is loaded
	<-globalIAMSys.configLoaded

	writeResponse(w, http.StatusOK, nil, mimeNone)
}
```

I'm not sure if that's the correct approach, but it did the trick.
