### ISSUE TITLE
minio does not respect sgid-flag on linux filesystem

### ISSUE THREAD

**Issue by phormanns** [minio/minio#12579]
We would like to use a group quota in the Linux file system in order to
limit the memory requirements of single or multiple buckets.

For this purpose, the rights are set as follows:

drwxr-sr-x 2 minio-user group1 45056 Jun 25 12:56 bucket1
drwxr-sr-x 3 minio-user group2    19 May 16 20:45 bucket2

## Expected Behavior

We expect files to be created in the bucket "bucket1" as follows. 

-rw-r--r-- 1 minio-user group1     1948426 May 16 20:11 objectfile

## Current Behavior
Unfortunately, the "sgid" flag is not respected, the permissions are set as follows.

-rw-r--r-- 1 minio-user minio-user 1948426 May 16 20:11 objectfile

## Possible Solution
Can minio's behavior be customized or made configurable?

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2021-05-16T05-32-34Z

* Server setup and configuration:
single instance

* Operating System and version (`uname -a`):
Linux h97 4.19.0-16-amd64 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
@phormanns can you share how is the setgid/setuid set here?

**Comment by phormanns** [comment]
I do not understand your question. The setgid-flag is set as shown above:

drwxr-sr-x 2 minio-user group1 45056 Jun 25 12:56 bucket1
drwxr-sr-x 3 minio-user group2 19 May 16 20:45 bucket2

a file created by

  touch bucket1/testfile
  ls -l bucket1/testfile

-rw-r--r-- 1 minio-user group1 0 Jun 29 20:12 bucket1/testfile

But file uploaded by minio
-rw-r--r-- 1 minio-user minio-user 0 Jun 29 20:12 bucket1/file2

**Comment by harshavardhana** [comment]
> drwxr-sr-x 2 minio-user group1 45056 Jun 25 12:56 bucket1
> drwxr-sr-x 3 minio-user group2 19 May 16 20:45 bucket2

and you set this manually after the bucket was created on MinIO @phormanns ?

**Comment by harshavardhana** [comment]
also what benefit does this bring - are you trying to concurrently use the backend as well as through MinIO? . 

Because setting sgid is quite meaningless from an S3 API point of view - Unix permissions are not really how you would control access to objects and buckets.

**Comment by harshavardhana** [comment]
Okay, the main reason we cannot honor this is that we write the data first at `.minio.sys/tmp/uuid` until we rename it at EOF - once all the stream is read and saved on disk. 

We write it this way to provide strict consistency and other concurrency primitives - allows us to not leave any partial objects on the bucket, think of it like chrome writing a `<filename>.part` and then renames to `<filename>` 

We really cannot honor per-directory SGID flags since Unix permissions are not very useful internally for MinIO S3 implementation and S3 clients are also not relying on Unix permissions trying to talk to MinIO. 

It is possible to preserve setgid and setuid by making multiple additional system calls at the cost of syscall performance but this is kludgy and error-prone.  

This issue is a very niche requirement and simply increases the scope of simple implementation like we have today - don't see a good reason why we would do this inside MinIO. 

Feel free to send a patch if this is a must for you, closing this as **wontfix** on our end.

**Comment by phormanns** [comment]
> also what benefit does this bring 

Our use case: assign a linux group to each bucket to use filesystem group quota. So we would be able to assign a quota to buckets by setting the group and the sgid-bit to the bucket folder. Will there be a way to limit the size of a single bucket or better a group of buckets?

**Comment by harshavardhana** [comment]
> > also what benefit does this bring
> 
> Our use case: assign a linux group to each bucket to use filesystem group quota. So we would be able to assign a quota to buckets by setting the group and the sgid-bit to the bucket folder. Will there be a way to limit the size of a single bucket or better a group of buckets?

You can use `mc admin bucket quota`  for such scenarios.

**Comment by phormanns** [comment]
I had tried the "bucket quota" before trying to use the sgid flag as a workaround:
mc: <ERROR> Unable to get bucket quota. This 'admin' API is not   
    supported by server in 'mode-server-fs'.
Is there documentation about 'mode-server-fs' and alternatives to it?

**Comment by harshavardhana** [comment]
> I had tried the "bucket quota" before trying to use the sgid flag as a workaround:
> mc: Unable to get bucket quota. This 'admin' API is not
> supported by server in 'mode-server-fs'.
> Is there documentation about 'mode-server-fs' and alternatives to it?

You need to use erasure coded setup for bucket quota..
