### ISSUE TITLE
docs: How to use minio server as a windows service, to keep running all the time?

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1259]

**Comment by harshavardhana** [comment]
- https://github.com/kardianos/service
- https://godoc.org/golang.org/x/sys/windows/svc

**Comment by zerkms** [comment]
What is the conclusion though?

Thanks.

**Comment by harshavardhana** [comment]
> What is the conclusion though?

@zerkms here is the conclusion - https://github.com/minio/minio-service/tree/master/windows

**Comment by ghost** [comment]
Wonderful! I can see why NSSM is called as such. The first attempt and everything works. I've been trying with windows' sc for two hours doing basically the same thing and couldn't get it to start the service.

**Comment by harshavardhana** [comment]
Are you able to now ?

**Comment by ghost** [comment]
I am. Thank you very much!

**Comment by labnewbie** [comment]
@harshavardhana I followed the instructions at https://github.com/minio/minio-service/tree/master/windows and the service starts without any errors.  But when I try to access the minio server I get this:

C:\Users\administrator>mc admin service status myminio
mc: <ERROR> Cannot get service status. Get https://192.168.86.133:9000/minio/admin/v1/service: http: server gave HTTP response to HTTPS client.

I know the minio server is running since when I try to start the server from a command prompt while the service is running:

Error: [31m[1mlisten tcp :9000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.[0m[0m

If I stop the service and try to start the server from the command prompt it starts fine.

This is the info from nssm:
C:\Users\administrator>nssm dump minio
nssm install Minio C:\Minio\minio.exe
nssm set Minio AppParameters "server C:\Minio\Data"
nssm set Minio AppDirectory C:\Minio
nssm set Minio AppExit Default Restart
nssm set Minio DisplayName Minio
nssm set Minio ObjectName LocalSystem
nssm set Minio Start SERVICE_AUTO_START
nssm set Minio Type SERVICE_WIN32_OWN_PROCESS

**Comment by harshavardhana** [comment]
Well if you haven't configured TLS accessing via Https will not work.

**Comment by labnewbie** [comment]
sorry - TLS is configured and works fine when started from cli.  Its when I try to make minio a service that things go downhill.

**Comment by harshavardhana** [comment]
Yes that is a problem on Windows, it's a Go runtime issue https://github.com/minio/minio/issues/6979

**Comment by labnewbie** [comment]
Thanks.  As always, you have been a great help.  I did see that issue earlier tonight but didnt think it applied in this case.  I will stop banging my head and wait to see if this gets resolved.

Thanks again!!!
