### ISSUE TITLE
feature: Question about versioning

### ISSUE THREAD

**Issue by paulovictorv** [minio/minio#1309]
Hi, I've looked around in your website + issues and I couldn't find anything about versioning - except a comment that says that minio does not support it (yet?).

So I was wondering: do you guys have any intention on implementing versioning or is something that you're not considering?

Thanks!

**Comment by harshavardhana** [comment]
> Hi, I've looked around in your website + issues and I couldn't find anything about versioning - except a comment that says that minio does not support it (yet?).
> 
> So I was wondering: do you guys have any intention on implementing versioning or is something that you're not considering?
> 
> Thanks!

At the moment no, we haven't really charted out this one yet.  We will keep this issue here and in-time update it.

**Comment by paulovictorv** [comment]
OK, great! Thanks for the quick reply

**Comment by oddietaco** [comment]
This is something that my company would love!

**Comment by harshavardhana** [comment]
> This is something that my company would love!

Great to know.

**Comment by abperiasamy** [comment]
If we implement versioning inside the server, it comes with a price. It introduces complexity and increases the chances for failures or corruption. Complexity is inversely proportional to scalability.  It is best to keep the server design focussed on storing large quantities of data safely and reliably. Features like silent-data-corruption verification are lot more important than versioning.

Alternatively, we can implement versioning as a layered library on the client side. This layered API simply saves objects as .1, .2 and so on (of course with a proper delimiter instead of dot). From object storage point of view, this looks like an application problem.

Any thoughts?

**Comment by paulovictorv** [comment]
If I understood what you said correctly, versioning would only be supported under the official Minio client and SDK's, right?

Wouldn't that break the 's3 compatibility' claim?

**Comment by abperiasamy** [comment]
Yes you are correct @paulovictorv. It will be implemented at the SDK level. In terms of feature compatibility matrix, it will be more like **Amazon S3 supports versioning** and **Minio doesn't**.

Amazon keeps introducing new features to stay ahead of others. Minio will instead focus on minimalist design. We only need to implement what we see as a **core** functionality for object storage.  "Core" is defined as bare essential features to store and retrieve objects. 

Idea of application layer versioning is to show that "versioning" doesn't belong to the core. Saving newer objects with .1, .2 and so on (or with a timestamp suffix) is a simple idea that applications may do it themselves. I proposed to do it inside Minio library just for convenience.

**Comment by GarimaKapoor** [comment]
Follow recommendations as described above or you may look at [s3git project](https://github.com/s3git/s3git). It also has language bindings in addition to CLI.

**Comment by paulovictorv** [comment]
Would you be accepting pull requests that implemented this functionality?
