### ISSUE TITLE
Server-side bucket replication needs some permission that's not obvious

### ISSUE THREAD

**Issue by Olliferdl** [minio/minio#13105]
When putting files with a restricted policy, replication metadata will not be set and replication won't work. There are no errors reported in the trace or logs

## Expected Behavior
Replication should work even when putting with restricted permissions

## Current Behavior
The put looks successful, but the replication doesn't happen and the metafield will be missing

## Possible Solution
Make it clear, which permissions are needed to put objects when using replication or fix needing it in the first place

## Steps to Reproduce (for bugs)
setup synchronous remote bucket,
setup replication with --replicate "existing-objects,delete-marker,delete"
use following policy to put an object:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAME"
            ]
        }
    ]
}`

run mc stat on the object and note the version's missing "Replication Status" Metafield

use following policy to put (consoleAdmin default):
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}`
run mc stat on the object and note the new version with existing "Replication Status" Metafield

## Your Environment
minio version: RELEASE.2021-08-25T00-41-18Z

Server setup and configuration: 2 Clusters, 4 Nodes, 4 Disks per Node, Encryption enabled
Operating System and version (uname -a): Linux ***** 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

**Comment by poornas** [comment]
you are missing "s3:GetReplicationConfiguration" in your policy.

**Comment by harshavardhana** [comment]
Very evidently documented as well https://github.com/minio/minio/tree/master/docs/bucket/replication#how-to-use 

> The user running the above command needs s3:GetReplicationConfiguration and s3:GetBucketVersioning permission on the source cluster. We do not recommend running root credentials/super admin with replication, instead create a dedicated user. The access credentials used at the destination requires s3:ReplicateObject permission.

**Comment by Olliferdl** [comment]
I'm aware of the permissions the admin user needs for setting up the replication config. I'm talking about the user doing the actual putObject. Did you even read my report?

**Comment by Olliferdl** [comment]
@poornas was right though, if the user that puts the object has the s3:GetReplicationConfiguration too it will replicate. Still, this can't be intended and it's not documented either.

**Comment by harshavardhana** [comment]
> Very evidently documented as well https://github.com/minio/minio/tree/master/docs/bucket/replication#how-to-use
> 
> > The user running the above command needs s3:GetReplicationConfiguration and s3:GetBucketVersioning permission on the source cluster. We do not recommend running root credentials/super admin with replication, instead create a dedicated user. The access credentials used at the destination requires s3:ReplicateObject permission.

@Olliferdl documented here.

**Comment by klauspost** [comment]
@harshavardhana It seems to me @Olliferdl is talking about the user *uploading* an object, not the user creating the replication config.

**Comment by Olliferdl** [comment]
@klauspost yes exactly

**Comment by ravindk89** [comment]
@Olliferdl I'll try to reproduce today. If I can, we can re-open this.

**Comment by ravindk89** [comment]
@Olliferdl so I could reproduce the missing metadata, but I think this is intentional. Adding the `s3:GetReplicationConfiguration` permission to the user allowed me to retrieve the metadata as expected.

I could not, however, reproduce the replication failure. It would be very unusual for the client-side policy to have any affect on the server-side replication. Server-side replication requires its own set of users/policies. 

For reference, my test environment:

1) VirtualBox VM running Ubuntu 20, 1 node x 4 drives (`minioalpha`) running `RELEASE-2021-08-31T05:46:54Z`
2) VirtualBox VM running Ubuntu 20, 1 node x 4 drives (`miniobaker`) running `RELEASE-2021-08-31T05:46:54Z`
3) Local machine running Archlinux, connecting via `mc` `RELEASE.2021-07-27T06-46-19Z`

1) I followed our [Active-Passive](https://docs.min.io/minio/baremetal/replication/enable-server-side-one-way-bucket-replication.html) tutorial to set up replication between two MinIO clusters

2) I created a new user that used the policy you created

3) I copied a 500MB file to my "alpha" cluster. The file successfully replicated to my "baker" cluster. 

```sh
[mc-RELEASE.2021-07-27T06-46-19Z]$ ./mc stat repltest/data/yellow_tripdata_2020-01.csv
Name      : yellow_tripdata_2020-01.csv
Date      : 2021-09-02 09:50:26 EDT 
Size      : 566 MiB 
ETag      : b89e7be354be97ef2a9e17ca11d50f49-36 
VersionID : 163b5a73-8705-4e44-a465-f95fd413aca2 
Type      : file 
Metadata  :
  Content-Type: text/csv 


[mc-RELEASE.2021-07-27T06-46-19Z]$ ./mc stat minioalpha/data/yellow_tripdata_2020-01.csv
Name      : yellow_tripdata_2020-01.csv
Date      : 2021-09-02 09:50:26 EDT 
Size      : 566 MiB 
ETag      : b89e7be354be97ef2a9e17ca11d50f49-36 
VersionID : 163b5a73-8705-4e44-a465-f95fd413aca2 
Type      : file 
Metadata  :
  Content-Type: text/csv 
Replication Status: COMPLETED 


[mc-RELEASE.2021-07-27T06-46-19Z]$ ./mc stat miniobaker/data/yellow_tripdata_2020-01.csv
Name      : yellow_tripdata_2020-01.csv
Date      : 2021-09-02 09:50:26 EDT 
Size      : 566 MiB 
ETag      : b89e7be354be97ef2a9e17ca11d50f49-36 
VersionID : 163b5a73-8705-4e44-a465-f95fd413aca2 
Type      : file 
Metadata  :
  Content-Type: text/csv 
Replication Status: REPLICA 
```

From my local testing, everything documented in our tutorials works correctly. I would venture the problem is either:

1) An intermittent network issue causing replication to fail or lag, *or*
2) A problem with your server-side replication config

We have [documentation](https://docs.min.io/minio/baremetal/replication/enable-server-side-one-way-bucket-replication.html#required-permissions) on the explicit permission list for server-side replication.

As it stands, this issue should remain closed unless we can get specific reproduction steps (i.e. from a set of clean MinIO deployments).

**Comment by Olliferdl** [comment]
It will not be replicated synchronously in my case. I just tested it again.
A new file just wouldn't exist on the target bucket if the uploading user didn't have the permission. When i upload with the permission, the file appears on the target almost instantly.
Is it possible it was replicated later on because it was picked up by the "existing-objects" option?

**Comment by Olliferdl** [comment]
To make it clear, my replication works fine, everything is good as soon as the uploading user has the "s3:GetReplicationConfiguration" permission.
When the uploading user doesn't have this permission, synchronous replication won't work. It will work eventually, i guess, because some worker will pick up the file later on, because the existing-objects option is set in the replication rule.

**Comment by ravindk89** [comment]
@Olliferdl so I did notice some odd behavior, but it doesn't have anything to do with the client user permissions:

1) Create the remote w/ sync:

```
mc admin bucket remote add minioalpharepl/data http://replicationRemoteUser:replicationRemoteUser@192.168.1.101:9000/data --service "replication" --sync
Remote ARN = `arn:minio:replication::fd84007d82acc8362c38eb9c2281d62366b5c121c9787442931c1581ba70d29a:data`
```

2) Add the replication rule

```
mc replicate add --arn "arn:minio:replication::fd84007d82acc8362c38eb9c2281d62366b5c121c9787442931c1581ba70d29a:data" --remote-bucket data --replicate "delete,delete-marker,existing-objects" minioalpharepl/data
```

3) Copy a file using the limited policy user

```
./mc cp yellow_tripdata_2020-02.csv repltest/data
...ripdata_2020-02.csv:  557.13 MiB / 557.13 MiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 212.78 MiB/s 2s[ravindk-minio@ravindk-desktop mc-RELEASE.2021-07-27T06-46-19Z]$ 
[ravindk-minio@ravindk-desktop mc-RELEASE.2021-07-27T06-46-19Z]$ ./mc stat repltest/data/yellow_tripdata_2020-02.csv
Name      : yellow_tripdata_2020-02.csv
Date      : 2021-09-02 10:52:39 EDT 
Size      : 557 MiB 
ETag      : 277101c45a67f8dba37d3c01d904b6f3-35 
VersionID : 12bf841d-7ea7-46f7-96fb-9368ecc3030b 
Type      : file 
Metadata  :
  Content-Type: text/csv
```

4) Confirm status:

```
[ravindk-minio@ravindk-desktop mc-RELEASE.2021-07-27T06-46-19Z]$ ./mc stat miniobaker/data/Unicauca-dataset-April-June-2019-Network-flows.csv
Name      : Unicauca-dataset-April-June-2019-Network-flows.csv
Date      : 2021-09-02 10:57:54 EDT 
Size      : 1.2 GiB 
ETag      : 2bb0e6208bc6ebe6cc1fbafd2c491da4-77 
VersionID : fe9b4b60-115c-4e97-b9c1-77220f8bf4cb 
Type      : file 
Metadata  :
  Content-Type: text/csv 
Replication Status: REPLICA 
[ravindk-minio@ravindk-desktop mc-RELEASE.2021-07-27T06-46-19Z]$ ./mc stat minioalpha/data/Unicauca-dataset-April-June-2019-Network-flows.csv
Name      : Unicauca-dataset-April-June-2019-Network-flows.csv
Date      : 2021-09-02 10:57:54 EDT 
Size      : 1.2 GiB 
ETag      : 2bb0e6208bc6ebe6cc1fbafd2c491da4-77 
VersionID : fe9b4b60-115c-4e97-b9c1-77220f8bf4cb 
Type      : file 
Metadata  :
  Content-Type: text/csv 
Replication Status: COMPLETED 
```

One thing I *did* notice:

After copying the file, mc returns successfully. When i `mc stat` the file on `minioalpha`, it does not have the metadata associated to replication and it is not yet replicated to miniobaker.

A few seconds later, I re-checked and the file has completed replicating *and* the metadata is now visible.

@poornas I would have expected after `mc cp` completed that I could `mc stat` on the remote and get the object back, since with sync replication I *thought* the behavior is the application waits until replication completes.

In practice, it took a few seconds before the metadata updated and both nodes showed the data in question. This might be because I'm running in VM so there's some general lag in processing, fwiw.

**Comment by Olliferdl** [comment]
@ravindk89 try it without the existing-objects option. But i guess @poornas commit makes the issue clearer

**Comment by ravindk89** [comment]
@Olliferdl yeah there we go. You're correct - I'm going to re-open this issue now that we have something linked.

Thanks for your patience around the initial confusion. Having the wrong permissions on setup is a very common configuration error, thus the initial response.

**Comment by ravindk89** [comment]
@Olliferdl fwiw with Poorna's fix (building from that branch) the behavior appears to be as expected for sync workloads - `mc cp` waits until sync completes on both target + remote, and replication behaves as expected in trace.

Once that fix is merged I think we are good to go.

**Comment by Olliferdl** [comment]
Thank you very much!
