### ISSUE TITLE
OIDC incorrect redirect

### ISSUE THREAD

**Issue by adyanth** [minio/minio#13304]
## Expected Behavior
Redirect to my keycloak instance for authentication

## Current Behavior
Stays in the same login page
![image](https://user-images.githubusercontent.com/33192449/134803409-b56444e9-a072-4a9e-88e8-7f2bcc35c71e.png)
![image](https://user-images.githubusercontent.com/33192449/134803424-6e7d97c8-2720-4f5e-818b-2b2c0bcf32af.png)

If I manually substitute the actual URL, it goes to keycloak and comes back to the `/login` page on MinIO.
![image](https://user-images.githubusercontent.com/33192449/134803735-a8a62cb2-a14d-4df5-9cee-2e697f298768.png)

## Steps to Reproduce (for bugs)
Fresh docker image deployment with the below environment

## Context
I am trying to integrate OIDC SSO to MinIO

## Regression
N/A

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-09-24T00-24-24Z, `minio/minio:latest` (image id `1afc478341fd`)
* Server setup and configuration:
Environment:
```bash
MINIO_SERVER_URL=https://minio.<domain>
MINIO_BROWSER_REDIRECT_URL=https://minio-console.<domain>
MINIO_IDENTITY_LDAP_SERVER_ADDR=10.10.10.4:389
MINIO_IDENTITY_LDAP_SERVER_INSECURE=true
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=true
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=CN=Minio,OU=ServiceAccounts,DC=<domain>,DC=lan
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=bindpass
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN=OU=People,DC=<domain>,DC=lan
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectCategory=user)(sAMAccountName=%s))
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectClass=group)(member=%d))
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN=CN=MinioUsers,OU=Groups,DC=<domain>,DC=lan

MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=password

MINIO_IDENTITY_OPENID_CONFIG_URL=https://<keycloak>/auth/realms/<realm>/.well-known/openid-configuration
MINIO_IDENTITY_OPENID_CLIENT_ID=<clientID>
MINIO_IDENTITY_OPENID_CLIENT_SECRET=<clientSecret>
MINIO_IDENTITY_OPENID_SCOPES=openid profile email
```

* Operating System and version (`uname -a`): docker build

**Comment by harshavardhana** [comment]
You cannot handle LDAP and OpenID configured together. You need to use either use 

- LDAP
- OpenID

**Comment by adyanth** [comment]
Isn't OIDC usually implemented with another backend (like LDAP) for user management? Either way, will try without LDAP. Thanks for the info @harshavardhana !

**Comment by Scapal** [comment]
I have the same behaviour, no LDAP settings on my side:

I'm running Minio (gateway nas) + Etcd + KeyCloak.

Upgrading the Minio Docker image from RELEASE.2021-08-25T00-41-18Z  to RELEASE.2021-09-24T00-24-24Z breaks the authentication. Every other settings remaining the same.

The "_Login With SSO_" is calling the Minio URL instead of the OpenID server.

On the 2021-08-25 version, the "_Login With SSO_" button has this link: `https://kc.mydomain.com/auth/realms/master/protocol/openid-connect/auth?client_id=minio-cstorage&redirect_uri=https%3A%2F%2Fcstorage.mydomain.com%3A9001%2Foauth_callback&response_type=code&scope=openid+address+web-origins+phone+profile+offline_access+email+microprofile-jwt+roles&state=TEFHUFlaM0dOMEwwNUxNQVRDEADBEEFDEADBEEFuRDRzK2gwWWFmWFkxTEpkSGdvPQ%3D%3D`

On the 2021-09-24 version: 
`https://cstorage.mydomain.com:9001/login?client_id=minio-cstorage&redirect_uri=https%3A%2F%2Fcstorage.mydomain.com%3A9001%2Foauth_callback&response_type=code&scope=openid+address+web-origins+phone+profile+offline_access+email+microprofile-jwt+roles+openid&state= TEFHUFlaM0dOMEwwNUxNQVRDEADBEEFDEADBEEFuRDRzK2gwWWFmWFkxTEpkSGdvPQ%3D%3D`

**Comment by adyanth** [comment]
Hey @harshavardhana 
As @Scapal noted, even I see the same behaviour. Even after disabling LDAP, I can see that OpenIDConnect does not work, and the login redirects to itself.

Even if I correct the link to go to my IdP, it logs in and redirects back to `/login`

Can you reopen this please?

**Comment by captnbp** [comment]
Hi,

I have the exact same issue using OIDC only : it redirects back to `/login`

minio version `DEVELOPMENT.2021-09-24T00-24-24Z`

(It works fine with version `2021-09-18T18:09:59Z`)

@harshavardhana I'm also interested to reopen the issue.

**Comment by harshavardhana** [comment]
> Hi,
> 
> I have the exact same issue using OIDC only : it redirects back to `/login`
> 
> minio version `DEVELOPMENT.2021-09-24T00-24-24Z`
> 
> (It works fine with version `2021-09-18T18:09:59Z`)
> 
> @harshavardhana I'm also interested to reopen the issue.

This is fixed in master branch
