### ISSUE TITLE
Minio Teanant - Error - no such host (*fmt.wrapError)

### ISSUE THREAD

**Issue by Bhagi33** [minio/minio#13732]
API: SYSTEM()
Time: 11:31:49 UTC 11/23/2021
Error: Marking http://minio1-pool-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export3/data/v41 temporary offline; caused by Post "http://minio1-pool-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export3/data/v41/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio1-pool-0-2.minio1-hl.minio.svc.cluster.local on 172.20.0.10:53: no such host (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 11:31:49 UTC 11/23/2021
Error: Marking http://minio1-pool-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export2/data/v41 temporary offline; caused by Post "http://minio1-pool-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export2/data/v41/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio1-pool-0-2.minio1-hl.minio.svc.cluster.local on 172.20.0.10:53: no such host (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 11:31:49 UTC 11/23/2021
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       5: cmd/prepare-storage.go:268:cmd.connectLoadInitFormats()
       4: cmd/prepare-storage.go:317:cmd.waitForFormatErasure()
       3: cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()
       2: cmd/server-main.go:637:cmd.newObjectLayer()
       1: cmd/server-main.go:542:cmd.serverMain()
Waiting for a minimum of 8 disks to come online (elapsed 55s)
$ kubectl logs minio1-pool-0-1 -n minio

can you please help me.
this is the kube-dns IP 172.20.0.10:53, why minio hostname trying to point to the DNS IP.

**Comment by klauspost** [comment]
> why minio hostname trying to point to the DNS IP.

MinIO uses the DNS to look up host names. It doesn't know the host.

Investigate if kube-dns has issues. Not really a minio issue AFAICT.

**Comment by Bhagi33** [comment]
Yes, why this DNS  lookup  for minio1-pool-0-2.minio1-hl.minio.svc.cluster.local on 172.20.0.10:53 is pointing on kube-dns svc Ip.
172.20.0.10=kube-dns service ip

**Comment by klauspost** [comment]
@Bhagi33 Not sure what your question is. 

MinIO needs to look up the host to make a connection.

**Comment by harshavardhana** [comment]
> Error: Marking http://minio1-pool-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export2/data/v41 temporary offline; caused by Post "http://minio1-pool-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export2/data/v41/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio1-pool-0-2.minio1-hl.minio.svc.cluster.local on 172.20.0.10:53: no such host (*fmt.wrapError)

kube-dns is the DNS server that is responding to a DNS name that doesn't resolve.  Most probably your kube-dns requires a restart to pull in new DNS entries.

**Comment by SergeyLadutko** [comment]
Me too in docker 
  minio_release_minio1.1.ketklwhsztoc@test    | Error: Marking http://minio3:9000/minio/storage/data1/v41 temporary offline; caused by Post "http://minio3:9000/minio/storage/data1/v41/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio3 on 127.0.0.11:53: no such host (*fmt.wrapError)
  minio_release_minio1.1.ketklwhsztoc@test    |        6: internal/rest/client.go:149:rest.(*Client).Call()
  minio_release_minio1.1.ketklwhsztoc@test    |        5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
  minio_release_minio1.1.ketklwhsztoc@test    |        4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
  minio_release_minio1.1.ketklwhsztoc@test    |        3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
  minio_release_minio1.1.ketklwhsztoc@test    |        2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
  minio_release_minio1.1.ketklwhsztoc@test    |        1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

**Comment by klauspost** [comment]
@SergeyLadutko Check you localhost DNS server.
