### ISSUE TITLE
Can't upload file when caching enabled

### ISSUE THREAD

**Issue by AlexZIX** [minio/minio#13907]
When cache enabled it's not possible to upload file to minio using Web UI or any S3 client - only download available. After disabling cache uploading works fine.

## Expected Behavior
Normal files upload and download with cache enabled

## Current Behavior
When cache enabled it's not possible to upload file to minio using Web UI or any S3 client - only download available.

## Steps to Reproduce (for bugs)
1. Setup minio.
2. Enable caching (I use separate ssd) in Web GUI at Settings -> Cache page.

## Context
I have 3 minio servers each with 4 disks running in cluster.

## Regression
No, previous September's version works fine.

## Your Environment
* Version used (`minio --version`): 2021-12-10T23:03:39Z
* Server setup and configuration: 3 servers with 4 disks each in cluster, each server have separate ssd disk fo caching
* Operating System and version (`uname -a`): Linux minio-1 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AlexZIX** [comment]
This is my caching params:

#MINIO_CACHE="on"
#MINIO_CACHE_DRIVES="/disks/ssd-cache-cold"
#MINIO_CACHE_QUOTA=100
#MINIO_CACHE_AFTER=3
#MINIO_CACHE_WATERMARK_LOW=70
#MINIO_CACHE_WATERMARK_HIGH=95

**Comment by vadmeste** [comment]
@AlexZIX any log in MinIO when you try to upload/download an object when caching is enabled ?

**Comment by AlexZIX** [comment]
Nothing in system log - minio starts, found that cache is 50 GB and think that all fine. In S3 Browser uploading process are infinite until nginx which works as reverse proxy doesn't return gateway timeout.

**Comment by AlexZIX** [comment]
I've tried to set caching options as environment variables instead of set it in Settings but nothing changes. Any operation which should write file doesn't work - I even can't delete existing file - only list or download.

**Comment by harshavardhana** [comment]
> I have 3 minio servers each with 4 disks running in cluster.

Do not use distributed mode @AlexZIX with disk caching this is not supported.  Disk caching is meant to be used with Gateway mode only.

**Comment by harshavardhana** [comment]
@poornas can you send a PR to disable caching for distributed setups?

**Comment by AlexZIX** [comment]
This was worked for me in previous releases and helps to create CDN based on Minio. I had distributed minio setup on 3 servers in different locations. Each server serves content to customers with caching on locally attached SSD even if my distributed setup uses HDD. Often used files cached on SSD which improve performance. Is it possible to just fix it instead of disable?

**Comment by harshavardhana** [comment]
> This was worked for me in previous releases and helps to create CDN based on Minio. I had distributed minio setup on 3 servers in different locations. Each server serves content to customers with caching on locally attached SSD even if my distributed setup uses HDD. Often used files cached on SSD which improve performance. Is it possible to just fix it instead of disable?

Yes, they will but that is not recommended setup. We do not want our users to use disk caching with distributed setups.  It is never meant to work and the usage is not correct.  

Disk caching was never designed to be used with erasure-coded deployments and that is why it broke because we never test it on our end with distributed setups.

You will never really gain any benefit from using SSDs in front of HDDs unless your HDDs are really networked mounts and are terribly slow.  

SSDs can provide IOPS but with a concurrent workload that distributed setup supports you are basically choking single SSD v/s a large pool of HDD that will be any day more performant. 

If you are in production here you are better off getting our support to architecture this properly, as we would like to know how much performance gain we are talking about here. 

We did benchmark NVMe's in front of MinIO distributed setup saw actually performance dropped as the number of IOPS a single drive can handle locally was way lower than the entire distributed setup combined.

But if your setup let's say as 4 drives per node with 3 servers then this is considered as a toy setup, you do not have much HA and not many IOPS. Servers are basically under-provisioned for a performant setup. 

Instead of doing this you could simply remove those HDDs on the 3 servers instead add an extra SSD and setup MinIO distributed on top with 6 drives you will get more IOPS per server than 12 drives (distributed setup). 

This is a neater architecture with the limited number of servers that your current setup has.

**Comment by AlexZIX** [comment]
Thanks for this detailed answer.

Just my case is small different. I have 3 servers in different regions. Throughput between servers is 100 Mbps and throughput from this servers to clients in this regions is 1 Gbps. So I use minio not only as HA storage but also as CDN with S3 support. In one storage I have some files (6.6 TB for now). Access to 95% of this files are rare (~15 times per year) and other 5% is often requested files which I want to serve with maximum speed in region where server location. I use cache on NVME for this. Is case of direct downloading from distributed minio main bottleneck will be throughput between servers in different region and I want to prevent it using cache.
So for now I see 2 solutions for me:
1. Setup minio as S3 gateway to my distributed setup in each region.
2. Enable cache at my nginx which acts as reverse proxy for minio. 

Also I host my servers on colocation in data centers in this regions. Each server have 1U size and only 4 HDD and 2 NVMe can be installed. So for such setups this usage of minio better in my opinion.

**Comment by klauspost** [comment]
@AlexZIX Evaluating and helping to design your system setup is beyond what we can offer here. Please take a look at our [subscription options](https://min.io/pricing), where we can go into much more details about your situation and requirements.

**Comment by harshavardhana** [comment]
> * Setup minio as S3 gateway to my distributed setup in each region.

This is what we would recommend @AlexZIX for you.

**Comment by AlexZIX** [comment]
@harshavardhana Thanks so much for your advice.
I've already tried to setup cache on my nginx but seems there is too much troubles can be. GeeseFS (S3 filesystem) works incorrectly in this case and some thin tuning and tests needs. So I'll try minio as S3 gateway.
