### ISSUE TITLE
Disabled account is enabled after changing password

### ISSUE THREAD

**Issue by Feiniu6ABC** [minio/minio#13957]
Go to the console of MinIO, disable an existing account. After changing the password of this account, it becomes enabled again

## Expected Behavior
The disabled account remains disabled after changing its password

## Current Behavior
The disabled account is activated after changing its password

## Steps to Reproduce (for bugs)

1. Log into console as administrator
2. Disable an existing account
3. Change the password of the account that is disabled
3. Refresh the web page
4. The disabled account is shown as enabled

## Your Environment
* Version used (`minio --version`):
* version RELEASE.2021-11-16T20-37-36Z
* Server setup and configuration:
* Operating System and version (`uname -a`):
* MINGW64_NT-10.0-19042 DESKTOP-KSDCPBK 3.1.7-340.x86_64 2021-10-12 16:29 UTC x86_64 Msys

**Comment by harshavardhana** [comment]
Yes, this is expected - password change is mainly meaningless on a disabled user if you are not planning to enable them. 

The password change event is implicitly considered as you want to enable access for this user. So it assumes to enable the user that was previously disabled for access. 

It is designed for you to avoid a step where you want to re-enable the user after a password change event. 

The password event happens because you wish to make sure no application is using the credentials by disabling the user, so when you change the password it is implicitly assumed that this is to enable the said "user" - otherwise, there is no point changing the user password when the user is disabled.

This leading assumption is the reason why it re-enables the "user" that was disabled after a "password" change.
