### ISSUE TITLE
Lifecycle rule cannot be executed

### ISSUE THREAD

**Issue by danboming** [minio/minio#14162]
I added an lifecycle rule to delete the file after one day,but the file is still in the bucket when one day passed. do you have any solution to fix this problem?

**Comment by klauspost** [comment]
Same as your [duplicate report](https://github.com/minio/minio-java/issues/1292).

Since you don't provide any information whatsoever, and you didn't fill out the requested form, I will guess on the cause:

My guess is that you do not know when an object expires:

> Amazon S3 calculates the time by adding the number of days specified in the rule to the time when the new successor version of the object is created and rounding the resulting time to the next day midnight UTC. For example, in your bucket, suppose that you have a current version of an object that was created at 1/1/2014 10:30 AM UTC. If the new version of the object that replaces the current version is created at 1/15/2014 10:30 AM UTC, and you specify 3 days in a transition rule, the transition date of the object is calculated as 1/19/2014 00:00 UTC.

From https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html
