### ISSUE TITLE
xl: DeleteFile(): meta data will be lost when complete delete of meta data files

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1427]
When all disks are online and having consistent meta data file and data file, those meta data files are also deleted in DeleteFile(). In this case, if any one of disk failure causes lose of meta data in previous successful delete in other disks.

**Comment by balamurugana** [comment]
Need a discussion to close out this issue.

**Comment by krishnasrinivas** [comment]
@balamurugana you mean when deletion is happening one of the disks go down, so when they come back up they still have the metadata file?

**Comment by balamurugana** [comment]
Currently the function returns error immediately.  if we do https://github.com/minio/minio/issues/1428 there is chance of stale data/meta data files on those failed disks.

**Comment by krishnasrinivas** [comment]
one way to tackle this situation is by using generation numbers for objects.

**Comment by krishnasrinivas** [comment]
@balamurugana this is the situation right?
- out of 16 disks 11 disks are up
- now there is a delete operation on the object as we have write quorum

now two situations can happen.
1st :
- when the deletion is happening 1 disk goes down
- deletion would have happened on 10 disks
- in this case we can still return success because there is still read quorum to detect that file is deleted

2nd:
- when deletion is happening 4 disks goes down
- deletion would have happened on 7 disks
- we return error as deletion did not happen on readQuorum number of disks

In both the situations we can recover right? (worst case by returning IO error)

**Comment by balamurugana** [comment]
I think you missed the issue description.  The issue happens when all disks are online.
