### ISSUE TITLE
bucket directories size limits

### ISSUE THREAD

**Issue by LinTechSo** [minio/minio#14466]
HI, Is there a way to set quotas for directories inside each bucket in a MinIO server and monitor the size and quota with the API of each directory in the bucket?

**Comment by ureykane** [comment]
Since object storage adopts a distributed storage method, objects are not physically stored according to folders. That is to say, not all files in a folder will be stored together. In the process of backend storage, the files in different folders are only different in the prefix of the key value. Therefore, under this architecture, it is impossible to conveniently count summary information under a certain folder, such as folder size, number of files, etc.
