### ISSUE TITLE
`mc replicate resync …` not working?

### ISSUE THREAD

**Issue by DirkDittmarMonday** [minio/minio#14702]
## Expected Behavior

We've established a "active -> passiv" replication between two clusters to use the replica as a backup (in case of desaster). The replication works fine. Both buckets have "versioning" enabled.

To test the "desaster" we completly remove the source cluster (with all volumes etc) and reinstalled it. Then we reconfigured the replication (lets say alpha -> beta) and tried to resync (`mc replicate resyc start alpha/test --remote-bucket "arn:minio:beta::<uuid>:test"`)

If we look with `mc replicate resync status ...` we get
```
Resync status summary:
● arn:minio:beta::<uuid>:test                                           
   Status: Completed
   Replication Status | Size (Bytes)    | Count          
   Replicated         | 0 B             | 0              
   Failed             | 0 B             | 0 
```

We expect that minio copies the files back from the replica.

## Your Environment
* Minio Version: 2022-03-26T06:49:28Z (in both clusters)
* `mc` Version: RELEASE.2022-03-09T02-08-36Z

**Comment by ravindk89** [comment]
@DirkDittmarMonday to confirm - what do you mean by "We reconfigured the replication". Did you restore the original replication settings, or change it so that the original "replica" cluster is now the "source" ?

@poornas this feels somewhat similar to the situation I ran into, where I started doing a resync while the normal synchronization was ongoing at the start of replication configuration. I think I just had to wait for resync to scan the remote and confirm all files already existed and matched the source, not 100% sure.

@DirkDittmarMonday what is the new replication rule? Assuming it includes existing objects here - are you seeing normal replication traffic and replication to the remote (e.g. via mc replicate status alpha/test?)

**Comment by poornas** [comment]
@DirkDittmarMonday , replication resync is always from the site that has data to the one that needs to be synced. Since you are doing an active-passive replication, were you trying resync from the active which now is empty? 

You should create a replication config on DR site now pointing back to the source and then use the `resync` command.

**Comment by poornas** [comment]
@ravindk89 , this may be a confusion w.r.t resyncing on active-passive setup. Most of our docs assume active-active replication

**Comment by DirkDittmarMonday** [comment]
@ravindk89 to make it clear:
1. we setup a replication (A->B)
2. we destroy cluster A completly and set it up again
3. we restore the original replication (A->B)

.. and the replication is working (new files are transfered from A to B) and `mc replicate status A/test` shows that everythings is working fine. The replication rule is always `mc replicate add "A/test" --remote-bucket "arn:minio:B::<uuid>:test" --replicate "existing-objects,delete-marker" --priority 1`

**Comment by harshavardhana** [comment]
> @DirkDittmarMonday , replication resync is always from the site that has data to the one that needs to be synced. Since you are doing an active-passive replication, were you trying resync from the active which now is empty?
> 
> You should create a replication config on DR site now pointing back to the source and then use the `resync` command.

As mentioned here you need to follow this for resync for passive site setups. 

Active/Active is best way to setup replication - keeps things simple and avoids new activity during DR recovery.

**Comment by DirkDittmarMonday** [comment]
@poornas you mean I should try something like this (?):
1. setup a replication from A to B (A->B) and replicate some files to B
2. destroy A and set it up again
3. setup a replication from B to A (B->A) and then try the `resync` ...

I will try that...

**Comment by poornas** [comment]
>setup a replication from B to A (B->A) and then try the resync ...
that's correct
