### ISSUE TITLE
Capacity-based retention.

### ISSUE THREAD

**Issue by radimkohout** [minio/minio#14779]
**Is your feature request related to a problem? Please describe.**
The capacity-based retention doesn't exist.

**Describe the solution you'd like**
When the capacity limit is reached, minio will delete the oldest file in the bucket.

**Describe alternatives you've considered**
Time-based retention - It's quite useless for this purpose
**Additional context**
Minio distributed, Linux, ext4

**Comment by harshavardhana** [comment]
> When the capacity limit is reached, minio will delete the oldest file in the bucket.

For this, we need to do expensive walks on the namespace, not an efficient way to do things. In fact such a setup will next to useless for any reasonable performance requirements.

Closing as not going to be implemented for now.

**Comment by klauspost** [comment]
For a bit more context, a bucket can have many millions of objects and finding the "oldest" can take several hours, even days, since all objects must be scanned to be sorted by timestamp - all while spending IO not serving requests.

We are considering this for tiering since the "hot" tier usually has enough IOPS if designed correctly, but for general retention it isn't feasible.
