### ISSUE TITLE
Treat LDAP bind password as a secret

### ISSUE THREAD

**Issue by mattdowdell** [minio/minio#14774]
**Is your feature request related to a problem? Please describe.**
Currently the LDAP bind password is input in plaintext in the console and via environment variables. As it's a password, it should technically be treated as one for those inputs, even if the user the password is for is only expected to have readonly access. As far as I can see there's nothing that stops a non-readonly user being utilised, and even then one might not want the give others the ability to freely browse the directory if they get hold of the password.

**Describe the solution you'd like**
1. Set the bind password input type in the console to password (currently set to text).
2. Allow the bind password environment variable to be read in from a secret/file, as `MINIO_ROOT_PASSWORD` can be today.

**Describe alternatives you've considered**
None at this time.

**Additional context**
I don't have knowledge of how the password and other configuration is treated in the backend, but it may be desirable to ensure it's encrypted if it isn't already.

**Comment by harshavardhana** [comment]
It is a secret if you must deploy it in trustable orchestrated environments such as k8s where you can securely pass these values using central Vault.

Baremetal environment you are out of luck since most of these cross trust and RBAC is not present.

If you want deployment trust and security  - consider deploying using k8s.
