### ISSUE TITLE
Update/create documentation for DARE version 2.0

### ISSUE THREAD

**Issue by RaulMendiratta** [minio/minio#14975]
The [documentation for DARE](https://github.com/minio/sio/blob/master/DARE.md) version 2.0 does not exist. 
It would be nice to have a document for version 2.0 as there are a lot of differences from version 1.0.

Also, continuing on this topic,
Why the decision of adding to the header only the 12B nonce and not the 12B nonce xored seqnumber. 
It seems more unnecessary effort to do the xor calculation every time for encrypt and decrypt.

**Comment by aead** [comment]
DARE v2 differs only in the package header format:
- DARE v1 allows packages (header + ciphertext) with different lengths within the same stream. DARE v2 fixes the package size to `16 + 64*1024 + 16`.
- DARE v2 uses different en/decryption nonces for any non-final and the final package of a data stream. This prevents extension / truncation attacks. See: https://github.com/minio/sio/blob/master/dare.go#L56
- DARE v2 xor's the sequence number into the en/decryption nonce. DARE v1 simply concatenates the nonce and sequence number.

Xor'ing a 12 byte nonce with a 4 byte sequence number gives slightly less nonce collisions compared to concatenating a 8 byte nonce with a 4 byte sequence number when the data streams are "short".
For example, if your data stream is only 64 * 1024 bytes long, then you use a 95 random nonce (1 bit is influenced by the sequence number). DARE v1 always uses a 64 bit random nonce since the remaining 32 bits are always deterministic.
The longer the data streams get the less difference is between v1 and v2 w.r.t. nonce reuse probability. 

> Why the decision of adding to the header only the 12B nonce and not the 12B nonce xored seqnumber.
It seems more unnecessary effort to do the xor calculation every time for encrypt and decrypt.

A in-memory XOR operation is cheap. Virtually anything else done by DARE is more expensive then xor'ing two `uint32`.
Further, we can check that the same nonce is used for the entire data stream - See: https://github.com/minio/sio/blob/master/dare.go#L259

**Comment by aead** [comment]
@RaulMendiratta For further reference take a look at: https://github.com/secure-io/sio-go#secure-io
It is used by MinIO already for config / IAM data encryption and eventually will be used for S3 objects as well.

It has a formal mathematical security proof and has minimal memory overhead.
