### ISSUE TITLE
High CPU (iowait) usage standalone erasure code

### ISSUE THREAD

**Issue by kshvakov** [minio/minio#15488]
## Your Environment
 
* minio version RELEASE.2022-08-02T23-59-16Z (commit-id=76f950c6632fe67b17e9f0cc00905d7093ef837d)
* Server setup and configuration: /usr/bin/minio server /data/hdd{0...35}/minio
* Operating System and version (`uname -a`): Ubuntu 20.04.3 LTS 5.4.0-96-generic

We have a very simple setup in a single node. There is no significant load on the server, we have about 40 buckets with 1.5k objects with a total size of 250Gb. At the same time, MinIO regularly eats CPU. Also on this server there is a service that allows to write/read files from disk, but there are no problems with iowait with it

<img width="687" alt="Screenshot 2022-08-07 at 1 51 49 PM" src="https://user-images.githubusercontent.com/978534/183287264-38d2b270-14dd-41c7-93dc-9f90125c5c25.png">

as you can see on the graph, the CPU load does not correlate with network activity in any way

**Comment by harshavardhana** [comment]
This is mostly related to https://github.com/golang/go/issues/51654 you have to upgrade to the latest release and let us know @kshvakov 

Also capture profiling we cannot rely on Host level information here you need to run `mc support profile start --type cpu alias/`

**Comment by kshvakov** [comment]
Same problem with RELEASE.2022-08-05T23-27-09Z (go1.18.5 linux/amd64)
[profile.zip](https://github.com/minio/minio/files/9277211/profile.zip)

**Comment by harshavardhana** [comment]
there is actually hardly any CPU usage by MinIO in the profile.  I would say something else is up here some of your drives are either misbehaving or there is some activity that is happening outside of MinIO. 

> Also on this server there is a service that allows to write/read files from disk, but there are no problems with iowait with it

This doesn't make any sense - can you explain?

**Comment by kshvakov** [comment]
Before installing MinIO on the server, we did not observe any problems with the CPU, we also see increased MinIO activity in htop/iotop every minute

<img width="393" alt="Screenshot 2022-08-08 at 9 02 47 AM" src="https://user-images.githubusercontent.com/978534/183350022-ff0e0cbc-37fe-4001-9e49-70de96100d1f.png">

On the same server there is a service that allows you to read and write files to disk, despite the fact that it serves 3 times more traffic, it has no problems with disks or CPU.

**Comment by harshavardhana** [comment]
That is always present because MinIO is running a usage scanner all the time @kshvakov is a normal activity. This has nothing to be surprised about. This usage scanner also attempts to verify the content i.e healing of some of these objects. 

I do not see any CPU activity that actually causes problems from the profile it looks normal, MinIO is using the relevant resources that are available at its hand.  All the CPU activity is from the system calls on the disk that's all. 

> 
> On the same server there is a service that allows you to read and write files to disk, despite the fact that it serves 3 times more traffic, it has no problems with disks or CPU.

We are MinIO, we are not just "serving" traffic but actively managing your data. So the comparison is apples and oranges. 

> Before installing MinIO on the server, we did not observe any problems with the CPU, we also see increased MinIO activity in htop/iotop every minute

what kind of a problem are you talking about? NOTE: you cannot run multiple services on the same system that is a bad architecture - co-existing MinIO with another service will have noisy neighbor problems both for MinIO and your service.

For true isolation you need to start using cgroups (k8s/containers)

**Comment by harshavardhana** [comment]
Closing this since there is no real problem here, please let us know otherwise.

**Comment by harshavardhana** [comment]
Another data point - Scanner runs for 40 buckets on 40 disks in parallel. Since you are not using scale-out architecture MinIO cannot spread out this activity across remote disks so you are simply blocked by the CPU on the single node. 

This is an incorrect architecture TBH you should build a scale-out system when you are planning to > 10 buckets.
