### ISSUE TITLE
It is not possible to create a object with two consecutive slashes

### ISSUE THREAD

**Issue by graywolf-at-work** [minio/minio#15684]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

Since minio claims to be S3 compatible, I would expect to be able to create file
with key `https://example.org`. However it is not possible.

## Current Behavior

It is not possible.

## Steps to Reproduce (for bugs)

Try to create object with `https://example.org` key.

## Context

We are using S3 for caching and wanted to uses minio to run test suite. However,
minio does not support the keys we are using (full URIs).

## Regression

No.

**Comment by harshavardhana** [comment]
No it is not possible @graywolf-at-work because there is no such thing on filesystem that preserves `//` .

We do not manually transcode such objects to some internal representation. 

Having // is mostly a bug in the application implementation, where paths are not properly normalized.

Having // support is not cornerstone of S3 compatibility we specifically mention things to avoid

https://github.com/minio/minio/blob/master/docs/minio-limits.md#object-name-restrictions-on-minio

**Comment by graywolf-at-work** [comment]
Wouldn't it be better to consider encoding the object names in some way in order to get mostly free improvement to S3 compatibility?

**Comment by harshavardhana** [comment]
> Wouldn't it be better to consider encoding the object names in some way in order to get mostly free improvement to S3 compatibility?

@graywolf-at-work no there are more complications than just encoding - sorting for Listing etc takes a hit as the sorted order now needs to cater for various encoded patterns. 

There are more corner-cases.
