### ISSUE TITLE
XL: removed file reappears

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1595]
Follow steps in https://github.com/minio/minio/issues/1594
- Remove the file 

```
mc rm myminio/mybucket/zero
```
- now run

```
mc ls myminio/mybucket/zero
```

The object appears.

Minio used:

```
$ minio version
Version: 2016-05-11T05:13:12Z
Release-Tag: DEVELOPMENT.2016-05-11T05-13-12Z
Commit-ID: 49141eb3e4c0f335b8668ab7057b753afec5c125

```

**Comment by krisis** [comment]
Following is the xl-backend directory structure after the second `mc cp bigfile` as described in #1594.

```
disk1/bucket1/zero
├── 00000.minio.multipart
│   ├── file.0
│   └── file.json
├── 00001.minio.multipart
│   ├── file.0
│   └── file.json
├── 00002.minio.multipart
│   ├── file.0
│   └── file.json
├── 00003.minio.multipart
│   ├── file.0
│   └── file.json
├── 00004.minio.multipart
│   ├── file.0
│   └── file.json
├── 00005.minio.multipart
│   ├── file.0
│   └── file.json
├── 00006.minio.multipart
│   ├── file.0
│   └── file.json
├── 00007.minio.multipart
│   ├── file.0
│   └── file.json
├── 00008.minio.multipart
│   ├── file.0
│   └── file.json
├── 00009.minio.multipart
│   ├── file.0
│   └── file.json
├── 00010.minio.multipart
│   ├── file.0
│   └── file.json
├── 00011.minio.multipart
│   ├── file.0
│   └── file.json
├── 00012.minio.multipart
│   ├── file.0
│   └── file.json
├── 00013.minio.multipart
│   ├── file.0
│   └── file.json
├── 00014.minio.multipart
│   ├── file.0
│   └── file.json
├── 00015.minio.multipart
│   ├── file.0
│   └── file.json
├── 00016.minio.multipart
│   ├── file.0
│   └── file.json
├── 00017.minio.multipart
│   ├── file.0
│   └── file.json
├── file.0      
└── file.json

```

Following is the xl-backend directory structure after the `mc rm <objectname>`

```
└── zero
    ├── file.0
    └── file.json
```

Note that `file.0` and `file.json` under `disk1/bucket1` are remains of the file copied first. These two files must not be present after the second copy. The xl's `DeleteObject` implementation, triggered as part of `mc rm`, detects that the object is stored as multipart and removes the constituent parts. Due to the inconsistent state of the backend, we are left with `file.0` and `file.json` which resembles a 'simple' object (< 5M). This is why `mc ls` lists a non-existent object.

**Comment by krishnasrinivas** [comment]
@krisis cool, as discussed i will fix this as part of the support for directory rename fix during complete-multipart-upload. It will also fix https://github.com/minio/minio/issues/1598 https://github.com/minio/minio/issues/1594 https://github.com/minio/minio/issues/1558

**Comment by harshavardhana** [comment]
@krishnasrinivas - is this already fixed?

**Comment by krishnasrinivas** [comment]
@harshavardhana yes
