### ISSUE TITLE
mc mirror slows down while uploading large number of objects in small size (May 14th)

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#1601]
mc mirror slows down while uploading large number of objects in small size

```
minio@minio2:~$ mc mirror ./gopath myminio9/atul
...fbebaec.pack: 56.68 MB / 116.21 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░┃  48.77 % 6.12 MB9s
```

**Comment by harshavardhana** [comment]
After doing several benchmarks the overall usage time is [Most syscall time spent](https://github.com/minio/minio/files/260543/test.pdf) is not much, there are no known bottle necks in this path alone.

If you look at the output of 'mc' v/s 'aws cli' for the same data set being copied to 'minio server'. 

Almost same amount of files were being copied -negating the time it takes for session building for 180k files around 45secs.  It takes around 2480 files around 1m+.

```
2480

real    1m47.813s
user    0m34.072s
sys 0m9.900s

```

Similar or more number of files at a point in time shows aws cli does in 47secs, the reason is parallel uploads.

```
//testbucket/new/awscli/1.8.6/libexec/lib/python2.7/site-packages/awscli/examples/iam/create-account-alias.rst
Completed 2902 part(s) with ... file(s) remaining

real    0m47.813s
user    0m18.072s
sys 0m4.900s
```

So to copy around 182k files it would take around 4410 secs for 'mc' where as it would take '3002' secs, considering there are no multipart operations involved which might get even lower since aws cli uploads in parallel. 

The next approach which i am going to validate is reading larger blocks and copy in larger blocks than default 32k which io.Copy uses. 

Will report back in a bit.

**Comment by harshavardhana** [comment]
@koolhead17 can this be validated again with the latest master?

**Comment by koolhead17** [comment]
This is how i see it now (May 14)

```
minio@minio1:~$ mc mirror gopath/  myminio92/atul
...fs/doc.go: 158.01 MB / 178.01 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░┃  88.77 % 7.40 MB2s
...y/find.go: 178.01 MB / 178.01 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 13.87 MB12s
```

**Comment by harshavardhana** [comment]
Interestingly just a regular FS behaves the same way, i think this issue is not really inside XL anymore. 

```
$ mc mirror ~/tests test/testbucket/test1
...asesRequest.html: 311.79 MB / 6.65 GB  ▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    4.58 % 6.33 MB17m1s
```

Even a multipart is around. 

```
...ests/bigfile.5gb: 1.56 GB / 6.65 GB  ▓▓▓▓▓▓▓▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   23.50 % 15.28 MB5m38s
...
...ests/bigfile.5gb: 3.57 GB / 6.65 GB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░   53.73 % 20.87 MB2m28s
...ests/bigfile.5gb: 3.58 GB / 6.65 GB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ░░░░░░░░░░░░░░░░░░░░░░░░░   53.83 % 20.88 MB2m28s
```

This is just local SSD, provides 250-350MB/sec Removing md5sum check also leads only minor benefit

```
$ mc mirror ~/tests test/testbucket/test3
...ventsResult.html: 230.24 MB / 6.65 GB  ▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    3.38 % 8.17 MB13m20s
...odelRequest.html: 233.00 MB / 6.65 GB  ▓ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    3.42 % 8.20 MB13m19s
```

So we are looking at something else is going on here which needs investigation.

**Comment by darkdragon-001** [comment]
Have there been any further insights on this topic?

**Comment by klauspost** [comment]
@darkdragon-001 Almost everything has changed since this. If you have specific problems open an issue or go to slack for general questions.
