### ISSUE TITLE
Remote buckets are not removed completely

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/minio#16211]
After re-enabling site-replication or re-adding a bucket replication rule:
- 'mc replicate status ALIAS/BUCKET' still shows old/deleted remote buckets or ARN's.

These remote buckets or ARN's also still show up in metrics.

## Expected Behavior
These remote buckets or ARN's should be completely gone.

## Current Behavior
They still show up in metrics and 'mc replicate status'

## Steps to Reproduce (for bugs)
1. Configure site-replication or bucket replication
2. Remove site-replication or bucket replication
3. Re-configure site-replication or bucket replication
4. 'mc replicate status ALIAS/BUCKET'

## Your Environment

* Version used (`minio --version`): RELEASE.2022-11-17T23-20-09Z (commit-id=a22b4adf4c5cc3e4db13fe92da683ef1ce45cd5a)
* Server setup and configuration: 6 nodes, 4 drives each
* Operating System and version (`uname -a`): Linux minio01 5.10.0-15-amd64 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

**Comment by poornas** [comment]
This is intentional to avoid losing information on previously replicated content. If you remove and re-add the site replication config, the replication metrics shown on the new ARN is just for content replicated after the re-configuration. Metrics on objects that were replicated already will show up under the old ARN and will not be re-replicated.

Of course, we can avoid displaying the metrics under older ARN unless user asks for it with a --verbose flag
