### ISSUE TITLE
Allow setting root password in some other form than plaintext

### ISSUE THREAD

**Issue by Krasauskas** [minio/minio#16284]
**Is your feature request related to a problem? Please describe.**
Right now there does not seem to be a way to not have the root password stored in a plaintext file and have the servers survive reboots.

**Describe the solution you'd like**
`MINIO_ROOT_PASSWORD` should accept a hashed password. `/etc/shadow` format comes to mind first, but anything that's not plaintext would be better, really.

**Describe alternatives you've considered**
Setting the password in a shell session, but that means every service/server restart requires that.

**Comment by harshavardhana** [comment]
@Krasauskas you should be using Kubernetes and borrowing this from the vault - MinIO is not really dictating how to protect it 

- as there are many ways to protect credentials
- launch MinIO sandboxed in such environments

These practices already exist and are well established. We do not really wish to re-invent the wheel here by making incompatible implementations or hard-to-use ones.

Securely saving credentials is a job of vault, and this vault provides mechanisms to trust the nodes running MinIO with vault via mTLS . After such a handshake runs MinIO under a sandboxed environment where the root credentials are only available and not part of the OS namespaces.

**Comment by Krasauskas** [comment]
This is such a backhanded response :( We don't have a usecase to run Kubernetes - all we need is an object store.
Hashing a password is so far from reinventing the wheel I'm actually speechless.

**Comment by harshavardhana** [comment]
> This is such a backhanded response :( We don't have a usecase to run Kubernetes - all we need is an object store.
> Hashing a password is so far from reinventing the wheel I'm actually speechless.

Hashing passwords doesn't lead to anything in our case.  We still need to know what the original secret is - your argument of the basis of this on /etc/shadow means someone has to interactively enter these passwords to start a distributed service and every single interaction with the service henceforth.

k8s secrets, and vault secrets are all designed for this purpose. If you want more secure functionalities then you must make secure choices as well for your infrastructure.

**Comment by klauspost** [comment]
@Krasauskas This is not just *validating* a password - the server needs to know that actual password - not just a hash to compare against. So the password would need to be *encrypted* and not *hashed*.

And if the server can decrypt the password so can anyone else. Thus gaining you nothing but false security.

**Comment by Krasauskas** [comment]
Thank you guys, it makes more sense now. One last follow up - why does the server need to _know_ the password?

**Comment by klauspost** [comment]
For request signatures: https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

This allows HTTP transport without leaking the keys.

**Comment by ravindk89** [comment]
@Krasauskas it's worth noting that if using an environment file (as our docs do), you can also use standard Linux file permission semantics to add a layer of protection. For example, ensuring `/etc/default/minio` is only readable by the `minio-user` user or root. In a case like that, someone would have to break into `root` (since we recommend creating `minio-user` as a system user, not one you can log in as) to gain access to the keys - and if someone gets root on one of your boxes, them having access to MinIO's configuration envvars is the least of your worries.

You *could* also experiment with systemd configuration options like `ExecStartPre=` where you include some sort of decrypt protocol as part of starting the service. But that's basically going to be touching on Harsha's suggestion (hooking up the proccess startup with a vault-based en/decrypt setup). That's not MinIO's wheelhouse.

At the least I'll put it on my ToDo list to experiment a little bit with Linux permissions to see if we can come up with an optimized recommendation to limit access to /etc/default/minio such that any other non-root user on the system would fail to read its contents.
