### ISSUE TITLE
GitLab infinite loop when using Minio S3 as registry storage

### ISSUE THREAD

**Issue by nkukard** [minio/minio#16362]
I'm cross-posting an issue logged against [GitLab issue 386845](https://gitlab.com/gitlab-org/gitlab/-/issues/386845) where when using Minio S3 as a registry storage backend an infinite loop is encountered when removing manifests.

I've had some time over the past two days to test more extensively and tried AWS, Scaleway, Vultr and OVH object storage services and couldn't reproduce. It seems to only affect Minio (and providers using Minio) as far as I can see.

The issue is present with Minio 2023-01-02.

I'm suspecting the response returned by Minio is possibly different to other S3 object storage services, or possibly the result of requests against objects differs.

I'm more than willing to assist in any way I can if anyone can point me where I can maybe start looking in the code and possibly what to look for.

## Expected Behavior

No infinite loop when using as a GitLab S3 storage backend.

## Current Behavior

Infinite loop in GitLab after a few minutes when removing a registry manifest.

## Possible Solution

I've not found one yet.

## Steps to Reproduce (for bugs)

Full details in [GitLab issue 386845](https://gitlab.com/gitlab-org/gitlab/-/issues/386845).

I can assist on Slack if there are any questions, assistance or help needed reproducing and also more than willing to assist in any way I can to debug.

## Context

I'm trying to use Minio as a S3 backend for GitLab, I configured all GitLab storage backends to use S3 and after testing a bit I found that removing registry manifests caused GitLab to choke due to an infinite loop.

I created the simplest minimum working example I could and created an issue on GitLab's project page. At first I thought it affected all S3 storage backends, but after further testing over the past 2 days as far as I can see it only affects Minio.

## Regression

I don't think so. At least not in Minio. Using a few GitLab versions back there is no inifinite loop with Minio, so that is definitely new. I checked their commit history and their issues and they seem to of made some changes regarding removing of manifests.

The fact of the matter is it works with other S3 providers, so we need to determine whats up with what its doing when interacting with Minio.

## Your Environment

My minimum working example uses the official Minio docker container and official GitLab docker container with docker-compose. Latest versions tested last on 2023-02-05.

On a side note, I've tested it out on 3 completely different systems and on a VM just to be 100% sure it is not something to do with my setup.

**Comment by harshavardhana** [comment]
@nkukard please capture `mc admin trace -v`  output for this entire run when you are deleting the manifests

We need to see which call returns an erroneous response.

**Comment by nkukard** [comment]
@harshavardhana no probs.

Loop starts at around 2023-01-05T04:00:06.784

This is from startup to when the issue occurs (a job gets run when there is a pending registry manifest removal).

The log is huge due to the loop, 1MB for just a few seconds. I put it in a pastebin. I'm unsure of what would be relevant and I don't want to flood this issue with cruft. Could I kindly ask if you could copy out what is relevant into the issue?

https://paste.linux.chat/?92f692a9e0ad409b#8AndgUkSf6Dj8mFCZwgTR84ukvqJZrLVMcBv9bwmvWWF

**Comment by harshavardhana** [comment]
This looks like a bug in GitLab @nkukard we return back the `ContinuationToken` if the client needs to query for the next elements it is simply asking it again and again?

```
minio:9000 [REQUEST s3.ListObjectsV2] [2023-01-05T03:53:17.649] [Client IP: [64:ff9b::1:2]]
minio:9000 GET /registry?list-type=2&max-keys=1&prefix=
minio:9000 Proto: HTTP/1.1
minio:9000 Host: minio:9000
minio:9000 X-Amz-Date: 20230105T035317Z
minio:9000 Accept-Encoding: gzip
minio:9000 Authorization: AWS4-HMAC-SHA256 Credential=testtest/20230105/none/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=f664b5704b431e81ca496b2783fc5989a248da951a63a8e7a4a88385b7199221
minio:9000 Content-Length: 0
minio:9000 User-Agent: docker-distribution/v3.61.0-gitlab (go1.18.7) aws-sdk-go/1.44.64 (go1.18.7; linux; amd64)
minio:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
minio:9000 
minio:9000 [RESPONSE] [2023-01-05T03:53:17.651] [ Duration 1.614ms  ↑ 93 B  ↓ 894 B ]
minio:9000 200 OK
minio:9000 Vary: Origin,Accept-Encoding
minio:9000 X-Content-Type-Options: nosniff
minio:9000 Accept-Ranges: bytes
minio:9000 Content-Length: 894
minio:9000 Content-Security-Policy: block-all-mixed-content
minio:9000 Content-Type: application/xml
minio:9000 Server: MinIO
minio:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
minio:9000 X-Amz-Request-Id: 17374D512DF22AA0
minio:9000 X-Xss-Protection: 1; mode=block
minio:9000 <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>registry</Name><Prefix></Prefix><NextContinuationToken>ZG9ja2VyL3JlZ2lzdHJ5L3YyL2Jsb2JzL3NoYTI1Ni8wOC8wOGQ5OWY4YWVlZTU1MGQyOTIzZjE2ZDVlY2RjZWQ4ZGM3NTRkMGQ3ZWJlZWRhNTJhMTE3M2M3OGE5YmYyNmEzL2RhdGFbbWluaW9fY2FjaGU6djIscmV0dXJuOl0=</NextContinuationToken><KeyCount>1</KeyCount><MaxKeys>1</MaxKeys><Delimiter></Delimiter><IsTruncated>true</IsTruncated><Contents><Key>docker/registry/v2/blobs/sha256/08/08d99f8aeee550d2923f16d5ecdced8dc754d0d7ebeeda52a1173c78a9bf26a3/data</Key><LastModified>2023-01-03T09:28:35.153Z</LastModified><ETag>&#34;5d41810a8b00c34dbab4597cb124e560&#34;</ETag><Size>740</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
```

And the key is already returned as part of the response.

**Comment by harshavardhana** [comment]
Okay I see the problem this is to do with versioning, GitLab is not aware of versions and it creates delete markers only on the MinIO and recursively waits on it because the "top-level" prefix is not purged yet as there are versioned objects inside a prefix.

and there is no way GitLab can use versioned buckets here - so not sure why are you using versioning in the first place here.

> I logged into minio on http://localhost:9001 using `testtest/testtest`and created buckets (I enabled versioning for all of them as this is mandatory/default for almost any cluster setup)...I logged into minio on http://localhost:9001/ using testtest/testtestand created buckets (I enabled versioning for all of them as this is mandatory/default for almost any cluster setup)...

This is not mandatory not sure where this is documented as such. If you use a registry bucket to be versioned then the GitLab application must know to delete the actual content by using ListObjectVersions() API instead of ListObjectsV2().

I don't know how this works with other vendors though.

**Comment by nkukard** [comment]
That is a bit weird. When I tested to compare other providers I used versioning too. Here is the screenshot from AWS I tested with last night...

https://imgur.com/b7Vqffp

In terms of why I'm using versioning, I have 3 sites which are replicated so versioning is enabled because of that.

**Comment by nkukard** [comment]
@harshavardhana you are 100% correct that it is related to versioning, thanks so much for picking this up! I removed the bucket, recreated it without versioning and I cannot reproduce the issue.

I then tested again with AWS, I removed my versioned bucket, created it again and ensured versioning was on. I then pushed 2 manifests and proceeded to delete them. The odd thing is it works with AWS.

At least I know where to look now, thanks.

**Comment by harshavardhana** [comment]
I will explain after I gather some information and where exactly this behavior has some changes.

**Comment by harshavardhana** [comment]
Okay, there is no purge actually working here, it is quite simply creating DELETE markers and leaving all the content in there. So if you are assuming that your repo is "DELETED" it is not. 

It will be always around. 

On AWS S3 its the same situation too however there is a slight difference in how the folders get listed when an object "key" has a DEL marker.

On MinIO for example 

```
bucket/foo/parent/1.txt
```

if you create let's say `1.txt` to have a DEL marker AWS does not list the `bucket/foo/parent/` folder i.e because it's a flat key name for them unlike MinIO
where the parent exists independently of the object as a folder on the filesystem.

So on MinIO when `1.txt` has a DEL marker the parent gets listed when you do

```
ls bucket/foo/
parent/
```

NOT on AWS S3. This is a key difference perhaps that is confusing the GitLab code. However, I would argue here that if GitLab code needs to purge content on the versioned bucket it must use ListObjectVersions() API instead of calling ListObjectsV2() which will only return latest objects without version ID.

This kind of process would accumulate content and you won't know that older data still exists on the namespace causing confusion eventually. 

So if you are going to use versioning on the buckets you need to make sure that application is aware of it too, this is how AWS S3 expects versioning to be used. If you are not aware of it then it can lead to a confusing state of affairs.

I am going to close this issue as there is nothing actionable here for MinIO.
