### ISSUE TITLE
metadata has incomplete body appears every six hours

### ISSUE THREAD

**Issue by naughtyGitCat** [minio/minio#16513]
# env
linux: 3.10.0-693.el7.x86_64
server:  `/home/dba/minio/minio server --console-address=AAA.BBB.CCC.DDD:9001 http://AAA.BBB.CCC.DDD/data1/ http://AAA.BBB.CCC.DDD/data2/ http://AAA.BBB.CCC.DDD/data3/ http://AAA.BBB.CCC.DDD/data4/ http://AAA.BBB.CCC.DDD/data5/ http://AAA.BBB.CCC.DDD/data6/`

# Current Behavior
the minio server log shows this info, every six hours.
```
API: ListObjectsV2(bucket=bak)
Time: 06:00:02 UTC 02/01/2023
DeploymentID: 923cc9d9-1720-4e2c-8256-33028b3193d8
RequestID: 173F9DE7275E11F6
RemoteHost: AAA.BBB.CCC.DDD
Host: AAA.BBB.CCC.DDD:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.23 mc/RELEASE.2022-03-17T20-25-06Z
Error: Resuming listing from drives failed reading first part metadata: .minio.sys/buckets/bak/.metacache/4e1af0cb-0299-4ddb-b0f7-a16fe
063adb7/block-0.s2 has incomplete body, proceeding to do raw listing (*fmt.wrapError)
       6: internal/logger/logger.go:258:logger.LogIf()
       5: cmd/metacache-server-pool.go:214:cmd.(*erasureServerPools).listPath()
       4: cmd/erasure-server-pool.go:1316:cmd.(*erasureServerPools).ListObjects()
       3: cmd/erasure-server-pool.go:1190:cmd.(*erasureServerPools).ListObjectsV2()
       2: cmd/bucket-listobjects-handlers.go:246:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

## Context
* is this a serious error?
* how can i fix it

**Comment by vadmeste** [comment]
@naughtyGitCat why did you remove the issue template? what is MinIO version here ?

This can happen when you have networking issues between your nodes or maybe the cluster is overloaded with requests and your hardware cannot follow. This is not dangerous and even listing result will be correct in that case since it is using a fallback listing mechanism as the error mentionned.

**Comment by naughtyGitCat** [comment]
sorry for removing the template, and missing the minio server version.

minio: ` RELEASE.2023-01-25T00-19-54Z (commit-id=50d58e9b2dbbfbe2f3afa2c16ae701f9c1cf03ec)`

this is one node run on same host,with command like `/home/dba/minio/minio server --console-address=AAA.BBB.CCC.DDD:9001 http://AAA.BBB.CCC.DDD/data1/ http://AAA.BBB.CCC.DDD/data2/ http://AAA.BBB.CCC.DDD/data3/ http://AAA.BBB.CCC.DDD/data4/ http://AAA.BBB.CCC.DDD/data5/ http://AAA.BBB.CCC.DDD/data6/`

this  should not be a network issue

**Comment by vadmeste** [comment]
@naughtyGitCat what type of disks are you using ? JBOD, NFS, .. ?

**Comment by naughtyGitCat** [comment]
![image](https://user-images.githubusercontent.com/20264659/216026310-052c1dda-2471-4c58-97d1-b0cd45893a3d.png)
SATA DISK with 40 core and 128G RAM

**Comment by klauspost** [comment]
No, this is not serious, this is expected fallback.

You should however not specify servers as you are doing. See https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html#sequential-hostnames

We recommend XFS as backend file system, since ext4 has limitations and rare flakyness.

**Comment by naughtyGitCat** [comment]
thanks
