### ISSUE TITLE
Add extension to work with tar.xz archives on the fly

### ISSUE THREAD

**Issue by Shumek** [minio/minio#16691]
**Is your feature request related to a problem? Please describe.**
I have a lot of pdf files with similar data loaded into minio, and I want to archive them. 

**Describe the solution you'd like**
Minio already has an extension to work with zip files https://github.com/minio/minio/tree/master/docs/extensions/s3zip and I want the same but for tar.xz format because LZMA algorithm is good for compressing similar files. I know that decompressing a single file from xz archive is slower and requires more CPU power, but we're using self-hosted solution and we think that it's fine for us :)

**Describe alternatives you've considered**
7z format is also okay because it also uses LZMA.

**Additional context**
zip compresses such similar pdfs with 95% compression ratio, while 7z/xz have 6% compression ratio.

**Comment by klauspost** [comment]
No.

Longer version:

We do not see a need for 7z. It is a complex format and there are no good Go tools for it. Secondly LZMA is too slow in decompression and requires too much memory, even when using the best tools. Thirdly, there is no tool to provide [indexing](https://github.com/minio/zipindex) which we need. ZIP is available in virtually any programming language, whereas 7zip is much less available Fourthly, 7z archives are usually "solid", meaning you cannot decompress a single file without having to decompress a lot of unneeded data - this is probably why you are seeing so much compression, but it makes it useless for this purpose.

We do not want to add a format that will be rarely used and can only be used with big limitations.

Finally, it you are looking for better compression you can use `zstandard` for files inside zip files. If you use method `93` you can use zstd compression for individual files. This is not documented, since it require some specialist knowledge to use.

**Comment by klauspost** [comment]
- `tar.xz` or any `.tar.???` will not work, since there is no central index and parsing will require full decompression. Accessing a single file will have the same problem.

We support archives that can be hundreds of gigabytes in total size and having to spend minutes on indexing is not an option.
