### ISSUE TITLE
Profiler: Block profiling failing. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1669]
Not able to run the interactive profiler on the block profile generated. Getting the following error 

`parsing profile: unrecognized profile format`

**Comment by harshavardhana** [comment]
This is not entirely fixed yet, still able to reproduce the problem with latest master.

**Comment by harshavardhana** [comment]
This is actually fixed, I tried multiple packages the issue of 'unrecognized format' was not block.pprof being readable. In-fact mem and block profile are always readable they are not in gob format like cpu.pprof.  The issue was the order of arguments on the command line, giving profile output first and then binary later. 

User error :( at best. closing.
