### ISSUE TITLE
Helm Chart: Don't run the post-job hook with the default service account

### ISSUE THREAD

**Issue by LinAnt** [minio/minio#17076]
The post-job hook runs as the `default` service account which is not recommended. Since the helm chart has support for creating a new service account for the minio service, I suggest we use that instead if available.

**Comment by Gwojda** [comment]
Hi,
Got issue with Post-job :
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-u9ikky4ho1an/?location=": dial tcp 1.2.3.4:9000: i/o timeout.


But minio is working and i can connect with mc from my computer.
I'm using terraform, so my state is fked because of this job :( How can i disable it manually?
thanks,

**Comment by LinAnt** [comment]
Not relevant to this issue, but make sure all the configuration the job takes care of is `null`. Using default `values.yaml` the job will create a user for the minio dashboard. Remove that user and I think it should skip the hook :+1:
