### ISSUE TITLE
MINIO_API_* options explanation

### ISSUE THREAD

**Issue by ddzobov** [minio/minio#17137]
Please explain these options and difference between values in documentation:

**MINIO_API_LIST_QUORUM** - for this one we have only options list ("optimal", "reduced", "disk", "strict"), but nothing about difference and performance
**MINIO_API_EXTEND_LIST_CACHE_LIFE** - this option mentioned only in #10873

**Comment by harshavardhana** [comment]
> Please explain these options and difference between values in documentation:
> 
> **MINIO_API_LIST_QUORUM** - for this one we have only options list ("optimal", "reduced", "disk", "strict"), but nothing about difference and performance **MINIO_API_EXTEND_LIST_CACHE_LIFE** - this option mentioned only in #10873

extend_list_cache_life is deprecated and long removed almost 2yrs ago.

For list_quorum you should be only interested in "strict" no other quorum makes sense for practical purposes. It is available as configurable for internal testing purposes and in some cases during production support.

It is not documented on purpose so that you do not mess around with values that you may not understand. So it will not be documented further than what it already does.

**Comment by ddzobov** [comment]
@harshavardhana if we need to do backup via commvault, which quorum type will be faster for us?
At now, commvault for incremental backups takes about 95% of time for reading meta and only 5% to download data. At this time, MinIO have huge memory comsumption.

Maybe another than strict type will be much more fast for us?

**Comment by klauspost** [comment]
@ddzobov For performance guidelines to your setup see our [subscription offers](https://min.io/pricing).
