### ISSUE TITLE
The specified id cannot delete the replication rule

### ISSUE THREAD

**Issue by hjun881** [minio/minio#17286]
## bug
When I specified the replication rule ID to delete the replication rule, the rule does not exist
![image](https://github.com/minio/minio/assets/18508499/7a37648b-787b-433c-b543-ce056848b57b)
![image](https://github.com/minio/minio/assets/18508499/8cd7051f-289e-4053-8621-95c07f326d8f)

**Comment by shtripat** [comment]
What about `--force` option here?

**Comment by vadmeste** [comment]
@hjun881 what is your mc version ? (mc --version)

**Comment by hjun881** [comment]
@shtripat Adding `--force` is not enough either

**Comment by hjun881** [comment]
@vadmeste 
```bash
[root@mpp106 clickhouse]# mcli -version
mcli version RELEASE.2023-04-12T02-21-51Z (commit-id=1843717c57fb87612469b7610344a7d49d97a497)
Runtime: go1.20.3 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by poornas** [comment]
you should be using `mc replicate rm --all --force alias/bucket` if you are deleting the last / only rule in the bucket. The error message shown is intentional

**Comment by justinhippo** [comment]
I'm having the same issue, but using `--all --force` gives `mc: <ERROR> Unable to remove replication configuration. Cannot alter local replication config since this server is in a cluster replication setup.`. I removed the site replication rules, and confirmed with `mc admin replicate rm --all --force alias` which gives `mc: <ERROR> Unable to remove cluster replication. Invalid site-replication request (site replication is not enabled).` but it still won't delete the last replication rule.

**Comment by poornas** [comment]
@justinhippo , looks like site replication internal config did not get fully removed while doing `mc admin replicate rm` - you can try `rm -rf /path-to-minio/.minio.sys/config/site-replication/state.json` from all nodes in the backend and restart your cluster

**Comment by justinhippo** [comment]
~~I'm running on the kubernetes operator on a Rancher cluster, but can't seem to find a `state.json` on any of my pods...~~
A restart of the pods seemed to fix the site replication state and I was able to delete the remaining replication rules.
