### ISSUE TITLE
Missing FTP-Client commands

### ISSUE THREAD

**Issue by schaefed** [minio/minio#17326]
We are using MinIO as part of a time series management system and are really excited about the new MinIO FTP/SFTP-Server Support. The use case of our system involves relatively simple measurement devices sending data via (S)FTP. Unfortunately quite a few of these devices rely on the ftp `rename` command to send data. [Here](https://github.com/minio/minio/tree/master/docs/ftp#minio-ftpsftp-server) you list both `rename` and `append` as unsupported ftp client commands. Are there any underlyingl reason (apart from missing resources) why these features are currently missing?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Because we cannot possibly give a consistent rename() or append() functionality that won't be racy on object storage.

Remember ftp server still has underlying object storage to use here that has no concept of rename(), append().

We have avoided this on purpose to not overcomplicating FTP. 

Ftp server implementation is to ensure that you can use some older clients, if you want to have full fledged ftp functionality then you might have to look elsewhere for now.

If you have a strong production use case feel free to become our customer https://min.io/pricing and we can look at prioritizing this if this a must have.

**Comment by schaefed** [comment]
Thank you for the fast reply! I really appreciate your efforts!

Just out of curiosity, could you please give me a bit more context about the specific racy issues with especially the `rename` command? How are these issues different from the ones that might also appear in something like `mc mv`?

**Comment by klauspost** [comment]
@schaefed There is no move primitive in S3. These are implemented as copy+delete in mc.  Objects versions are immutable, so no append is possible.

We don't want to add commands to the server that hides underlying complexity. As such we are only interested in functionality that provides basic object ingress/egress and delete functionality.

**Comment by schaefed** [comment]
Thanks again! Would you be willing to accept a PR implementing the ftp-client command `rename` (we don't have a need for `append`)?

**Comment by klauspost** [comment]
It seems to me that RENAME implementation with versioning will result in unclear behavior. Creating a copy and adding a delete marker seems the most reasonable - but adding internal copy behavior is complex. So I tend to think that it will add too much maintenance for what it adds.

I will leave that @harshavardhana

**Comment by harshavardhana** [comment]
> Thanks again! Would you be willing to accept a PR implementing the ftp-client command `rename` (we don't have a need for `append`)?

@schaefed not right now. Thanks for the offer though.
