### ISSUE TITLE
List objects fails with sio.Error 'authentication failed'

### ISSUE THREAD

**Issue by rluetzner** [minio/minio#17377]
## Expected Behavior

I should be able to list objects -- recursively or not -- for a specific prefix.

## Current Behavior

At least one object from a prefix consistently prevents me from listing objects. The list objects request fails with the following error message:

```text
mc ls --versions minio/krmkzs/masdfmm/data/lkasldfkljsdf/ajskldlfdskjl
mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(sio: authentication failed)
```

MinIO is running as a systemd service. Here's the relevant error from the system's journal:

```text
API: ListObjectVersions(bucket=krmkzs)
Time: 08:04:56 UTC 06/06/2023
DeploymentID: 86c7b55e-bad7-4e2c-abff-21a9e6c379c0
RequestID: 17660342E0502334
RemoteHost: 127.0.0.1
Host: ecs3-mal1-miaus1:9001
UserAgent: MinIO (linux; amd64) minio-go/v7.0.46 mc/RELEASE.2023-01-28T20-29-38Z
Error: sio: authentication failed (sio.Error)
6: internal/logger/logger.go:258:logger.LogIf()
5: cmd/api-errors.go:2282:cmd.toAPIErrorCode()
4: cmd/api-errors.go:2307:cmd.toAPIError()
3: cmd/bucket-listobjects-handlers.go:124:cmd.objectAPIHandlers.listObjectVersionsHandler()
2: cmd/bucket-listobjects-handlers.go:63:cmd.objectAPIHandlers.ListObjectVersionsHandler()
1: net/http/server.go:2122:http.HandlerFunc.ServeHTTP()
```

I've taken a look at the code, up to the point where I'm pretty certain the error is coming from the following chain of function calls:

```text
github.com/minio/sio/sio.go:???:sio.DecryptBuffer()
internal/crypto/key.go:132:crypto.ObjectKey.Unseal()
internal/crypto/sse-s3.go:127:crypto.S3.UnsealObjectKeys()
cmd/encryption-v1.go:173:cmd.DecryptETags()
```

I can't follow along anything that goes on in the sio package. Actually, I'm lost even before we get there. Apparently something doesn't match up, when MinIO tries to unseal the secret to decrypt the data / metadata? I'm unsure if I'm supposed to follow the `decryptBufferV20` path or not, but there are only two places in the sio package that return this exact error message. One for `authDecV10` and one for `authDecV20`.

If it helps, we're using KES with a local keystore containing a single encryption key. The key has been distributed to all MinIO nodes and is exactly the same everywhere. We can write and read other files without problems, only this prefix seems to be affected. We haven't touched the encryption key in any way.

As a test I setup a similar system and replaced the encryption key with a different one. That causes a different error. I also triple checked that the encryption keys on the productive system are the same everywhere.

## Possible Solution

None.

## Steps to Reproduce (for bugs)

Sadly I can't say how we got here. We only noticed problems with this prefix recently and it is unclear what exactly was done. Because it contains only a few files (much less than I'd expect) I assume that files have been deleted.

I'm real sorry that I can't help more. I'm hoping that the trace I provided above will be telling for someone with deeper MinIO knowledge.

## Context

I can't recursively list objects from one of my buckets.

I also can't remove the files in the prefix or the prefix itself recursively.

## Regression

I don't know if this is a regression or not.

## Your Environment

* Version used (`minio --version`): RELEASE.2023-05-18T00-05-36Z
* Server setup and configuration:
  * 2 MinIO clusters with 6 nodes each
  * 12 disks per node
  * clusters are using server-side site replication
  * MinIO is running as a systemd service
  * KES is configured as a KMS with a local keystore; the encryption key has been distributed to all nodes and verified to be exactly the same
* Operating System and version (`uname -a`): Linux fs-minio-n1 5.14.21-150400.24.63-default #1 SMP PREEMPT_DYNAMIC Tue May 2 15:49:04 UTC 2023 (fd0cc4f) x86_64 x86_64 x86_64 GNU/Linux
  * OS is a SUSE Linux Enterprise Server 15.4

**Comment by harshavardhana** [comment]
This is not a regression - kes had a bug where the wrong DEK key was used to encrypt the file. The file is basically unreadable at this point i.e it can't be decrypted.


> As a test I setup a similar system and replaced the encryption key with a different one. That causes a different error. I also triple checked that the encryption keys on the productive system are the same everywhere.

If you do things like this it will break more. if you want to purge the object just use `mc rm --purge --force minio/krmkzs/masdfmm/data/lkasldfkljsdf/ajskldlfdskjl`

**Comment by rluetzner** [comment]
Ok...well f*** 😱 . Can you tell me which version of KES was affected, @harshavardhana ? And does this affect all files that were written with this version?

**Comment by rluetzner** [comment]
I went through the changelog of the last few KES releases, but nothing jumped out at me. Is it possible that deploying the old KES version would at least allow me to read the files again and copy them off the system?

I checked the system and apparently we started out with KES 0.22.0 and sometime later updated to 0.22.3. Not sure which version contains the bug or if both did. But at least for a while the files were accessible. And most of the files still seem to work.

**Comment by harshavardhana** [comment]
> Ok...well f*** scream . Can you tell me which version of KES was affected, @harshavardhana ? And does this affect all files that were written with this version?

only some of them not all since it was a transient issue.

**Comment by rluetzner** [comment]
Umm...I don't want to be rude @harshavardhana , but I'm really scared for our data right now. Can you help me a bit with what the best course of action is? Are we safe with KES 0.22.3? Because I couldn't find any obvious fixes for the problem you described in KES' changelog. Or should we just update to the latest KES version? Will it make things worse?

I'm scared that this transient error -- whatever it was and wherever it came from -- will happen again and destroy more data. Any information would be highly appreciated. 😨

**Comment by harshavardhana** [comment]
> Umm...I don't want to be rude @harshavardhana , but I'm really scared for our data right now. Can you help me a bit with what the best course of action is? Are we safe with KES 0.22.3? Because I couldn't find any obvious fixes for the problem you described in KES' changelog. Or should we just update to the latest KES version? Will it make things worse?

I don't know really @rluetzner you are running a production cluster all by yourself we have no way to communicate to you that these issues can come in. This is why we always say don't run a production cluster without support.

> I'm scared that this transient error -- whatever it was and wherever it came from -- will happen again and destroy more data. Any information would be highly appreciated.

You just have to upgrade kes to the latest release to avoid further problems.

**Comment by rluetzner** [comment]
Okay, good to know. I'll discuss MinIO support with the higher-ups. But even so, there's nothing that can be done for the data. Any objects that were encrypted with the wrong key are irrecoverably lost. Or is there anything MinIO support could do for us right now, @harshavardhana ?

**Comment by harshavardhana** [comment]
> Okay, good to know. I'll discuss MinIO support with the higher-ups. But even so, there's nothing that can be done for the data. Any objects that were encrypted with the wrong key are irrecoverably lost. Or is there anything MinIO support could do for us right now, @harshavardhana ?

I think no it's not possible @rluetzner unfortunately.

**Comment by harshavardhana** [comment]
I am going to close this since it was fixed properly on our end, however there is no retroactive fix here.

**Comment by rluetzner** [comment]
>I think no it's not possible @rluetzner unfortunately.

Thank you for your help @harshavardhana . I was just going to close this myself. If I turn up more information on which versions of kes contain this bug and the change that fixes it, I'll add them here. 🙂

**Comment by omarkohl** [comment]
@harshavardhana could you point to the specific KES commit where this issue was fixed?

> you are running a production cluster all by yourself we have no way to communicate to you that these issues can come in

Prominently featuring such severe (irretrievable data loss!) issues in the changelog would be helpful.

**Comment by harshavardhana** [comment]
> Prominently featuring such severe (irretrievable data loss!) issues in the changelog would be helpful.

It was fixed in a private branch 

```
commit baaed6bab8237b7fe4220cefba199607ceb2d659
Author: Andreas Auernhammer <hi@aead.dev>
Date:   Wed May 3 21:09:59 2023 +0200

    key: Sync Get access to the key store
    
    This commit prevents concurrent read access
    to the key store wrapped by the key manager.
    
    This prevents cases, where KES receives many
    requests that try to fetch a key (which is not
    in the cache) concurrently, and therefore, issues
    multiple concurrent requests to the key store.
```

It has the potential to affect some objects not all since it 
was a race, that's why we never heard of it for a long time.

However in the upstream branches we had re-implemented it so - 
so there is no direct "evidence" of a fix because it existed 
in some releases and then it didn't. 

That's why building some production clusters in silos without 
involving MinIO support folks is a big no-no if you do you 
are on your own @omarkohl

You need to do your own due diligence as we have no idea
how you are using the software, whether is it supported 
environments etc.

**Comment by rluetzner** [comment]
I'm a bit surprised by the date @harshavardhana . The last KES release is from the day before. The only thing I can find that coincides with this and is roughly about the same subject matter is the following commit.

```text
commit 0b32a5dc775201811ccdaa62f88732e863ca556c
Author: Andreas Auernhammer <hi@aead.dev>
Date:   Fri May 5 15:50:32 2023 +0200

    keystore: improve caching mechanism
    
    This commit replaces the existing key caching
    with a new keystore caching implementation.
    
    Therefore, this commit adds a new `internal/cache`
    package with provides:
     - The `cache.Cow` type, a copy-on-write
       concurrency-safe cache.
     - The `cache.Barrier` type, a concurrency primitive
       that provides mutual exclusion for sets.
    
    The new `keystore.Cache` type is now built on top
    of these two primitives.
    
    The `cache.Cow` is a type-safe, concurrency-safe
    and reader-optimized cache implementation.
    It is well-suited as primitive for the `keystore.Cache`
    since KES requests mostly read keys. Writing a key,
    fetched from the KMS keystore, into the cache is a
    rare operation.
    
    For many concurrent readers, a `cache.Cow` is a
    better fit than a map with a `sync.Mutex`.
    
    ***
    
    The `cache.Barrier` is a locking primitive that
    prevents a subtle issue in the previous cache
    implementation.
    
    In general, the `keystore.Cache` should avoid
    requesting the same key multiple times. For example,
    given N concurrent requests trying to access some
    key `A`, the cache should only request `A` from
    the key store once and serve the remaining N-1
    request from the cache.
    So, at any given point there should be at most
    one request fetching `A` from the keystore while
    the remaining N-1 requests wait until:
     - The active request succeeded to fetch `A`.
     - The active request failed. In this case
       the next request can try to fetch `A`.
    
    On the flipside, blocking N-1 requests for `A`
    should not block an incoming request trying to
    fetch `B`.
    So, a simple `sync.Mutex` is a suboptimal solution
    since it serializes access to the keystore. Instead,
    we want to serialize access per key.
    
    Such a serialization mechanism is implemented by
    the `cache.Barrier` type. It is used very similar
    to a `sync.Mutex`. Instead of `Lock` call `Lock(key)`
    and instead of `Unlock` call `Unlock(key)`.
    
    Various `cache.Barrier` implementations have been
    tested, including ones build using lock-free primitives.
    However, the current one seems to perform best w.r.t
    lock contention:
    
    ```
    goos: darwin
    goarch: arm64
    pkg: github.com/minio/kes/internal/cache
              │ /Users/andreas/Desktop/1key_1000g_a.txt │  /Users/andreas/Desktop/1key_1000g_b.txt  │
              │            sec/op            │    sec/op     vs base          │
    Barrier-8                    392.8µ ± 2%   498.7µ ± 68%  ~ (p=0.089 n=10)
    
    goos: darwin
    goarch: arm64
    pkg: github.com/minio/kes/internal/cache
              │ /Users/andreas/Desktop/5key_1000g_a.txt │      /Users/andreas/Desktop/5key_1000g.txt       │
              │            sec/op             │     sec/op      vs base                  │
    Barrier-8                     509.0µ ± 1%   11234.3µ ± 24%  +2107.33% (p=0.000 n=10)
    ```
    
    Signed-off-by: Andreas Auernhammer <hi@aead.dev>
```

But this commit is in none of the KES releases. Is there a chance the fix was not yet released after all?

----

Edit: I'm talking about the last available KES release on GitHub: [Release 2023-05-02T22-48-10Z](https://github.com/minio/kes/releases/tag/2023-05-02T22-48-10Z).

**Comment by harshavardhana** [comment]
> But this commit is in none of the KES releases. Is there a chance the fix was not yet released after all?

No it has been fixed for some time now, it is just that there is no direct evidence of the fix due to refactors and re-implementations.

I can only make educated guesses about your environment - I have no idea how you set it up before when you started the cluster, and how all this came to be - for all of this we need to look at the data in question and understand the order of events.

For me to spend that much amount of time currently is not possible.

**Comment by rluetzner** [comment]
Well the commit you posted above is about a month old. Depending on your definition this might be "some time now", but it seems pretty recent to me. Additionally it coincides pretty well with the commit I posted, so that is where I would start looking.

Could you post the diff of the private fix, so we can figure it out ourselves?

Right now there's no need to look at any logs or data or reconstruct any chain of events. But I would really like to understand how this could happen and be certain that it is fixed.

And again: if it is in the commit *I* posted above, it is not yet released.

**Comment by omarkohl** [comment]
> That's why building some production clusters in silos without
involving MinIO support folks is a big no-no if you do you
are on your own @omarkohl

I understand that neither you @harshavardhana nor anyone else in the MinIO community is under any obligation to provide any kind of support. All I said is that it would be helpful if such severe issues were **prominently featured in the changelog**. There are KES versions affected by the issue and others that are apparently not. Anyone currently using an affected KES version or anyone who used one in the past should ideally have the option of becoming aware of this issue by **proactively checking the changelogs and other public documentation** that you provide in order to salvage as much data as possible, for instance by updating the KES version or by trying to read back potentially affected data and recovering it from a backup etc.

> there is no direct "evidence" of a fix because it existed
in some releases and then it didn't.

Could you specify which KES releases are affected and which are not?

Are you absolutely certain that in release [Release 2023-05-02T22-48-10Z](https://github.com/minio/kes/releases/tag/2023-05-02T22-48-10Z) the issue has been fixed?

**Comment by rluetzner** [comment]
Maybe you can help figure this out @aead . The commit message Harshavardhana posted in [an earlier comment](https://github.com/minio/minio/issues/17377#issuecomment-1587637901) came from you and fixed the behavior on a private branch.

I've now spent more than a week looking through the diff between KES v0.22.0 (which according to my experience contains a bug, as described by my initial report) and the latest KES "master" (1e46c482c170614d9e61f16b50de39cac3593a22), but was unable to figure out what caused the behavior and which change fixes it. The reason why I am trying to figure this out is to have full **confidence** that I can update to the latest KES version and the problem will be gone.

Here's a summary of what I understood from the discussion so far.

* "kes had a bug where the wrong DEK key was used to encrypt the file."
  * The datatype only consists of a plaintext and ciphertext. The only way I could interpret the last sentence is that there's a chance that plaintext and ciphertext do not match up.
* It's a transient error, so only a few objects are affected.
* This seems to be a race condition.

But I fail to understand how concurrent access to an encryption key could cause such a behavior.

> This prevents cases, where KES receives many
> requests that try to fetch a key (which is not
> in the cache) concurrently, and therefore, issues
> multiple concurrent requests to the key store.

The above quote is talking about the encryption key that is used to generate the ciphertext in a DEK, not the DEK itself.

What's bugging me is that we're using a single consistent encryption key. It hasn't been changed, it hasn't been updated. We're not connecting to another KMS, but using a file on the local filesystem. It shouldn't matter if multiple requests cause KES to access the file and read it multiple times instead of caching it. The contents of the encryption key do not change. Even if KES is accessing a KMS it seems reasonable to assume that the KMS will always return the same key no matter how many concurrent requests are made.

How exactly can we end up with a DEK where the plaintext and ciphertext values don't match up? I fail to see it in the code. Or what else is meant by "kes had a bug where the wrong DEK key was used to encrypt the file."?

I am investing significant amounts of time into debugging an issue which would resolve itself with clear communication by the MinIO team. **We are talking about a bug that causes irreversible data loss.** This affects at least people who are still using older KES versions (maybe even the newest one?) and also affects people who at some point used an older KES version because they could unknowingly have data that is encrypted and no longer readable. The more time passes the less likely it is this data can be recovered from another source. It is surprising to me that this does not receive more attention.

# Concrete Questions

* Can you describe the underlying technical cause of the bug?
* Which KES releases are affected and which are not?
* Can you post a diff of the bugfix? e.g. the diff of the commit 0b32a5dc775201811ccdaa62f88732e863ca556c from the private branch?
* Are you certain that [Release 2023-05-02T22-48-10Z](https://github.com/minio/kes/releases/tag/2023-05-02T22-48-10Z) of KES no longer contains the bug? Note that there are several commits in "master" that are not part of this release.

**Comment by klauspost** [comment]
@rluetzner We do not provide the analysis you are requesting as a community service.

I suggest you talk to your upstream managers about getting a [support subscription](https://min.io/pricing).

**Comment by aead** [comment]
@rluetzner I'm very sorry for the inconvenience. Let me clarify what probably happened here.

> Can you describe the underlying technical cause of the bug?

First, there are two different bugs that potentially could cause an error like:
```
mc ls --versions minio/krmkzs/masdfmm/data/lkasldfkljsdf/ajskldlfdskjl
mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(sio: authentication failed)
```

One (which most likely does not affect you) is very dangerous since it can lead to data corruption. 

The other one is a bug in the S3 replication implementation w.r.t. S3 ETags. This bug is, compared to the other, not critical. I assume your object was an SS3-S3 replicated object. This bug has been fixed by https://github.com/minio/minio/commit/ad4e511026794cadd71790111bea70b3ff49e83e

***

Now, I explain the technical details of the dangerous data corruption bug that affected KES.
In particular, it only affected KES + Hashicorp Vault. Specifically, KES used to create a key at the backend KMS and, if this succeeded, put the key directly into its in-memory cache. Ref: https://github.com/minio/kes/blame/v0.15.1/internal/secret/store.go#L115-L118

Conceptually, this is fine as long as the KMS backend returns success if and only if it persisted the key. Well, this was not the case for Hashicorp Vault - more precisely for the Vault Go SDK. Ref: https://github.com/minio/kes/commit/c4379cec46572b1359854d0f73ac6ea734cab3df

The Vault SDK used by KES to talk to the Vault server would not always return a non-nil error when the creation of a secret failed. For example, `_, err := s.client.Logical().Write(location, data)` may return `err == nil` in cause of some network connection issue causing the request to fail.
However, KES - seeing an `err == nil` considered the request to be successful, and therefore, stored the key in its in-memory cache.

This behavior could lead to situations where e.g. two KES servers end up with two different keys in the their caches.
One key will be the one persisted at Vault. However, the other never got persisted and will be gone forever - once the cache expires or the server restarts. If you would have used this key for encryption you will loose your encrypted data. 

***

> Which KES releases are affected and which are not?

This bug affected KES versions before `v0.16.0` and in `v0.17.1` KES implemented a workaround for the unexpected Vault SDK behavior. In particular, KES `v0.16.0` stopped putting the key into the cache on creates. Instead, only reads can put an entry in the cache. This adds one extra round trip after key creation but is more resilient.

> Can you post a diff of the bugfix?

Sure, but as stated there are two different issues. The replication issue that can cause the `sio: authentication failed`
error is fixed by: https://github.com/minio/minio/commit/ad4e511026794cadd71790111bea70b3ff49e83e 
As said, this issue is **not** the one causing corrupted objects by using an non-persistent encryption key.

The specific fix for the Vault SDK behavior is: https://github.com/minio/kes/commit/c4379cec46572b1359854d0f73ac6ea734cab3df

***

> Are you certain that [Release 2023-05-02T22-48-10Z](https://github.com/minio/kes/releases/tag/2023-05-02T22-48-10Z) of KES no longer contains the bug? Note that there are several commits in "master" that are not part of this release.

Yes, the Vault SDK issue has been fixed 2 years ago.

***

I hope I was able to clarify some of your questions. Otherwise, let me know.
Best regards.
