### ISSUE TITLE
Write failed. Insufficient number of drives online -- Error

### ISSUE THREAD

**Issue by drohnow** [minio/minio#17555]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

Summary:
We have a 6 pod ha minio environment in a  3 node kube cluster for over 5 months. All was working well until we encountered the following errors in logs on each of the pods:

Error: Unable to initialize backend: Storage resources are insufficient for the write operation .minio.sys/tmp/8a8a6367-82be-4874-9ef1-ffa22120e8c2/d3dea701-4e60-4a73-9558-502dd6a38413/part.1, retrying in 3.781393211s (*fmt.wrapError)

Error: Write failed. Insufficient number of drives online (*errors.errorString)

## Expected Behavior
Minio object store will continue to function.

## Current Behavior
The minio pods are online but throwing the above mentioned errors.  Restarted pods but errors persist.

## Steps to Reproduce (for bugs)
I attempted to reproduce in a lab environment but was not able to.

## Context
Application that utilizes minio as object store is currently offline

## Your Environment

* Version used (`minio --version`): 2022-10-20T00-55-09Z
* Server setup and configuration: 3 node kube cluster -- 1.21.14
* Operating System and version (`uname -a`): Ubuntu 20.04.6 LTS

**Comment by harshavardhana** [comment]
Please upgrade your setup to latest release. This looks like your setup is having some quorum issues.

**Comment by drohnow** [comment]
Unfortunately an upgrade in the environment is not possible at this time.

Understood this is a quorum issue; is there a way to remdiate without upgrading?

how does Minio achieve quorum?

**Comment by harshavardhana** [comment]
Well if you running a critical system as community user (not advisable). So it is largely self support @drohnow. 

What it shows is that we are not able to write to disks.

- network
- disk permissions
- failed disks 

Are all responsible here. You need to verify those.

My advice you are better off registering with us as a customer where we can provide more detailed analysis.

I am going to close this since this is non actionable for us until you upgrade, there may be legitimate bugs fixed that require an upgrade. 

If the upgrade also shows the same issue, please reply here we will reopen this issue . At that time please do share full server logs from all nodes for a 24hr period.

Thank you.
