### ISSUE TITLE
`mc admin config set identity_ldap` should emit an error but doesn't

### ISSUE THREAD

**Issue by feorlen** [minio/minio#17790]
Per @donatello, the following outdated but still functional command should emit an error (or warning?) It does not.
```
mc admin config set myminio identity_ldap identity_ldap_server_insecure="on" server_addr="example.com:389" lookup_bind_dn="cn=admin" lookup_bind_password="pass" user_dn_search_base_dn="dc=foo" user_dn_search_filter="(cn=%s)"
```

The older style `mc admin config set identity_ldap` commands still work, but the newer `mc idp ldap` ones are preferred.

**Comment by harshavardhana** [comment]
Older ones work because newer ones are simply a wrapper around older ones. We do not simply have to document them. 

I do not think we should error out in previous behavior, we may throw a warning but if its documented with new CLI - I do not think anyone would even want to use older style.

I already see customers adopting to the newer command line.

This doesn't need any fixing AFAICS on the server side.
