### ISSUE TITLE
Multi-language support for the repository

### ISSUE THREAD

**Issue by SnmzMert** [minio/minio#17931]
**Multi-language support for the repository**

_Translating the .md files of this repository into different languages can help it reach a wider audience. If you agree to this, I can start with the Turkish language._

**Comment by klauspost** [comment]
Thanks for the offer!

The README isn't really anything but a quick getting started, which may be simplified a lot, since the main docs are on [docs.min.io](https://min.io/docs/minio/kubernetes/upstream/index.html).

To be honest I see it more realistic that the README will mostly be a link to the official documentation at some point in the future. Maybe with some developer specific information - but not aimed at users of the server. I am speculating as we have no specific plans at the moment.
