### ISSUE TITLE
Permission denied when running `mc` binary inside docker image

### ISSUE THREAD

**Issue by ab-andresc** [minio/minio#18015]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

mc should run, instead permission denied

## Current Behavior

 docker run --entrypoint bash -it quay.io/minio/minio:RELEASE.2023-07-07T07-13-57Z
[root@b602200e6371 /]# mc
bash: /opt/bin/mc: Permission denied
[root@b602200e6371 /]#

Instead I should see this screen.

~ $ mc
──────────────────────────────────────────────────────────────────────────────────────────────── (q)uit/esc
NAME:
  mc - MinIO Client for object storage and filesystems.

## Possible Solution

CI likely needs to chown image

## Steps to Reproduce (for bugs)

docker run --entrypoint bash -it quay.io/minio/minio:RELEASE.2023-07-07T07-13-57Z
[root@b602200e6371 /]# mc

## Context

Trying to run mc for a live migration

**Comment by ravindk89** [comment]
https://github.com/minio/minio/releases/tag/RELEASE.2023-08-04T17-40-21Z

This is likely addressed as part of this PR. Use a newer or latest stable image of MinIO. If you encounter the issue again you can re-open this issue with further logging.

Context: This is due to the Helm chart being slightly out of date. Any user can update the Community Helm Chart to follow latest stable.
