### ISSUE TITLE
Helm Chart - missing health probes in the chart ?

### ISSUE THREAD

**Issue by adlnc** [minio/minio#18178]
Hi, I'm just wondering why there are no readiness/liveness probes configured by default in the helm chart provided within this repository.
Everything seems documented and available.
https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html#healthcheck-api
Is it just missing from the chart and I could propose that tiny change or am I missing something here ?

Thanks for your help

**Comment by opencmit2** [comment]
@adlnc  I think I should be able to complete this task.

**Comment by WVenus** [comment]
Hi @adlnc 
  It does lack some detection functionality and I'd be happy to help you add these small changes

**Comment by opencmit2** [comment]
Hi @adlnc
It does lack some detection functionality and I'd be happy to help you add these small changes

**Comment by jiuker** [comment]
We can't detect whether the whole cluster is healthy or not as a criterion. This is because the startup itself can be time-consuming, leading to liveness failures or readness failures. Infinite self-restart.
You can also found that the k8s's etcd will not config the liveness about the cluster's healthy.
