### ISSUE TITLE
S3 API: GetObjectAttributes

### ISSUE THREAD

**Issue by zveinn** [minio/minio#18608]
There is new S3 API [GetObjectAttributes](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectAttributes.html) that needs implementing into minio.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectAttributes.html
https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.GetObjectAttributes

**Comment by cameronelliott** [comment]
As someone researching backup software design, this seems like it might be very valuable for checksum based backup designs.
I don't know the full scope of the S3 API, but this does seem to add new capabilities with the ability to retrieve the MD5/CRCxx/SHA1/SHA256 hashes.

It seems to me it would be nice to have it in Minio.

I do have one question if anyone knows.

Does this call re-compute the checksums? Or does it just return saved values of the checksums?
It seems like it would be very valuable if there is an option to re-compute the checksums.  This would help protect again disk bit-rot.  (Originally computed checksums saved as meta-data might be incorrect, depending on filesystem and hardware features and the potential for bit-rot to occur)
Thanks for any thoughts or feedback.

**Comment by zveinn** [comment]
Helllo @cameronelliott 

I'm not sure if it's re-computing the checksum but it seems like that would be a pretty expensive functionality to add into a query that is designed for attribute lookup. 

However, minio has in-built methods to protect again bitrot in the form of a object scanner and object healing methods. So there would not really be a need to re-compute the checksum when using minio. 

Once we implement this API we might have more information about re-computing the checksums.

**Comment by klauspost** [comment]
> Does this call re-compute the checksums? Or does it just return saved values of the checksums?

It returns only values stored. Objects can be terabytes in size, so that is also the only reasonable approach. 

Bitrot is checked when objects are downloaded and fixed with erasure codes if needed. This is not tied into the checksum system. The uploader supplies the checksum expected, which is validated on upload. MinIO applies bitrot detection/protection on uploaded objects.

The returned checksum on download can be used by the client to validate that the transfer from S3/MinIO did not introduce anything unexpected. Multiparts checksums are pretty horrible. I expect that is why they added this API.

Also note that I don't expect this API to make a checksum magically appear. If objects were uploaded without checksum the response will not contain them - but can of course confirm that is also the case on AWS.

**Comment by harshavardhana** [comment]
This is added and released.
