### ISSUE TITLE
Why minio not write a restful api document

### ISSUE THREAD

**Issue by joebnb** [minio/minio#18997]
Why minio not write a restful api document, as says it can refrence from aws s3 document,and write a lot of sdk documents and implement codes. (if i have a sdk，may be im not read the doc on sites,i will read the IDE refrence by comment or function parameters )

as a user,im try to looking s3 documents,i have worried about the wrong parameters and consistency is up to date of two system

why not spend a little time to make a own handbook of development.

![image](https://github.com/minio/minio/assets/1646883/d3e9cb79-8d70-4296-838f-994ab624f05a)

**Comment by joebnb** [comment]
and i read this try with minio
![image](https://github.com/minio/minio/assets/1646883/55d3a358-851b-4f94-a9b9-4696a69c85ec)

and then have issues for search 
![image](https://github.com/minio/minio/assets/1646883/bbb67288-744b-4896-80d5-d5d0c8e2a987)

and the answer

![image](https://github.com/minio/minio/assets/1646883/d1cade1b-0612-4c94-9553-e8ec7115ab87)

**Comment by ravindk89** [comment]
> why not spend a little time to make a own handbook of development.

Because it's not a "little time". It's a significant amount of effort to build, test, and maintain an API corpus. We're not just going to copy what S3 has blindly, and as you and others have pointed out it's not necessarily a complete reference anyways. It exists as a starting point if people really want to brute force it, or more likely build their own custom wrapper/SDK around it.

The larger issue with REST is exactly what Klaus noted - you must *also* construct the appropriate AWS SignatureV4 or V2 headers, which are difficult to do by hand without mistakes. There are dozens of headers and other bits and bobs you can shove onto any given API request. All of that has to be covered in appropriate detail.

What you've actually stumbled upon is that there is a reason that we ([and I believe others](https://stackoverflow.com/questions/15754449/amazon-s3-sdk-or-rest-api)) recommend S3 development through the usage of SDKs. The SDKs wrap the underlying REST calls correctly, implement the signature calculations correctly, and handle functionality like transparent retry or multipart uploads. 

We are scheduling work on the SDK docs to improve their overall accessibility and coverage. But we will not, at least in this year, be focusing efforts on documentation around the S3 REST API as a standalone interface.

If any community user is interested in trying their own hand at it, I'm open to allocating resources to review that work. I would expect any such work to rely heavily on OpenAPI or Swagger, so I look forward to someone making the attempt at integrating that into the MinIO Server code.
