### ISSUE TITLE
Data transfer going, disk space usage is expanding, but the number of objects is not growing

### ISSUE THREAD

**Issue by ww7** [minio/minio#19391]
We configured two nodes with 4 HDD drives on each (8 in total)
Data transferring from DigitalOcean Spaces is very slow, CPU and RAM are enough, but `iowait` around 60-85%

We are using `rclone` 
```sh
rclone sync do:recognition bb:recognition --progress --checkers 48 --tpslimit 180 --checksum --max-backlog 99999999 --retries 999999
```
(10 000 000 files, most of them small)

The problem is one of transferring bucket shows active transfers but stats on Minio dashboard is not growing, number of objects and size not changing. Bucket index or something can be corrupted?

**Comment by harshavardhana** [comment]
> The problem is one of transferring bucket shows active transfers but stats on Minio dashboard is not growing, number of objects and size not changing. Bucket index or something can be corrupted?

There is no such thing as a bucket index to show values that require time; it is not instantaneous or real-time. It is run via scanning of scheduled disks and runs under very low priority. 

Observe what is happening with `mc admin scanner status alias/.`

Next time, please explain your setup. Removing the entire issue reporting template is not acceptable to us. 

Going to close this issue since it's just informational.
