### ISSUE TITLE
Kafka event for automatic deletion (change data capture)

### ISSUE THREAD

**Issue by comassky** [minio/minio#19419]
When "automatically" deleting a file from a bucket, we can use : 
1- a "rule" using object lifecycle management (expiration)
2- an "expire" batch
 
If we set up an event (capture data change) to kafka in the bucket concerned by this purge, in the first case the event is generated (with all metadata including the file path), but not in the second.
 
The batch documentation indicates an endpoint which retrieves the status at the end of the batch, but not information similar to that of the event capture data change.
 
Is there any way of sending the event using a batch?

**Comment by harshavardhana** [comment]
Batch expiration doesn't generate the event because it's not "automatic.". Batch expiration is triggered manually. 

Batch expiration has a notification system that you need to use to notify a webhook endpoint. It does not honor or piggyback on existing bucket notifications at this point.

Feel free to send a fix if you want to enable notifications for batch expiration as well.
