### ISSUE TITLE
mc admin replicate rm not work

### ISSUE THREAD

**Issue by boynicholas** [minio/minio#19701]
I tried using mc admin replicate rm alias --all --force, but it returned: Unable to remove cluster replication. Invalid site-replication request (site replication is not enabled). but by looking at the log, remote target is offline for bucket:ltj-thumb arn:arn:minio:replication::437fb97e-71d2-4821-9e3b-218e8e1ad144:ltj-thumb retry:1 (*errors.errorString)，It seems that the replication was not deleted completely.

How do I remove site replication?

<img width="1285" alt="image" src="https://github.com/minio/minio/assets/6275408/fa557252-ca17-4e19-9593-4a2b6503c7a9">

When I look at site replicate info it returns SiteReplication is not enabled
<img width="475" alt="image" src="https://github.com/minio/minio/assets/6275408/7694c497-25ba-460c-a440-55901b5bf0c6">

**Comment by ravindk89** [comment]
Can you run `mc replicate ls ALIAS/ltj-thumb` and see if you have bucket replication rules configured?

You have also omitted nearly all the information we request in our template s- MinIO version, mc version, startup configuration, etc.

Please provide *all* of that information, otherwise we have to close this ticket out.

**Comment by harshavardhana** [comment]
> Please provide _all_ of that information, otherwise we have to close this ticket out.

Let's close it, and the let the user resubmit again with all the relevant information.
