### ISSUE TITLE
RE: FS gateway migration is not reliable

### ISSUE THREAD

**Issue by Haarolean** [minio/minio#20046]
Re-raising [this issue](https://github.com/minio/minio/issues/20018), as it seems the original one hasn't been thoroughly read as I mentioned that I've tried migrating storage between two (old and new) setups. 

P.S. I would really appreciate if we could keep the issue open (in a trige state or whatever) until there's a definitive decision, as replies to a closed issue are [ignored](https://github.com/minio/minio/issues/20018#issuecomment-2198423684).

**Comment by harshavardhana** [comment]
You need two setups with both aliases, Just do `mc mirror` between them.

Once finished delete the FS deployment.

No need to do config export and import, they won't work. You need to manually perform those if necessary.

This is mostly just a documentation cleanup @ravindk89

Closing this issue since it's not relevant for this repo.

**Comment by Haarolean** [comment]
@harshavardhana "mc mirror" is not a migration, it synchs data between a local FS and a remote **_bucket_**. I have around 5-6 buckets with different IAM policies, this recommendation doesn't cover this.

**Comment by harshavardhana** [comment]
There is no other migration possible. Your data is what is important you can always copy the policies out manually and recreate them. Nothing much of rocket science here.

The FS mode is too old and the APIs that it presented are long deprecated. There is no way to retroactively fix them.

This issue is discussed enough and the ship has sailed.

**Comment by Haarolean** [comment]
@harshavardhana wdym 'too old'? As I've already mentioned, I'm running two containers alongside, `RELEASE.2022-06-25T15-50-16Z` and `RELEASE.2022-10-24T18-35-07Z` with mc client `RELEASE.2022-10-22T03-39-29Z`, which all should have compatible APIs (to make migration still possible) as mentioned in your [migration guide](https://min.io/docs/minio/container/operations/install-deploy-manage/migrate-fs-gateway.html).

1) It's not rocket science, you're right, but it's a huge waste of time which scales up depending on the number of buckets/policies/users one has. 
2) What's the point of the aforementioned migration guide if it contradicts your words about impossible migration? I've spent like 6 hours trying to follow that guide.

**Comment by harshavardhana** [comment]
As I have mentioned before, this is part of docs https://github.com/minio/docs and must be reported there. 

It may be overly promising things that might not work, I will guide the docs team to simplify this further.

Rest I have already told you what needs to be done. `mc mirror -a fs-old/ new-fs/` does everything that you need from a bucket and data point of view.

**Comment by ravindk89** [comment]
Ah, I see - we wrote that guide a while back, I thought that the config export/import cycles were valid. Very possible we missed something in all of that, and simple enough to rip those instruction sets out and focus on data migration.

If at this point that's a no-go, we can modify the tutorial to focus on using `mc mirror` to migrate data, and then provide general guidance on migrating IAM policies or bucket configs by hand.

I doubt the process of migrating from FS/Gateway is going to get easier as time goes on - the product has long since moved on from that code base.
