### ISSUE TITLE
S3 key "aws:SecureTransport" isn't properly set with Minio SSL Setup

### ISSUE THREAD

**Issue by UKFr-DIZ** [minio/minio#20061]
Hi, 

I have configured properly a SSL setup for the minio server. 
We have a simply apache reverse proxy in front of the minio server (+ console) which handles the SSL termination. 
The proxy does locally communicate with HTTP with the minio server, however that shouldn't affect the `aws:SecureTransport` context var. 

https://github.com/minio/console/blob/649c3d74b8a64b102a283e2d493ba8d07faf30cc/api/user_session.go#L112
It should be set to true, as long as the `MINIO_SERVER_URL` starts with `https`. Our url looks like this : `https://<server>:9000`. The `MINIO_BROWSER_REDIRECT_URL`  looks the same just no portnumber at the end (443). 

Given the "only SSL" IAM Policy below it fails to properly work, which leads to my understanding 

## Expected Behavior
When setting the following policy, I expect to be able to access all buckets regularly, given I have the proper SSL setup. Meaning the `aws:SecureTransport` variable should always be set true. 

~~~
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Allow SSL communication only",
            "Effect": "Deny",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": [
                        "false"
                    ]
                }
            }
        }
    ]
}
~~~

## Current Behavior
When enabling that policy for a user it false denies all s3 access / rights. 

Any idea how to progress with debugging or analyzing the problem ? I don't know how to actually check the s3 context keys. 

## Your Environment

* MinIO version used (`minio --version`): minio version RELEASE.2024-02-06T21-36-22Z (commit-id=980fb5e2ab3674287207c9388bb8fda7a142cc64)
Runtime: go1.21.6 linux/amd64
* Server setup and configuration: Linux Ubuntu Server 22.02

**Comment by cesnietor** [comment]
we'll investigate this and try to reproduce

**Comment by ramondeklein** [comment]
We have investigated this issue and it's probably caused, because you use the following situation:
- NGINX is doing TLS termination.
- NGINX connects to MinIO using plain HTTP.

MinIO will detect that it's connected without TLS and not accept the request. I had created a PR that looks at the `X-Forwarded-Scheme` header, so it could detect that the actual request was using secure transport. The problem is that you can also add this header when you're connecting via plain HTTP to MinIO (without NGINX). That would also satisfy the `aws:SecureTransport: true` condition. That's why we probably won't merge the PR.

@UKFr-DIZ Wouldn't it be easier to only expose MinIO via HTTPS and drop this policy?

**Comment by UKFr-DIZ** [comment]
Hi, thanks for checking the issue in detail. 
We were just trying out the policies and that behaviour came into our attention. 

We have standard setups on our machines using webserver in front of the actual apps. We will simply drop this policy in particular and ensure otherwise that we use HTTPS only :)
