### ISSUE TITLE
Unexpected Synchronization Behavior in MinIO: Data Loss After Deleting Site Replication

### ISSUE THREAD

**Issue by boynicholas** [minio/minio#20080]
Hi,

We have identified a significant issue. For example, we have two clusters named `old-minio` and `new-minio`. We created a site replication on new-minio using the command: `mc admin replicate add old-minio new-minio`, initiating continuous synchronization.

After a few days of synchronization, we noticed that the synchronization speed was not as expected. Since the storage on `old-minio` was nearing full capacity, we deleted the site replication on `new-minio` using the command:
`mc admin replicate remove new-minio --all --force`

After confirming the command executed successfully, we also ran the commands `mc admin replicate info new-minio` and `mc admin replicate status new-minio` to verify that the site replication had been deleted and stopped. Following this, we executed the command to delete objects on `new-minio`:
`mc rm --recursive --force --versions new-minio/bucket`

However, strangely, the objects we deleted in `new-minio` were synchronized to `old-minio`, causing the corresponding objects in `old-minio` to disappear.

This resulted in a significant loss of data. We need to confirm whether this is a feature or a bug in MinIO. Specifically, why did the synchronization not stop as expected after deleting and stopping the site replication? Instead, deletions in `new-minio` were still synchronized to `old-minio`.

## Regression
Is this issue a regression? (Yes / No): No

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2024-05-01T01-11-10Z (commit-id=7926401cbd5cceaacd9509f2e50e1f7d636c2eb8)
* Operating System and version (`uname -a`): Linux minio-02.ltj.dy6b.com 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> However, strangely, the objects we deleted in `new-minio` were synchronized to `old-minio`, causing the corresponding objects in `old-minio` to disappear.

I tried this locally, and it all works fine. From what I can tell, we couldn't unregister the cluster correctly since you ran out of storage on the old minio, which would simply disallow writes, causing the registration of replication to be not appropriately removed or perhaps partially removed i.e only the top-level caller knows, that site replication is not set but the lower layers per bucket level rep[location is still valid which seems like you didn't validate perhaps with `mc replicate status alias/bucketname`

Willy Nilly doing `mc rm` on the entire bucket is not a great sign of good administration; caution must always prevail in unusual situations.

Remember a few things: when you use `--all` and `--force`, the site replication is removed forcibly regardless of whether the remote site is reachable. This is a dangerous situation that is only useful when the remote site is completely gone, not like in your case.

So, it looks like the admin here dropped the ball and used all the dangerous options when they shouldn't have clearly. 

> This resulted in a significant loss of data. We need to confirm whether this is a feature or a bug in MinIO. Specifically, why did the synchronization not stop as expected after deleting and stopping the site replication? Instead, deletions in `new-minio` were still synchronized to `old-minio`.

Yes, it's a feature in `mc` - you wanted to forcibly remove site replication without caring for any errors to be propagated from the server.

**Comment by boynicholas** [comment]
In fact, our old MinIO cluster still has some available space, approximately 600GB per disk. So, does running the command mc admin replicate remove new-minio --all --force to remove the site replication not completely stop the replication process?

**Comment by michaellee123** [comment]
I'm a boynicholas's colleague. On other words, we need to check that: after the sync stopped, did the `old-minio` will sync the `mc rm` command when we run it on the `new-minio`?

**Comment by harshavardhana** [comment]
> In fact, our old MinIO cluster still has some available space, approximately 600GB per disk. So, does running the command mc admin replicate remove new-minio --all --force to remove the site replication not completely stop the replication process?

It may or may not, this is not guaranteed since `--all --force` is specified.

**Comment by harshavardhana** [comment]
From what I can tell we may have to add another flag here called --dangerous because it looks like users are making mistakes in using these flags.

**Comment by boynicholas** [comment]
I believe this point needs some clarification. When using the command `mc admin replicate remove -h`, the examples provided always include `--force`. This does not clearly indicate that removing the replication does not necessarily stop the synchronization. Moreover, after running `mc admin replicate info new-minio` and `mc admin replicate status new-minio`, there was no indication that synchronization was still ongoing. This could potentially mislead users.

![image](https://github.com/user-attachments/assets/d518a6e0-7b1a-4361-9dfd-633a77ac0e35)
