### ISSUE TITLE
Update `KMSListKeysHandler` to also return `CreatedAt` and `CreatedBy` fields.

### ISSUE THREAD

**Issue by ramondeklein** [minio/minio#20132]
The `KMSListKeysHandler` returns a structure that holds the `CreatedBy` and `CreatedAt` fields, but these are never filled by the [`KMSListKeysHandler`](https://github.com/minio/minio/blob/61bd861a4232ba1c22a9854b94813072bee8bdd8/cmd/kms-handlers.go#L169-L202). Code must be updated, so these fields are properly filled for MinKMS and KES (when possible).

See also https://github.com/minio/madmin-go/issues/289#issuecomment-2245253705.

**Comment by marktheunissen** [comment]
@ramondeklein Hi Ramon, couple questions on this:

For KES: MinIO in `KMSListKeysHandler` ultimately uses a call to KES to the ListKeys API, which only returns key names. See: https://github.com/minio/kes/blob/master/internal/api/response.go#L52-L56

Fields `CreatedAt` and `CreatedBy` are only returned by `DescribeKey` API in KES.

It is technically possible for KES to first ListKeys, then for each key, call DescribeKey, however this would be slow and wasteful. I assume you're not asking for that, as you did say "when possible". Assume that KES will not populate these values, unless the KES API can be updated such that ListKeys returns the Created fields in its ListKeys response.

For KMS, it seems like it does return the CreatedAt/By fields here, when doing ListKeys: https://github.com/minio/kms-go/blob/main/kms/client.go#L1042. 

I think that part should be doable, it does mean some small interface changes in MinIO but manageable. 

Let me know your thoughts, thanks.

**Comment by ramondeklein** [comment]
The "problem" is that `madmin-go` pretents that it will return this information, but it never does. So there are three options:
1. Add the information (if possible).
2. Remove the fields from the structure, however this will be a breaking API change.
3. Do nothing and keep the current confusing API. It's not good to have fields that pretent to provide information, but will always be empty.

Option 1 is by far the best option, but if we need an N+1 solution, then that's too slow. We shouldn't do that.

We could extend the KES ListKeys endpoint with a `createdInfo` query parameter that -when specified- will also return the creation information. When the query parameter is detected, then it returns a `[] struct { name: string, createdAt: time.Time, createdBy: string }` instead of `[]string`. The client can first try to unmarshal the new struct and if it fails, it falls back to the string array.

It's a bit complicated though, so we may also want to remove these fields from the console and leave it like it is. I don't expect non-MinIO clients to use this API. Key management shouldn't be done from MinIO, but from the actual KMS. So I would be fine with removing the information from the console. The `ListKeys` is typically used to select a key to encrypt a bucket.

Let @aead decide, but I guess he'll be fine with removing the creation information from the console...

**Comment by marktheunissen** [comment]
Thanks, I'll wait for @aead 's input on this.

**Comment by aead** [comment]
My suggestion would be to change the MinIO internals to return a `[]KeyInfo` each containing a name, created at and created by. The KMS will return this information. KES does not because not all KMS backends do provide this information during listing and KES has to stick to the least common denominator.

So we can simply change `ListKeyNames []string` to `ListKeys []KeyInfo` and define a `kms.KeyInfo` (if not already there). Admin API clients must be able to handle the case where some of the fields are empty. Either not showing them at all or displaying a place-holder or N/A value

**Comment by marktheunissen** [comment]
PR is up: https://github.com/minio/minio/pull/20223/files

> Either not showing them at all or displaying a place-holder or N/A value

@aead Just to confirm my approach for the above... The `madmin` SDK has the following signature:

`func (adm *AdminClient) ListKeys(ctx context.Context, pattern string) ([]KMSKeyInfo, error) {`

A caller will get empty strings for `KMSKeyInfo.CreatedAt` and `KMSKeyInfo.CreatedBy` when they are not available. I'm going to leave that as-is, and then a user of the SDK can assume that an empty string means "not available" and can display "N/A", rather than changing the function signature and breaking the API, which in turn would require updating console, etc.
