### ISSUE TITLE
Error 502 is reported in the standalone console

### ISSUE THREAD

**Issue by liautumn** [minio/minio#20222]
![Snipaste_2024-08-07_10-20-01](https://github.com/user-attachments/assets/3cfb5b3d-1d62-451c-bba1-ce08fee97ec6)

**Comment by marktheunissen** [comment]
@liautumn Please check your browser debugger tools to see if there are any JS console errors, or any failed requests (presumably there will be at least one 502 in there), and copy-paste as much information as possible to this ticket.

Also run `mc trace ALIAS -a -v` on your server and reproduce the issue to see what the server logs, and paste those logs here.

**Comment by allanrogerr** [comment]
We also need the bug template filled out. Im not sure how it was skipped when filing this. See below for a template
***
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.



## Expected Behavior



## Current Behavior



## Possible Solution



## Steps to Reproduce (for bugs)




1.
2.
3.
4.

## Context



## Regression



## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
