### ISSUE TITLE
Can't add node ti minio Cluster

### ISSUE THREAD

**Issue by umlumpa** [minio/minio#20659]
Hi guys! I have  minio CLuster with 4 nodes , and i want to add 2 more nodes to cluster.
Minio cluster running like this:
```
MINIO_VOLUMES="http://minio{1...4}.cluster.local/mnt/minio
```
every node has just one disk and mount in /mnt/minio
 and when want to add 2 more nodes 
 ```
 MINIO_VOLUMES="http://minio{1...6}.cluster.local/mnt/ 
 ```
 like this it says 
 ```
 FATAL Unable to initialize backend: /mnt/minio drive is already being used in another erasure deployment. (Number of drives specified: 6 but the number of drives found in the 1st drive's format.json: 4
 ``` 
 how can i expand cluster

**Comment by marktheunissen** [comment]
It's not possible to do it that way, you have to add a pool, follow the docs here: https://min.io/docs/minio/linux/operations/install-deploy-manage/expand-minio-deployment.html

**Comment by umlumpa** [comment]
> It's not possible to do it that way, you have to add a pool, follow the docs here: https://min.io/docs/minio/linux/operations/install-deploy-manage/expand-minio-deployment.html

What i have to do in my case how can i expand? 
```
MINIO_VOLUMES="http://minio{1...4}.cluster.local/mnt/minio http://minio{5...6}.cluster.local/mnt/minio
```
if like this also not working

**Comment by marktheunissen** [comment]
That will work if your DNS is setup correctly. What is the problem?

Here is the example from the docs I linked:

`MINIO_VOLUMES="https://minio{1...4}.example.net:9000/mnt/disk{1...4}/minio https://minio{5...12}.example.net:9000/mnt/disk{1...8}/minio"`

**Comment by umlumpa** [comment]
> That will work if your DNS is setup correctly. What is the problem?
> 
> Here is the example from the docs I linked:
> 
> `MINIO_VOLUMES="https://minio{1...4}.example.net:9000/mnt/disk{1...4}/minio https://minio{5...12}.example.net:9000/mnt/disk{1...8}/minio"`

![Screenshot 2024-11-18 at 14 24 15](https://github.com/user-attachments/assets/05dfb348-633f-4e2a-9247-3a21a63803cb)

**Comment by marktheunissen** [comment]
That's a different error, the problem is now parity. The answer is in the docs I linked.

MinIO requires each pool satisfy the deployment [erasure code](https://min.io/docs/minio/linux/operations/concepts/erasure-coding.html#minio-erasure-coding) settings. Specifically the new pool topology must support a minimum of 2 x EC:N drives per [erasure set](https://min.io/docs/minio/linux/operations/concepts/erasure-coding.html#minio-ec-erasure-set), where EC:N is the [Standard](https://min.io/docs/minio/linux/reference/minio-server/settings/storage-class.html#minio-ec-storage-class) parity storage class of the deployment. This requirement ensures the new server pool can satisfy the expected SLA of the deployment.
