### ISSUE TITLE
Investigate block profile results for concurrent uploads of objects 

### ISSUE THREAD

**Issue by krisis** [minio/minio#2082]
## Setup
- Ran block profiling on #2066 

[2066-blockprof.pdf](https://github.com/minio/minio/files/345399/2066-blockprof.pdf)

**Comment by harshavardhana** [comment]
Assigned to @krisis for further investigation and fix.

**Comment by krisis** [comment]
I have started the analysis, expect to send a proposed fix by Jul 7th.

**Comment by krisis** [comment]
As part of making the namespace locks granular, the following changes are proposed,
- Use `ModTime` saved in xl.json for every object as a means to identify (parts of or whole of) objects erasure coded across the disks as part of the same PutObject or PutObjectPart.
  All disks that witnessed a PutObject, PutObjectPart, CompleteMultipartUpload, AbortMultipartUpload should have the same `ModTime` in their xl.json. If any of the above request handlers don't have quorum number of disks have the same `ModTime`, we will fail them with `errXLWriteQuorum`.
- Modify `Version` saved in xl.json to be a string. With `ModTime` used to identify the 'good' copy, healing shouldn't rely on `Version` anymore. This field will be left in xl.json for possible future use.
-  A write lock on the entry corresponding to the part or whole of object in the namespace would be taken only during the rename phase. To delay the need to read xl.json to erasure code the content available from http request's body, and extend the region under the namespace lock, we will make the erasure distribution deterministic using hashing.

**Comment by krishnasrinivas** [comment]
@krisis with the discussion the day before
- version can still be a number instead of string and two disks with same version should have contents exactly same.
- putObjectPart should upload part only to disks with latest version. Hence if you upload a part to a set of disks, a next part can be uploaded to either same disks or a subset of those disks but can never include a new disk.
- upload IDs are unique UUIDs (we rely on UUIDs to be unique for tmp files too) and it's safe to assume that UUIDs will never get reused (atleast not for a long time).

so is this proposal still valid?
