### ISSUE TITLE
docker hub images versioning

### ISSUE THREAD

**Issue by ErezHorev** [minio/minio#2186]
Currently there are only two versions of minio image on docker-hub ('latest','edge')

Using 'latest' tag is kind of risky as things are rapidly being changed inside.

Please create more tags (versions) to be able and nail specific static version. 

Thank you

**Comment by harshavardhana** [comment]
> Currently there are only two versions of minio image on docker-hub ('latest','edge')
> 
> Using 'latest' tag is kind of risky as things are rapidly being changed inside.
> 
> Please create more tags (versions) to be able and nail specific static version.
> 
> Thank you

Minio is written with continuous deployment model in mind so we kept 'latest' so that users can upgrade to new releases and 'latest' only changes for specific releases only from the 'release' branch, 'edge' changes for each commit in the master. 

But yes, we can do released based tagging as well - which i think supported on docker hub as well.

**Comment by ErezHorev** [comment]
:) Thanks for the reply.
I understand. so the term 'rapidly changes' is probably too extreme.
well, it still means that release might change without me being aware of it and then something might be changed and break at my code which is actually what I've experienced.

I'll just use a specific tag release on 'release' branch (as you just mentioned) and create image out of it until more docker release tags will be available

Thank you

**Comment by ErezHorev** [comment]
BTW - you can definitely add more tags

> A repository potentially holds multiple variants of an image. In the case of our ubuntu image you can 
> 
> see multiple variants covering Ubuntu 10.04, 12.04, 12.10, 13.04, 13.10 and 14.04. Each variant is identified by a tag and you can refer to a tagged image like so:
> 
> ubuntu:14.04
> [https://docs.docker.com/engine/tutorials/dockerimages/](url)

**Comment by harshavardhana** [comment]
> :) Thanks for the reply.
> I understand. so the term 'rapidly changes' is probably too extreme.
> well, it still means that release might change without me being aware of it and then something might be changed and break at my code which is actually what I've experienced.

That must have been due to the fact that we had to delete our previous repo and migrate to a more docker recommended github based build. 

So most probably not associated with any versioning as such, any thing that goes into "latest" is backward compatible.  This reasoning comes from continuous deployment model. If something breaks we fix and make a new release.  

This way we are all moving forward,  there are some corner cases when someone wants to strictly stick to a version will see how docker can help us solve this locally by not complicating the hub itself.

Thanks for providing the background on this @ErezHorev

**Comment by ErezHorev** [comment]
I see.
Actually this was caused by the way we wrapped minio image.

**TL;TR**
our issue was that we've provided minio server with the export point inside our own Dockerfile (before minio had a Dockerfile):

> FROM minio/minio:latest  
> CMD ["export"]

And minio latest release already does that inside its (relatively new) Dockerfile.

> ...
> ENTRYPOINT ["go-wrapper", "run", "server"]
> CMD ["/export"]

I just removed the '/export' command from my dockerfile and its all good now :)
Thank you

**Comment by harshavardhana** [comment]
> I see.
> Actually this was caused by the way we wrapped minio image.
> 
> TL;TR
> our issue was that we've provided minio server with the export point inside our own Dockerfile (before minio had a Dockerfile):
> 
> FROM minio/minio:latest
> 
> CMD ["export"]
> And minio latest release already does that inside its (relatively new) Dockerfile.
> 
> ...
> ENTRYPOINT ["go-wrapper", "run", "server"]
> CMD ["/export"]
> I just removed the '/export' command from my dockerfile and its all good now :)
> Thank you

Okay thanks @ErezHorev

**Comment by ErezHorev** [comment]
@harshavardhana ,i see you closed the issue. 
Does that means you don't intend to do it ?
Its not critical but would be nice to have it eventually
Thank you

**Comment by harshavardhana** [comment]
> @harshavardhana ,i see you closed the issue. 
> Does that means you don't intend to do it ?
> Its not critical but would be nice to have it eventually
> Thank you

@ErezHorev we decided to stick to 'latest' and 'edge', the fact being continuous release model. We will eventually do when are absolutely sure of breaking away from backward compatibility or if we re-write the backend format.

**Comment by ErezHorev** [comment]
Ok thank you @harshavardhana
