### ISSUE TITLE
Validate and support elasticsearch s3 plugin

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2217]

**Comment by nl5887** [comment]
By default Elasticsearch uses V2 signatures. This can be changed by adding 

```
cloud:
    aws:
        s3:
            signer: "AWS4SignerType"
```

to **elasticsearch.yml**.

Next it will fail with the error: 

> Caused by: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: rmb2cl86qocjKRNcDsSxmA== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@40ff56e1, bucketName: elasticsearch, key: tests-Bef82zPqQuCKeGJYK4xJiA/master.dat-temp)

This is being caused by the java library not recognising the `ETag` header, because this is being canonicalized by [CanonicalMimeHeaderKey](https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey) as `Etag`. I think the current handling of setting http headers in Go is not correct, and shouldn't modify the keys of the headers. We should create this as an issue with Go, which shouldn't modify the response headers being set.
- https://golang.org/src/net/http/header.go#L31
- https://golang.org/src/net/textproto/header.go?s=659:701#L11
- https://golang.org/src/net/textproto/reader.go?s=14875:14919#L552

**Comment by harshavardhana** [comment]
Go HTTP server is behaving correctly. HTTP headers are case insensitive in lieu with the spec. 
It was aws-sdk's fault to treat it case sensitively breaking HTTP spec compliance, looks like elasticsearch to update its aws-sdk version.

**Comment by nl5887** [comment]
This issue is being discussed at golang/go#5022 as well, and it complies with rfc. repository-s3 is using version 1.10.69 of Apr 11 of the aws sdk. The bug has been fixed in a later release.

**Comment by nl5887** [comment]
Created a pull request (https://github.com/elastic/elasticsearch/pull/19489) containing a version bump of the aws sdk to 1.11.18.

**Comment by GarimaKapoor** [comment]
@harshavardhana  can we close this issue.

**Comment by harshavardhana** [comment]
> @harshavardhana can we close this issue.

Closing - upstream fix sent by @nl5887
