### ISSUE TITLE
api - content-disposition missing

### ISSUE THREAD

**Issue by brackxm** [minio/minio#2266]
## Expected behaviour

getObject/headObject returns Content-Disposition
## Actual behaviour

getObject/headObject do not return Content-Disposition
## Steps to reproduce the behaviour

putObject with Content-Disposition
getObject/headObject
## Minio version

Version: 2016-07-22T06:19:39Z
Release-Tag: DEVELOPMENT.2016-07-22T06-19-39Z
Commit-ID: 5d118141cd3d92f7d501b7045992df9e9f312b8d
## System information

aws-cli/1.10.48

**Comment by harshavardhana** [comment]
We are not saving content-disposition on purpose, since it is redundant with 'presigned' operations. Can you explain the requirement @brackxm ?

**Comment by brackxm** [comment]
i would like to store the content-disposition.
the client does not now it when getting.

**Comment by harshavardhana** [comment]
> i would like to store the content-disposition.
> the client does not now it when getting.

No what i was talking about is http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html 
`response-content-disposition` - Sets the Content-Disposition header of the response. This would automatically set the 'Content-Disposition' , it would allow for the request to be dynamic. Rather than saving this meta information. 

Let me know what you think @brackxm .

**Comment by brackxm** [comment]
yes, that is what i assume you were talking about.

being more explicit:
client A puts an object
client B gets an object

in my case, client A decides the content-dispostion, and client B does not know it
and needs is when getting the object
similar to other headers, like content-type
client B only knows the key

note that storing the content-disposition not preclude for overriding it in the get

**Comment by krishnasrinivas** [comment]
@brackxm are you using presigned URLs to download the object from client-B? or have you made the bucket publicly accessible so that client-B does not provide auth info to download the object?

I am asking because if you use presigned URLs then we can generate presigned URLs such that the URL has the info on the key and also what the `content-disposition` response header should be.

**Comment by brackxm** [comment]
no, not using a presigned url

**Comment by harshavardhana** [comment]
> yes, that is what i assume you were talking about.
> 
> being more explicit:
> client A puts an object
> client B gets an object
> 
> in my case, client A decides the content-dispostion, and client B does not know it
> and needs is when getting the object
> similar to other headers, like content-type
> client B only knows the key
> 
> note that storing the content-disposition not preclude for overriding it in the get

I see so it is more about publicly accessible objects, these clients have no relation. Sending a fix.
