### ISSUE TITLE
tests: Need better coverage for format-config-v1.go

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2416]

**Comment by vadmeste** [comment]
This patch https://github.com/minio/minio/pull/2424 enhanced the code coverge by 0.5%, will see if I can do better

**Comment by harshavardhana** [comment]
Can you add tests for these -cases ://codecov.io/gh/minio/minio/src/385543ebe06ca191cd1af1233f56a3a9dffedd0e/cmd/format-config-v1.go @vadmeste

**Comment by vadmeste** [comment]
@harshavardhana, codecov.io is hard with us :)

Since the only remaining code not covered are when errors occur (disk not found, etc..), I guess I will write something similar to faulty disks which returns programmed errors, like:

`disk = FaultyDisk{Errors: []DiskError{NoError, NoError, DiskNotFound, ..}, ...}` 

What do you think?

**Comment by harshavardhana** [comment]
> Since the only remaining code not covered are when errors occur (disk not found, etc..), I guess I will write something similar to faulty disks which returns programmed errors, like:
> 
> disk = FaultyDisk{Errors: []DiskError{NoError, NoError, DiskNotFound, ..}, ...}
> 
> What do you think?

Yes that would make sense.

**Comment by harshavardhana** [comment]
Closing as we have reached sufficient coverage for `format-config-v1.go`
