### ISSUE TITLE
tests: Need better coverage for notify* files.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2418]
- Includes  `notifiers.go` . 
- Includes  `notify*` files.

**Comment by harshavardhana** [comment]
Moving this to Phase 2 since there are many places here which requires additional services for writing tests, we would even have to evaluate if we can write tests even for this. 

Unless we can mock this fully there is no easier way.

**Comment by harshavardhana** [comment]
> Moving this to Phase 2 since there are many places here which requires additional services for writing tests, we would even have to evaluate if we can write tests even for this.
> 
> Unless we can mock this fully there is no easier way.

There is no real way to test the code this path since it requires external entities like elasticsearch, redis and rabbitmq, currently all the paths that could be tested already has tests.  

Each code path has been sufficiently manually tested, so closing this since we won't be able to do 'go tests' for these files.

**Comment by brodock** [comment]
For redis, you have this two alternatives: 
- https://github.com/rafaeljusto/redigomock (mock library)
- https://github.com/alicebob/miniredis (simulated redis)

**Comment by harshavardhana** [comment]
> For redis, you have this two alternatives:
> 
> https://github.com/rafaeljusto/redigomock (mock library)
> https://github.com/alicebob/miniredis (simulated redis)

Nice suggestion @brodock we will evaluate them. Thanks
