### ISSUE TITLE
docs: write a curl client quickstart guide and API reference

### ISSUE THREAD

**Issue by matm** [minio/minio#2611]
## Expected behaviour

To have a curl client quickstart guide in the "Minio Client SDK" section. Also a raw HTTP API reference would be very useful (so other people can easily implement clients in different languages).

That would be a good place to document custom HTTP headers like  `X-Minio-Meta-*` :)
## Actual behaviour

No curl guide/reference in the docs.
## Steps to reproduce the behaviour

Go to Minio docs then scroll down to the "Minio Client SDK" section. No entry regarding curl documentation.
## Minio version

any
## System information

any

**Comment by krishnasrinivas** [comment]
@harshavardhana i think we should provide for custom headers in our client sdk putobject API?

**Comment by harshavardhana** [comment]
> To have a curl client quickstart guide in the "Minio Client SDK" section. Also a raw HTTP API reference would be very useful (so other people can easily implement clients in different languages).

Raw HTTP API reference should be same as AWS S3 HTTP API reference, we didn't want to duplicate the efforts because underneath we don't differentiate these things. 

> That would be a good place to document custom HTTP headers like X-Minio-Meta-\* :)

X-Amz-Meta-\* is supported and should be used instead of X-Minio-Meta-*, former is already documented by AWS S3 docs.

**Comment by harshavardhana** [comment]
> Go to Minio docs then scroll down to the "Minio Client SDK" section. No entry regarding curl documentation.

This we will fix. 

> @harshavardhana i think we should provide for custom headers in our client sdk putobject API?

@krishnasrinivas we could do that will need run this down by @abperiasamy - since we wanted to enhance PutObject() to take 'http.Header' map.

**Comment by agamdua** [comment]
This would be incredibly useful, I am patching a library to make the target URL configurable to support minio (and I guess other s3 compatible backends). I'm getting a 400 and even a dummy curl example would be helpful! :)

Whenever I hack on this project again, I'll try to get a working request from the AWS docs and paste it here for "posterity"

**Comment by koolhead17** [comment]
@agamdua will get this published by this week. 👍

**Comment by abperiasamy** [comment]
We should not directly expose HTTP header access via putObject API. If we need to accept X-Amz-Meta-, then we add a new arg called meta of type map[string]string. We should also validate if all the keys have X-Amz-Meta-  prefix. My preference is to not introduce this extra arg. It encourages bad behavior. Good APIs encourage application developers to do what is correct and desired. Metadata belongs to external database and not object storage.

**Comment by harshavardhana** [comment]
> We should not directly expose HTTP header access via putObject API. If we need to accept X-Amz-Meta-, then we add a new arg called meta of type map[string]string. We should also validate if all the keys have X-Amz-Meta- prefix. My preference is to not introduce this extra arg. It encourages bad behavior. Good APIs encourage application developers to do what is correct and desired. Metadata belongs to external database and not object storage.

Agreed, let's not do that.

**Comment by krishnasrinivas** [comment]
@harshavardhana i am helping @koolhead17 on how to go about this issue.

Since we are aws-s3 compatible and rest calls already documented by AWS do we need to do anything?

If we have to document then we have a huge list of REST calls to document.

**Comment by harshavardhana** [comment]
> Since we are aws-s3 compatible and rest calls already documented by AWS do we need to do anything?
> 
> If we have to document then we have a huge list of REST calls to document.

You are right our REST calls are already documented through higher level client APIs,  for more detailed spec AWS S3 already does the extensive documentation. 

Now regarding `curl` we can talk about a simple how-to on `curl` to Minio. With Signature V2 support it is quite easy - https://gist.github.com/harshavardhana/f6814f3196bc307faa24e42394cc6df0

**Comment by krishnasrinivas** [comment]
> Now regarding curl we can talk about a simple how-to on curl to Minio. With Signature V2 support it is quite easy - https://gist.github.com/harshavardhana/f6814f3196bc307faa24e42394cc6df0

Actually I think @matm intention for curl command is to know about the REST call request and response structure for each REST API to implement custom clients in different languages. Also because it helps us to document `X-Minio-Meta-*` in that section. The intention is not to know how to use curl itself with minio.

i.e :

> To have a curl client quickstart guide in the "Minio Client SDK" section. Also a raw HTTP API reference would be very useful (so other people can easily implement clients in different languages).
> 
> That would be a good place to document custom HTTP headers like X-Minio-Meta-\* :)

like this http://docs.basho.com/riak/cs/2.1.1/references/apis/storage/s3/put-object/

But we haven't had the need for a document like this riak reference because if someone asked `what features do you support from aws-s3` or `how does the rest call look` we would just say `look at our client-libs` and `look at aws-s3 rest api docs` on how the rest calls look.

But the confusion for @matm is because `X-Minio-Meta-*` is not documented (as it is not supported on client libs) and he is suggesting us where we can document this. Since this is an exception we can just put a separate document on meta-data on objects explaining how we support on the server and why we don't support it on the client-libs.

**Comment by harshavardhana** [comment]
>  But the confusion for @matm is because X-Minio-Meta-\* is not documented (as it is not supported on client libs) and he is suggesting us where we can document this. Since this is an exception we can just put a separate document on meta-data on objects explaining how we support on the server and why we don't support it on the client-libs.

X-Minio-Meta actually has no purpose yet, it was put there as a placeholder for future use. On the other hand fundamentally we are discouraging accumulation of metadata such as these which do not belong on Object Storage.  We can in-fact do-away with it too since X-Amz-Meta provides the same behavior and would be the most common header.

So for API reference the best place to start is http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html .

**Comment by krishnasrinivas** [comment]
> We can in-fact do-away with it too since X-Amz-Meta provides the same behavior and would be the most common header.
> 
> So for API reference the best place to start is http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html .

:+1: 

we can close this issue then. If someone wants to use object-metadata we can say that they can look up aws docs on how to set header key/val and that we haven't documented it because we discourage it.

**Comment by harshavardhana** [comment]
> we can close this issue then. If someone wants to use object-metadata we can say that they can look up aws docs on how to set header key/val and that we haven't documented it because we discourage it.

Closing.
