### ISSUE TITLE
event: Notifier should support postgres database

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2739]

**Comment by krishnasrinivas** [comment]
postgres support can be "derived" from amqp right? i.e instead of implementing for all the targets we can just implement amqp (ex rabbit mq) and users can just subscribe to the target that implements amqp to implement their own target. this way we can keep our targets minimal. This way we can remove elastic-search and redis notification?

**Comment by harshavardhana** [comment]
> postgres support can be "derived" from amqp right? i.e instead of implementing for all the targets we can just implement amqp (ex rabbit mq) and users can just subscribe to the target that implements amqp to implement their own target. this way we can keep our targets minimal. This way we can remove elastic-search and redis notification?

The reason here is that Minio server updates the target directly by using a direct database connection, also it has to do it slightly intelligently i.e basically  Update and Delete entries as the notifications come by. 

We can do this approach too but just supporting AMQP requires good work on the other end, in-fact only redis can be removed.  ElasticSearch has other benefits altogether.

**Comment by donatello** [comment]
I could take this up and support for mysql too if desired.

**Comment by harshavardhana** [comment]
> I could take this up and support for mysql too if desired.

We will be only doing postgres only not mysql - mysql is going proprietary route.  Reassigned to you.
