### ISSUE TITLE
[fs] Initialize '.minio.sys' as a separate directory '.minio.sys.<uuid>' and rename to '.minio.sys' 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2782]

**Comment by vadmeste** [comment]
Looks like we need to add RenameVol to storage interface to make an atomic rename. What do you think?

**Comment by krisis** [comment]
@harshavardhana @vadmeste, what is the motivation behind this issue?

**Comment by vadmeste** [comment]
> @harshavardhana what is the motivation behind this issue?

@krisis, I guess data consistency inside .minio.sys

**Comment by donatello** [comment]
With a shared backend (e.g. same NFS directory) for multiple Minio servers in FS mode we want to work sanely. Different Minio servers are not cluster aware in this case. User will need to shape traffic, so that writes to a bucket always comes to the same server. Then all features should work.

This change makes sure that the system directory names don't clash.

**Comment by GarimaKapoor** [comment]
@vadmeste please update the timeline for the fix.

**Comment by harshavardhana** [comment]
Closing this since this requires changing and introducing RenameVol() to posix we don't need to do that as it might end up complicating the behavior.
