### ISSUE TITLE
Nightly builds for minio

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2800]
Support nightly builds for minio so that if we want some user to try latest master (for ex. https://github.com/minio/minio/issues/2793) then the user does not need to install Go to compile and try latest minio, we can point him to the latest nightly binary for the user to try it out. We can keep a cache of last 7 days builds.

**Comment by harshavardhana** [comment]
> Support nightly builds for minio so that if we want some user to try latest master (for ex. #2793) then the user does not need to install Go to compile and try latest minio, we can point him to the latest nightly binary for the user to try it out. We can keep a cache of last 7 days build.

We can do this with travis and appveyor artifacts for each commit.

**Comment by harshavardhana** [comment]
Looks like it is more complicated than predicted on CI's.

After discussing with @abperiasamy suggestion is that we do this on-demand depending on when user asked or asking them to do 'go get' if they already have Go installed.  The accumulation of these builds might not be worth the effort since we will be making frequent releases.
