### ISSUE TITLE
server: Support multiple api keys

### ISSUE THREAD

**Issue by theredcat** [minio/minio#2998]
Is minio going to implement multiple accesskey?

I am aware of #811, but minio-xl repo doesn't exsits anymore.
Also aware of the workaround using multi tenant as described in #2751 (which will be fixed in docs by #2752 ), but this approach need externals tools to be implemented.

Do you plan to implement such a feature in minio (even in a distant future) ?

**Comment by harshavardhana** [comment]
> Do you plan to implement such a feature in minio (even in a distant future) ?

We will not be implementing multiple access key support. #2752 is what holds good for the future as well.

**Comment by pdf** [comment]
@harshavardhana multiple instances do not solve the same problems as multiple keys, unless multiple instances are safe to point at the same data (the multi-tenant docs appear to suggest otherwise)?  For example, compromised keys require rolling credentials on every client, or the need for differing access levels for shared data.

If it is not possible to point multiple instances at the same data (which is in any case quite painful to maintain), is there something technical (rather than philosophical) that makes it particularly difficult to support multiple keys?
