### ISSUE TITLE
Running minio with --address chooses that to the API endpoint. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3130]
## Expected Behavior

--address shouldn't be defaulted to be the API endpoint instead it should be a resolvable address or a publicly accessible IP associated with that DNS. 

## Current Behavior

Current behavior points to a DNS entry which might not be accessible from outside world. 

```
Endpoint:  http://minio2:9001
AccessKey: V8MXUWRVR4NQ8Y442TR1 
SecretKey: 2ZIPHZyYgxFMMzYFsSqxY/iBG++N1X9Prpwdh5Cy 
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://minio2:9001

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://minio2:9001 V8MXUWRVR4NQ8Y442TR1 2ZIPHZyYgxFMMzYFsSqxY/iBG++N1X9Prpwdh5Cy

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 1.6 TiB Free, 1.7 TiB Total
Status:         16 Online, 0 Offline. We can withstand [8] more drive failure(s).
```

## Possible Solution

We resolve the DNS perhaps to its actual IP in this case so that to assume that it is the publicly accessible IP.  If the DNS is fully qualified then we include that as well including the IP.

## Steps to Reproduce (for bugs)

Run a cluster of 16 nodes running a process per disk. 
## Context

This issue affects when they wish to now directly access the cluster by copy pasting the `mc config` option but it doesn't work since the DNS is not accessible outside. 

## Your Environment

Current git master for minio.

**Comment by krishnasrinivas** [comment]
> We resolve the DNS perhaps to its actual IP in this case so that to assume that it is the publicly accessible IP. If the DNS is fully qualified then we include that as well including the IP.

this will not add value because if the name resolves to an IP means the host is as accessible using IP as the DNS host name.

If all the servers are on NAT behind a public proxy then still guessing anything will not be helpful.

The setup where it will be helpful is if there is a private network between the servers for internal communication and the servers have a public IP addresses for external access. To help this case we can check if any of the interfaces have public IP (by checking if the IP does not fall in the internal ip range https://en.wikipedia.org/wiki/Private_network) and use it to display for mc configuration etc.

**Comment by GarimaKapoor** [comment]
@krishnasrinivas what is the update of this issue and the possible fix for this?

**Comment by harshavardhana** [comment]
> this will not add value because if the name resolves to an IP means the host is as accessible using IP as the DNS host name.

I see now closing this,  its working as expected.
