### ISSUE TITLE
Review Minio Server UI/UX 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3229]

**Comment by harshavardhana** [comment]
After review with @abperiasamy  we decided to remove all the unnecessary options 

#### Deprecated ENVs:
- MINIO_BROWSER (Implemented as a security feature but now deemed obsolete since even if blocking access to MINIO_BROWSER, s3 API port is open)
- MINIO_CACHE_EXPIRY (Defaults to 72h)
- MINIO_MAXCONN (No one used this option and we don't test this)
- MINIO_ENABLE_FSMETA (Enable FSMETA all the time)

#### Deprecated options:

Remove --ignore-disks option - this option was implemented when XL layer would initialize the backend disks and heal them automatically to disallow XL accidentally using the root partition itself this option was introduced. 

This behavior has been changed XL no longer automatically initializes `format.json`  a HEAL is controlled activity, so ignore-disks is not useful anymore. 

This change also addresses the problems of our documentation going forward and keeps things simple.

**Comment by krishnasrinivas** [comment]
@harshavardhana MINIO_CACHE_EXPIRY is useful for testing XL, i.e i can be sure that the data is being fetched from the disks and not from the cache. Else we'll have to restart minio every time (so that there is no cached content) we want to check to be sure that XL is working fine.

Otherwise it is very easy to have false positives while testing as we might forget to restart minio and think that it is working well when infact minio is serving from cache which otherwise it would have failed when it tries to fetch data from disk because of a bug (which we will miss detecting because of the cache).

**Comment by harshavardhana** [comment]
> @harshavardhana MINIO_CACHE_EXPIRY is useful for testing XL, i.e i can be sure that the data is being fetched from the disks and not from the cache. Else we'll have to restart minio every time (so that there is no cached content) we want to check to be sure that XL is working fine.
> 
> Otherwise it is very easy to have false positives while testing as we might forget to restart minio and think that it is working well when infact minio is serving from cache which otherwise it would have failed when it tries to fetch data from disk because of a bug (which we will miss detecting because of the cache).

Let's discuss about this @krishnasrinivas
