### ISSUE TITLE
api/mgmt: Implement new lock management APIs (List, Clear).

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3394]
## Expected Behavior
Management API to cater for `minio control lock` command which was previously removed.

## Current Behavior
No way to list the locks held and clear stale locks.

## Possible Solution

A new API perhaps like this 

- ListLocks(olderThan time.Time) 
- ClearLock(lockPath string)

## Context
To bring in management functionalities through this API.

**Comment by krisis** [comment]
@harshavardhana I can take this up. Following is a proposal for the API,

### Lock Management APIs
* List
  - GET /?lock&bucket=mybucket&prefix=myprefix&older-than=rel_time
  - x-minio-operation: list
  - bucket, prefix are optional query parameters
  - Response: On success 200, json encoded response containing all
    locks held, older than rel_time. e.g, older than 3 hours.

* Clear
  - POST /?lock&bucket=mybucket&prefix=myprefix&older-than=rel_time
  - x-minio-operation: clear
  - bucket, prefix are optional query parameters
  - Response: On success 200, json encoded response containing all
    locks cleared, older than rel_time. e.g, older than 3 hours.

**Comment by vadmeste** [comment]
@krisis, can we also specify errors ? like when a bucket doesn't exist.. With Service API, we can only have signature mismatch error which is the one standard specified by S3.

**Comment by krisis** [comment]
@vadmeste if we see ``bucket`` and ``prefix`` query parameters as filter criteria then it is not an error to have found zero matching locks, simply because bucket doesn't exist.

Consider the case where we take a namespace lock on a bucket during MakeBucket operation to synchronize with other concurrent MakeBucket requests. Assume we query for the list of locks while the lock is held, but the MakeBucket operation holding the lock hasn't created the bucket yet. In a sense, the bucket lock exists even without the bucket itself existing in the namespace. I am of the opinion that the lock API returns lock subsystem specific information and doesn't return errors describing the state of the object namespace itself.

We could still return errors like InvalidBucketName, InvalidPrefix, etc which are independent of the state of the object namespace. Does that make sense?

**Comment by vadmeste** [comment]
> Consider the case where we take a namespace lock on a bucket during MakeBucket operation to synchronize with other concurrent MakeBucket requests. Assume we query for the list of locks while the lock is held, but the MakeBucket operation holding the lock hasn't created the bucket yet. In a sense, the bucket lock exists even without the bucket itself existing in the namespace. I am of the opinion that the lock API returns lock subsystem specific information and doesn't return errors describing the state of the object namespace itself.

Yes, you are right. That makes sense.

**Comment by GarimaKapoor** [comment]
@krisis do we have a timeline for the fix?

**Comment by krisis** [comment]
@GarimaKapoor I expect to have a PR for review by 22nd Dec.

**Comment by GarimaKapoor** [comment]
@krisis is it ready for review?

**Comment by harshavardhana** [comment]
> @krisis is it ready for review?

@krisis reviewed the patch check the comments.

**Comment by harshavardhana** [comment]
Fixed by #3491
