### ISSUE TITLE
[distributed] minio high cpu usage with locks running continously

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3404]
![image](https://cloud.githubusercontent.com/assets/622699/20918252/f1435578-bb4a-11e6-8e12-be60a2d87cb0.png)

![image](https://cloud.githubusercontent.com/assets/622699/20918257/fc924ba0-bb4a-11e6-848b-615924ab2696.png)

High CPU usage reported by @dcharbonnier 

## Expected Behavior
Low CPU footprint of dsync and high cluster responsiveness.

## Current Behavior
High CPU usage with 15k locks without no active i/o. 

```
$ go run pcap-reader.go minio.pcap  | strings | grep Dsync | wc -l
15443
```

## Possible Solution
No possible solution yet.

## Steps to Reproduce (for bugs)
Do not have any steps just the minio tcpdump. 

## Your Environment
Latest master

[minio-pcap.zip](https://github.com/minio/minio/files/633283/minio-pcap.zip)

```
package main

/// go run pcap-reader.go minio.pcap

import (
	"fmt"
	"log"
	"os"

	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
	"github.com/google/gopacket/pcap"
)

var (
	handle *pcap.Handle
	err    error
)

func main() {
	// Open file instead of device
	handle, err = pcap.OpenOffline(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}
	defer handle.Close()

	var eth layers.Ethernet
	var ip4 layers.IPv4
	var ip6 layers.IPv6
	var tcp layers.TCP
	var udp layers.UDP
	var dns layers.DNS

	var payload gopacket.Payload

	parser := gopacket.NewDecodingLayerParser(layers.LayerTypeEthernet, &eth, &ip4, &ip6, &tcp, &udp, &dns, &payload)
	decodedLayers := make([]gopacket.LayerType, 0, 10)

	// Loop through packets in file
	packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
	for packet := range packetSource.Packets() {
		err = parser.DecodeLayers(packet.Data(), &decodedLayers)
		if err != nil {
			log.Fatalln(err)
		}
		fmt.Println(string(payload))
	}
}
```

**Comment by dcharbonnier** [comment]
Potential link to #3403, some nodes of this cluster have been killed

**Comment by krisis** [comment]
@harshavardhana There weren't 15K locks. A simple grep on a wireshark trace output includes two lines for every RPC call. At dsync level, an RPC call which appears as two lines with the pattern ``Dsync`` in it, should be counted as an attempt to acquire one lock. Further, if we differentiate lines containing ``Dsync.Lock`` and ``Dsync.Unlock`` using awk and grep generously, we find that 3871 lock calls and 3900 unlocks calls were in transit.

Further, the locks were being taken (and released) on the following object prefixes. @dcharbonnier, it appears that there were ongoing API requests. This is not due to any sort of internal maintenance operation. It is possible that the tcpdump was taken while there was IO in progress from some of the clients. Let us know if you see the issue still.
```
5working-files/0e395bb0-86d5-4b11-b498-4c20ccc18fe3/21
5working-files/0e395bb0-86d5-4b11-b498-4c20ccc18fe3/30
5working-files/3b769660-2e29-4954-8110-bcdcef83d3af/10
5working-files/3b769660-2e29-4954-8110-bcdcef83d3af/34
5working-files/3b769660-2e29-4954-8110-bcdcef83d3af/39
5working-files/5331c7e8-8967-4a34-9775-a3053971a3b8/13
5working-files/5331c7e8-8967-4a34-9775-a3053971a3b8/17
5working-files/5331c7e8-8967-4a34-9775-a3053971a3b8/22
5working-files/5331c7e8-8967-4a34-9775-a3053971a3b8/26
5working-files/7c7d5aad-b5ec-4d1f-8543-8554adf4ba6e/14
5working-files/7c7d5aad-b5ec-4d1f-8543-8554adf4ba6e/18
5working-files/7c7d5aad-b5ec-4d1f-8543-8554adf4ba6e/21
5working-files/7c7d5aad-b5ec-4d1f-8543-8554adf4ba6e/30
5working-files/7c7d5aad-b5ec-4d1f-8543-8554adf4ba6e/34
5working-files/87f9eb1d-76b0-4095-9da8-0698cb8e8488/11
5working-files/87f9eb1d-76b0-4095-9da8-0698cb8e8488/24
5working-files/9f51e2fa-353e-4c92-b8e4-eeaccf5c2ee8/10
5working-files/9f51e2fa-353e-4c92-b8e4-eeaccf5c2ee8/14
5working-files/9f51e2fa-353e-4c92-b8e4-eeaccf5c2ee8/22
5working-files/9f51e2fa-353e-4c92-b8e4-eeaccf5c2ee8/27
5working-files/9f51e2fa-353e-4c92-b8e4-eeaccf5c2ee8/30
5working-files/9f51e2fa-353e-4c92-b8e4-eeaccf5c2ee8/36
5working-files/9f51e2fa-353e-4c92-b8e4-eeaccf5c2ee8/41
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/10
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/15
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/18
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/22
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/26
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/34
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/37
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/39
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/42
5working-files/d89d84fa-71b7-4dc6-b40a-5aecc3832f11/49
5working-files/f5623f60-5494-475b-abcb-6e016377d8df/11
5working-files/f5623f60-5494-475b-abcb-6e016377d8df/24
5working-files/f5623f60-5494-475b-abcb-6e016377d8df/33
5working-files/f5623f60-5494-475b-abcb-6e016377d8df/36

```

**Comment by dcharbonnier** [comment]
there may be few clients connected (2) at that time doing really few operation nothing that can justify this load, I've been running many clients against minio on this setup and I never had a load like that.
And  this load was never going down even after hours.
There is definitely a bug.
I'm not running tests on minio now and you ~fixed the minio crash (removing the cache) so this may not re-appear on my setup, this does not mean that there is no bug, minio should not react like that after a crash, a kill -9 or a reboot may do the same in some conditions.

**Comment by krisis** [comment]
The repeated lock RPC messages seen on tcpdump on the above object prefixes, without corresponding API requests from any client, could be due to unavailability of quorum. i.e at this point in time, there must have been lesser than quorum (N/2+1, where N is the number of disks) disks. The lock subsystem in minio repeatedly tries to acquire the lock until it gets a quorum. This is expected. If you don't expect the crashed servers to be online anytime soon, you could bring the remaining servers offline too, to avoid CPU being consumed unnecessarily. In production, we can expect the server to be replaced or brought back online within a reasonable period of time.

**Comment by harshavardhana** [comment]
@dcharbonnier closing issue as stale and not reproduced since we have fixed networking related issues in dsync.  Will revisit this if seen again.
