### ISSUE TITLE
cli: validate if the order of arguments are consistent across all nodes for the first time.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3425]
## Expected Behavior
Order of arguments are validated properly across all nodes for the first time.

## Current Behavior
Currently if the order of arguments are given wrong for the first time it can end up corrupting the data and create a wrong backend format.

## Possible Solution
Validate the args early on before even proceeding to generate `format` configs.

## Steps to Reproduce (for bugs)
Quite easy start fresh servers with incorrect orders across nodes, as soon as the nodes `format` themselves they fail with inconsistent `format.json`. 

## Context
This is required since it is a common mistake and we should error out early on.

**Comment by harshavardhana** [comment]
any takers here?

**Comment by krisis** [comment]
@harshavardhana One way to get around this issue is to sort the endpoints. This is necessary only for a fresh setup, to determine which Minio server would generate the format.json. Once we have a formatted setup, format.json is the source of truth for order of disks. Further, each object has its own permutation of disks, described in xl.json, as to where the erasure encoded chunks are placed. Does this approach sound OK?
