### ISSUE TITLE
Absolute path?

### ISSUE THREAD

**Issue by dR3b** [minio/minio#3472]
## Expected Behavior
Apache proxy with url "https://www.minio.io/cloud" should work.

## Current Behavior
**Browser:**
```bash
Not Found
The requested URL /minio/ was not found on this server.
```
**Apache logfile:**
```bash
X.X.X.X - - [19/Dec/2016:11:11:36 +0100] "GET /cloud HTTP/1.1" 307 43
X.X.X.X - - [19/Dec/2016:11:11:36 +0100] "GET /minio/ HTTP/1.1" 404 204
```
## Possible Solution
Don't use absolute path?

## Steps to Reproduce (for bugs)
Apache proxy config:
```bash
ProxyRequests Off
ProxyVia Block
ProxyPreserveHost On
ProxyPass "/cloud" "http://10.0.0.17:9000/"
ProxyPassReverse "/cloud" "http://10.0.0.17:9000/"
```

**Comment by koolhead17** [comment]
@dR3b http://minio.io/cloud is confusing. Please explain more, what are you trying to achieve.

**Comment by donatello** [comment]
@dR3b According to https://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass - you are asking that requests like http://youserver.com/cloud/a/b/c should get redirected as http://10.0.0.17:9000/a/b/c - this requires that your clients prefix all URL paths to the Minio server with `/cloud` as configured above. 

This scheme however will interfere with the published AWS Authentication and Signing specification and so I doubt we will be able to support this. Could you describe you use case? We may be able to suggest an alternative approach.

**Comment by dR3b** [comment]
@donatello Yes thats right. I have the following configuration:
```bash
domain: example.com
host: www
url: www.example.com
```
I can't use "/" in apache because there are other things running on this server like **garafa** oder **icinga** and even a blog (default redirect):
```bash
www.example.com/telemetry
www.example.com/monitoring
www.example.com/blog
```
If i use this configuration:
```bash
ProxyPass "/cloud" "http://10.0.0.17:9000/"
ProxyPassReverse "/cloud" "http://10.0.0.17:9000/"
```
... it doesn't work. The url is wrong.
```bash
https://www.example.com/minio/login
```
Should be:
```bash
https://www.example.com/cloud/minio/login
```
Of coure i can use **cloud.example.com** but thats not a solution for me right now.

Thanks.

**Comment by donatello** [comment]
@dR3b This approach will not work because the Minio Server (and AWS S3), the request authentication system and all client libraries (written by Minio and by AWS, and still others), all assume that the server runs at the root of the domain.

So http://example.com/abcd/pqr/abc (where example.com is an S3 compatible object storage server like Minio) represents an object `pqr/abc` in bucket `abcd`. This is why adding `/cloud` as a prefix to support this kind of redirection requires all client-side tools (even the Minio browser login url at `/minio/login` is one) to be modified to use a prefix setting like `/cloud` while building URLs for the object store server. The client-side tools ecosystem for S3 compatible services is large, and we cannot support this use-case in all of them.

A simple alternative that requires no extra servers, and just some configuration is as you suggested using a subdomain like `cloud.example.com` or a completely different host name (say `example1.com`) attached to the server, and setting up apache proxy to perform hostname based redirection to the Minio server.

**Comment by dR3b** [comment]
@donatello 
> ...The client-side tools ecosystem for S3 compatible services is large, and we cannot support this use-case in all of them...

You don't have to. Just implement it in ```mc``` and sell it as a **special feature** ;)

Anyway thanks.

**Comment by harshavardhana** [comment]
> You don't have to. Just implement it in mc and sell it as a special feature ;)
> 
> Anyway thanks.

Can we close this @dR3b ? - Thanks.

**Comment by dR3b** [comment]
Yes thanks.
