### ISSUE TITLE
distributed/shared: potential race between GetObject and GetObjectInfo

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3521]
In GetObjectHandler() we release the fcntl lock between getObjectInfo and getObject giving scope for race condition. i.e a different minio server can replace the object.

Very rare case, nevertheless needs to be addressed in future.

**Comment by harshavardhana** [comment]
This requires fcntl lock on the actual namespace itself.

**Comment by deekoder** [comment]
Can't reproduce easily.

**Comment by deekoder** [comment]
@harshavardhana  & @abperiasamy  pending discussion today.

**Comment by deekoder** [comment]
Discussion today.

**Comment by harshavardhana** [comment]
Discussion still pending will get to this tomorrow.  ETA to fix perhaps by Sat.

**Comment by harshavardhana** [comment]
This issue is not blocked anymore the decision was to bring the locking primitives to object layer interface itself. 

- Since the object layer has the awareness of namespace each such implementation needs to hold its own lock this allows for a simpler behavior overall and allows for namespace lock to be the member of the object layer rather being a global object.
- Implementation entails bringing in 4 new set of APIs at object layer.  

```diff
$ git diff
diff --git a/cmd/object-api-interface.go b/cmd/object-api-interface.go
index 2e4e26d..2408ce1 100644
--- a/cmd/object-api-interface.go
+++ b/cmd/object-api-interface.go
@@ -54,4 +54,10 @@ type ObjectLayer interface {
        ListObjectsHeal(bucket, prefix, marker, delimiter string, maxKeys int) (ListObjectsInfo, error)
        ListUploadsHeal(bucket, prefix, marker, uploadIDMarker,
                delimiter string, maxUploads int) (ListMultipartsInfo, error)
+
+       // Locking operations.
+       Lock(bucket string, object string)
+       Unlock(bucket string, object string)
+       RLock(bucket string, object string)
+       RUnlock(bucket string, object string)
 }
```

**Comment by krishnasrinivas** [comment]
@harshavardhana thinking about it, while implementing the gateway I noticed that the locking code for gateway was not making sense. Hence the right thing to do would be to move NS locking into object layer completely and make the GetObject() signature as:
```
GetObject(bucket, object string, startOffset int64, length int64) (io.ReadCloser, ObjectInfo, error)
```

That way S3 layer is kept free of the NS locking.

**Comment by harshavardhana** [comment]
> That way S3 layer is kept free of the NS locking.

In-fact this style we thought about before the problem is that we need to know ObjectInfo{} before to validate the HTTP Range header.  You won't know `length` of how much should to read until you have parsed and validated the Range header. which would lead to having GetObjectInfo() function to be called before calling GetObject(). So with that in mind passing range header to object layer is wrong leading to breakage of abstraction.  

This problem is only with shared-fs backend.  Erasure coded and distributed erasure coded do not have this problem since they do not rely on filesystem locks. So we don't need to change the object layer behavior of GetObject() to suite just shared fs. Since it would complicate the behavior of erasure coded. 

The approach agreed above also has some fundamental challenges. `fcntl` locking is held while the object is being Read() so we can't easily move fcntl closer to object layer. It is not same as `sync.Lock`

**Comment by harshavardhana** [comment]
Removing the blocked label -  discussion was finished yesterday and it was decided to introduce a change for GetObject() API itself at object layer. 

```
GetObject(bucket, object string,  startRange, endRange int, conditions map[string]string, writer io.Writer) (err error) {
}
```

This is implemented in conjunction with catering the needs of the Gateway layer as well. This avoids implementing addition locking semantics for object layer but instead allows for GetObject() primitive to validate

 - Range header
 - Conditions

By coverting them into meaningful entities for GetObject().  This avoids the unnecessary GetObjectInfo() that is currently used to validate the size of the object against the incoming range header. 

For Gateway layer this function becomes a pass-through where the entire request including range and conditions are directly sent to the backend - making the gateway layer GetObjectHandler() more efficient and avoiding superfluous data transfer. 

Additionally to cater for Gateway requirement another bug needs to be open in minio-go and @krishnasrinivas is going to fix it. @krishnasrinivas can you please open a bug in minio-go to expose a new API? 

Will be working on this ETA 20th Apr.

**Comment by harshavardhana** [comment]
Found a way to address it properly.

**Comment by nitisht** [comment]
@harshavardhana is this still an issue?

**Comment by harshavardhana** [comment]
It is still an issue but v.rare , will need to revisit this after getting a hold on ongoing work on refactoring.

**Comment by harshavardhana** [comment]
We have moved away from these requirements - GetObject takes ETag to ensure that we send the right data if not we error out if the data changed.
