### ISSUE TITLE
package: Create RPM package for Minio (Fedora) 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3576]
## Expected Behavior
https://github.com/pld-linux/minio - much like this we need to publish RPMs for minio binary.

## Current Behavior
We do not have RPM package for Minio. 

## Possible Solution
Become an upstream maintainer. 

## Context
To provide easy to use packages..

## Your Environment
All RPM distributions.

**Comment by carloscarnero** [comment]
I wholeheartedly agree with this! In many environments (rhymes with NCC-1701) containers are still under investigation and traditional binary application packaging is the way to go. I think that compatibility with RHEL/CentOS should also be considered, IMO.

**Comment by carloscarnero** [comment]
@harshavardhana If it is possible to use [Fedora's COPR](https://copr.fedorainfracloud.org/) then I can try a first approach to RPM packaging.

**Comment by shantanugadgil** [comment]
@harshavardhana  @carloscarnero 
I would like to point you to https://github.com/jordansissel/fpm
I am not sure what sort of integration you need, but if building rpm/deb is the requirement,
this tool is pretty awesome.

Cheers,
Shantanu

**Comment by spotrh** [comment]
Someone (I don't remember who) came up to the Fedora table on the first day of FOSDEM, and asked if I would help start an effort to package Minio (and dependencies).

My efforts are here:

https://copr.fedorainfracloud.org/coprs/spot/minio/
https://spot.fedorapeople.org/minio/

Caveats: 

1) I'm not a Go programmer. At all. I'm just a Fedora packager.
2) The "minio" binaries generated by the packages do not seem to work at all on Fedora 26 (what my laptop is running). They just segfault, and I don't really know where to go to troubleshoot that.
3) I patched the code to use paulrosania/go-charset (instead of rogpeppe/go-charset), because it was under a Free license (and there was no licensing information for rogpeppe's go-charset code).

I'm hoping this work is useful to someone else who can take it and run with it. I do not have much time to continue to put into this effort.

**Comment by harshavardhana** [comment]
> Someone (I don't remember who) came up to the Fedora table on the first day of FOSDEM, and asked if I would help start an effort to package Minio (and dependencies).
> 

This is great to know.

> My efforts are here:
> 
> https://copr.fedorainfracloud.org/coprs/spot/minio/
> https://spot.fedorapeople.org/minio/
> 

Thanks for doing this. 

> Caveats:
> 
> I'm not a Go programmer. At all. I'm just a Fedora packager.
> The "minio" binaries generated by the packages do not seem to work at all on Fedora 26 (what my laptop is running). They just segfault, and I don't really know where to go to troubleshoot that.
> I patched the code to use paulrosania/go-charset (instead of rogpeppe/go-charset), because it was under a Free license (and there was no licensing information for rogpeppe's go-charset code).
> I'm hoping this work is useful to someone else who can take it and run with it. I do not have much time to continue to put into this effort.

We started our effort on this feel free to share your RPM spec  - here is the work in progress link https://copr.fedorainfracloud.org/coprs/minio/minio/ 

We will validate and fix issues if there are any.

**Comment by harshavardhana** [comment]
https://copr.fedorainfracloud.org/coprs/minio/ - built packages are now available for Fedora 25, Fedora 26.
