### ISSUE TITLE
erasure: Enable logging when quorum is lost.

### ISSUE THREAD

**Issue by borkd** [minio/minio#3815]
## Expected Behavior
Disclaimer: this was a quick first stab at using minio, without combing through documentation for best practices hence I can't say I know what I am doing.

1. It would be greatly appreciated if Minio devs explicitly state the assumptions of what constitutes an acceptable/handled failure minio can guard against.

2. All occurrences of bit rot should be handled asap and transparently to the user, rewriting corrupted chunks on disk as needed, or at least warning the operator via log messages. It should not matter where bit rot hits first - part.XXX with chunks of raw data, or parity info. 

## Current Behavior / steps to reproduce

1. While server was running I have simulated bit rot in `disk2/bucket/dataset/part.1`. Another terminal ran`mc cat bucket/dataset` in a loop. Output was correct, either due to caching, or data was quietly corrected on the fly from parity info. Corrupted chunk `disk2/bucket/dataset/part.1` was not rewritten with expected content. There were no warning messages pointing out corruption that took place.

2. Corrupted `disk2/bucket/dataset/part.1` was not rewritten with expected content upon restart of the server and subsequent access. Server log stated:
_Status:         4 Online, 0 Offline. We can withstand [2] more drive failure(s)._

3. I have proceeded to kill `disk3` that held parity data for this dataset. `mc cat bucket/dataset` output remained correct, likely due to small size of the dataset and caching effects. Server provided  no warning messages.

4. I have then proceeded to kill `disk4` that also held parity data for this dataset. `mc cat bucket/dataset` output remained correct, likely due to small size of the dataset and caching effects. **At this point original data from bucket/dataset was corrupted, and both parity chunks were gone.** Server provided no warning messages.

5. Errors were reported only after restart of the server and an attempt to access the data. Needless to say, this is a data loss scenario.

## Possible Solution
This was a quick test on a tiny scale. I have a feeling this issue would not manifest itself with files that are bigger than any caching employed by the server or client, but didn't verify that. I'm not familiar with this code to point out the root cause. 

## Context
Evaluating minio in different failure scenarios. Typical use would be tens of millions of small files across multiple buckets. Integrity of data is paramount.

## Your Environment
* Server and client on the same node, four disks.
* Version used: minio: stable 20170216014730 (bottled)
* Operating System and version: OSX / homebrew

**Comment by harshavardhana** [comment]
> While server was running I have simulated bit rot in disk2/bucket/dataset/part.1. Another terminal ranmc cat bucket/dataset in a loop. Output was correct, either due to caching, or data was quietly corrected on the fly from parity info. Corrupted chunk disk2/bucket/dataset/part.1 was not rewritten with expected content. There were no warning messages pointing out corruption that took place.
> 

You have to manually heal the object which has corruption - https://github.com/minio/minio/blob/master/pkg/madmin/examples/heal-object.go - there is no auto healing. 

> Corrupted disk2/bucket/dataset/part.1 was not rewritten with expected content upon restart of the server and subsequent access. Server log stated:
> Status: 4 Online, 0 Offline. We can withstand [2] more drive failure(s).

This doesn't signify what is the current state because erasure coding is not at bucket level but at object level. So if you have lost one part for an object it doesn't mean that the disk itself is down or there is an issue.  Another reason that this is not logged is also because this is not an error condition for Minio.  We have enough read quorum i.e N/2 chunks so it continues to work fine.

You have to manually heal the object which has corruption - https://github.com/minio/minio/blob/master/pkg/madmin/examples/heal-object.go - there is no auto healing. 

> I have proceeded to kill disk3 that held parity data for this dataset. mc cat bucket/dataset output remained correct, likely due to small size of the dataset and caching effects. Server provided no warning messages.
> 

Server has enough read quorum - that is data blocks are still available - so the server keeps running and serving data. It is paramount at this point that you should be replacing the drives and getting them healed in a production system. 

It is also always a better idea to deploy with high parity i.e by using lot more disks like 12-16 - unless you are manually going to heal and replace drives on an occasional basis.

> I have then proceeded to kill disk4 that also held parity data for this dataset. mc cat bucket/dataset output remained correct, likely due to small size of the dataset and caching effects. At this point original data from bucket/dataset was corrupted, and both parity chunks were gone.  Server provided no warning messages.
> 

> Errors were reported only after restart of the server and an attempt to access the data. Needless to say, this is a data loss scenario.

Errors are reported after restart because we need minimum of N/2+1 to initialize the cluster. This is to make sure that you are not accidentally writing wrong data without any parity etc also not changing the order of disks due to some typo which can cause problems for erasure coding.

**Comment by borkd** [comment]
> You have to manually heal the object which has corruption - https://github.com/minio/minio/blob/master/pkg/madmin/examples/heal-object.go - there is no auto healing.

Manual healing is fine as long as there is an indication that an object needs such healing. A fsck/scrub that can be scheduled against a bucket would be quite handy for large buckets. Overhead is horrible when you have to test millions of objects one by one.

> Server has enough read quorum - that is data blocks are still available - so the server keeps running and serving data. It is paramount at this point that you should be replacing the drives and getting them healed in a production system.

I naively assumed quorum was borderline at step 3, and gone at step 4. Server gave no indication of a problem whatsoever at either step. Any data corruption or quorum problems, even if not handled automatically, could be flagged as action item for the operator and/or client.

If disks were to fail loudly during 3 or 4 they would get swapped, yes. If they suffered non-catastrophic silent bit rot for any reason I have an impression this test would still result in data loss. In absence of automated recovery, after step 2, there should have been a loud indication that `bucket/dataset` may need healing.

Thanks for prompt reply!

**Comment by harshavardhana** [comment]
> Manual healing is fine as long as there is an indication that an object needs such healing. A fsck/scrub that can be scheduled against a bucket would be quite handy for large buckets. Overhead is horrible when you have to test millions of objects one by one.

Healing also has listing for example once done you will have `mc admin heal list alias/bucket`  (PS: currently only available in master branch) which provides a '--json' output so that you can trigger them through scripts in parallel etc.

> I naively assumed quorum was borderline at step 3, and gone at step 4. Server gave no indication of a problem whatsoever at either step. Any data corruption or quorum problems, even if not handled automatically, could be flagged as action item for the operator and/or client.
> 
> If disks were to fail loudly during 3 or 4 they would get swapped, yes. If they suffered non-catastrophic silent bit rot for any reason I have an impression this test would still result in data loss. In absence of automated recovery, after step 2, there should have been a loud indication that bucket/dataset may need healing.
> 
> Thanks for prompt reply!

The loud indication cannot be done until you access the file. We can perhaps add a log message to indicate that the accessed file indeed needs healing or perhaps we are at border line.  We will add this.

**Comment by borkd** [comment]
Apologies for not stating this more explicitly. Object in question was being accessed every 2 seconds throughout all the steps. That's why I found lack of warning rather disturbing.

**Comment by borkd** [comment]
I have repeated the small object test with 16 disks and went on with deleting, corrupting or truncating `part.1` files while a client was repeatedly requesting the object every second. Server was restarted after each injected error. Findings:

1. After contents of one disk vanished reads continued without any warning from the server.
Only after the server was restarted: `Status:         15 Online, 1 Offline. We can withstand [7] more drive failure(s).`

2. When part.XXX containing chunk of raw data went missing reads continued without any warning. After server restart this issue was brought into view `ERRO[0013] Unable to calculate checksum ...`

3. When part.XXX containing chunk of raw data was truncated (i.e. due to filesystem corruption) reads continued without any warning. There was no error/warning message upon server restart.

4. When part.XXX containing parity data was truncated or overwritten with garbage reads continued without any warning. There was no error/warning message upon server restart.

5. When part.XXX containing parity data went missing reads succeeded without any warning. There was no error/warning message upon server restart.

After each restart and attempt to access the files for failures 3-5 (fies corrupted but not missing) server status was always a misleading `Status:         15 Online, 1 Offline. We can withstand [7] more drive failure(s).` and no other error messages.

In absence of completely missing files, and when chunk contents were just truncated (XFS could do that on occassion) or altered (bad memory, disk or controller) a long running instance of minio server will not emit a warning even after there are no valid copies left on disk. Clients will continue receiving contents cached in memory until server is restarted. That's when user/operator learns about the carnage and has to reach for backup media. There is some room for improvement here.

This last scenario is trivial to reproduce:

```
# start a server instance & configure client to use it
mc config host add local http://127.0.0.1:9000 APIKEY SECRET
mc mb local/bucket
mc cp file1 local/bucket/dataset
# in another session run "while true; do mc cat local/bucket/dataset | md5; sleep 1; done"
# corrupt a chunk & retrieve the object
for chunk in */bucket/dataset/part.1; do echo -n "$chunk     "; echo -n > $chunk; sleep 2; mc cat local/bucket/dataset | md5; done
# at this point raw data and parity info on disk are altered, 
# clients keep retrieves cached data and server is not reporting any issues
# now restart server
mc cat local/bucket/dataset | md5
mc: <ERROR> Unable to read from ‘local/bucket/dataset’ . [...]
```

Q1: Is the above inconsistent behavior a feature or a bug? 
Q2: Project is rapidly evolving. What failure scenarios can minio handle **today**?
Q3: Is there a way to force end-to-end checksumming for trust-but-verify types?

Thanks!

**Comment by harshavardhana** [comment]
> Q1: Is the above inconsistent behavior a feature or a bug?

This is expected behavior we don't hit the disk if its cached already, unless cache is invalidated. 

> Q2: Project is rapidly evolving. What failure scenarios can minio handle today?

Can you elaborate on this for a bit? 

> Q3: Is there a way to force end-to-end checksumming for trust-but-verify types?

Yes you can turn off the cache with env `export _MINIO_CACHE=off`

My questions to you at any point during these tests did you receive corrupted data? can you perform all the operations with `_MINIO_CACHE=off` ? . 

> When part.XXX containing parity data went missing reads succeeded without any warning. There was no error/warning message upon server restart.

As i explained before this won't a server restart doesn't start crawling the disk - remember there is no auto healing.  If parity went missing it is perfectly normal it doesn't log because - it doesn't need to since there is enough quorum.  

Also if you have 16 blocks and any 8 of them if are available Minio doesn't attempt to read rest of the disks at all it just moves forward to serve the object if quorum number of chunks are in-tact.

> After contents of one disk vanished reads continued without any warning from the server.
> Only after the server was restarted: Status: 15 Online, 1 Offline. We can withstand [7] more drive failure(s).

There are not active updates since there is no active thread verifying if a disk is online or offline.  Disk is available or not is a lazy operation only validated when an object read or write is requested.  But loosing parity of having some corruption on the parity blocks has nothing to do with disk statu. Rest of the disk is usually fine in a scenario like this displaying that disk is down is misleading. 

> After each restart and attempt to access the files for failures 3-5 (fies corrupted but not missing) server status was always a misleading Status: 15 Online, 1 Offline. We can withstand [7] more drive failure(s). and no other error messages.

One of the objects loosing parity blocks - has nothing to do with loosing disk or even printing it here. This is status is correct disk is indeed available it doesn't matter if it has bit-rot or missing part files. 

We will discuss internally how to log in situations like following. 

 - Parity file missing 
 - Data file missing
 - Parity checksum is wrong
 - Data checksum is wrong

This way it is indicated enough so for the administrator to take action.

**Comment by borkd** [comment]
Thank you for clarification. With cache off, error is reported once client requests the object and there is not enough chunks left for server to reconstruct the data 
`cause=Read failed. Insufficient number of disks online`
`cause=Storage resources are insufficient for the read operation.`.

**Comment by deekoder** [comment]
blocked on @abperiasamy

**Comment by deekoder** [comment]
We will consider fixing this in future via admin api feature.
