### ISSUE TITLE
Unable to create blank folders

### ISSUE THREAD

**Issue by tsmgeek** [minio/minio#3849]
Unable to create blank folders in browser.
Using S3 tool such as Cloudberry or S3 Browser I can request creating a new folder but is never created.

## Expected Behavior
Create new blank folder

## Current Behavior
Does nothing

## Your Environment
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311

**Comment by harshavardhana** [comment]
@tsmgeek this is not allowed.. It is expected as per design. You can upload a file with a prefix it can create folders for you.

**Comment by tsmgeek** [comment]
What you call prefixes is just the folder structure from the bucket name to file?

**Comment by harshavardhana** [comment]
> What you call prefixes is just the folder structure from the bucket name to file?

yes something like this `mc cp /etc/issue play/harsha/1/13/2/2/3/3/2/issue`  now here `1/13/2/2/3/3/2` is a prefix.  Minio is a flat namespace that is why it doesn't allow directories since there is no real purpose for them on object storage.  If you need a directory just copy a file with a desired prefix.

**Comment by harshavardhana** [comment]
Closing as answered.
