### ISSUE TITLE
docs: [ecosystem] document and package on official bosh-release for minio

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3850]
Work on http://bosh.io/ to complete bosh release document and project for Minio under multiple deployment configurations 

 - Single node filesystem
 - Single node erasure code
 - Multiple node erasure code

## Expected Behavior

Currently we do not have a document or a completed project to make this work.

## Current Behavior

All projects referenced 

- https://github.com/dpb587/minio-bosh-release
- https://github.com/Pivotal-Field-Engineering/minio-release
- https://github.com/shinji62/minio-dist-boshrelease

Are available as reference but we need to do one from scratch. 

## Possible Solution

Document all step by step instructions possibly follow the style used here - https://mariash.github.io/learn-bosh/

## Steps to Reproduce (for bugs)

Google search and complete documents not available.

## Context
As part of the ecosystem building activity, just like how we did Kubernetes etc.

**Comment by donatello** [comment]
Update on this:

1. FS mode minio works fine.
2. Single node XL mode does not appear to be supported, because Bosh seems to support only a single persistent disk per "job".
3. For dist-XL, there is a port clashing issue within the bosh-lite VM and the containers it attempts to launch - minio server in cluster mode fails to start with a message about bind address already taken.

This work in progress temporarily hosted at https://github.com/donatello/.bosh-minio-release

I am going to try out dist-XL in an actual cloud provider and see if it works.

**Comment by donatello** [comment]
Update on this:

1. All issues with bosh are now solved. As before only single disk FS mode and 1-disk per node distributed node is supported by bosh as we can only attach a single disk to a VM at this time.
2. The bosh release is temporarily hosted at https://github.com/donatello/.bosh-minio-release and makes use of a public read s3 bucket which we use as the bosh blobstore and store minio binaries.

**Comment by donatello** [comment]
The release is published from the new official repo at https://github.com/minio/bosh-minio-release

**Comment by GarimaKapoor** [comment]
Aditya, can we close this issue, since we are tracking it in the repo

**Comment by harshavardhana** [comment]
> Aditya, can we close this issue, since we are tracking it in the repo

Closing this as the project created here [Minio bosh release](https://github.com/minio/bosh-minio-release)
