### ISSUE TITLE
docker: Minio in Docker should be able to read swarm secrets

### ISSUE THREAD

**Issue by alexellis** [minio/minio#3896]
## Expected Behavior

When deploying Minio as a Docker container in Swarm Mode, I should be able to create a secure swarm secret with the access and secret keys. When minio starts, an additional flag should be able to specify the filename to read for secrets.

## Current Behavior

Current behavior generates secrets at start-up and these have to be edited manually outside the container, or created outside the container and bind-mounted.

This is understandable because Docker Swarm Secrets were made available only recently. 

## Possible Solution

Optional flag to minio binary:

```
minio server --secrets-from=/run/secrets/minio_server_1
```

Docker Swarm does not provide secrets through environmental variables because these can be leaked easily - the `/run/secrets/<secret_name>` convention is used. To create a secret use `docker secret create`.

Here is the documentation for Swarm secrets - https://docs.docker.com/engine/swarm/secrets/

CC @NitishT @abperiasamy 

If accepted, I would be open to working on this feature/addition and it would help adoption of Minio with Docker Swarm.

**Comment by nitisht** [comment]
Hi @alexellis, thank you for the proposal. IMHO, adding a secret doesn't add much value in terms of security (specifically for Minio). This is because the Minio server is supposed to be started by someone who has access to the Swarm env (and hence the secret). 

Once the server starts, users/applications accessing Minio will anyways need the credentials as well. 

We did secrets in Kubernetes Helm package. However, it did not need any changes to Minio server itself. For Swarm, as you mentioned we'll need an extra flag to pass the secret path. As minimalists, I think this isn't worth the effort for now. 

Let's wait for what @abperiasamy and @harshavardhana think on this.

**Comment by harshavardhana** [comment]
We decided to do it by writing an entry point script which points to the secret file location by default. 

```
echo "minio" | docker secret create access_key -
echo "minio123" | docker secret create secret_key -
```

```
docker service create --name="minio" --secret="access_key" \
      --secret="secret_key" minio/minio server /export
```

**Comment by alexellis** [comment]
Looks like a good approach. I've been doing something similar myself in a private repo but only for the client-side portion. This would make it much more usable for demos.

**Comment by deekoder** [comment]
needs review with @abperiasamy
