### ISSUE TITLE
ecosystem: Work with NextCloud to support Minio as backend

### ISSUE THREAD

**Issue by rusher81572** [minio/minio#3909]
Hello, I was working with @harshavardhana in Slack to get NextCloud working with Minio. We were both unable to point NextCloud to the Minio server. @harshavardhana did a little more debugging and figured out the error:

```
REQUEST : GET path:/testbucket?acl
Host: 172.17.0.1:8000
Authorization: AWS USWUXHGYZQYFYFFIT3RE:UdTergM/uEe072YpvuZ58J778Jw=
User-Agent: aws-sdk-php2/2.7.5 Guzzle/3.8.1 curl/7.38.0 PHP/5.6.30
Date: Wed, 15 Mar 2017 20:18:22 +0000

INFO[0019] Round trip: http://localhost:9001/testbucket?acl, code: 501, duration: 623.837µs 

-----
RESPONSE STATUS: 501 Not Implemented
Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-03-15T18-33-22Z (linux; amd64)
X-Amz-Request-Id: 14AC279613E45D5F
Date: Wed, 15 Mar 2017 20:18:22 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Key></Key><BucketName></BucketName><Resource>/testbucket</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

Problem:

Nextcloud requires bucket ACL support which Minio does not have yet.

## Steps to Reproduce (for bugs)
1. Enable External Storage in Next CLoud
2. Add S3 storage
3. Enter Minio credentials
4. Observe the red box that appears, meaning it did not connect

**Comment by fossxplorer** [comment]
+1 
Nextcloud/ownCloud + Minio bring the ability to store data from the sync clients supported by the Nextcloud/ownCloud projects, i.e sync client for Linux, Mac OS, Windows, Android and iOS.

**Comment by karlitschek** [comment]
Yes. It would be great to have Nextcloud compatibility. The easiest would be if minio would support ACLs. Is this planed soon?

**Comment by koolhead17** [comment]
@karlitschek Thanks a lot for replying. :)
Actually we are not supporting ACL and don't have any plan to support it. We support bucket policy which is compatible with AWS S3. 
What will be your advice  so that we can get Minio as a storage backend for NextCloud .

**Comment by karlitschek** [comment]
Someone needs to debug the S3 communication to see why it fails

**Comment by krishnasrinivas** [comment]
@harshavardhana what if we reply `public-read` if `read-only` is the bucket policy.

**Comment by harshavardhana** [comment]
> @harshavardhana what if we reply public-read if read-only is the bucket policy.

There is no reply of `public-read` for GetBucketACL @krishnasrinivas you have to reply a different set of XML entirely - which follows http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html a completely different set of language. 

What usually happens is GetBucketACL is initiated to inherit the permissions on the subsequent objects inside a bucket because by default S3 doesn't inherit ACLs as each ACL should be explicitly set for bucket and object separately. 

We implement bucket policies because there is no need to add ACL's for objects on Minio - but instead rely on single bucket policy call to make then either readable, only writable and readable/writable - if nothing is set they are all private. 

Returning any custom values like that won't provide any meaning at S3 spec level. Either we implement ACL fully or we don't. 

We fixed this in [Alluxio PR](https://github.com/Alluxio/alluxio/pull/4217) by not having to inherit bucket ACLs as an option which then disables performing `GetBucketACL()`.

I asked @rusher81572 to open a bug so that we can explore working with NextCloud if such an option is possible, if yes we can send a PR as well.

**Comment by rusher81572** [comment]
Update: I got Minio to work with NextCloud by following this tutorial: 

https://docs.nextcloud.com/server/11/admin_manual/configuration_files/primary_storage.html

I basically created the bucket and then modified config.php to use the object store with path_style_access

**Comment by harshavardhana** [comment]
> Update: I got Minio to work with NextCloud by following this tutorial:
> 
> https://docs.nextcloud.com/server/11/admin_manual/configuration_files/primary_storage.html
> 
> I basically created the bucket and then modified config.php to use the object store with path_style_access

This is great stuff - thank you for doing this @rusher81572

**Comment by rusher81572** [comment]
@harshavardhana You are welcome. So I guess the bug is only with adding external S3 storage, not setting it is a primary storage.

**Comment by haoguan2013** [comment]
@rusher81572 hi,can u share an example of ur config.php? got "Junk Message" exception on Minio. Seems NextCloud sent TSL messages while Minio kept rejecting since it doesn't support TSL messages anymore. Thx!

**Comment by harshavardhana** [comment]
@haoguan2013 Minio supports TLS you need to configure it as such.

**Comment by haoguan2013** [comment]
@harshavardhana i m having trouble set up a TSL connection between nextcloud & Minio. Should I generate a PEM format certificate file and distribute it to Nextcloud?

**Comment by harshavardhana** [comment]
You should setup follwing the docs here https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls

**Comment by deekoder** [comment]
We wont support ACL but other than that primary storage should work.

**Comment by ThisIsQasim** [comment]
I was able to successfully add minio as external storage to Nextcloud. However, Nextcloud is unable to list folders in minio bucket which means that I can only upload files to the root of the bucket and not in a folder. Any ideas what could be happening?
