### ISSUE TITLE
Refactor admin-api 

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4108]
After reviewing :  https://gist.github.com/krisis/3a92e3d7f204cdb2be4355fc01f0759a
Here is all the feedback to incorporate from our review.

# Minio Management API
Management APIs implements remote administrative operations over HTTP/REST. This guide is intended for core package development like [madmin](https://github.com/minio/minio/tree/master/pkg/madmin). 
If you are an enduser please take a look at [mc admin CLI interface](https://github.com/minio/mc).

## Authentication
* Requests are signed using AWS Signature V4
 * `us-east-1` :  defaults to us-east-1 for AWS S3 compatibility 

## Config APIs
Set Credentials goes under this.

### Status

Table is of the format :   Name | Value | Description | Required
 values should have all possible values. 

### Heal APIs
Refer to changes to heal command specified here : https://github.com/minio/mc/issues/2123
@krishnasrinivas  will propose API changes here based on : 

```
GET minio/admin/heal?bucket=mybucket&object=myobject&recursive=true&force=true&advanced=true&remove=true
 ```
### Lock APIs
 * In the list api do we need options since and duration? Need more info.
 * `older-than` : Specify time format with an example.

**Comment by krisis** [comment]
>@krishnasrinivas will propose API changes here based on :

>GET minio/admin/heal?bucket=mybucket&object=myobject&recursive=true&force=true&advanced=true&remove=true

As it stands now, we don't use a resource prefix like `minio/admin/` in the admin REST API. The decision to keep it simply `/?heal` was made during the previous [API review](https://gist.github.com/krisis/dfb01e450dadb75d8ab19bc0e342f1a1/40e2532e01cc0b026132202026c9d0656f3e73da). If we have decided to have `/minio/admin` then I assume it applies to all management operations like `service-restart`, `set-config` etc.

>In the list api do we need options since and duration? Need more info.

We display both duration for which a lock was held and the time since when it is held as it is being captured by our lock-instrumentation code. It is possible to return duration alone in our API.

**Comment by krisis** [comment]
@krishnasrinivas Let me know once the new API proposal is ready. It would be easy to collaborate if you share a Github gist containing the details.

**Comment by krisis** [comment]
@deekoder
>Status

>Table is of the format : Name | Value | Description | Required
values should have all possible values.

I am not sure what values you are referring to here. In `Service Status`, `x-minio-operation` is set to `status`. There are no other possible values.

**Comment by deekoder** [comment]
Clarification for >>Table is of the format : Name | Value | Description | Required

Wherever applicable for the tables in this doc, add value column. The user must be able to look at the table and know what all possible values each option can take.  Eg.  `True`, `False`.

**Comment by krishnasrinivas** [comment]
@krisis here are the issues I noticed with https://gist.github.com/krishnasrinivas/ea5603d16e6d706793332af674df83e3

- Usually there is a REST API endpoint and query-params to customize it.
  For ex. `GET /minio/admin/v1/locks` is an intuitive API.
  But `GET /?lock` with `x-minio-operation: list` header is not an intuitive API.
  Especially for other APIs when we use `x-minio-operation: bucket` and `x-minio-operation: object` for heal. `x-minio-operation` indicates that the value is a verb but bucket/object is not a verb.

- Auth being S3V4 makes usage of the admin rest apis using curl difficult. In kubernetes like environment it will be very convenient to use curl and simple scripts to invoke admin rest APIs. It will also be easy to write admin-sdk. Simple json-web-token based authentication will be enough.

- There was mix of JSON/XML.

- Versioning for REST APIs is needed so that the server can reject outdated clients (or support outdated API versions).

Suggested new API style:
https://gist.github.com/krishnasrinivas/4b216a6ec03925645253788d8e0e241d

**Comment by krisis** [comment]
@krishnasrinivas You can see how we iterated to the current admin REST API [here](https://gist.github.com/krisis/dfb01e450dadb75d8ab19bc0e342f1a1/revisions). Interestingly, [this older revision](https://gist.github.com/krisis/dfb01e450dadb75d8ab19bc0e342f1a1/ee688751ea82fceb58adde7c33e06e067d4a8b53) addresses _some_ of the concerns you bring up. We decided then to be similar to S3's notification APIs, without a resource prefix like `/minio/admin/`. I don't remember the rationale provided then, but this should provide some background while reviewing the new API proposed.

Since we are (re)designing the admin API, let everyone review your new proposal.

**Comment by krishnasrinivas** [comment]
@krisis discussed with @abperiasamy and here is the updated doc:

https://gist.github.com/krishnasrinivas/4b216a6ec03925645253788d8e0e241d

Let me know if anything does not make sense.

**Comment by deekoder** [comment]
need to have the backward compatibility discussion with @abperiasamy

**Comment by deekoder** [comment]
The api looks good. Please proceed. Response/Request can be changed later from type to a map.   Implement heal as a service which takes a prefix , start , stop and status params. In memory (ring buffer lifo object name).

**Comment by deekoder** [comment]
Moving this to next release milestone.

**Comment by nitisht** [comment]
This has been done here https://github.com/minio/minio/pull/5351 closing as fixed
