### ISSUE TITLE
Can't reach 172.17.0.2 (Docker on Mac)

### ISSUE THREAD

**Issue by marcoliceti** [minio/minio#4169]
Following the [quickstart](https://docs.minio.io/docs/minio-quickstart-guide), I do:

```
docker pull minio/minio
docker run -p 9000:9000 minio/minio server /export
```

And I get instructions such as:

```
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
```

Address `http://127.0.0.1:9000` is fine, while `http://172.17.0.2:9000` times out.

I guess that's because `http://172.17.0.2:9000` is meant to be used only from inside the Docker container. Can you confirm this?

**Comment by harshavardhana** [comment]
172.17.0.2 is not accessible on macOS docker because the networking on macOS is little weird for docker, docker starts a VM to support docker on macOS. To access the services you need to point to the VM.   But the VM IP is not available to the container until `host` networking is exposed, so if you wish to see the real IP to access `minio` you need to provide `docker --net="host"` (which is not recommended since it makes your container to be privileged)

This is a challenge so using `minio` binary directly on macOS using `brew install minio/stable/minio`  would be better and far more meaningful approach. 

`docker` support until its become native on macOS it is quite harder to navigate the networking issues which might come up with multiple levels of routing `docker` would have to do by using a VM.

**Comment by harshavardhana** [comment]
Closing this as answered @marcoliceti - please let us know if you have further issues.

**Comment by marcoliceti** [comment]
Yes, thank you.
