### ISSUE TITLE
Address X-Forward header  

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4208]

**Comment by harshavardhana** [comment]
Is this still valid? - don't know what is the context actually here with this header anymore.

**Comment by deekoder** [comment]
This was for windows SSL.

**Comment by krishnasrinivas** [comment]
@deekoder https://en.wikipedia.org/wiki/X-Forwarded-For would help the backend to know the originating IP address. I think this will not be useful for us.

**Comment by ebozduman** [comment]
After discussing the the need to address this issue with AB, Krishna and Deepa, it is concluded that adding `X-Forwarded-For:`  header field is not going to gain us anything other than having extra information for logging purposes.
Because of that, it is decided that we don't need to address it at this point and the issue can be closed.
