### ISSUE TITLE
Do we want to compress objects being stored on Minio?

### ISSUE THREAD

**Issue by nl5887** [minio/minio#4211]
We can compress each object when storing to disk, possibly saving disk storage (and depending on the configuration also speed). This won't work for every kind of file, but maybe make it optionally? Eg. only for certain mimetypes.

**Comment by harshavardhana** [comment]
> We can compress each object when storing to disk, possibly saving disk storage (and depending on the configuration also speed). This won't work for every kind of file, but maybe make it optionally? Eg. only for certain mimetypes.

This was very early on decided that should be done outside of Minio server - using the client tool rather than server side. i.e users can upload using a client SDK with libraries [1] [2]  optionally with `Content-Encoding` set. 

[1] - https://github.com/klauspost/compress is sort of the recommended library which has highly optimized versions for clients to use. 
[2] -  https://github.com/klauspost/pgzip - parallel gzip.

**Comment by deekoder** [comment]
We will consider this in the future after our current roadmap items are done. Will close for now.
