### ISSUE TITLE
[gateway] S3: Cannot put an object using signature v2

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4218]
## Expected Behavior
I should be able to upload an object using signature v2

## Current Behavior
Not able to upload an object using signature v2.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
**Terminal 1:**
1. `minio server --address ":9001" /tmp/fs/`

**Terminal 2:**
1. `MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway s3 http://localhost:9001/`

**Terminal 3:**

1. *Configure mc to point to localhost:9000 and use signature v2*
2. `mc mb myminio/testbucket`
3. `mc cp file myminio/testbucket`

```
ERRO[0002] Unable to create an object. /testbucket/api-stat.go  cause=The request signature we calculated does not match the signature you provided. Check your key and signing method. source=[object-handlers.go:539:objectAPIHandlers.PutObjectHandler()] stack=home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/gateway-s3.go:333:(*s3Gateway).PutObject home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/object-handlers.go:525:objectAPIHandlers.PutObjectHandler home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
```

## Context
Testing

## Your Environment
All, last master

**Comment by nl5887** [comment]
This issue is being caused by V2 not sending an SHA256 hash and minio-go enforcing the hash to be the hash of zero bytes when the connection is not secure. 

https://github.com/minio/minio-go/blob/master/api.go#L665

We can do the following:
* calculate the sha256 hash in the gateway, but we need to read the complete file, write it to disk and then re-upload it
* use UNSIGNED_PAYLOAD, eg change the default behavior of minio-go to not by default calculate the sum of zero bytes
* when using v2 use v2 to upload to Amazon also 

I think the UNSIGNED_PAYLOAD makes most sense, because the user decided not to send a sha256 sum with the request. Otherwise it makes more sense to just return an error instead of using a hash of zero bytes.

**Comment by harshavardhana** [comment]
> This issue is being caused by V2 not sending an SHA256 hash and minio-go enforcing the hash to be the hash of zero bytes when the connection is not secure.
> 
> https://github.com/minio/minio-go/blob/master/api.go#L665

Actually the issue is not that - issue is perhaps in gateway we should allocate both clients i.e one for signature v2 and another for signature v4 - and use them accordingly for each request as they come in. This requires a change in gateway layer to differentiate between V2 v/s V4 calling behavior. 

I would suggest that we disable Signature v2 instead for gateway, since it doesn't make sense to support it - most clients have moved to AWS Signature V4 already.

**Comment by deekoder** [comment]
Let's discuss it further.

**Comment by harshavardhana** [comment]
Most new AWS regions don't support Signature V2 and all regions supports Signature V4. So we will be good by making gateway only support signature v4. We can discuss this with @abperiasamy and finalize.

**Comment by abperiasamy** [comment]
Initialize both v2 and v4 instances of minio-go as @harshavardhana recommended. If the backend server does not support v2 or v4, we can pass on the same error response.

**Comment by krishnasrinivas** [comment]
I am sending the fix

**Comment by krishnasrinivas** [comment]
The problem was minio-go was not the latest

**Comment by nl5887** [comment]
Alright, the commit of @krishnasrinivas should fix this issue.

**Comment by deekoder** [comment]
@abperiasamy  so we did'nt have to do what you suggested.

**Comment by deekoder** [comment]
Support v2 to v4.

**Comment by nl5887** [comment]
* we will pass the md5 from client to server, server will verify the md5sum
* v2 will bridge to v4, so backend will only use v4
