### ISSUE TITLE
object locked indefinitely in one server only

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#4337]
https://gist.github.com/dcharbonnier/29ce3d4668d929bd8b112dcabde06f68
@krisis

**Comment by harshavardhana** [comment]
Thanks a lot @dcharbonnier - clearly looks like a bug on our end.

**Comment by fwessels** [comment]
One possible explanation for this could be that the locker maintenance thread (go-routine) has stopped on this server which would prevent clearing out stale locks. This would prevent this server from ever obtaining a lock on the object again as dsync requires the 'local' server to always participate in granting the lock.

On an alternative note, we are looking to use locks with timeouts (instead of blocking calls) which would (at least) report back an error to the client in case the lock cannot be acquired.

**Comment by fwessels** [comment]
This could be a fix: https://github.com/fwessels/dsync/commit/a27a410a488982448266119df5087a67e4d02cbd

**Comment by fwessels** [comment]
In addition we can implement timeouts (for Distributed as well as XL/FS behaviour), in a similar fashion to https://github.com/fwessels/lsync

**Comment by krisis** [comment]
@fwessels @harshavardhana There seems to be an issue with the instrumentation. totalBlockLocks is 0, but we have a list of blocked locks in the above paste output.

**Comment by harshavardhana** [comment]
> There seems to be an issue with the instrumentation. totalBlockLocks is 0, but we have a list of blocked locks in the above paste output.

Yes it seems like instrumentation lost some information. @krisis

**Comment by fwessels** [comment]
Good observation @krisis maybe some race condition going on

**Comment by deekoder** [comment]
Depends on implement timeouts #4367

**Comment by deekoder** [comment]
PR being reviewed currently.
