### ISSUE TITLE
Changes in Mesos universe package

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4363]
## Expected Behavior
Minimize user inputs while deploying Mesos universe package. 

## Current Behavior
Mesos universe package currently asks user to provide `id`, `cpu`, `mem`, `config-dir` name and size. 

## Possible Solution
Update the Mesos universe package. 
- `id` can be assigned automatically. User should not be expected to assign and remember all the unique names. 
- `cpu`, `mem` can be taken from default values. 
- `config-dir` size should be default and not shown in the UI at all. 
- Also explore Zookeeper style config management. 

## Context
Minio universe package

**Comment by hackintoshrao** [comment]
@krisis , any thoughts on this?

**Comment by krisis** [comment]
@hackintoshrao I can take this up. I already have a [PR](https://github.com/mesosphere/universe/pull/1169#issuecomment-301235857) under review addressing some aspects described here.

**Comment by deekoder** [comment]
ok i will reassign

**Comment by krisis** [comment]
> id can be assigned automatically. User should not be expected to assign and remember all the unique names.

I shall explore if `MARATHON_APP_ID` can be assigned as service `id` without user having to specify it during installation.

>  cpu, mem can be taken from default values.

`cpu` and `mem` already have default values.

> config-dir size should be default and not shown in the UI at all.

There is a PR fixing this under review - <https://github.com/mesosphere/universe/pull/1169>

>  Also explore Zookeeper style config management.

I will explore provisions that are available in DC/OS to use ZooKeeper for Minio server configuration as well.

**Comment by krisis** [comment]
> I shall explore if MARATHON_APP_ID can be assigned as service id without user having to specify it during installation.

There is no ready-made solution available to automatically set a unique `id` for each service instance. User should provide this during installation, either via command line or GUI.
(Correction: It should MESOS_TASK_ID instead of MARATHON_APP_ID.)

There is an open issue tracking a similar feature request here - <https://jira.mesosphere.com/browse/MARATHON-3602>. We shall continue to ask user for unique `id` until this is available.

**Comment by krisis** [comment]
DC/OS packages aspire to be single-click installs. This is made possible by providing default values for all configuration parameters. In Minio package, we have the following input parameters.
- `name`
- `data-size`
- `service-port`

Deploying Minio package with defaults for the above parameters have some consequences.
1. Marathon enforces all service instances to have unique name. So, user will be required to provide a different name for the service. This ensures the user won't have an invalid deployment by accident. 

2. `data-size` will be 2GiB by default. I.e, hosts with disks >= 2GiB will house the instance. Users should be careful about the size of their instance, but all is not lost. You can always spin a larger instance to augment the capacity.

3. `service-port` is a little tricky. As it stands now, user is expected to supply non-overlapping ports in the range [10000-10100] which will be exposed externally by Marathon-LB. We ask the user as opposed to dynamically assign one so that the user knows the port where Minio is listening _apriori_. 
Alternately, we don't ask user for a service port and let Marathon dynamically assign it. This leaves the user to find out the assigned service port after the installation using,

   `dcos marathon app show minio-test | jq '.container.docker.portMappings[0].servicePort'`
 Minio is accessible at `IP:servicePort`, where `IP` is the IP address/hostname of agent where  Marathon-LB is running.

@abperiasamy Let me know which approach we should take w.r.t `service-port` option. I was advised by Mesos folks not to ask for service-port from the user.

**Comment by krisis** [comment]
@deekoder could we add blocked label to this issue? We need to discuss how to expose networking configuration options to the user. This falls under installation UX.

**Comment by nitisht** [comment]
Discussed with @abperiasamy, we'll add default values for all the fields to make one click install work out of the box. Minio universe package advanced installation section will be changed as per the layout below - 

[This is only for standalone mode, further fields will be added for distributed and gateway modes]

```
Tabs for Advanced install section - 
- Service
    - Name - minio
- Resources
    - CPU - 1
    - Memory - 1024 (MB)
- Storage [Always persistent, Host volume (/export) is N/A, as it is used in non persistent.]
    - Volume Size - 1024 (MB) Check if there are units. Then change to GBs. 
- Credentials
    - AccessKey
    - SecretKey
- Network/Networking (check)
    - Remove HTTPS-REDIRECT
    - Public access (enable/disable)  
    - Port [Default: 9000]
```

Discussed with @krisis as well. We're on the same page now.

**Comment by nitisht** [comment]
@deekoder it can be unblocked now

**Comment by krisis** [comment]
https://github.com/mesosphere/universe/pull/1169 addresses all items listed in this issue except using Zookeeper for Minio service's configuration management. There is no Marathon API available to access the underlying Zookeeper instance, which Marathon and Mesos use for their state management. This option may be available if we choose to write our own scheduler framework in future. With this, this issue can be closed. @deekoder
