### ISSUE TITLE
Replace in memory caching with pool based caching.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4389]

**Comment by krishnasrinivas** [comment]
https://github.com/allegro/bigcache
https://github.com/coocood/freecache

**Comment by hackintoshrao** [comment]
Have been profiling and able to see the hotspots around the current cache implementation https://github.com/minio/minio/issues/4345#issuecomment-303608727 . I can evaluate these libraries and see the extent to which it optimizes the overall resource consumption.

**Comment by krishnasrinivas** [comment]
@hackintoshrao no need to test the above two libraries, we'll have to write our own. The APIs by these libraries expose key/value SET/GET, we want streaming SET/GET.

**Comment by hackintoshrao** [comment]
what is streaming GET/SET?

**Comment by krishnasrinivas** [comment]
check pkg/objcache/objcache.go:
```
func (c *Cache) Create(key string, size int64) (w io.WriteCloser, err error)
func (c *Cache) Open(key string, objModTime time.Time) (io.ReaderAt, error)
```

notice that "value" here is a stream. (io.Reader and io.Writer)

**Comment by harshavardhana** [comment]
> what is streaming GET/SET?

We need to writing a wrapper around these libraries or implement a sharded reusable cache implementation - current implementation has an issue because for two reasons 

-  malloc() of size number of bytes, this is a slower operation in general. Say if you have a burst mode of PUT's coming in this can become slower and slower as the referenced memory keeps increasing. Putting pressure on GC.

```
        cbuf := &cappedWriter{
                offset: 0,
                cap:    size,
                buffer: make([]byte, size),
        }
```

- Tuning GC to make sure that server doesn't crash under load also affects the overall usage. 

```
        // Change GC percent if the current cache usage might
        // become 75% of the maximum allowed usage, change
        // the GC percent.
        if c.currentSize+valueLen > (75 * c.maxSize / 100) {
                c.onceGC.Do(func() { debug.SetGCPercent(defaultGCPercent - 25) })
        }
```

These two libraries allows avoiding GC, the technique which was decided to be implemented is to have a pool which is actively reused for all incoming objects, there is no more allocation bottleneck - while the object is being uploaded. 

Any benchmarks or profiling that you will get would necessarily point to these things there will be high CPU usage due to aggressive GC.  Memory allocations are going to point to objectcache - presumably just because that is what it is doing (its not a surprise)

So until it gets fixed properly i don't see a good reason to run profiling with caching turned on, as it might over shadow other unusual memory allocations that we might necessarily have. Since we know the fix it is okay to run caching turned off  - IMHO for all the PDFs that you will generate @hackintoshrao

**Comment by krishnasrinivas** [comment]
> We need to writing a wrapper around these libraries 

writing wrapper will not help will not fix the GC problem, it has to be built  like io-cache (glusterfs) i.e have pool of pages. Each object will be associated with list of pages that gets returned back to free-pool once this object is evicted from the cache. For new object to be cached we reuse the pages from the free-pool.

**Comment by krishnasrinivas** [comment]
@deekoder @abperiasamy asked to close this issue. We can open this issue if performance becomes really a problem and we need to have mem pool based caching.
