### ISSUE TITLE
Minio Browser and mc should support kerberos/SAML auth.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4406]
User must be able to login with kerberos username/password and authenticate via minio browser and use Minio FS. mc should also work with kerberos username/password.

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/tree/sts initial work supporting this is here..

**Comment by harshavardhana** [comment]
- https://github.com/minio/minio/tree/sts working code for minio is here. ~~(Works for GCS as well)~~
- https://github.com/minio/mc/tree/sts working code for mc is here. ~~(Works with Minio and GCS as well)~~

Currently evaluating the Azure identity provider and service provider for our azure gateway backend.  Due to lack of docs and finding to hard to navigate the azure portal UI is causing the delays - hopefully we should have something working next week..

**Comment by harshavardhana** [comment]
With the new design `Federator` is a separate project. We can close this bug.

**Comment by gjonespf** [comment]
@harshavardhana this you mean?
https://github.com/minio/federator
Guessing you're looking at some plugin approach with something AzureAD specific?  Interested to see where this goes.

**Comment by harshavardhana** [comment]
> @harshavardhana this you mean?
> https://github.com/minio/federator
> Guessing you're looking at some plugin approach with something AzureAD specific? Interested to see where this goes.

@gjonespf soon will post more details, currently the code is local.

**Comment by harshavardhana** [comment]
> With the new design Federator is a separate project. We can close this bug.

Closing this bug.. as moved to https://github.com/minio/federator
