### ISSUE TITLE
Implement server side encryption AES 256

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4416]

**Comment by harshavardhana** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

An example to test it working.  Following example works with S3. 

https://github.com/minio/minio-go/blob/master/examples/s3/putobject-getobject-sse.go

**Comment by vadmeste** [comment]
First prototype: a working server encryption under FS with an aws sdk client, ETA: 24 May.

**Comment by vadmeste** [comment]
In server-side encryption mode, the client doesn't need to know anything to upload and download objects. It means that, if access/secret keys are compromised, all data will also be compromised. The developer can still use client side encryption to enforce his data protection strategy. 

The most secure way that I see for the moment when using server-side encryption, is to avoid storing a plain version of the access/secret keys. They can be shown to the user only the first time Minio is executed and the user has to store them safely. But that also means that if access/secret keys are lost, all encrypted data will be lost.

We probably can search for a framework that solves this problem with the best manner.

For the moment, I will continue with a master key = (access+secret) to simplify the first version of the PR.

**Comment by harshavardhana** [comment]
@vadmeste there are three types of mechanisms here 

 - http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html
 - http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html
 - http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html

What we need to implement is SSE-C that is the last one in the list where custom provides the keys to decrypt the data. If these headers are set we are supposed to reject the operation if its not on SSL connection.  

KMSEncryption requires KMS service which is a separate API layer which we don't need to implement, SSE-S3 is also another way where the keys are managed by the server itself which we don't need to implement.

**Comment by vadmeste** [comment]
yes @harshavardhana, SSE-S3 is more difficult to maintain its security. I'll stick with SSE-C as you suggested.

**Comment by aead** [comment]
[SSE-C](http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html) does not specify which algorithm is used to encrypt objects (it only says: AES-256 but not which mode). SSE-C is transparent to the client anyway so the best option would be [AES-GCM](https://en.wikipedia.org/wiki/Galois/Counter_Mode). Unfortunately it the Go standard library does not provide a streaming API  - See: [cipher.AEAD](https://golang.org/src/crypto/cipher/gcm.go?s=400:1713#L5). So I started a aesgcm project implementing AES-GCM with a streaming API.  

General plan:
1. Implement AES-GCM for SSE-C
2. Implement AES-CBC for client side encryption
3. Implement AES-GCM for the client side encryption to let users select whether they want to be AWS compatible or to use a modern (and more secure) encryption scheme.

**Comment by aead** [comment]
Actually there`s a better solution:

Instead of encrypting the objects in the Object-layer, we can move encryption down to the erasure coding. Since we will use an AEAD (AES-GCM or ChaCha20Pol1305) we can skip the BLAKE2b hash computation and use the generated authenticator as the bit-rot detection mechanism. So if we use the authenticator as the erasure-hash for encrypted objects we can actually use the authenticator to compute the erasure-hash for non-encrypted objects, too.

So we do the following:
 - If encrypt-mode: Encrypt and auth. object and use auth. MAC as bit-rot hash
 - Else: Compute the auth. MAC (without encryption) and use auth. MAC as bit-rot hash

This requires:
 - If we encrypt, the user must provide a key and we will be able to encrypt and authenticate the object.  
 - If we do not encrypt, we must generate a random/unique key (for the authenticator) and store the key in the xl.json The key can be used as a master-key to derive subkeys for the individual parts.
This scheme won`t work properly if we do not create a random/unique key for every object!!!

This change has some nice properties:
 - General speed-up (Authenticators are > 2GB/s on amd64)
 - Encryption  will have no (noticeable) performance impact.

See [polynomial authenticators](https://github.com/aead/poly)

**Comment by aead** [comment]
@deekoder We can close this. Basic support is merged and I'll open separate issues for each feature.
