### ISSUE TITLE
 ecosystem: Minio does not support encoding of : in the path names of objects on windows.

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4437]
Cloudberry creates a file structure with ":" character in the path name of the object
":" is not allowed on windows file systems. Minio doesn't try to encode and tries to be native to avoid any custom data format.

## Expected Behavior
 Decide how to handle this

## Current Behavior
 Not handling : in path names on windows.

## Context
This issue is reported by cloudberry. 
 
## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
Blocked on further discussions.

**Comment by harshavardhana** [comment]
This is unblocked after discussing with @abperiasamy .

- Minio will not do that special encoding and path translation. While it can be done it can cause incompatibilities across other clients when special encoding is used. 

   - Lets say `:` is encoded and written as `%2B`  and written successfully.
   - Another client uploads a file with `%2B` already encoded on the path, in this case we will
     write it as is.
   - Now on future lookups the path will get translated which will lead to issues since the client saved
     `%2B` but we are interpreting it as `:`  instead. 

- Minio connector by CBB is the right place to do these translations for windows. Since it is CBB only requirement we don't need to change anything on our end.

**Comment by harshavardhana** [comment]
Will communicate back to CBB folks with this suggestion.

**Comment by deekoder** [comment]
Closing this issue as explained above. This should not be handled in minio also because it will affect data liberation/migration later. So its best for the application to handle encoding strings. Please reopen this issue if you want to discuss further.
