### ISSUE TITLE
Distributed Docker Minio keeps throwing disk errors

### ISSUE THREAD

**Issue by TJC** [minio/minio#4626]
I spoke briefly with kp in the Slack channel about this issue.

I have four servers, and one Minio instance on each, running as a four-disk distributed cluster.

It works for a short time, then starts throwing errors a lot, like:

`msg="Unable to fetch disk info for &cmd.networkStorage{rpcClient:(*cmd.AuthRPCClient)(0xc4202a9760)}" cause="disk not found" source="[xl-v1.go:199:getDisksInfo()]"`

Running `mc admin info` says that three of the four nodes see three disks offline each; but after some seconds, it goes back to saying all disks online. But attempting to make a bucket fails if run again.

This is the setup. Assume you have four nodes, called m1, m2, m3, m4, then run this on each one:

```
mkdir -p /opt/minio/export
docker run --rm --hostname={{ ansible_fqdn}} \
    -p 9000:9000 \
    -v /opt/minio/export:/export \
    -e MINIO_ACCESS_KEY=something \
    -e MINIO_SECRET_KEY=somethingsecret \
    minio/minio server --address :9000 \
    http://m1:9000/export \
    http://m2:9000/export \
    http://m3:9000/export \
    http://m4:9000/export

```

Configure `mc` to talk to it, and just start creating buckets and adding files to them, removing files, and removing the bucket, with a delay. I guess you have test scripts like these that are more powerful than mine! (which is essentially a few lines, a counter, and a sleep, so I end up with `mc mb test/test$n` etc)

I find it starts failing quite quickly, especially if I run `mc admin heal test` a few times.

**Comment by TJC** [comment]
If it wasn't clear -- `{{ ansible_fqdn }}` should be converted into the hostname of that host; if you're not using ansible, you could do something like:

```
hostname=$(hostname -f)
docker run --rm --hostname=$hostname \
....
```

**Comment by TJC** [comment]
By the way, is it normal that `mc admin info` reports the first host as `localhost` but then the rest by their FQDNs?

Eg:
```
$ mc admin info uploader
●  localhost:5070
   Uptime : online since 47 minutes ago
  Version : 2017-06-13T19:01:01Z
   Region :
 SQS ARNs : <none>
  Network : Incoming 19KiB, Outgoing 28KiB
  Storage : Total 238GiB, Free 219GiB, Online Disks: 1, Offline Disks: 3

●  v05.xxxxxxxx.net:5070
   Uptime : online since 52 minutes ago
  Version : 2017-06-13T19:01:01Z
   Region :
 SQS ARNs : <none>
  Network : Incoming 83KiB, Outgoing 38KiB
  Storage : Total 954GiB, Free 875GiB, Online Disks: 4, Offline Disks: 0

●  v06.xxxxxxxx.net:5070
   Uptime : online since 52 minutes ago
  Version : 2017-06-13T19:01:01Z
   Region :
 SQS ARNs : <none>
  Network : Incoming 82KiB, Outgoing 40KiB
  Storage : Total 954GiB, Free 875GiB, Online Disks: 4, Offline Disks: 0

●  m07.xxxxxxx.net:5070
   Uptime : online since 52 minutes ago
  Version : 2017-06-13T19:01:01Z
   Region :
 SQS ARNs : <none>
  Network : Incoming 80KiB, Outgoing 39KiB
  Storage : Total 954GiB, Free 875GiB, Online Disks: 4, Offline Disks: 0

```

**Comment by harshavardhana** [comment]
Thanks for the bug report @TJC  - we will get back to you n this meanwhile can you provide more information regarding the network connectivity etc?

 - Are you using swarm? if not why? are there any reasons to use --hostname based approach. 
 - Does the --hostname based approach guarantee that all servers in the cluster get the hostname information populated i.e /etc/hosts have proper entries? 
 - Can you use `--net="host"` and see if this problem goes away since you are not using swarm? 

Just for your information admin API has not stabilized yet and it is not recommended for use in any form on a production system. It is going through a rewrite and will be different from how it is implemented today.

**Comment by TJC** [comment]
Hi @harshavardhana ,
We are using Swarm v1 unfortunately -- and while we have plans to migrate to swarm v2 with the overlay networks, we're not there yet. The --hostname method appeared to work initially, and after chatting in Slack, it sounded like quite a reasonable approach.

The --hostname approach, in our case, will guarantee that all nodes can resolve each other. The names given there are recorded in the DNS server used by all nodes.

I'll try out the --net=host method now.

**Comment by TJC** [comment]
Reporting back -- I tried using --net=host, but this didn't even boot up unless I used IP addresses for the endpoints, instead of host names.

With IP addresses it starts up and works briefly, but failed pretty quickly. I did run one `mc admin heal` in there as the command prior to it failing, I note.

**Comment by krishnasrinivas** [comment]
@tjc regarding the issue you are having, do you see problems even before using `mc admin` command? or do you see it only after trying out `mc admin` command? this is to know if `mc admin` caused any problems, or if the root cause is something else

**Comment by TJC** [comment]
Here's a test script that fails for me:
```
#!/usr/bin/env perl
use 5.18.0;
use warnings;
use IPC::Run qw(run);

for my $c (100..300) {
    if ($c % 20 == 0) {
        run("mc admin heal uploader");
        sleep 120
    }
    trytwice("mc mb uploader/test$c");
    for (1..4) {
        trytwice("mc cp test$_ uploader/test$c");
    }
    sleep 5;
    $c++;
}

for my $c (100..300) {
    for (1..4) {
        trytwice("mc rm uploader/test$c/test$_");
    }
    if ($c % 20 == 0) {
        run("mc admin heal uploader");
        sleep 120;
    }
    trytwice("mc rm uploader/test$c");
    sleep 5;
    $c++;
}


sub trytwice {
    my $cmd = shift;
    my $r = run($cmd);
    if ($r) { return }
    warn "Failed $cmd once...\n";
    run($cmd) or die "Failed $cmd\n";
}
```

**Comment by TJC** [comment]
Interesting, if I remove the `sleep` commands, it runs fine, for very long periods of time.

With the sleep commands, it dies pretty quickly

**Comment by harshavardhana** [comment]
This is the problem of our current https://github.com/minio/minio/blob/master/cmd/server-mux.go#L139 this actually creates a sort of a deadline where each 15 secs RPC timesout and has to reconnect upon a subsequent operation. Lets say the reconnect failed then we would see disk going up and down all the time. With sub-millisecond latency this might get noticeable. 

Just as @TJC found in high stress tests this doesn't happen, since the ReadDeadline is reset upon successful reads from the client so RPC has no reason to timeout. But without a sustained I/O if the network connection is idle for more than 15-secs then this would happen. 

We need to quickly fix this by removing the deadline which is the cause of this problem. This is the problem i have mentioned previously in bugs like 

- https://github.com/minio/minio/issues/4476
- https://github.com/minio/minio/issues/4476
- https://github.com/minio/minio/issues/4183

There are three possible solutions to this sorted by quickness 

- Have a quick fix to remove the Deadline for Read()
- Move to go1.8.x releases and remove our server-mux implementation.
- Merge https://github.com/minio/minio/pull/4217 PR (has lot of changes)

**Comment by krishnasrinivas** [comment]
> Move to go1.8.x releases and remove our server-mux implementation.

How will 1.8 help the deadline problem? @harshavardhana

**Comment by harshavardhana** [comment]
> How will 1.8 help the deadline problem? @harshavardhana

Because we won't set any - we can remove server-mux.go and let go1.8.x http server deal with it.

**Comment by harshavardhana** [comment]
> Because we won't set any - we can remove server-mux.go and let go1.8.x http server deal with it.

If deadlines needs to be used we should avoid it for RPC connections.

**Comment by krishnasrinivas** [comment]
> Because we won't set any - we can remove server-mux.go and let go1.8.x http server deal with it.

But isn't deadline needed to disconnect the inactive clients so that they dont eat up the resources?

**Comment by krishnasrinivas** [comment]
> If deadlines needs to be used we should avoid it for RPC connections.

Yes. Deadlines should apply only to S3 requests not minio internal communication or admin requests. We had discussed about this previously. At the place where we can set the deadline we won't know if it's an admin or S3 call. Maybe we can look at alternative http server implementation which exposes this capability?

**Comment by harshavardhana** [comment]
The problem happens because of this 

Once the **rpc.DialHTTP** is done by the client the rpc server hijacks the connection the conn obtained here is already set with the Deadline.

```go
  // Can connect to RPC service using HTTP CONNECT to rpcPath.
  var connected = "200 Connected to Go RPC"
  
  // ServeHTTP implements an http.Handler that answers RPC requests.
  func (server *Server) ServeHTTP(w http.ResponseWriter, req *http.Request) {
  	if req.Method != "CONNECT" {
  		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
  		w.WriteHeader(http.StatusMethodNotAllowed)
  		io.WriteString(w, "405 must CONNECT\n")
  		return
  	}
  	conn, _, err := w.(http.Hijacker).Hijack()
  	if err != nil {
  		log.Print("rpc hijacking ", req.RemoteAddr, ": ", err.Error())
  		return
  	}
  	io.WriteString(conn, "HTTP/1.0 "+connected+"\n\n")
  	server.ServeConn(conn)
  }
```

```go
  // ServeConn runs the server on a single connection.
  // ServeConn blocks, serving the connection until the client hangs up.
  // The caller typically invokes ServeConn in a go statement.
  // ServeConn uses the gob wire format (see package gob) on the
  // connection. To use an alternate codec, use ServeCodec.
  func (server *Server) ServeConn(conn io.ReadWriteCloser) {
  	buf := bufio.NewWriter(conn)
  	srv := &gobServerCodec{
  		rwc:    conn,
  		dec:    gob.NewDecoder(conn),
  		enc:    gob.NewEncoder(buf),
  		encBuf: buf,
  	}
  	server.ServeCodec(srv)
  }
  
  // ServeCodec is like ServeConn but uses the specified codec to
  // decode requests and encode responses.
  func (server *Server) ServeCodec(codec ServerCodec) {
  	sending := new(sync.Mutex)
  	for {
  		service, mtype, req, argv, replyv, keepReading, err := server.readRequest(codec)
  		if err != nil {
  			if debugLog && err != io.EOF {
  				log.Println("rpc:", err)
  			}
  			if !keepReading {
  				break
  			}
  			// send a response if we actually managed to read a header.
  			if req != nil {
  				server.sendResponse(sending, req, invalidRequest, codec, err.Error())
  				server.freeRequest(req)
  			}
  			continue
  		}
  		go service.call(server, sending, mtype, req, argv, replyv, codec)
  	}
  	codec.Close()
  }
  ```

> Yes. Deadlines should apply only to S3 requests not minio internal communication or admin requests. We had discussed about this previously. At the place where we can set the deadline we won't know if it's an admin or S3 call. Maybe we can look at alternative http server implementation which exposes this capability?

~~The differentiation is hard.. since on wire it looks like a HTTP connection at first. But becomes a RPC later - to fix this properly we should move to grpc which provides not only graceful shutdown also proper timeout management.~~

server-mux purpose earlier was to simply provide graceful shutdown and be able to serve HTTP and HTTPS on the same connection.  We deprecated the latter already, graceful shutdown is already present in go1.8.x release. ~~So the purpose of adding deadlines came in later, without a proper framework and understanding timeouts across the code - it is frivolous to just add them at connection layer without a proper canceler and resetter.~~

EDIT: There is an implementation problem in the current server-mux.go and we can indeed keep the code for the time being. Refactor PR from @balamurugana https://github.com/minio/minio/pull/4217 fixes this properly.
