### ISSUE TITLE
Organize packages related to bitrot and hashing algorithms 

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4649]
Vendorize external packages already published.

**Comment by aead** [comment]
The current approach/state:
For bitrot protection minio will use poly. authenticators (Poly1305, GHASH) and support hash functions (SHA-256, BLAKE2b-512) for backward compatibility reasons.
Both concepts (hash functions and poly. authenticators) share some properties but are not the same.
So currently there is a package `bitrot` under `github.com/minio/minio/pkg`. The design of the package is very similar to the hash API of the golang [crypto package](https://golang.org/pkg/crypto/)
This makes it very easy to add/exchange bitrot implementations/techniques to the minio server. Similar to Go's crypto package you can easily register a bitrot.Algorithm implementations by implementing bitrot.Hash.
The package is named `bitrot` because it provides a general API for detecting data manipulation. So it is probably useful for everyone who try to detect bitrot / malicious data manipulation.
For more details take a look at the `encryption` branch of minio/minio.

Every bitrot implementation (SHA-256, BLAKE2b and now Poly1305) is implemented in an own repository and vendored into minio/minio. (there is currently no GHASH implementation - it's on my todo list). They are vendored because these are projects which are not owned by minio (expect for SHA-256-simd).

### How bitrot will work in the future?
1. Implement a bitrot protection/verification technique which implements the `bitrot.Hash` interface
(like BLAKE2b or Poly1305)
2. Add an algorithm constant in `minio/pkg/bitrot` (see existing bitrot.Algorithm)
3. Register the implementation (bind the implementation to the algorithm). This is done by calling `bitrot.RegisterAlgorithm` from a `init` function in minio/minio (currently xl-v1-metadata.go)

As long as your technique does not require to save anything else then a hash value and maybe a key your done.
