### ISSUE TITLE
Inconsistent file listing when there is less than n/2 object in a cluster

### ISSUE THREAD

**Issue by akhmadfld** [minio/minio#4674]
Hi, I make experiment with minio cluster. I have an issue when there is less than n/2 object in a cluster.

## Expected Behavior
Without healing feature, I hope that minio server only list downloadable file, not file with less than n/2 object in the cluster

## Current Behavior
When there is n/2 object in cluster, sometimes minio list files with less than n/2 object, and sometimes not. When the file is listed and I try to download that file, the result is only file with 0 byte size.

## Possible Solution
Maybe not direct solution to this issue, but I hope that healing feature can solve this issue because it can make sure that every object is consistent with n/2 disk

## Steps to Reproduce (for bugs)

1. I make 3 instance, a,b,c
2. I make a cluster in them, with `2 disk in instance a`, and `1 disk in the rest instance`, the command is like this
`./minio server http://a/minio, http://a/minio2, http://b/minio, http://c/minio`
3. I upload 1 file (ex. file-a.txt) from server `b` with `all cluster on` -> success
4. I see in every minio directory in them with command `ls -l /minio/bucket/file-a.txt/`, and I get result that `every minio instance` have `file-a.txt` directory
5. I try to shutdown instance `b and c`, so the 2 disk in instance a are still up
6. I try to dowload file-a.txt from instance a -> success -> n/2 disk tolerant ok
7. I turn on instance `b and c`, so `all instance is up`
8. I turn off instance a -> 2 disk is missing
9. I download file-a.txt from instance b or c -> success -> n/2 disk tolerant ok
10. I try to upload new file with 2 instance -> fail -> because not quorum -> ok
11. I turn on instance a -> turn off instance b -> I have 2 disk in instance a and one disk in instance c -> it should be quorum
12. I upload 1 file (ex. file-b.txt) -> success -> quorum -> ok
13. I try to download file-b.txt from every instance-> success
14. I turn on instance b -> 4 disk up (The problem start here)
15. I try to download file-b.txt (which is uploaded when instance b down) from instance b web interface -> success
16. I try to shutdown instance a with 2 disk -> instance b and c is up with 2 disk total
17. I try to download file-b.txt from instance b again -> success but with 0 byte size -> error
18. I try to refresh browser of instance b and c many times -> file-a.txt always appear, sometimes `file-b.txt appear, sometimes not`
19. I try with `mc ls instanceb/bucket` and `mc ls instancec/bucket` -> file-a.txt always appear, sometimes `file-b.txt appear, sometimes not`
20. I look at instance b minio directory with command `ls -l /minio/bucket-name/`, I just see `file-a.txt` directory. 
21. I look at instance c, and there are `file-a.txt` and `file-b.txt` directory
22. I turn on instance a with 2 disk, and then look at the directory, I found `file-a.txt` and `file-b.txt` directory
23. I try to turn off instance b and c -> 2 disk up
24. I download file-b.txt from instance a -> success -> n/2 reached

I think this is why the download for `file-b.txt` was fail when there is only instance `b and c`. There is not enough n/2 disk available (the file only exist in instance c). 

When I look at the browser from instance b or c, I refresh the browser many times. Sometimes file

I expect that when there is instance b and c up, I can download `all` of uploaded file, although there is file that uploaded when b is down.

## Your Environment

* Version used (`minio version`):
```
Version: 2017-06-13T19:01:01Z
Release-Tag: RELEASE.2017-06-13T19-01-01Z
Commit-ID: 353f2d3a6e30f595a721abcd9cf1b108b041ee21
```

* Operating System and version (`uname -a`): 
```
Linux minio1 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (Centos 7)
```

**Comment by deekoder** [comment]
Maybe related to #4672

**Comment by akhmadfld** [comment]
> Maybe related to #4672

Exactly. I don't think that @vadmeste write this issue for me. Actually we have discussed this in slack. 

But I write a little more detail here. Maybe it can help resolve the issue.

**Comment by deekoder** [comment]
ok thanks @akhmadfld  will get back to you on this soon.

**Comment by fwessels** [comment]
First of all, thank you @akhmadfld for the extensive reporting.

The key issue here is that effectively you are running a three node system and not a four node system -- there is no point/advantage of running a three node system instead of a four node system, even if server instance a would be twice (2x) as powerful in terms of hardware and storage capacity compared to instances b and c. Let me explain.

### Downside of a three node system

The reason for this is precisely what you have discovered, when instance b is down (a & c are up), you are creating `file-b.txt` on three disks which gives you just about write quorum. Now when you bring instance b up you scale up to four disks, but when instance a goes down you lose **two** disks at once. And as `file-b.txt` was never created on instance b, only instance c has (a part of the contents of) the file and we are not meeting the minimum read quorum of 2.

The fact that the `file-b.txt` exists on instance c but not instance b, also explains your step 18) with the file sometimes appearing and sometimes not. This boils down to the randomized order in which the list of disks is determined (see https://github.com/minio/minio/blob/master/cmd/xl-v1-common.go#L22). Now you may argue that we should behave consistently and maybe we should, but I am not sure what is better in terms of showing the (bad) file or always hiding it....

Also note that in this case, without instance a being up, you will not be able to heal the file because, again, the read quorum is not there.

A better setup would be the following whereby, on instance a, you are running two minio processes at ports 9000 and 9001, for example:
```
$ minio server --address :9000 http://a:9000/minio, http://a:9001/minio2, http://b/minio, http://c/minio
$ minio server --address :9001 http://a:9000/minio, http://a:9001/minio2, http://b/minio, http://c/minio
```
(instances b and c the same as in your example).

Now taking instance a down would require terminating two processes (or two processes would have to crash which is must less likely than a single process).

Note that this setup is not much less efficient than your scenario, instead of a "larger" minio instance serving 2 disks, we now have 2 "smaller" minio instances each serving a single disk.

However, even in this setup, when for example the network to instance a goes down, you again end up with the scenario that you described. 

### Better solution: four node system

So an inherently better setup is to have four equal servers (whether real or virtual) in terms of disk capacity and run one minio process per server.

This way it does not matter which server is down when you are uploading a file and you can lose any two servers and still be able to serve the file back (and the flip flopping of the occurence of the file in the browser will not happen).

**Comment by deekoder** [comment]
Please reopen if you'd like to continue this discussion.
