### ISSUE TITLE
How can I extend the storage size after deployment in same instance ?

### ISSUE THREAD

**Issue by listeng** [minio/minio#4712]
@NitishT  It's related #4364 , but my question is that if I startup a new Minio instance when I run out of storage, the url and port will be changed. How to extend storage size like AWS S3 that do not need to change the url, and scale infinitely. Thanks.

**Comment by nitisht** [comment]
@listeng can you provide some more info about the setup, number of disks, disk capacity, number of servers, current data size and expected data size etc. so I can think of other ways/tools to handle your requirements.

**Comment by listeng** [comment]
Just like your CCTV video storage use case. I have setup a distributed Minio instance run on three machine, and each machine have 1TB free disk space. The web application can access the data from http://aaa:9000/xxx with AccessKey:AAA and SecretKey:BBB. 

After a month, the disk only have 100MB free space of disk. Is there any way to extend free usable disk space of Minio when I buy some new machine. If startup new Minio instance, the web application need to save the new url of Minio as http://bbb:9000/xxx and mapping another AccessKey/SecretKey. Sometimes, the old instance maybe delete some data, and how the web application know the free space of the old instance enough for store new files. 

Thanks.

**Comment by fwessels** [comment]
Minio is designed to scale with multiple instances instead of one single instance that scales "infinitely" which is even a bad design choice for Amazon S3 as they recommend to create multiple buckets over time and spread out your data.

Therefore it is a good design choice to store the bucket name somewhere in your application stack like in a database or key value store (and tie the bucket name to the hostname and port number). 

Typically you will run minio on a server with access to all disk space on a server. Once that disk space is filled up you launch another server with fresh disk space and run a second instance of minio. (And note that you can make the access and secret key identical by editing `~/.minio/config.json`)

As an alternative, if you add new disks to an existing server you can also keep the existing instance the same and run a second instance of minio on the same server at a different port. And create a new bucket for this instance where it is good practice to pick a different bucket name from the initial server.

Hope this addresses your question, let us know if you have additional questions.

**Comment by listeng** [comment]
Thanks for @fwessels . I have some questions. When we use AWS S3, we don't need to care about the free space, just save/delete objects on it. 

On Minio, once that disk space is filled up and we run another instance of Minio, but the old instances still will delete some files so that new file could be store on it.  So, if the web application store file on many Minio instance, how the application know which Minio instance has enough free disk space to store the new file.

**Comment by fwessels** [comment]
Typically we do not see a lot of "delete" intensive workflows and people just want to store data for longer periods of time.

The S3 API does not have a "free space" function so we cannot provide the information to the clients.

However you could periodically run a program to poll the free disk space on a server and save it somewhere in your application stack/orchestration software. That way you know how much space is available per server/bucket and can decide where to direct your data.

**Comment by listeng** [comment]
Thank, it's clear to me now.

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/distributed-minio-quickstart-guide.html expansion is already part of the main storage stack, so anyone landing here please read the latest documentation.
