### ISSUE TITLE
[Proposal] Reorganize codebase in a more idiomatc way

### ISSUE THREAD

**Issue by aead** [minio/minio#4812]
Currently `github.com/minio/minio` contains the main.go (and some build files, etc.) and everything else is located under `github.com/minio/minio/cmd`.
This has the following consequences:
 - It's tough for external contributors to dive into minio and understand the layer-structure of the minio server/gateway - it took me quite a while and I'm working currently full time on the minio server.
 - Build times are quite long - even tough the Go compiler is pretty fast.
 - Currently /cmd exports stuff more or less randomly.
 - It is very hard to test functionality properly because /cmd is one global namespace and you cannot rely on invariants. Somebody can modify every state from everywhere in the code.

Go natural approach to face these kind of problems is the package. Packages provide:
 - A structured way to organize code. It's easier to understand the architecture of a project if you can look at it's components and see how they interact. This helps new (and old :wink: ) contributors to figure out which part of the code is responsible for what.
- Faster build and test times. The go compiler does incremental builds by default. It only compiles packages which have changed. This sames time during development.
- Go supports internal (private) packages. Currently somebody can import `github.com/minio/minio/cmd` and may raise issues because we're breaking the code after every release. We can prevent misuse of minio/cmd by using internal packages.
- A package exports a public API used by other packages to build minio's functionality but we can also protect state and rely on certain invariants and assumptions. Packages will help us to prevent bugs by accidentally changing invariants.

## Expected Behavior
There a many Go projects which follow a package-based approach:
 - [Caddy](https://github.com/mholt/caddy)
 - [Kubernetes](https://github.com/kubernetes/kubernetes)
 - [Prometheus](https://github.com/prometheus/prometheus)
...

## Possible Solution
I propose to introduce packages for minio to face the listed problems. The packages should mirror the architecture of minio. Minio consists of 3 independent layers: storage, object and handler. Further minio supports FS and XL as well as Gateway (GCS, Azure and AWS). Within XL erasure coding and bitrot protection is a special/complex code base.

We should discuss about the right structure of packages and keep the balance between useful abstractions and over-engineering but I think the general structure should look like this:
```
minio/
   - main.go
   - ...
   - storage/
          - storage.go
          - storage_test.go
          - posix/
                 - posix.go
                 - ...
                 - posix_test.go
           - rpc/
                - rpc.go
                - ...
   - object/
         - object.go
         - fs/
               - fs.go
         - xl/
               - xl.go

.... 
```
/cc @fwessels @harshavardhana @abperiasamy @krishnasrinivas @donatello @krisis

**Comment by harshavardhana** [comment]
> Go natural approach to face these kind of problems is the package. Packages provide:
> 
> A structured way to organize code. It's easier to understand the architecture of a project if you can look at it's components and see how they interact. This helps new (and old  ) contributors to figure out which part of the code is responsible for what.

This is a plus

> Faster build and test times. The go compiler does incremental builds by default. It only compiles packages which have changed. This sames time during development.

This is a plus

> Go supports internal (private) packages. Currently somebody can import github.com/minio/minio/cmd and may raise issues because we're breaking the code after every release. We can prevent misuse of minio/cmd by using internal packages.

This not an issue, no one does it if they did its an architecture issue on their end.

> A package exports a public API used by other packages to build minio's functionality but we can also protect state and rely on certain invariants and assumptions. Packages will help us to prevent bugs by accidentally changing invariants.
> minio/
>    - main.go
>    - ...
>    - storage/
>           - storage.go
>           - storage_test.go
>           - posix/
>                  - posix.go
>                  - ...
>                  - posix_test.go
>            - rpc/
>                 - rpc.go
>                 - ...
>    - object/
>          - object.go
>          - fs/
>                - fs.go
>          - xl/
>                - xl.go

This is the exact structure we had 2yrs ago.  Inherent limitations of this approach is where states are lying across multiple packages and you always need a safe way to handle it (this is an expensive prospect).  Then if the claim is that in-variants for each packages get better control is also not true - Go by language itself never provides such protections you have to leverage other functionality to protect your entities - multiple objects being manipulated in a global tree style through `main.go` means inherently that your states are global it doesn't matter if you make your variables private you are going to use a heavy handed locking for each such functions to protect your values. Because one affects the other.. and so forth from top to bottom.  If a private invariant is never used by caller then there is no reason for it to be protected since it never changes - a constant in other words. 

I think we should not talk about safety under this topic, because saying things like "Packages help prevent bugs" is a very loaded statement and there is no quantifiable evidence to this under Go.  IMHO we should keep our focus only to the topic of code organization and other benefits like documentation, productivity (build time) etc. 

> There a many Go projects which follow a package-based approach:
> 
> Caddy
> Kubernetes
> Prometheus
> ...

Apparently Go projects do not follow nothing really as convention there are loose definitions, possible assumptions, at the end its generally what works for the given project.

> Go natural approach to face these kind of problems is the package. Packages provide:

This is an assumption packages by definition are only meant for re-usable entities and to be externally useful i.e without using minio.  For example `blake2b` should be a package.

**Comment by aead** [comment]
>This not an issue, no one does it if they did its an architecture issue on their end.

Agree, but this was an argument against packages in previous discussions - like "people could import stuff"...

> This is the exact structure we had 2yrs ago. Inherent limitations of this approach is where states are lying across multiple packages and you always need a safe way to handle it (this is an expensive prospect).

This is a design issue: Which package is responsible for what etc. State across packages indicates - from my perspective - a bug in the design...

>Then if the claim is that in-variants for each packages get better control is also not true - Go by language itself never provides such protections you have to leverage other functionality to protect your entities

Disagree. Go has the capability to "protect" state within a package. Examples are in the stdlib. Every struct within a package with "private" members keeps them "private" to protect some kind of invariant.

> multiple objects being manipulated in a global tree style through main.go means inherently that your states are global it doesn't matter if you make your variables private you are going to use a heavy handed locking for each such functions to protect your values. Because one affects the other.. and so forth from top to bottom. If a private invariant is never used by caller then there is no reason for it to be protected since it never changes - a constant in other words.

Didn't get the argument. I'm talking about problems like xlObject. Somebody can change the StorageAPI slice - which would be a bug - because it's **assumed** that the slice is immutable.    

>Apparently Go projects do not follow nothing really as convention there are loose definitions, possible assumptions, at the end its generally what works for the given project.

True, but after searching a bit through github I could not find any *popular* project which does not use sub packages (except minio of course :wink: ). This does not mean that it's automatically "the right" approach but it indicates that it is at least a commonly used convention which works/ed for many projects...

>This is an assumption packages by definition are only meant for re-usable entities and to be externally useful i.e without using minio. For example blake2b should be a package.

Disagree. See `internal` package keyword. As far as I know Go does provide package not only for developing a library which should be used by other projects.

**Comment by harshavardhana** [comment]
> This is a design issue: Which package is responsible for what etc. State across packages indicates - from my perspective - a bug in the design...

A state should be managed and protected is a programmer's prerogative either its available to you under a flat namespace or a hierarchical one.  Under hierarchy each state should be protected at each level which is okay while being quite expensive - but we do not have a hierarchical model in our code.  What we have is flat. 

> Disagree. Go has the capability to "protect" state within a package. Examples are in the stdlib. Every struct within a package with "private" members keeps them "private" to protect some kind of invariant.

This a wrong way to look at protection, unexported doesn't mean that its protected, its the life time and purpose of such an identifier which states it mutability.  If any given function gives different results each time its called then its indeed modifying the state underneath or is providing a modified state to the caller. We shouldn't think of state as just in-memory, we should think state also as on-disk. A variable needs protection of its own as and when they are modified during the life time of an object (if there are concurrency requirements) which is mostly the case with most of our code.

So again i don't see any **evidence**  here about protection without having protection internal to the object itself. 

From what i understand from the write up here is just this 
- Packages help in better code organization 
- Packages will help in build times. 

Both of them i fully **agree** with since there are clear evidences and it is helpful.  But we should stop saying that it provides protection and avoids bugs - packages are not a magic wand.

**Comment by aead** [comment]
> A state should be managed and protected is a programmer's prerogative either its available to you under a flat namespace or a hierarchical one. Under hierarchy each state should be protected at each level which is okay while being quite expensive - but we do not have a hierarchical model in our code. What we have is flat.

>This a wrong way to look at protection, unexported doesn't mean that its protected, its the life time and purpose of such an identifier which states it mutability. If any given function gives different results each time its called then its indeed modifying the state underneath or is providing a modified state to the caller. We shouldn't think of state as just in-memory, we should think state also as on-disk. A variable needs protection of its own as and when they are modified during the life time of an object (if there are concurrency requirements) which is mostly the case with most of our code.

We have probably different understanding of what "protection" means. I'm trying to say that it is much harder to accidentally break an invariant when the state is not visible/modifiable. 
```
type Foo struct {
     buffer []byte
}
```
Depending on whether this struct is defined in your namespace or not you can directly modify the buffer. Of course the namespace does not prevent modifying the state. It just prevent somebody outside the namespace from modifying the state in an unindented way / break an invariant. If the exported API allows "unintended" modification it's obviously a bug in the API.
In complex code it is "easy" to overlook such an invariant. A namespace (introduced by a package) just makes this dependency explicit instead of forcing the developer to take care about the implicit dependencies.
I'm not saying that a package automatically protects state from (concurrent) modifications - this is the job of the API. A package just prevents breaking the guaranties provided by its API. The difference here is that a package makes the dependency between code / invariants explicit. So the compiler will raise an error if you try to violate those explicit dependencies while in a "flat namespace" the developer must take care about this too. Minio currently tries to cover this with tests. But this approach is limited...

>Both of them i fully agree with since there are clear evidences and it is helpful

Glad to hear :tada:

**Comment by brendanashworth** [comment]
I want to emphasize one of the advantages of the subdirectory approach, in regards to tests.

- Splitting the main namespace into multiple subdirectories will allow developers to only run tests for the part of code they're changing (for me, the whole run takes 2 minutes).
- It emphasizes that a file should be primarily tested by its own testing file (e.g., `jwt.go` and `jwt_test.go`), as opposed to being covered from another unrelated package (`fs-v1_test.go`). When tests are "covered" like this, the functionality isn't *truly* tested because it's from an *unrelated unit test*. This will be more obvious if a folder with 8 files only has 2 test files. (If you don't think this is a problem, there's 163 non-test files yet just 113 test files in `cmd/`. That's 50 files that are *only tested from unrelated unit tests*, if covered at all)
- Code coverage can be [broken down by subdirectory](https://docs.codecov.io/docs/graphs#section-sunburst). Right now we have pretty [abhorrent gateway coverage](https://codecov.io/gh/minio/minio/tree/master/cmd), and it'd be very interesting to see just how well other packages are tested (xl, fs, web, s3, etc), and if that's dropping as well.

**Comment by harshavardhana** [comment]
// cc @aead 

All of this is already solved by either using interfaces and structs with strict types.  Any interface change  causes build to fail, any struct change also causes build to fail.  API contract doesn't get anymore benefit than this.  It is unfortunate that there are structs with exposed identifiers and we should have avoided that. 

It is inherently a problem of package paradigm itself every package as a whole is sort of a global state you need explicit protection to identifiers to be safe and you are hoping as a caller that someone has written code that way.

For packages if we move out a suggestion is - should be inside an `internal` prefix directory such that there are no unexplained uses outside of minio project and we clearly state their purpose in that manner.

> Splitting the main namespace into multiple subdirectories will allow developers to only run tests for the part of code they're changing (for me, the whole run takes 2 minutes).

// cc @brendanashworth you can run `go test -run <MyCodeTest>` - you don't need to run everything. 

> It emphasizes that a file should be primarily tested by its own testing file (e.g., jwt.go and jwt_test.go), as opposed to being covered from another unrelated package (fs-v1_test.go). When tests are "covered" like this, the functionality isn't truly tested because it's from an unrelated unit test. This will be more obvious if a folder with 8 files only has 2 test files. (If you don't think this is a problem, there's 163 non-test files yet just 113 test files in cmd/. That's 50 files that are only tested from unrelated unit tests, if covered at all)

We lack unit tests is an ongoing issue - moving to packages doesn't solve that, writing more unit tests will.  This is not to be construed as a failure of flat style v/s package style, but a failure of our tenacity. 

> Code coverage can be broken down by subdirectory. Right now we have pretty abhorrent gateway coverage, and it'd be very interesting to see just how well other packages are tested (xl, fs, web, s3, etc), and if that's dropping as well.

Nothing will change really if we don't have more unit tests. Gateway coverage is smaller (more like not written) for an entirely different reason.

**Comment by aead** [comment]
cc/ @harshavardhana 
>All of this is already solved by either using interfaces and structs with strict types. Any interface change causes build to fail, any struct change also causes build to fail. API contract doesn't get anymore benefit than this. It is unfortunate that there are structs with exposed identifiers and we should have avoided that.

That's not the point. A package in Go separates the code. The code within the package has access to everything inside the package. Code outside the package cannot modify state within the package except in a (intended) way provided by the API of the package.

> It is inherently a problem of package paradigm itself every package as a whole is sort of a global state you need explicit protection to identifiers to be safe and you are hoping as a caller that someone has written code that way.

That's true, but it is much easier to understand and cover all code in small packages than in a large one. This is exactly my point - currently there is one huge "global state": `cmd/`  
Further if two packages interact with each other they can only do this in a "safe" way. Safe means that the package can only be used in a certain way and nobody can come across and break the invariants by bypassing the API.

Just one super simple example: [BitrotVerifier](https://github.com/minio/minio/pull/4758/files#diff-4d9e079c886613c2bd0b4ded8886f61cR99)
It provides two functions to modify the internal state (set the verified flag to true). Those functions are used in posix.go to verify the checksum of the file. Somebody can modify the internal state **within posix** and set the value to false again - this would be a bug but it would not cause any crash, just a performance problem. If posix and BitrotVerifier would be in separate packages (I'm not saying they should :wink: ) this would not be possible. The compiler would return an error because the verified flag is not exported.

A package does not prevent developers from doing stupid things, it just helps them to not do mistakes by enforcing: "You cannot access/modify this value/state - maybe there is a reason why..."

**Comment by fwessels** [comment]
As an observation:

```
$ ls -l *.go | wc -l
     279
$ ls -l *_test.go | wc -l
     113
```

I think some form of directory structure can make our code base easier to get into. Right now for novice users (or the casual Github user browsing around) the `cmd` directory will be looking quite intimidating — this sends out the wrong message that it is a “complex” code base whereas it really is not.

For those of us who have been using it for a longer period of time we may have grown accustomed to the way things are, new users by definition do not have this history and then it is interesting to hear their observations.

Actually, in my architecture document I am (was?) planning to write a section on the organisation of the source code/file-naming. But better yet this wouldn't be necessary at all.

Also with ever more functionality being added you can question whether it is the way to proceed forward and we shouldn’t do something to address it sooner or later...

I don’t think a directory structure should actually be seen as a panacee for preventing bugs, indeed we are using interfaces already at the critical places which is the proper thing to do — which also means that these are the “logical” boundaries to split the code up.

Seems to me we have a flat namespace with a hierarchy of one (how’s that for a contradiction?) — all too often due to supposedly “proper design” you see too many layers over-engineered and stacked on top of each other which we should avoid at all costs.  

As such a simple flat directory structure along the following lines could make sense (whereby still plenty of files would be left in place at cmd):
```
cmd
    admin
    fs
    gateway
    object
    posix
    network
    xl
```

**Comment by fwessels** [comment]
Did a quick reorganizing, just to get an idea of what it would look like... https://github.com/fwessels/minio/tree/feature/code-reorg/cmd 

(note that I haven't yet dared trying a build...  😉 )

This would still leave 100+ files in `cmd`:

```
$ ls -l *.go | wc -l
     118
$ ls -l admin/*.go | wc -l
       7
$ ls -l api/*.go | wc -l
      10
$ ls -l bucket/*.go | wc -l
      14
$ ls -l fs/*.go | wc -l
      11
$ ls -l gateway/*.go | wc -l
      20
$ ls -l lock/*.go | wc -l
      11
$ ls -l network/*.go | wc -l
      12
$ ls -l notifier/*.go | wc -l
      15
$ ls -l object/*.go | wc -l
      17
$ ls -l posix/*.go | wc -l
      14
$ ls -l xl/*.go | wc -l
      29
```

**Comment by deekoder** [comment]
moving this to revisiting in the next milestone.

**Comment by redbaron** [comment]
I clicked "cmd" in github interface and it took ~10 seconds for it to build page. Not much of an argument , but maybe it can revive discussion here :)

**Comment by harshavardhana** [comment]
This is being actively done phase by phase. So it is a work in progress..

**Comment by leitzler** [comment]
Is this still work in progress? Would be great if related issues could be linked to this one.

**Comment by harshavardhana** [comment]
It is not, it is a work in progress as the time gets along.

**Comment by harshavardhana** [comment]
Closing this issue as we have sufficiently moved enough sub-systems to their own respective packages.
