### ISSUE TITLE
Signature does not match error for buckets with / char in them using

### ISSUE THREAD

**Issue by drahnr** [minio/minio#4835]
This error pop's up and push is not successful with a Forbidden 403 on the client side.

With `mc` this does not happen, I assumed this might be due to additional gate keeping / sanity checks.

## Expected Behavior
Return a good, understandable error message.

## Current Behavior

It happens when used with the S3 resource plugin and using a bucketname including a slash /
with a https://concourse.ci S3 plugin which source code is available at https://github.com/concourse/s3-resource

`minio/minio:edge`'s logs then look like this:
```
Aug 20 14:12:42 example.com docker[14487]: time="2017-08-20T14:12:42Z" level=error msg="{\"method\":\"GET\",\"reqURI\":\"/oregano%2Fdrop?marker=&prefix=\",\"header\":{\"Accept-Encoding\":[\"gzip\"],\"Authorization\":[\"AWS4-HMAC-SHA256 Credential=abc123/20170820/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=12....4f1\"],\"Connection\":[\"close\"],\"Content-Length\":[\"0\"],\"Host\":[\"minio.spearow.io\"],\"User-Agent\":[\"aws-sdk-go/1.6.10 (go1.8.3; linux; amd64)\"],\"X-Amz-Content-Sha256\":[\"e3b0....5\"],\"X-Amz-Date\":[\"20170820T141242Z\"]}}" cause="Signature does not match" source="[auth-handler.go:122:checkRequestAuthType()]" 
```

I am aware that this setup is somewhat complex, but I am happy to setup a dummy project for you to test on.

**Comment by harshavardhana** [comment]
> {\"method\":\"GET\",\"reqURI\":\"/oregano%2Fdrop?marker

This seems to be a problem in how you are setting this up - there is no '/' in bucket name, if you need to look for files inside a particular prefix then concourse.ci is asking you to set `regexp`  - perhaps as shown below. 

```
    bucket: oregano
    regexp: drop/*
```

**Comment by drahnr** [comment]
What I did was setting `bucket: oregano/drop` to get the files in a pseudo hirarchy. This fails nicely with `mc` but with the `resource-s3` of `concourse.ci` I get this pretty hard to backtrack error.

**Comment by harshavardhana** [comment]
> What I did was setting bucket: oregano/drop to get the files in a pseudo hirarchy. This fails nicely with mc but with the resource-s3 of concourse.ci I get this pretty hard to backtrack error.

Yes for that concourse.ci plugin should do basic bucket name validation if they don't and they send the request by will fully encoding the `/` characters - it is a bug perhaps in aws-sdk-go.  Minio server cannot do much here instead since due to routing rules are based on '/'  --> `oregano` is a perfectly valid bucket name and so this request fails on sort of a GET object request where an object name would become `drop?marker=&prefix=` - Since the encoding is wrong not following the AWS S3 spec i.e '/' shouldn't be converted to '%2F'  if its part of resource - which i see happened here means aws-sdk-go did some wrong here.

**Comment by drahnr** [comment]
Thanks for the clarificatio, I guess you can close that then since it is not related to minio 👍
