### ISSUE TITLE
Multipart Upload Regression between RELEASE.2017-07-24T18-27-35Z and RELEASE.2017-08-05T00-00-53Z

### ISSUE THREAD

**Issue by godfoder** [minio/minio#4850]
## Expected Behavior
Multipart uploads should complete successfully. 

## Current Behavior
A MalformedXML error is returned when complete_upload is called.

## Possible Solution
It looks like there was a major change to multipart in this release, hopefully this is a simple request parsing bug that can be easily fixed.

## Steps to Reproduce (for bugs)
1. Install boto (tested on both 2.40 and 2.48)
2. Launch minio with docker:
`docker run -d --net host --name minio-test -e "MINIO_ACCESS_KEY=testAccessKey" -e "MINIO_SECRET_KEY=testSecretKey"  minio/minio:RELEASE.2017-08-05T00-00-53Z server /export`
3. Run the code in this gist:
https://gist.github.com/godfoder/3b6eb57b1f4d268edf8869384810f257

## Context
We use minio on travis via docker to provide a lightweight s3 environment to run our test code against for our project. Our production systems are a large Ceph cluster, and this code works against production.

## Your Environment
* Version used (`minio version`): Minio RELEASE.2017-08-05T00-00-53Z docker tag
* Environment name and version (e.g. nginx 1.9.1): Python 2.7.11, Boto 2.48
* Server type and version: (not sure what this is asking for)
* Operating System and version (`uname -a`): Ubuntu Trusty environment on travis, also on an Ubuntu Xenial desktop
* Link to your project: https://github.com/idigbio/idb-backend

**Comment by krishnasrinivas** [comment]
@godfoder we made a change to return empty list for "GET ListParts" request to discourage incorrect client behavior.

Here are more details from AWS doc:
https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html

> Only use the returned listing for verification. You should not use the result of this listing when sending a complete multipart upload request. Instead, maintain your own list of the part numbers you specified when uploading parts and the corresponding ETag values that Amazon S3 returns.

boto is doing ListParts call and use its result to do CompleteMultipart call which AWS docs do not recommend. The reason is explained well in this issue https://github.com/minio/minio/issues/4792 by @krisis 

The right way for the clients to behave is remember the parts that they have uploaded and use it (instead of doing ListParts) for the CompleteMultipart call

However boto3 is implemented correctly and works as expected. https://docs.minio.io/docs/how-to-use-aws-sdk-for-python-with-minio-server

**Comment by ws141** [comment]
@krishnasrinivas I see the reason for why you chose to drop the list of parts that is returned by GET ListParts but you are effectively dropping the support for verification of uploads of parts that some clients/users need to have. 

It's even stated in the paragraph that you quoted by the AWS API:
> Only use the returned listing for verification.

Since this is the only way to perform a verification it poses a problem to clients/users since they can no longer perform this operation. How do you suggest that clients/users otherwise verify the uploads of parts?

The rationale behind a feature is not automatically negated by the possibility of abuse in my opinion. Neither would I conclude that from the previously quoted AWS API paragraph.

**Comment by harshavardhana** [comment]
The verification is already done when you do PutObjectPart i.e With setting Content-Md5. Now ListParts only returns partNumber and md5 hex this is of no use if the PutObjectPart already succeeded and duly verified the Content-Md5 set by the client so you are guaranteed that what you remembered on the client side is the same one server has.

Now even if it's not, upon CompleteMultipart server will verify what was asked by client v/s which it already has. So the verification done by the client using ListParts is not trust worthy or couldn't have done anything better than CompleteMultipart. 

In a concurrent environment ListParts is always considered to provide partial result. This is what is indicated by the AWS API docs on not trusting the output. So a verification here is pointless you can't use it or trust its output in the first place. This is also one of those reasons why ListParts is never used by aws-sdk upload manager implementations.

Added advantage for us was it made the multipart implementation simpler. 

If you have implementations which rely on ListParts and trust its output then they should be considered buggy and should be fixed immediately.

**Comment by krishnasrinivas** [comment]
@godfoder @ws141 can this issue be closed? do you have any concerns? As @harshavardhana has explained the reason to return empty list for the ListObjectParts API is not just to make clients not use it but also it simplifies minio internally.

**Comment by ws141** [comment]
@krishnasrinivas The AWS API docs referenced did not indicate the output of list parts is partial or cannot be trusted as far as I can tell - maybe consider adding list part to the list of not implemented object queries instead to make clients not use it? We understand if there is a need to simplify minio internally and are fine with your decision either way.

By the way, regarding #4564, if you also drop the ability to list multipart uploads, how are users suppose to clean up dangling multipart uploads?

**Comment by harshavardhana** [comment]
> @krishnasrinivas The AWS API docs referenced did not indicate the output of list parts is partial or cannot be trusted as far as I can tell - maybe consider adding list part to the list of not implemented object queries instead to make clients not use it? We understand if there is a need to simplify minio internally and are fine with your decision either way.

The reason it is partial because of PutObjectPart() concurrency at any given point in time ListParts() is not guaranteed to return all the parts that are being uploaded (concurrently). So a client decision cannot be performed based on this.  Client knows which part it uploaded and which part failed so client knows when to complete. 

ListParts() is just sort of a good way to know how much of storage space is currently being for a given uploadID but it is not a definitive answer for client to complete a multipart session.  

> By the way, regarding #4564, if you also drop the ability to list multipart uploads, how are users suppose to clean up dangling multipart uploads?

Dangling multipart uploads are cleaned up automatically on the server side every 2 weeks.  This process runs every 24hrs to look for incomplete files older than 2 weeks.

**Comment by ws141** [comment]
@harshavardhana Alright, thanks for the explanation!
