### ISSUE TITLE
minio can not delete a folder

### ISSUE THREAD

**Issue by dingjs** [minio/minio#4852]
Hi
minio can use /folder1/folder2/file to upload a file to a minio bucket with folders. if using mc rm /folder1/folder2,it can not rm the folder and have no error message.If I change the foler name to a not exist folder,mc throw a error message:Failed to remove XXXX.Object doest not exist.Do minio prefer to use folders or not,If I don't use folders.a bucket would have millions of files.
Thanks

**Comment by donatello** [comment]
@dingjs Minio server does support the usage of folders. However, empty directories cannot be created. If you want to delete a folder and its contents recursively, you can do `mc rm -r --force myminio/bucket/folder1/folder2`.

Minio server has no preference for using folders or not - it just implements the AWS S3 API. **It would be a good practice to use folders instead of having a bucket with a large number of files, as it ensures better filesystem performance.**

Not showing an error message when a folder inside object storage is removed, is a bug in mc. Thank you for reporting it. I will create an issue in the `mc` repo for this.

Please let us know if this answered your question or if you have any more questions. You can also chat with us on slack.minio.io.

**Comment by dingjs** [comment]
Thank you for your reply . mc rm -r --force works fine.
You were saying that a bucket with millions of files works better than using folders.
My experience taught me that when a folder(a bucket is a folder in the filesystem) contains a lot of files has poor performance. Am I wrong or minio did some optimization of the bucket.

**Comment by donatello** [comment]
@dingjs No, I actually meant the opposite. I have edited the original. A folder with a large number of files will have poor performance at the filesystem level itself.

**Comment by Musti70** [comment]
how can I remove minio.exe from my pc please

**Comment by nitisht** [comment]
you can simply delete the `minio.exe` file @Musti70 , also if you want to delete the config directory, find the `.minio` directory in user's home directory and delete that..

**Comment by harshavardhana** [comment]
@Musti70 navigate to where you installed your binaries - `del minio.exe` and `del mc.exe` from cmd prompt

**Comment by Musti70** [comment]
Thank you guys for the prompt response. I downloaded minio.exe from https://dl.minio.io/server/minio/release/windows-amd64/minio.exe and I opened it .  I deleted it from the download folder but I don't see it in my home directory (I'm in windows 10).

**Comment by Biond1** [comment]
`mc: <ERROR> Failed to remove `myminio/bucket/folder` recursively. Truncated response should have continuation token set`
I get this error when trying to remove this folder using
`mc rm -r --force myminio/bucket/folder`
anyone can help me?

**Comment by harshavardhana** [comment]
Please open a new issue @Biond1 with details about server etc.
