### ISSUE TITLE
[gateway/azure] validate whether gateway sends Content-MD5 or checksum to server

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4994]
Currently Content-MD5 or other checksum is not sent to Azure server for `PUT`, `POST` methods.  Its required to send at least one checksum header to server to verify transferred body.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment]
We need to do this in the next release.

**Comment by jmaitrehenry** [comment]
Actually, I found 1 bug about this issue:
```
func s3MetaToAzureProperties(s3Metadata map[string]string) (storage.BlobMetadata,
	storage.BlobProperties, error) {
[...]
	for k, v := range s3Metadata {
		k = http.CanonicalHeaderKey(k)
		switch {
-		case k == "Content-MD5":
+		case k == "Content-Md5":
			props.ContentMD5 = v
		}
	}
	return blobMeta, props, nil
}
```

And it should already works if the client sent the `Content-MD5` header.
I didn't think Minio should calculate the md5 from `r.Body` and send it to Azure because we don't have an easy way to to it without reading the Reader as Azure need the `io.Reader`.

I will send a PR for the bug

**Comment by harshavardhana** [comment]
:+1:  @jmaitrehenry nice find.

**Comment by harshavardhana** [comment]
There is a reason we still need to calculate Md5, when `Content-Md5` is not present in the incoming request. But your PR will address one case though.

**Comment by harshavardhana** [comment]
One interesting point from Azure doc is here to notice https://blogs.msdn.microsoft.com/windowsazurestorage/2011/02/17/windows-azure-blob-md5-overview/ 
> MD5 checking is optional on both PUT and GET operations; however it does provide a convenience facility to ensure data integrity across the network when using HTTP. Additionally since HTTPS provides transport layer security additional MD5 checking is not needed while connecting over HTTPS as it would be redundant.

So looks like for Azure the recommended approach is if you are using HTTPS then don't set MD5, i am sure that we are using MD5 so if the Content-Md5 really doesn't exist we don't need to set it ourselves as indicated/recommended by the Azure docs and it is repeatedly mentioned in their docs.

**Comment by jmaitrehenry** [comment]
I understand but I can't see how we could do this on minio side if we use `CreateBlockBlobFromReader`.

Maybe we could check it by uploading the file on Azure and checking the returning md5 with the md5 created on minio side. It's could be easy.

**Comment by jmaitrehenry** [comment]
@harshavardhana 

Hum, I found a really simple way to check the md5:
```diff
func (a *azureObjects) PutObject(bucket, object string, data *HashReader, metadata map[string]string) (objInfo ObjectInfo, err error) {
        [...]
	err = blob.CreateBlockBlobFromReader(data, nil)
	if err != nil {
		return objInfo, azureToObjectError(traceError(err), bucket, object)
	}
	if err = data.Verify(); err != nil {
		errorIf(err, "Verification of uploaded object data failed against client provided checksums.")
		derr := blob.Delete(nil)
		errorIf(derr, "Failed to delete blob when cleaning up a bad blob upload.")
		return ObjectInfo{}, azureToObjectError(traceError(err))
	}
-	return a.GetObjectInfo(bucket, object)
+	obj, err := a.GetObjectInfo(bucket, object)
+	md5 := base64.StdEncoding.EncodeToString(data.md5Hash.Sum(nil))
+	if md5 != obj.ContentMD5 {
+		fmt.Println("error", obj.ContentMD5, "other", md5)
+	}
+
+	return obj, err
}
```

What do you think?

**Comment by harshavardhana** [comment]
@jmaitrehenry  it is quite racy.  Once the namespace has been acquired we have no way of handling access to this object we would have potentially uploaded corrupted object.

Our idea is to convert the PutObject() into a Multipart style using PutBlobs() instead which would be more cleaner and safer avoiding the namespace pollution.

**Comment by jmaitrehenry** [comment]
It's exactly the other idea I had, the first one was an easy one that give the responsibility to the client to send the md5sum, and give the possibility to the client to know that he had uploaded a corrupt object if he doesn't send an md5sum.

**Comment by Praveenrajmani** [comment]
The `Content-Md5` is set in the `blob.Properties` ( [https://github.com/minio/minio/blob/4280e68de3f4ec368b4d70b8788a74236b05f4f3/cmd/gateway/azure/gateway-azure.go#L728](url)) only  if the request (`metadata`) has it.

If the `Content-Md5` is not set in the metadata, We need to perhaps calculate the `data.MD5Current()`. The difficulty here is .. We cannot pro-actively calculate the Md5sum before uploading the data. Especially here in [https://github.com/minio/minio/blob/4280e68de3f4ec368b4d70b8788a74236b05f4f3/cmd/gateway/azure/gateway-azure.go#L729](url). Anyway the other case ( when `data.Size() < azureBlockSize/10` in putObject) has provision to calculate the `MD5Current()` and we can update the metadata like `metadata["Content-Md5"] = hex.EncodeToString(data.MD5Current())` so that the `s3MetaToAzureProperties` can take it and update the `blob.Properties` (Which is again not pro-active)

In such cases we may require a staging upload, Where we can read into a temporary `[]byte` and calculate the md5sum and then do the actual upload. Here, we need a dedicated memory for this.
Is this a good approach to go ahead ? @balamurugana @harshavardhana @kannappanr 
Else should we rely on the request metadata alone ?

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.
