### ISSUE TITLE
Minio returns wrong error message

### ISSUE THREAD

**Issue by fkautz** [minio/minio#505]
when bucket/1 already exists:

``` sh
$ mc cp file localhost:bucket/1

mc: <DEBUG> HTTP/1.1 501 Not Implemented
Connection: close
Content-Length: 207
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 27 Apr 2015 03:13:07 GMT
Server: Minio
```

**Comment by harshavardhana** [comment]
yeah we need to debate about this, it only seemed natural to send that back since "re-writing" object is not implemented. 

Amazon doesn't have any standard error messages for this case. But we could construct one from HTTP standards. 

Perhaps we can use 

405 Method Not Allowed
A request was made of a resource using a request method not supported by that resource; for example, using GET on a form which requires data to be presented via POST, or using PUT on a read-only resource.
