### ISSUE TITLE
Rename minio client from mc to something else

### ISSUE THREAD

**Issue by sokoow** [minio/minio#5060]
Hi All,

Just to let you know that minio client (mc) name is clashing with Midnight Commander. That might be a problem for machines that have commander installed.

**Comment by balamurugana** [comment]
@sokoow You can refer https://github.com/minio/mc/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20midnight%20in%3Abody

Minio Client as mc is project which creates a single statically compiled executable binary which can be placed anywhere (by any name) in the system for user convenience.

When distributing mc's executable, package maintainer could choose convenient name which works for the system. We encourage this. Package maintainers are already doing it e.g. Ubuntu snap is called as minio-client.

Hope this helps.

I am closing this issue because it is applicable to minio/mc, not minio/minio
