### ISSUE TITLE
Support lockfree fs

### ISSUE THREAD

**Issue by deekoder** [minio/minio#5063]
* When fs supports extended attributes, use them for user metadata
*  When fs does not support extended attributes, use fs.json 
*  Migrate fs.json to extended attributes during minio startup
* Remove fcntl locking code

**Comment by deekoder** [comment]
We have to remove fnctl locking code. But we have to discuss again on the remaining items on this list.

**Comment by harshavardhana** [comment]
@krishnasrinivas is this done? should we close this issue.

**Comment by krishnasrinivas** [comment]
@harshavardhana we had discussed about implementing this but never implemented. We did not implement because of the migration that had to be done from fs.json to ext attrs and also we will not be able to support metadata on NFSv3 that does not have ext attr support. We need to check with AB if we should close this issue or not.

**Comment by harshavardhana** [comment]
Closing this since this issue is stale and quite old. We are not implementing any new features in FS mode at the moment.
