### ISSUE TITLE
Minio doesn't work if 2 out of 6 disks are out

### ISSUE THREAD

**Issue by davidgeorgealex** [minio/minio#5089]
I use a custom docker image where I bundle both Minio and MC with the latest release versions (attached is an archive with the files [docker.tar.gz](https://github.com/minio/minio/files/1401229/docker.tar.gz) ).
I have a custom image because I do a couple of things:
1. run a heal when the container started - wait that the whole Minio cluster is up - to achieve I run `mc admin info local` an check for errors, and waiting till no errors are returned (like server not initialized).
2. have a cronjob that runs minio every 10 mins on the hostname minio-0
3. have a status.sh script that return the status of the local minio service

Next I have the docker-compose file that spins 3 containers of the image, each with two disks.
[docker-compose.txt](https://github.com/minio/minio/files/1401254/docker-compose.txt)

The problem is that everything starts, I can create a bucket and upload some files, but when I bring down a node (docker kill) and do a `mc ls local` multiple times, some of the requests fails (mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.). Also the UI doesn't work.

Also in the logs I see thing like:
`minio1    | time="2017-10-20T08:18:15Z" level=error msg="Unable to fetch disk info for &cmd.networkStorage{rpcClient:(*cmd.AuthRPCClient)(0xc4202cebb0)}" cause="disk not found from rpc shutdown" source="[xl-v1.go:199:getDisksInfo()]" `
or
`minio1    | time="2017-10-20T08:18:41Z" level=error msg="Unexpected error, please report this issue at https://github.com/minio/minio/issues" cause="disk not found from net error" source="[web-handlers.go:1099:toWebAPIError()]" `

**Comment by donatello** [comment]
Acknowledge the bug. I am able to reproduce it using the docker-compose setup described here. However, I am unable to reproduce this using a non-docker based 3-instance minio cluster running on different ports on my laptop.

The problem seems to arise because when listing `errDiskNotFoundFromNetError` is thrown which is not ignored during listing as it should be.

There are couple of ways to fix, so some discussion is required to find the appropriate fix:

1. It seems that the `retryStorage` type converts this error to `errDiskNotFound` (which is ignored during listing) - so perhaps disks should be initialized with this type rather than `networkStorage`.
2. We can add errDiskNotFoundFromNetError as an ignored error for listing.

**Comment by donatello** [comment]
// cc: @harshavardhana inputs?

**Comment by harshavardhana** [comment]
@donatello disks are initialized with retryStorage always. So it shouldn't have caused this problem unless some one else is not translating the errors appropriately.

**Comment by davidgeorgealex** [comment]
It seams like the problem is still present even in the new release :(. I've opened https://github.com/minio/minio/issues/5189 and https://github.com/minio/minio/issues/5190. Thanks!
