### ISSUE TITLE
Remove "logger" field from config.json

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#5176]
Remove "logger" field from config.json. Support for logging to a file needs to be removed as part of the improvements we are making to server side logging. 

The changes that need to be made are
1. Change the config.json structure version from 20 to 21.
2. Upgrade the structure from 20 to 21 upon startup.
3. Make sure that the unit tests reflect this change.
4. Add structure version 21.
5. Remove file-logger.go

**Comment by harshavardhana** [comment]
If the template format is not used we should simply remove when reporting the issue - template when not used otherwise looks half finished and half updated.

Something like this https://github.com/minio/minio/issues/5040 while not using the issue template, the issue description is clean and provides the gist to external readers what might be scheduled to be changed.
