### ISSUE TITLE
[refactor]: unify SHA-256 usage

### ISSUE THREAD

**Issue by aead** [minio/minio#5374]
The minio server uses a [custom](https://github.com/minio/sha256-simd) SHA256 implementation because of performance advantages on ARM64 during bitrot protection. SHA-256 is further used for signature V2/4 and also S3 checksums...

The minio server uses the custom and standard library implementation somehow randomly. See for
example:
 - [Standard library](https://github.com/minio/minio/blob/f1355da72ed78c43c7d3559d5c0e216dc7400d2b/pkg/hash/reader.go#L22)
- [Custom](https://github.com/minio/minio/blob/5db1e9f3dd74ecce06cbab1cf1c52930a62a302f/cmd/signature-v4-utils.go#L28) 

As a result the server uses the standard library version even during [bitrot protection](https://github.com/minio/minio/blob/master/cmd/xl-v1-metadata.go#L21) - so the main advantage of the custom SHA-256 implementation is lost...

## Expected Behavior
There should be a central point providing the SHA-256 implementation to the rest of the server.
This is anyway required by the current bitrot protection implementation.

## Possible Solution
One possible solution is to use the `Hash` mechanism used by the `crypto` package provided by the standard library. A hash function implementation is registered under a name once and can be used by its name - like: `crypto.SHA256`. (This mechanism is already used by the current bitrot protection)
Further there is already a package `pkg/hash` implementing the `HashReader` functionality. This package can be used to provide some utility functions like SHA-256 HMAC checksum computation / verification to centralize code using SHA-256.    

## Context
#5358 

## Your Environment
master

**Comment by harshavardhana** [comment]
Some more clarity on the issue here. 

The problem with sha256 and sha256-simd loading is that goimports tries to load `crypto/sha256` more than it tries to load `minio/sha256-simd` and it varies from system to system i.e `sha256-simd` is a drop in replacement.  

https://golang.org/src/crypto/sha256/sha256block_amd64.s sha256 started using the AVX2 version since go1.7+ days already.  In-fact there was time we thought of deprecating our sha256-simd - For example https://github.com/minio/sha256-simd/issues/27

But since then we have moved forward and eventually would love to contribute and here is the bug regarding aarc64 support to be upstreame'd https://github.com/minio/sha256-simd/issues/7

Standard library `crypto/sha256` is not as bad as one may think and is quite comparable to the performance on most Intel architectures other than - aarch64 (NEON),  AVX512 (newest addition).  

NOTE: In-fact aarch64 performance numbers we added are only for pine64 - aarch64 pocessors.  Now for practical usage lets say packet.net cavium aarch64 processors give around 2x lower performance due to their SOC limitations, around 1x slower than the Intel AVX2 numbers. https://github.com/minio/sha256-simd/issues/14#issuecomment-289527372

So under all practical scenarios we are not really experiencing a serious problem - but we need to definitely move to sha256-simd for AVX512 requirements and simply renaming crypto/sha256 to minio/sha256-simd would do the work. There is no easier way avoid the drop-in replacement problems. 

There is no way to stop someone from not doing a mistake even after we have a centralized way to manage sha256 initialization, so i would say we have to catch this under review and should have never made it into master in its current form.

**Comment by fwessels** [comment]
Also note that with moving to HighwahHash we do no longer need SHA256 on ARM for bit rot (that still leaves payload verifcation etc. of course).

**Comment by aead** [comment]
@harshavardhana 
>The problem with sha256 and sha256-simd loading is that goimports tries to load crypto/sha256 more than it tries to load minio/sha256-simd and it varies from system to system i.e sha256-simd is a drop in replacement.

Correct, that's the issue I faced.

>Standard library crypto/sha256 is not as bad as one may think and is quite comparable to the performance on most Intel architectures other than - aarch64 (NEON), AVX512 (newest addition).
So under all practical scenarios we are not really experiencing a serious problem - but we need to definitely move to sha256-simd for AVX512 requirements and simply renaming crypto/sha256 to minio/sha256-simd would do the work. There is no easier way avoid the drop-in replacement problems.

Here I do not agree. First it's correct that the standard library implementation gives similar performance on all platforms except ARM64 because of NEON implementation.
The AVX512 implementation is only faster in certain scenarios - For a "normal" hash computation like Signature V2/4 or S3 checksums AVX512 won't give a speedup unless you've independent data lanes - even if so it requires benchmarking. 

There are basically two ways to avoid the described import problem:
1. Usage of `crypto.SHA256` - This way there would be only one import registering the hash function
and all other files will not import a sha256 implementation - of course that must be ensured by review.
2. A file containing the utility functions like `SHA256HMACSum()` or similar - so whenever you want to use SHA256 you are supposed to use one of these functions (or add one if missing) - of course that must be ensured by review, too.

Since were are using HH for bitrot - as @fwessels mentioned - IMO the main advantage of a custom SHA-256 implementation is lost anyway. However we may be able to use AVX512 for S3 checksum verification but as said that requires bechmarking...

**Comment by fwessels** [comment]
I think the AVX512 will still be very useful for SHA256 payload verification which is the big burden. For just header authentication/verification there is not much to gain.

**Comment by aead** [comment]
Yes, AVX512 can give a performance improvement for content-sha256 verification. However we have to check that we don't hit AVX-512 frequency scaling which could decrease the overall performance. Have you checked that already on some test setup? @fwessels

**Comment by fwessels** [comment]
I am getting the impression that this is tied to the "level" of the Skylake CPU, thus far on the Platinum and Gold CPUs that I have encountered it wasn't an issue.
There are Silver (and even Bronze I believe) CPUs as well, they are obviously scaled-down versions but it is not really clear what trade-offs have been made. This one article that you shared earlier mentioned a Silver CPU if I recall correctly.

**Comment by aead** [comment]
Oh okay - interesting. Wikichip mentions also AVX512 throttling for Gold chips like the [Xeon 5117](https://en.wikichip.org/wiki/intel/xeon_gold/5117)  - at least if AVX-512 is run on more than one core... But your right the cloudflare blog was about a Xeon sliver CPU...

**Comment by fwessels** [comment]
Well, even there, I would pick 512-bit at 1400 MHz over 256-bit at 1600 MHz (provided of course that your algorithm exploits the full width, just switching from Y to Z registers and not modifying your algortithm doesn't make any sense).

**Comment by harshavardhana** [comment]
> There are basically two ways to avoid the described import problem:
> 
> Usage of crypto.SHA256 - This way there would be only one import registering the hash function
> and all other files will not import a sha256 implementation - of course that must be ensured by review.
> A file containing the utility functions like SHA256HMACSum() or similar - so whenever you want to use SHA256 you are supposed to use one of these functions (or add one if missing) - of course that must be ensured by review, too.

Both of these are circumstantial and requires documentation/communication. It will be unexpected for external contributors and even newer members in the team.  So not an easy thing to enforce, the best way is do a good review and catch it during PR submissions than adding unusual ways of enforcement which moves away from standard behavior.  I would suggest we simply rename all sha256 usage to sha256-simd and be done with it for now. Enforce it properly as part of review.

**Comment by aead** [comment]
> I would suggest we simply rename all sha256 usage to sha256-simd and be done with it for now. 

That we can do - will follow this approach.

> So not an easy thing to enforce, the best way is do a good review and catch it during PR submissions than adding unusual ways of enforcement which moves away from standard behavior.

Hm - IMO we should either focus on code which is easier to review or tool support. For just this case alone it may work but just saying we should do a better job at review is an approach which does not scale. However that's a generic issue - solution/correct approach unknown.
