### ISSUE TITLE
Support for APFS/HFS+, recommended filesystems, and Mac support?

### ISSUE THREAD

**Issue by jspiro** [minio/minio#5379]
I have many years of experience backing up blobs with Arq to many cloud services. I finally set up Minio locally with a 4TB drive on an old Mac and got about 45 days of daily backups out of it before Arq could proceed no further.

I'm unable to PUT new files or do much of anything, really. I can't get out of this situation by deleting files either, since I can't read or delete objects with the OS nor with Minio without wiping the partition.

## Current Behavior
There are two issues I'm observing:
* The objects folder for a large repo (over 500k-1.5m objects, I think) stops loading at some point on HFS+ and even APFS. Minio can't stat it, Finder can't, every *nix file listing tool I have cannot. I can't even `rm -rf *` the darn thing.
* `.minio.sys` contains a file per blob (or so it seems), which is a crazy overhead given that it seems to not do much (it looks like it regenerates the files when deleted too... soo...?). Therefore, `.minio.sys` exhibits the same problem and eventually dies.

## Possible Solution
This is definitely a filesystem issue, but it's odd because even HFS+ is supposed to support 2 billion files (even 2 million should suffice). APFS certainly should be able to handle this... I don't think it's a Minio-specific issue, but maybe Minio did something that Mac filesystems hate.

One thing that would massively mitigate this would be partitioning the objects across folders until a file limit is hit. Is there a reason Minio doesn't do this?

In any case, I would recommend a document on filesystem choice and object counts vs performance, so people can decide if Minio can scale to their needs. I still hope it can for me, so I'm finally breaking down and asking for help :-)

## Steps to Reproduce (for bugs)

1. Upload a million small files on any Mac filesystem. I haven't tested that this reproduces it, I only know that's how I got here.

## Context

I was unable to find _any_ recommendations for filesystems or maximum number of objects in Minio's issues and readmes. So either no one is foolish enough to run this on a Mac filesystem, there's a bug in Minio, I've configured it incorrectly, I am misusing it, or this issue would occur in any Minio installation eventually.

I started on HFS+ and later converted it to APFS (hoping it would solve the issue). APFS made it much worse since it performs terribly on anything but SSD. It's also possible that starting on a clean APFS partition and adding millions of files to a folder might work, if the conversion process is not equivalent.

## Your Environment

* Version used (`minio version`): Version: 2017-12-28T01:21:00Z
* Environment name and version (e.g. nginx 1.9.1): -
* Server type and version: -
* Operating System and version (`uname -a`): macOS 10.12.6 and 10.13.3
* Link to your project:

Also, this is running on spinning rust and not SSD, but that probably should not make a difference.

**Comment by harshavardhana** [comment]
> I'm unable to PUT new files or do much of anything, really. I can't get out of this situation by deleting files either, since I can't read or delete objects with the OS nor with Minio without wiping the partition.

your issue is primarily with the backend filesystem if backend cannot do much we cannot do either.  In this situation i most probably think the disk is dying and you should run a filesystem check to understand why its behaving this way.  Since on Linux XFS and ext4 can easily handle hierarchical namespace of 1.5million objects.

**Comment by jspiro** [comment]
@harshavardhana Appreciate the quick response. The disk seems to be in excellent health and I've tried rebuilding the filesystem (which would reveal issues if there were any). The disk only has issues in two directories, both Minio-controlled.

If Minio partitioned its objects rather than dumping them in a single directory, then it could do something about it.

If this is a known or now discovered limitation, it should be noted for Mac users. But I hope that's not the end of the story.

**Comment by harshavardhana** [comment]
> If Minio partitioned its objects rather than dumping them in a single directory, then it could do something about it.

That is upto you to decide you need to choose a right hierarchy when uploading objects, dumping all objects into a single directory is bad for all filesystems in general and would lead to issues like this. We do not decide on what you choose as path for the objects. 

> If this is a known or now discovered limitation, it should be noted for Mac users. But I hope that's not the end of the story.

This is a limitation of all filesystems, so we are just bound by those limitations - it is in our intention to keep the namespace of the filesystem in-tact by keeping it similar to the more familiar style of heirarchy.

**Comment by jspiro** [comment]
If Minio is a document store like S3, then it should be able to accommodate documents with UUIDs as their names, right? The application putting data in it shouldn't have to make assumptions about the backend of the storage endpoint, nor should it have to accommodate it; i.e. it won't know what names will cause subdirectories to be created in order to accommodate a large number of documents, and what number can it handle? It should be able to handle as many documents as there is free storage on the machine, probably.

Asking the application to do this is like asking a developer to know the size of a hashtable before putting keys in it, and to accomodate the way the keys and values will be stored internally. But in reality, hashtables rebuild themselves when they need to, and they distribute their keys for performance.

Even if this partitioning was done upfront by the application, Minio is creating two files in .minio-sys per document, which quickly becomes equally untenable. These should only be created when they're needed. In my case, they are completely unnecessary, but their existence taxes the filesystem.

---

Regarding normal usage, Arq recommends Minio for hosting your own S3 endpoint. If Minio is really only meant to be used by a human that hand-uploads files through the web interface, and could not possibly upload enough to break the system, I accept that, but then it must be upfront on what it is and isn't good at, and to what extent it does or does not scale. And it should warn people to not use it for long-term backup or application data storage.

---

**Summary:** It's up to Minio to understand the platform it's running on and make good decisions about how it stores the data, shards it, does erasure, etc.; It should not allow you to break the filesystem from normal usage, or it should define normal usage. If there are limits, they should be published and generate warnings. Minio bills itself as a robust and mature codebase, so people like me rely on it not knowing it's eating our data in an unrecoverable way.

**Comment by harshavardhana** [comment]
> If Minio is a document store like S3, then it should be able to accommodate documents with UUIDs as their names, right? The application putting data in it shouldn't have to make assumptions about the backend of the storage endpoint, nor should it have to accommodate it; i.e. it won't know what names will cause subdirectories to be created in order to accommodate a large number of documents, and what number can it handle? It should be able to handle as many documents as there is free storage on the machine, probably.
> 
> Asking the application to do this is like asking a developer to know the size of a hashtable before putting keys in it, and to accomodate the way the keys and values will be stored internally. But in reality, hashtables rebuild themselves when they need to, and they distribute their keys for performance.

That is an incorrect way to think about this problem in-fact AWS S3 documents and recommends best scenarios https://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html on why it is a good idea to fully utilize hierarchical namespace and the related performance benefits as you scale your buckets. This is quite similar in theory for local filesystems and Minio as well. 

> Even if this partitioning was done upfront by the application, Minio is creating two files in .minio-sys per document, which quickly becomes equally untenable. These should only be created when they're needed. In my case, they are completely unnecessary, but their existence taxes the filesystem.

This is not taxed by file-system, given there is a higher inode usage but that's about it. It is not unusual for filesystems to not support large number of files in a hierarchical namespace, for filesystems the problem arises when a single directory Readdir() happens along with Stat() operations, which eventually results in random I/O slowing the disks down. For example Apple Finder is one such application which would perform a Readdir() operation along with subsequent Stat() calls, which eventually results in a random I/O at disk level. 

> Summary: It's up to Minio to understand the platform it's running on and make good decisions about how it stores the data, shards it, does erasure, etc.; It should not allow you to break the filesystem from normal usage, or it should define normal usage. If there are limits, they should be published and generate warnings. Minio bills itself as a robust and mature codebase, so people like me rely on it not knowing it's eating our data in an unrecoverable way.

From our benchmarks on Linux XFS even 10 million files in single directory on NVMe takes about 11secs for us to fully List on minio server.  I would suspect that the issue lies in perhaps HFS+ not scaling for your application needs perhaps you could consider using XFS instead on a Linux system. 

To re-iterate myself it is incorrect and incomplete assumption to base scalability on one application point of view i.e Arq. While not exploring all other available options and file-systems in question.  Practically It is in-fact less common when applications do not know what their objects are going to be, for a most common scenario a more hierarchical namespace is preferred. If Arq does this by default and there is no way to change then it is safe to assume it might not work appropriately for Minio + HFS+ . I would be curious to know if Arq works well with Minio + XFS on Linux. 

There are other applications which might handle this differently such as [restic](https://restic.readthedocs.io/en/v0.2.0/Manual/#create-a-minio-server-repository), [cloudberry](https://www.cloudberrylab.com/solutions/minio) to name a few.

**Comment by harshavardhana** [comment]
Closing this issue as answered.
