### ISSUE TITLE
Improve testing code by using stretchr/testify

### ISSUE THREAD

**Issue by iwanbk** [minio/minio#5554]
I think minio could use https://github.com/stretchr/testify to improve testing code, the advantages:
- shorter code
- cleaner code

## Expected Behavior

Test code could be like this
```go
assert.Equal(t, http.StatusOK, rec.Code)
```

## Current Behavior
Current code
```go
if http.StatusOK != rec.Code {
		t.Errorf("Unexpected status code - got %d but expected %d",
			rec.Code, http.StatusOK)
	}
```
## Possible Solution

I can start with small parts, i think `gateway` package is good start because this is the package that i currently work on.

If my work getting merged, me or someone else could continue the work.

## Your Environment

Any environment

**Comment by harshavardhana** [comment]
we used to have testify we purposefully removed it because of the underlying complexity involved in using testify, we would like to keep the code simple and use only `Go` testing package. 

```
commit 2a21b7d63910e8e26e6468fdcb3ad5ee857492cc (origin/pr/453)
Author: Harshavardhana <harsha@minio.io>
Date:   Tue Apr 7 00:44:01 2015 -0700

    Implement headBucketHandler() and its related tests
    
    Remove internal testify/mock and use upstream - update all godeps
```

**Comment by iwanbk** [comment]
> we used to have testify we purposefully removed it because of the underlying complexity involved in using testify,

Would be great if you could give more detail about the reason, because i'm sure many people use it a lot.

>  Remove internal testify/mock

btw, what i propose is `testify/assert` or `testify/require`, still not OK?

**Comment by harshavardhana** [comment]
> Would be great if you could give more detail about the reason, because i'm sure many people use it a lot.

The reasoning is simple 

- Go provides a rich testing framework already there is no reason to use `testify`. 
- On-boarding new contributors would require them to stick to a framework which is proposed by testify, 
  It adds complexity to our development cycle asking contributors to read externally maintained packages
  involves cycles which we would like to avoid especially for writing tests.  
- We would like to avoid mocking our tests, instead have good unit tests and improve http://github.com/minio/mint for doing real world tests.

> btw, what i propose is testify/assert or testify/require, still not OK?

The problem is in enforcing and we wish to avoid such enforcement in the development cycle, our only mechanism is simply use Go `testing` package, eventually if Go `testing` packages provides more methods eventually we will use it. If these methods are so important i am pretty sure Go team will implement them natively.

**Comment by iwanbk** [comment]
Thanks for the explanation, closing it then :)
