### ISSUE TITLE
Option to avoid deleting parent directory

### ISSUE THREAD

**Issue by edgar86cru** [minio/minio#5664]
Possibility to add an option to avoid deleting parent directory

## Expected Behavior

I create the object folder1/
I add an object file.txt into the folder1/
I delete object file.txt, I would expect that folder1/ is still available

## Current Behavior

I create the object folder1/
I add an object file.txt into the folder1/
When I delete the file.txt minio deletes also the folder1/ but they are two different entities (keys)
I think that it deletes also the parent folder because the folder is empty

## Possible Solution

https://github.com/minio/minio/blob/ea8973b7d78d86b981b9ee9b496d352459df81b4/cmd/posix.go#L870
Add parameter to avoid deleting parent directory

## Your Environment

* Version used (`minio version`): 4.0.7
* Environment name and version (e.g. nginx 1.9.1): docker
* VERSION
2017-11-22T19:55:46Z
* MEMORY
Used: 5.7 MB | Allocated: 30 GB | Used-Heap: 5.7 MB | Allocated-Heap: 17 MB
* PLATFORM
Host: c22a324e3ffb | OS: linux | Arch: amd64
* RUNTIME
Version: go1.9.1 | CPUs: 4

**Comment by harshavardhana** [comment]
@edgar86cru - we implemented directory support for purely compatibility reasons. In-fact it is advised to not create directories in this manner instead simply use the <parent_dir>/object in the PUT object call and parents are created automatically. Deleting parents when dir is empty is an effective means of cleaning up namespace and providing the nature of flat namespace on POSIX backends. Avoiding this would simply complicate system and undermine the flat namespace nature. 

You should explain a bit more about your use case here, what is the application and why a parent directory is necessary to be present when its empty? since they do get created automatically when an object is uploaded.

**Comment by harshavardhana** [comment]
Closing this bug as stale,  please re-open with more answers to the requirement details.
