### ISSUE TITLE
Handle 'panic()' calls in our code and replace them with 'logger.FatalIf()'

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#5728]
There are `panic()` calls in several places in the code which does not log in our new standard logging format. 
With the new `logger` package approach, we do have `logger.FatalIf()` function to do the same or similar job. So, we need  to replace all `panic()` calls with `logger.FatalIf()` calls.
## Expected Behavior
All error conditions, including `panic()` errors, we have to use our new `logger` package functions to control logging and make sure all errors are logged in our unanimously decided new standard logging format.
## Current Behavior
`panic()` calls do their own logging which violates our new `logger` format standard.
## Possible Solution
Replace `panic()` calls with `logger.FatalIf()` calls.
## Steps to Reproduce (for bugs)
Code review
## Context
`panic()` calls violate our new `logger` format standard.

**Comment by aead** [comment]
Just replacing `panic()` calls in our code is not sufficient. Also third-party code and the standard library panics in many cases which would also violate our logging format. In general code **should** `panic` if it detects misuse that indicates a logical error: like an out-of-bound read/write or copying where destination is smaller than the source a.s.o. 

IMO the correct way to handle this is to `recover()` from a `panic()` at "the top-level" (whatever the top-level is, probably there are two: the main go-routine and the go-routine handling a request)
The recovering code can handle and log the error. 
Notice: Since the signature of `recover()` is `func recover() interface{}` we can reflect on the returned value - if it's our logging context our code caused the panic and we can use the context for proper logging. If not some code (which we do not maintain directly) caused the panic and we can only try to create a good log message...

**Comment by balamurugana** [comment]
Agreed with @aead 

`panic()` is done deliberately (on packages) so that consumer can  fail or `recover()`.  `logger.Fatalf()` is not a replacement for this (unless it `panic()` inside `logger.Fatalif()`

**Comment by ebozduman** [comment]
It looks like it'd be a good idea to discuss this with @abperiasamy and @harshavardhana too. I'll bring the subject up in our next meeting.

**Comment by ebozduman** [comment]
I specifically reworded the title to address the `panic()` calls in our code.
There'll be a separate effort to address panic() calls in vendors' codes. We have to address them differently and introduce `recover()` logic to control logging and decide on the behavior as @aead and @balamurugana suggested above.
