### ISSUE TITLE
[security]: Server should set security related HTTP headers 

### ISSUE THREAD

**Issue by aead** [minio/minio#5813]
## Expected Behavior
The minio server should set security headers such as:
 - `X-Frame-Options: SAMEORIGIN` (See #5805)
 - `X-XSS-Protection: 1; mode=block` (See #5805)
 - `Content-Security-Policy:`
 - `Expect-CT`
 - `Strict-Transport-Security: max-age=x ; includeSubDomains`

## Current Behavior

Server only sets `X-Content-Type-Options: nosniff

## Possible Solution

Add headers in `/cmd/http`

## Context
Security

## Your Environment
master

**Comment by viralpickaxe** [comment]
This should be configurable... Breaks any setup using minio to serve content for an iframe...

**Comment by aead** [comment]
@viralpickaxe I think this okay for now. Embedding the minio browser in an iframe is a very unusual use case. If it becomes a commen one we can think about making it configurable.
From my side: working-as-intended

**Comment by viralpickaxe** [comment]
@aead oh no I didn’t mean that, the issue is I have an html file being generated, saved in minio and then I’m trying to load the file directly from inside an iframe, and it’s being blocked because it has these headers. This header should only be applied to the minio dashboard portal, not the resources saved inside.

**Comment by aead** [comment]
@viralpickaxe Ah, I see your point. Your right about the `X-Frame-Options`. We should not set it for regular S3 requests. Will fix it
