### ISSUE TITLE
Hide version in Header

### ISSUE THREAD

**Issue by rwagner-inf** [minio/minio#5927]
Hi guys!

How do I, to disable, or not to display the version in the http headers?
What part of the code can I remove or comment on so it does not display the version?

![image](https://user-images.githubusercontent.com/24550871/39969748-12cc6500-56b7-11e8-877e-18fffec649c5.png)

I know the contact here would not be for that. But since I do not know any channel of discussion of the mine, I decided to ask here.

**Comment by harshavardhana** [comment]
You can ask in https://slack.minio.io, why do you want to disable it ? This similar to nginx version or Apache version in the headers. ??

**Comment by rwagner-inf** [comment]
I believe it is. that's precisely why I want to disable it.

**Comment by harshavardhana** [comment]
Can you state the requirement here ? Like what is the purpose behind removing Version information..

**Comment by harshavardhana** [comment]
Closing this as non-actionable for us for the time being.

**Comment by Laykou** [comment]
Hi, I'd also like to figure out how to disable this header.

The reason is **security**. You don't want to reveal any unnecessary information to potential hacker, do you? This way they know the content/files are served by Minio. The less information is exposed, the more secure the web is. The best approach is to minify/obfuscate any information and not to reveal any versions ... nothing.

Is there a way to disable it? If this behaviour is hard-coded, then this issue is perfect as foundation for a potential pull request to make this behaviour (version in header) either optional or remove it completly.

Is there any benefit of having this (or any similar) header in the HTTP response?

**Comment by aead** [comment]
At the moment there is no way to disable sending the version as part of  the response header. However, this does not imply that doing so gives an attacker any (significant) advantage. Sure, an attacker could (automatically) identify a (potentially) vulnerable server. However, the same is true for admins, security researchers, scanner/tools, ... So hiding the version may also make it harder to identify and upgrade outdated servers.

Further assuming a working exploit against the server an attacker can simply try it against any server. So this is about tradeoffs. The main reason for hiding the version - from my experience -  is to not reveal that there is an outdated / vulnerable server. So IMO the correct approach is to fix/upgrade instead of concealing the fact of running vulnerable software...

**Comment by zefie** [comment]
@aead 

can we revisit this to disable at least the architecture? on an arm machine it reports:

Server: Minio/DEVELOPMENT.GOGET (linux; arm)

we can argue about the security of versions, but reporting arm exposes that this machine can easily be overtaken by cpu intensive tasks (a DoS attempt against an ARM minio will likely go down faster than an x86)

requesting option to at least hide arch so that reports as such:

Server: Minio/DEVELOPMENT.GOGET (linux)

while we are talking version strings, maybe have development report the git commit rather than "DEVELOPMENT.GOGET", as this basically hides the version as the OP wanted, but you did not.

**Comment by aead** [comment]
> but reporting arm exposes that this machine can easily be overtaken by cpu intensive tasks (a DoS attempt against an ARM minio will likely go down faster than an x86)

What is the rationale behind this?
There are very powerful ARM and X86/AMD64 machines and also very "slow" machines of different architectures. AFAICS the CPU architecture does not indicate whether the server is computational-wise powerful or not.

Apart from that I forward your proposal of sending the commit instead of `DEVELOPMENT.GOGET` / `REALESE...`. However, that does not help w.r.t. the version-concern. If someone knows the commit ID he/she can go to github and can directly see which fixes / features are part of the deployment and which are not. So from @rwagner-inf point of view that would be even worse than sending the version number.

**Comment by zefie** [comment]
In any case, it should be up to the user. 

> So hiding the version may also make it harder to identify and upgrade outdated servers.

If the admin wanted to know the version they could enable it in the config, think Apache. You can have it as verbose as telling the versions and all of its modules, or as quiet as just "Apache".

We should assume legitimate admins would have other, more secure ways of identifying their installed version than having to use a public header. We should allow the admin to decide if they want this convenience, or would rather the extra peace of mind of not sending more than we need to.

Suggestion would be something like: force sending at least "Minio", then use a config/env variable to parse optional extended version. can default to current, eg "%v (%o, %a)" (where %v = version, %o = os, %a = arch)

**Comment by aead** [comment]
I don't want a make a final decision about this - ping @harshavardhana @donatello 

However, my point is the following:
Hiding the server version / commit ID does not improve the security of a deployment. The rationale is that if we *assume* a working exploit against a specific version / commit than hiding the version / commit does not prevent any attack since an attacker can try the exploit "blindly". In contrast it makes it harder to find servers which are not up to date. I don't see that hiding the version provides an advantage - apart from maybe "a better feeling".
However, I agree that security-aware admins may prefer the `mc admin` API for keeping track of their deployments. I'm leaving this for others to decide.

**Comment by zefie** [comment]
> The rationale is that if we assume a working exploit against a specific version / commit than hiding the version / commit does not prevent any attack since an attacker can try the exploit "blindly". 

One example scenario I can think of is if an attacker knows the exact version, they can attack with the initial connection. If they are attacking blindly, it is more likely external security measures can detect and block the attack before the working exploit (if any) is reached. The delaying of an attacker only gives the admin that much more time to respond. Wouldn't we want to give any advantage possible to the admin?

**Comment by abperiasamy** [comment]
Knowing that it is Minio server is sufficient to try all the known vulnerabilities. In fact, there is only a hand full of S3 compatible object storage implementations out there. Hiding version or ARCH info is not going to help with security that much. I don't mind anonymizing the public responses with a special flag. Every option we add increases testing and maintenance burden.  We really need to ask if it will make a difference. If we hide this info, what do we lose or break? @harshavardhana @aead

**Comment by harshavardhana** [comment]
Perhaps --anonymous flag can turn off sending `Server:` header ? We can perhaps selectively turn off any other server revealing info in HTTP headers.

**Comment by abperiasamy** [comment]
If it is a security issue, it is better to disable it by default and not worry about --anonymous flag. If it is not a security issue, then we should move the anonymous flag to logging subsystem instead of keeping it global.

**Comment by harshavardhana** [comment]
Okay then let's just keep `Server: Minio` minimum information, and `--anonymous` for logging only.

**Comment by abperiasamy** [comment]
Let's wait to hear from the security experts in the community to make a reasonable case for exposing version info to be a matter of concern. If not no change.

**Comment by harshavardhana** [comment]
Now reading http://httpd.apache.org/docs/2.4/mod/core.html#servertokens apache has following opinion @abperiasamy @aead 

> Setting ServerTokens to less than **minimal** is not recommended because it makes it more difficult to debug **interoperational** problems. Also note that disabling the Server: header does nothing at all to make your server more secure. The idea of "security through obscurity" is a myth and leads to a false sense of safety.

**Comment by zefie** [comment]
> The idea of "security through obscurity" is a myth and leads to a false sense of safety.

I have many servers, one requires SSH to be on port 22 due to compatibility. The rest do not, and I run on an alternate port. The server at port 22 gets over 2000 attempts an hour and needs fail2ban. The ones on the alternate port NEVER (at least for the past 3 years) have had any fail attempts.

Perhaps in the case of hiding the version, this is correct, but overall, I argue "security through obscurity" is definitely a thing.

My final opinion on this matter is, if you want to go ahead and add the git commit to the version for dev builds, then you should offer an option that retains the current functionality of displaying the generic "DEVELOPMENT/GOGET". Users wanting to hide their version could be told to simply build from git and use the flag that you would implement to retain the current version implementation.

**Comment by harshavardhana** [comment]
> Perhaps in the case of hiding the version, this is correct, but overall, I argue "security through obscurity" is definitely a thing.

AFAICS we will be doing `Server: Minio`  @zefie so that should cover all cases.

**Comment by nitisht** [comment]
Fixed by #7074
