### ISSUE TITLE
Minio is listing only directories as object which is empty

### ISSUE THREAD

**Issue by zetaab** [minio/minio#6047]
I have problems that minio is not listing directories that it does in AWS. It is listing only directories that is empty.

## Expected Behavior

Expected Behavior is same that aws does

The output in aws:
```
% python main.py
dirwithfiles/ 0
dirwithfiles/firstfile 7
emptydir/ 0
```

## Current Behavior

The output in minio:
```
% python main.py
dirwithfiles/firstfile 7
emptydir/ 0
```

## Steps to Reproduce (for bugs)

create following dir structure to minio:
```
emptydir/ (this is just empty directory)
dirwithfiles/firstfile (file inside directory)
```

```
/storage/test2 # ls -lR
.:
total 8
drwxr-xr-x    2 root     root          4096 Jun 15 05:44 dirwithfiles
drwxr-xr-x    2 root     root          4096 Jun 15 05:44 emptydir

./dirwithfiles:
total 4
-rw-r--r--    1 root     root             7 Jun 15 05:46 firstfile

./emptydir:
total 0
```
Listing everything
```
        response = self.client.list_objects_v2(
            Bucket=self.bucket,
            Prefix='/',
        )
        for obj in response.get('Contents', []):
            print("%s %d" % (obj['Key'], obj['Size']))
```

## Your Environment

I am using minio/minio:latest docker container

**Comment by harshavardhana** [comment]
This is expected, we cannot provide AWS S3 like behavior in this matter. We use POSIX hierarchy to simulate the directory tree structure. To provide for flat namespace we had to ensure this translation stays. 

- The directory is shown only if it has no files in it.
- The directory is flattened out if it has more than 1 files in it. 

It is advisable and recommended to stop using empty directories as they do not serve any real purpose on object storage systems. You can do away with such calls since key in its entirety is already handled properly to provide for the hierarchy.

**Comment by kannappanr** [comment]
@zetaab #6010 issue is about not listing an empty directory, which is not the case in this issue. Based on comments by @harshavardhana I am closing this issue as it is working as intended.

**Comment by vikrantrathore** [comment]
@harshavardhana @kannappanr We are using pyfilesystem to abstract the calls. Pyfilesystem has an api called opendir which works with s3, google file system, local filesystem, NAS. It fails in case of minio. 

This is due to fact that minio fails to return directories with files. If we change the code it will become very specific to minio. So I believe it will be nice if this behaviour works like S3.

There is a ticket in pyfilesystem project which was closed because it follows S3, but minio is an exception.

**Comment by harshavardhana** [comment]
I am afraid we are not interested in supporting directories at the moment. It is a niche use case to provide POSIX behavior it's not in our interests.
