### ISSUE TITLE
Docs/cli help are unclear about DIR arguments

### ISSUE THREAD

**Issue by ematvey** [minio/minio#6063]
Until today I was refraining from using minio as I found the way it combines peer specification unclear and was unable to find answer in the docs. Let me illustrate what was confusing to me:

1 server multiple disks setup: 
```minio server /data1 /data2```
Everything is clear in this example.

Distributed multi-disk setup:
```minio server http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2```
Not very clear. Below are confusing points.
1. How does it resolves local fs storage paths? Checks local hostname, ports and scheme are not applicable/ignored? Path is resolved relative to fs root?
2. How does it resolves peer API endpoints? Are they also addressed relative to fs root or DIR specified? Since I am specifying not only API endpoint but also path on the remote, should I expect to be able to attach a local peer to some subdirectory on the remote?
3. What about ports? HTTP scheme without port specification assumes 80, but in this case it is 9000.

Overall, API seems concise but doesn't map very well onto my existing mental model of how fs paths and HTTP URL's path part are mostly separate things. If I was designing the API, I would explicitly separate storage paths and peer endpoints. Maybe a new section in the docs + more explanation to DIR argument in server cli are in order?

**Comment by ebozduman** [comment]
@ematvey,
Thank you very much for pointing out what is missing and unclear in Distributed Minio Server documentation. I'll look into what we can improve and make it more clear for end-users to better understand how to set up and use Distributed Minio Server.

Let's go through your example and answer your  questions before deciding what needs to be updated in Minio documentation:
> `minio server http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2`
Q1. How does it resolves local fs storage paths? Checks local hostname, ports and scheme are not applicable/ignored? Path is resolved relative to fs root?

A1. Hostnames, ports and scheme are not ignored. Hostnames are resolved (see /etc/hosts configuration file), if a port number with `"--address"` option is not provided, then default port `":9000"` is assumed, otherwise the provided port number is used for all hosts/nodes, and "Yes", path is resolved relative to fs root.

Probably a good example would be from the [Distributed Minio Quickstart Guide](https://docs.minio.io/docs/distributed-minio-quickstart-guide) doc:
```
export MINIO_ACCESS_KEY=<ACCESS_KEY>
export MINIO_SECRET_KEY=<SECRET_KEY>
minio server http://192.168.1.11/export http://192.168.1.12/export \
             http://192.168.1.13/export http://192.168.1.14/export \
             http://192.168.1.15/export http://192.168.1.16/export \
             http://192.168.1.17/export http://192.168.1.18/export
```
Note: Above example in the doc shows endpoints with <ip>/export`<No>` and unnecessarily differentiates the export points with some numbers. I'll remove those numbers from the endpoints in the doc and have it look like above.

The above exact same command needs to be run on every single Distributed Minio Server host, 192.168.1.11 through 192.168.1.18, provided that the `/export` is the exported mount point to the disk drive/file system on every single host, your Distributed Minio Server intends to be using.

> Q2. How does it resolve peer API endpoints? Are they also addressed relative to fs root or DIR specified? Since I am specifying not only API endpoint but also path on the remote, should I expect to be able to attach a local peer to some subdirectory on the remote?

A2. Peer endpoints are resolved exactly the same way as explained in A1. They are also addressed relative to their fs roots. The endpoints on remote hosts are supposed to be `exported` disk drives/file systems (see regular /etc/exports configuration file), made accessible for the other remote hosts/nodes of your Distributed Minio Server setup. 

> Q3. What about ports? HTTP scheme without port specification assumes 80, but in this case it is 9000.

A3. In Minio context, the endpoints use port `:9000` if not specified. If specified with `--address` option, the user provided value will be used instead. Obviously, this means all Distributed Minio Server hosts/nodes will be running on this port.

Please let me know if this helps clarify your questions.

**Comment by ematvey** [comment]
Thanks for the explanation. I guess most confusing part is using `http` scheme in examples with non-standard implicit port. Maybe you should introduce `minio://` scheme or remove scheme alltogather?

Regarding paths, are nodes allowed to export several mount points on the single host+port combo? I was under inpression that 1 minio instance corresponds to 1 mount point and 1 address (host+port). If that is so, maybe there's no need to specify path at all?

**Comment by ebozduman** [comment]
> Maybe you should introduce minio:// scheme or remove scheme altogether.

I see your point. It is a good suggestion to think about. I'll bring it up to the attention of the architect/designer team to consider.

You may have several mount points/disk drives on a single Minio node. However, user needs to be aware of the setup differences and how they impact high availability in distributed setups. Having multiple disks in one server creates a single point of failure. If that server goes down for some reason, all  drives on that server is lost in one shot. So, it decreases the level of high availability and data protection.

Some related explanations from the  [Distributed Minio Quickstart Guide](https://docs.minio.io/docs/distributed-minio-quickstart-guide) doc:

---
### High availability
A stand-alone Minio server would go down if the server hosting the disks goes offline. In contrast, a distributed Minio setup with _n_ disks will have your data safe as long as _n/2_ or more disks are online. You'll need a minimum of _(n/2 + 1)_ [Quorum](https://github.com/minio/dsync#lock-process) disks to create new objects though.

For example, an 8-node distributed Minio setup, with 1 disk per node would stay put, even if upto 4 nodes are offline. But, you'll need at least 5 nodes online to create new objects.
### Limits
As with Minio in stand-alone mode, distributed Minio has a per tenant limit of minimum 2 and maximum 32 servers. There are no limits on number of disks shared across these servers. If you need a multiple tenant setup, you can easily spin multiple Minio instances managed by orchestration tools like Kubernetes.

Note that with distributed Minio you can play around with the number of nodes and drives as long as the limits are adhered to. For example, you can have 2 nodes with 4 drives each, 4 nodes with 4 drives each, 8 nodes with 2 drives each, 32 servers with 24 drives each and so on.

---

**Comment by ebozduman** [comment]
@ematvey  
Could we we close this issue?

**Comment by ematvey** [comment]
Yep

**Comment by ebozduman** [comment]
Thank you

**Comment by zefie** [comment]
This seems like the best existing issue to drop this in. I have been frustrated by this vague error message for about 12 hours, so I apologize if some frustration comes across in this comment. It feels like a combination of not-yet-implemented features on top of actual intent to block what I am trying to do.

**"server address and local endpoint have different ports"** is too vague of an error.

I am trying to do a distributed setup, with 2 remote hosts and 1 local host.

1. https://remote0:9001 (actually same machine as distrib, but not localhost as thats blocked, so local's public ip)
2. https://remote1:9000 
3. https://remote2:9000
4. https://remote2:9001

This is where everything goes wonky, and the above error message is displayed. Regardless of "local endpoint" ports. Even if I try to run the distributed on port 9000 (as our system only has 9001 bound), it still thows this error. Swapping this also fails. In fact, basically everything I try throws this same error.

I have come to the conclusion this error really means **"cannot have endpoints with different ports**", or maybe "**cannot have endpoint on same host as us**" (since localhost is blocked after all). If I am wrong, please explain, if I am right, please explain why this limitation exists.
