### ISSUE TITLE
Minio Kubernetes Statefulset Extend/Add Disks

### ISSUE THREAD

**Issue by mitchellmaler** [minio/minio#6277]
Hello,

I have Minio running in kubernetes as a stateful set using the manifests that your website generates and I am getting to about half disk capacity. Do you have any documentation on how to extend the existing disks or add more disks using kubernetes (without losing data of course),

**Comment by nitisht** [comment]
Hi @mitchellmaler Minio by design doesn't allow adding disks in an existing setup. The complexity of rebalancing data, and the downtimes while cluster gets rebalanced is not worth the advantages. 

We recommend adding new deployments as your storage needs grow, please refer https://docs.minio.io/docs/minio-federation-quickstart-guide.html

Other option is to create a bigger cluster and move data out of this cluster using `mc mirror`.

**Comment by mitchellmaler** [comment]
@nitisht That makes sense. Since I already back up the data I think creating a new one with mc mirror would work.
