### ISSUE TITLE
Server side encryption specified but KMS is not configured

### ISSUE THREAD

**Issue by shantanugadgil** [minio/minio#6367]
We use Minio as a local S3 server.
After updating to the most recent versions (KMS enabled ones), we have started getting the following error during uploading files into Minio.

```
Server side encryption specified but KMS is not configured
```

Failing on versions
```
Version: 2018-08-21T00:37:20Z
Release-Tag: RELEASE.2018-08-21T00-37-20Z
Commit-ID: 2d84b02bc429ad059a060001bccd712491e6e6a3
```

It also fails on the latest version
```
RELEASE.2018-08-25T01-56-38Z
```

I see a new "kms" section added in the config.json.
My config.json is at version 28 (twenty eight)

Is there any way to disable KMS altogether as we are using this "on premise" and not on AWS.

OR

Is there something that the client code can do to not "enable" KMS code at all.

Ideally an environment variable to "disable" SSE would be awesome.

## Your Environment
* Version used (`minio version`):
RELEASE.2018-08-25T01-56-38Z

* Operating System and version:
CentOS 7.5+ updates

*** For now, we have reverted to using an older version of Minio (from around Aug 02)

Regards,
Shantanu

**Comment by aead** [comment]
@shantanugadgil You see this error message because you haven't configured a KMS but send SSE-S3 requests. If you look at the S3 request headers of your client application(s) you should see: 
`X-Amz-Server-Side-Encryption: AES256`.
So your client requests SSE-S3 but no KMS is provided to store/manage the SSE-S3 keys. 
So either you have to specify a KMS or not send this S3 header. The server cannot ignore this because otherwise it would store objects unencrypted while encryption is requested...

To fix this:
 - either setup [vault](https://www.vaultproject.io/) as described [here](https://docs.minio.io/docs/minio-kms-quickstart-guide.html)
 - or fix your client applications to not request SSE-S3 when it shouldn't
   (Don't send `X-Amz-Server-Side-Encryption`)

For a setup without vault refer to: https://github.com/minio/minio/issues/6329#issuecomment-414837743

**Comment by shantanugadgil** [comment]
@aead Thanks. I will check up on the headers being sent by the client and see if it can be switched off optionally.

**Comment by shantanugadgil** [comment]
confirming that the code was using the `encrypt=True` parameter during an S3 upload code (boto function: `set_contents_from_string`) which was causing this.

The upload worked fine after trying with `encrypt=False`

Thanks and Regards,
Shantanu
