### ISSUE TITLE
Distributed Minio (3-nodes) Resiliency tests and outcome

### ISSUE THREAD

**Issue by deepak71** [minio/minio#6442]
Files do not automatically sync to an offline node/disk once it comes back online

## Expected Behavior
Minio service was brought down on one of the node (out of three), created a new bucket and uploaded a file. But that file didn't sync when that node brought online. We would expect the files to be synced once that node comes back online.

## Current Behavior
Service was brought up on the node, however data (bucket and file) was not replicated

## Possible Solution
We didn't run mc admin heal to sync them back up. There is no auto-heal in minio it was reported in one of the minio issue.

## Steps to Reproduce (for bugs)
- Service on all nodes running, a new bucket was created and file was uploaded (data was replicated on all three node). 
- Then,  Minio service was brought down on one of the node (out of three), another file was uploaded.
- Again,  Service was brought up and we observed that new file did not replicate on that node on which service was down.

## Context
Are we missing something other than heal TARGET step in the first place? Do we only need to  run `mc admin heal ` or any option is available to enable an auto healing in minio when node(s) go in out of sync .

**Comment by nitisht** [comment]
@deepak71 can you explain the actual problem you're facing. I see the actual outcome, but not the outcome you're expecting

Also please use the issue template for reporting issues - it helps understand what you're trying to achieve and what is not working as expected. I dont see info like Minio version used / how many disks per node etc

**Comment by deepak71** [comment]
@nitisht Edit the reported issue. Thank you!!

**Comment by nitisht** [comment]
Thanks @deepak71

**Comment by nitisht** [comment]
Minio by design doesn't heal itself automatically, this is to keep design straight forward and avoid potential downtime when Minio system tries to heal itself at incorrect times (say for example while there is high incoming load). 

Minio Admin/operator is best placed to actually handle this situation. They know very well about the traffic situation and can plan heal accordingly. 

> Are we missing something other than heal TARGET step as a first place? Do we only need to run mc admin heal or any option is available to enable an auto healing in minio when node(s) go in out of sync .

So, to answer your question, you need to run `mc admin heal <alias>` when nodes go out of sync.

**Comment by deepak71** [comment]
Thank you! @nitisht for clarifying this.

Then, we would create a systemd service to inspect objects health and heal them if needed.

**Comment by nitisht** [comment]
Thanks @deepak71 . Feel free to close the issue if everything is clear now

**Comment by mtparet** [comment]
I am surprised. What happens if the network goes down for few seconds or milliseconds ?
Does it means buckets/files will be inconsistent across minio nodes ?

**Comment by harshavardhana** [comment]
> I am surprised. What happens if the network goes down for few seconds or milliseconds ?
> Does it means buckets/files will be inconsistent across minio nodes ?

It shouldn't be thought of as inconsistent that would mean that object is corrupted, but that is not the case here. Yes, there might be a situation that you only have 7 parity instead of 8 expected from a 16 disk setup. That is why we keep N/2 parity count to provide a much higher resiliency for a long period of time even with multiple disk failures. 

This model was primarily chosen from our experience writing GlusterFS synchronous replication systems. We choose this model on purpose because running a heal on every sort of network disconnection is frivolous, it should be done on a timely basis where you give room for disconnections to occur such that they can be fixed in lower priority threads. 

We will be implementing self-healing but not in the traditional manner which other distributed systems have implemented, it will not trigger itself unnecessarily for simple network disconnects because that can be frivolous and overwhelm any given system.

 `mc admin heal` is a more controlled tool to perform these operations, if you have temporary network disconnections with high enough parity it is much less of a concern.

**Comment by mtparet** [comment]
Thank you very much @harshavardhana for your detailed answer, I better understand the model chosen.

For now, if I understand correctly, it means we could run `mc admin heal` periodically to ensure all disks are synced for better resiliency even if it is not required to keep the resiliency up (thanks to the N/2 parity).
