### ISSUE TITLE
Config on backend should be stored in all sets if > 16 disks in EC mode

### ISSUE THREAD

**Issue by jonassvatos** [minio/minio#6497]
I have an instance with 32 disks, and the config data on backend is only stored in the first set (16 disks). The other 16 disks doesn't contain the config.

## Expected Behavior
```
$ /usr/local/bin/minio server /mnt/dl1-data60-1/disk{00...31} &
$ ls /mnt/dl1-data60-1 |wc -l
32
$ find /mnt/dl1-data60-1/*/.minio.sys/config -maxdepth 0|wc -l
32
```

## Current Behavior
```
$ /usr/local/bin/minio server /mnt/dl1-data60-1/disk{00...31} &
$ ls /mnt/dl1-data60-1 |wc -l
32
$ find /mnt/dl1-data60-1/*/.minio.sys/config -maxdepth 0|wc -l
16
```
## Possible Solution
Include config in all sets in EC mode

## Your Environment
```
$ minio version
Version: 2018-09-12T18:49:56Z
Release-Tag: RELEASE.2018-09-12T18-49-56Z
Commit-ID: ce419c98352324caa4c79b159a9f840ca714c3d5
```
EC mode, single node, 32 physical disks
OS: EL7

**Comment by harshavardhana** [comment]
config cannot be stored @lsde it is always stored on the first set, same as policy.json, notification.xml etc

**Comment by jonassvatos** [comment]
@harshavardhana ok, but shouldn't be these crucial data present in all sets? suposing the whole first set gets corrupted, and my parity is over n/2..when i upload something into an instance with multiple sets, the files are split among them, so the system should not be dependent only on the config data present just in the first set, right?

**Comment by harshavardhana** [comment]
> @harshavardhana ok, but shouldn't be these crucial data present in all sets? suposing the whole first set gets corrupted, and my parity is over n/2..when i upload something into an instance with multiple sets, the files are split among them, so the system should not be dependent only on the config data present just in the first set, right?

config.json is nothing but another object, even your object doesn't spread across all 32 disks. They only spread up to the maximum set count i.e 16. 

Minio is designed to be used on 1000's of disks, mathematically you cannot erasure code across all the disks since erasure code is maximum of 256 disks.

With current 16 disks, you get 8 disk failure rate so loosing 8 disks is practically rare in a given set so it is not a big problem. Minio startup doesn't depend on `config.json` to be present to make your objects accessible it is simply a file to capture/enable features like logging and notification - so it is not a crucial piece to get the server up and running.

**Comment by jonassvatos** [comment]
ok, thanks for an excellent explanation!
