### ISSUE TITLE
Minor typo with go install instructions on OSX?

### ISSUE THREAD

**Issue by justinclift** [minio/minio#654]
In the OSX installation section of [INSTALLGO.md](https://github.com/minio/minio/blob/master/INSTALLGO.md#setup-goroot-and-gopath-1), it mentions adding those environment variables to .bashrc.

Shouldn't that be .profile on OSX?  Asking because on my OSX 10.9.5 desktop, .bashrc isn't sourced when terminals are started, though .profile is. :smile:

**Comment by harshavardhana** [comment]
> Shouldn't that be .profile on OSX? Asking because on my OSX 10.9.5 desktop, .bashrc isn't sourced when terminals are started, though .profile is.

On Yosemite 10.10 it seems to be .bashrc , perhaps it could be related to bash version on both these platforms.  I will find what works for both bash versions and see which fits here.

**Comment by justinclift** [comment]
No worries.  It's also possible I've modified my desktop config from default and don't remember doing so. :wink:

**Comment by harshavardhana** [comment]
> No worries. It's also possible I've modified my desktop config from default and don't remember doing so.

I will verify, thanks for your inputs @justinclift

**Comment by harshavardhana** [comment]
I found the problem why this happens, snippet from bash documentation

#### 6.2 Bash Startup Files

This section describes how Bash executes its startup files. If any of the files exist but cannot be read, 
Bash reports an error. Tildes are expanded in filenames as described above under Tilde Expansion 
(see Tilde Expansion).

##### Invoked as an interactive login shell, or with --login

When Bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option,
 it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it 
looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes 
commands from the first one that exists and is readable. The --noprofile option may be used when the
shell is started to inhibit this behavior.

When a login shell exits, Bash reads and executes commands from the file ~/.bash_logout, if it exists.

##### Invoked as an interactive non-login shell

When an interactive shell that is not a login shell is started, Bash reads and executes commands from
~/.bashrc, if that file exists. This may be inhibited by using the --norc option. The --rcfile file option will
force Bash to read and execute commands from file instead of ~/.bashrc.

So, typically, your ~/.bash_profile contains the line

if [ -f ~/.bashrc ]; then . ~/.bashrc; fi after (or before) any login-specific initializations.

**Comment by justinclift** [comment]
Interesting. Guess it depends which is more useful for minio then.  For me at the moment, doing stuff through a login shell, it's .profile.  Not sure that's going to be the case for everyone else though. :wink:
