### ISSUE TITLE
High IO load on server with few thousands objects every 12 hours

### ISSUE THREAD

**Issue by weedek** [minio/minio#6541]
## Expected Behavior
No disk load on non busy server.

## Current Behavior
Every 12 hours minio causes high CPU load (IO wait) on server with few thousands objects. 
The more objects the longer it lasts. 
I suspect that this causes a disk usage routine that checks disk usage.

## Possible Solution
Add configuration option to disable checking disk usage.

## Steps to Reproduce (for bugs)
Put few thousands files into minio. 
Wait 12h and 24h and observe the system load.

## Your Environment
* Version used (`minio version`):  2018-05-25T19:49:13Z
* Server type and version: XenServer VM
* Operating System and version (`uname -a`): Debian 4.9.88-1+deb9u1

**Comment by harshavardhana** [comment]
This is expected we calculate disk usage every 12 hours if there is active I/O we suspend the disk usage calculation as well. 

Are you saying we shouldn't do this?

**Comment by weedek** [comment]
On server with large amount of files (hundreds of thousands) that is a problem with high disk and CPU usage when server is idle and counting in that way will take hours.

Why we need that information counting in such way?
Is information from filesystem (like in df command) inaccurate?

Please add posibility in configuartion to disable disk usage counting in that way and relay on filesystem disk usage.

**Comment by harshavardhana** [comment]
> On server with large amount of files (hundreds of thousands) that is a problem with high disk and CPU usage when server is idle and counting in that way will take hours.
> 
> Why we need that information counting in such way?
> Is information from filesystem (like in df command) inaccurate?
> 
> Please add posibility in configuartion to disable disk usage counting in that way and relay on filesystem disk usage.

@weedek we can only get `df` when you point your `minio` to the entire disk, if not if you picked a directory inside the mount - we cannot say what is the correct usage since many minio servers might share the same drive.

For now the behavior will stay, we will think about adding an option to turn this off and force use `df`

**Comment by weedek** [comment]
So if I point MINIO_VOLUMES directly to disk/partition mountpoint, "disk usage routine" won't be run and information about disk usage will be taken from `df `command?

**Comment by harshavardhana** [comment]
> So if I point MINIO_VOLUMES directly to disk/partition mountpoint, "disk usage routine" won't be run and information about disk usage will be taken from `df`command?

Yes that is correct @weedek

**Comment by kannappanr** [comment]
@weedek Closing this issue as answered. Please feel free to reach out to us if you have further questions.

**Comment by fdaone** [comment]
Hi

First of all, sorry for adding to a closed issue. However, I wanted to share my experience with this as I upgraded our MinIO cluster this week from an ancient version (RELEASE.2018-01-02T23-07-00Z) to RELEASE.2019-06-04T01-15-58Z. So roughly an 18 month jump. :) It was long overdue but we were simply nervous to upgrade due to the size of the object store (more than 20 million objects - mostly small files). The total inode count is north of 150 millions. :)

Long story short, we were right to be nervous. :) After upgrading the load went beserk on all nodes in the cluster. Load average quickly rose to more than 1,000 (one thousand! :)) and basically stayed there. Before the upgrade the cluster nodes saw nearly no load whatsoever (load average of less than 1). Memory consumption also sky-rocketed (it *doubled* from roughly 15 GB to 30 GB).

MinIO is extremely difficult to troubleshoot when something like this happens. Nearly nothing is being logged about all its internal activities/house-cleaning/diskUsageCalc/whatever, but then I finally found this issue, luckily. As such, I've been busy today migrating all data (node by node) from /mountpoint/subdir to /mountpoint to avoid the insane disk usage calculation. If only there had been a switch to turn it off to quickly work around the problem (hint: https://github.com/minio/minio/pull/6016). :)

Generally, MinIO is waaaay too static in its configuration. Speaking of which, I see a new feature has been introduced this week. Self-healing. Sounds cool, but I'm soooo glad I didn't happen to upgrade to this most recent version as I can imagine that such a feature could also possibly put extra load of the cluster nodes(?) So is there a switch to turn off self-healing in case it is needed? :)

Don't get me wrong, I like MinIO, and I'm grateful for what you, the MinIO developers, have brought to the table. However, more configurable options/switches to enable/disable features would be very, very welcome. :)
![minio_trouble](https://user-images.githubusercontent.com/46779585/59428409-68f9c900-8ddd-11e9-9960-efdf442b9a47.png)
