### ISSUE TITLE
Regression made assumed roles incompatible with minio when using aws sdks & cli

### ISSUE THREAD

**Issue by bermi** [minio/minio#6739]
Recent changes in minio are preventing us from using AWS assumed roles.

## Steps to Reproduce

1. Add two profiles to the AWS credentials file, one with a session token and another one without it:

```bash
cat >> ~/.aws/credentials <<EOL

[minio]
aws_access_key_id=admin
aws_secret_access_key=password

[minio-assumed-role]
aws_access_key_id=admin
aws_secret_access_key=password
aws_session_token=sessionToken

EOL
```

2. Create a test bucket

```bash
mkdir -p minio-test/test-bucket
cd minio-test
```

3. Run the minio server using the latest docker version

```bash
docker run -e "MINIO_ACCESS_KEY=admin" -e "MINIO_SECRET_KEY=password"  -v `pwd`:/data -p 9000:9000 minio/minio server /data
```
## Current Behavior

Listing bucket fails when using the profile with a session token.

```bash
$ aws --profile minio-assumed-role --endpoint-url http://0.0.0.0:9000 s3 ls

An error occurred (InternalError) when calling the ListBuckets operation (reached max retries: 4): We encountered an internal error, please try again.
```

It works fine if we use a profile without a session token.

```bash
$ aws --profile minio --endpoint-url http://0.0.0.0:9000 s3 ls
2018-10-31 00:42:39 test-bucket
```

## Regression

Versions newer than `minio/minio:RELEASE.2018-08-02T23-11-36Z` caused this change in behavior.

```bash
docker run -e "MINIO_ACCESS_KEY=admin" -e "MINIO_SECRET_KEY=password"  -v `pwd`:/data -p 9000:9000 minio/minio:RELEASE.2018-08-02T23-11-36Z server /data
```

Allows us to use the profile with the assumed identity and its session token.

```bash
$ aws --profile minio-assumed-role --endpoint-url http://0.0.0.0:9000 s3 ls
2018-10-31 00:54:46 test-bucket
```

**Comment by harshavardhana** [comment]
> ```shell
> An error occurred (InternalError) when calling the ListBuckets operation (reached max retries: 4): We encountered an internal error, please try again.
> ```

The session token is meaningless for us @bermi provided by AWS - if you provide that we will have to try to decode it based on temporary credentials that we support with STS. 

Why is this set anyways for Minio server? - This worked because we previously didn't support `x-amz-security-token`

**Comment by bermi** [comment]
@harshavardhana We are using minio instead of s3 on our CI pipeline. The code uses the aws-sdk and the assumed roles for interacting with AWS services (except s3) which has been replaced with minio by changing the endpoint.

What would be the proper way to share the ID and Key when connecting with minio through the aws-sdk/cli and using assumed roles and tokens?

**Comment by harshavardhana** [comment]
> @harshavardhana We are using minio instead of s3 on our CI pipeline. The code uses the aws-sdk and the assumed roles for interacting with AWS services (except s3) which has been replaced with minio by changing the endpoint.
> 
> What would be the proper way to share the ID and Key when connecting with minio through the aws-sdk/cli and using assumed roles and tokens?

We cannot understand AWS tokens @bermi - Minio implements its own Token understanding mechanism for STS temporary credentials.  If you provide us with AWS session token we can't make sense of it since we are not an AWS service - neither we have a way to look up what it means. 

AWS cli would automatically set these tokens if used in the credentials file. So when you get credentials from AWS for the assumed role you should avoid setting session tokens to Minio because they are inherently meaningless for us. Avoid setting this in request header i.e in your application, simply use the access/secret key.

**Comment by bermi** [comment]
@harshavardhana Thanks for the detailed explanation. 

Unfortunately, I'm not sure there's a way to opt-out sending the headers for temporary credentials when using AWS clients.

Is there an environment variable that we could use to disable the STS feature in minio when starting the server?

**Comment by harshavardhana** [comment]
> Unfortunately, I'm not sure there's a way to opt-out sending the headers for temporary credentials when using AWS clients.
> 
> Is there an environment variable that we could use to disable the STS feature in minio when starting the server?

It may not be possible - we cannot disable/enable features in that manner - these are becoming core functionalities of Minio @bermi it is unfortunate that you are trying to re-purpose AWS credentials for Minio. Since Minio is also an S3 alternative such a conflict that would exist.

When testing with Minio your application should use something simple, since you are using aws-sdk's you can chain the credentials? i.e start with static credentials and if they are not available them fallback to AssumeRole ones? 

This way it will work with Minio since those will be static credentials, and when testing against S3 they will be Assume Role credentials.

**Comment by bermi** [comment]
@harshavardhana We have some integration tests that spawn three different microservices. Each microservice uses multiple AWS services, S3 being one of them.  We intend to use minio to replace AWS S3 in our non-AWS datacenters (Alibaba in mainland China), so we started familiarizing with minio on our CI pipeline and for local testing.

Anyhow, it looks like we'll need to get creative in our code by selectively using minio-js or the aws-sdk.

I will be closing this issue for now and update it if I find a way around it.

Thank you for minio and for your help!
