### ISSUE TITLE
Transfer compression support

### ISSUE THREAD

**Issue by koliyo** [minio/minio#6880]
Is it possible to have a compressed object transfer between client and server?

I am not talking about the server side disk storage compression, but the network communication between the client and server.

Can I have json-files in my bucket and transfer these compressed without explicity storing them as compressed archives?

I see this https://github.com/minio/minio/pull/6292

But that is only serverside compression right?

**Comment by Praveenrajmani** [comment]
Hi @koliyo,

Ideally, compressing a compressed-object is less efficient, since it does not have efficient run-length-encoding (RLE) . So minio does not support compression ( if compression is enabled ) for such compressed objects.

Minio recognizes a compressed object from its extension/content-type. We can still cheat by not explicitly specifying the extension or by renaming `data.zip`  to `data.log` or modifying the content-type before upload. But that will not produce a better compression experience as explained above. 

One such way to upload a compressed object is by disabling compression.

And yes that is a server-side compression

please refer [https://docs.minio.io/docs/minio-compression-guide.html](url) for more

**Comment by koliyo** [comment]
Ok, I understand that we don't want to compress already compressed objects.

But I am still not sure if automated transferring compression is possible. Just setting `content_type` on `fput_object` will not automatically compress data, right?

So if I understand this correctly i need to manually compress the data on the client, then putting the compressed data with proper `content_type` setting.

And when I download the data I need to reverse the process and manually decompress the received data from `fget_object`.

Am I understanding this correctly? If so feel free to close the issue. 

**UPDATE**
I guess it is the `Content-Encoding` metadata header that is supposed to be used, not content_type?

**Comment by nitisht** [comment]
> So if I understand this correctly i need to manually compress the data on the client, then putting the compressed data with proper content_type setting.
And when I download the data I need to reverse the process and manually decompress the received data from fget_object.

This is correct @koliyo .

>  guess it is the Content-Encoding metadata header that is supposed to be used, not content_type?

Yes, `Content-Encoding` is right.
