### ISSUE TITLE
Duplicate uploads while copying large files, which halves the performance

### ISSUE THREAD

**Issue by gadgilsanjeev** [minio/minio#6890]
<I am copying a 25G file over into a bucket. At the back end, I see new files being generated in the /tmp and /multipart folder. If I run a du -sh on the folder, around 50G is taken by the end of it. Once the upload is done, the du -sh drops back to 25G, multipart and tmp folders go back to being empty and the file is present in the bucket I created>

## Expected Behavior
<What this does is that my disk writes become 2x, causing a halving of performance. and hence if I could have copied 50G in time t, only 25G is possible now.>

## Current Behavior
<as mentioned above>

## Possible Solution
<I am sure this is done with some thought in mind, but is there a toggle to turn this off?>

## Steps to Reproduce (for bugs)

1.  Make bucket
aws --endpoint-url http://192.168.31.11:9000 s3 mb s3://bucket1
   make_bucket: bucket1

aws --endpoint-url http://192.168.31.11:9000 s3 ls
   2018-11-28 17:26:11 bucket1

aws --endpoint-url http://192.168.31.11:9000 s3 cp ~/25Gfile s3://bucket1

On checking the minio server side, i see the following folders populated with additional data

.minio.sys/tmp
.minio.sys/multipart

Once the upload is done, both go back to empty, and the file is properly available at the required destination bucket
## Context
<trying to benchmark object store performance>

## Regression
<No>

## Your Environment

* Version used (`minio version`): 
Version: 2018-09-25T21:34:43Z
Release-Tag: RELEASE.2018-09-25T21-34-43Z
Commit-ID: aa4e2b1542b98097e08680f21b790de0b776378c
* Environment name and version (e.g. nginx 1.9.1):

* Server type and version:
Dual socket 2RU supermicro
* Operating System and version (`uname -a`):
CentOS Linux release 7.5.1804 (Core) 
3.10.0-862.el7.x86_64
* Link to your project:

**Comment by nitisht** [comment]
@gadgilsanjeev the upload happens only once to `/tmp` directory. Then object is simply moved to the bucket atomically. Only when the atomic operation is successful - we return 200/OK to client. This is to ensure that Minio is strictly consistent and we're able to recover without inconsistencies in case the upload fails. 

There is no upload performance cost - as the actual upload happens only once. Also, there is no way to turn this off.

**Comment by gadgilsanjeev** [comment]
What does the multipart folder do? Why does it get additional files during upload? 

I also see the disk writes happening twice. If I run iostat at the back end, I see 2x writes going to the disk.

**Comment by nitisht** [comment]
> What does the multipart folder do? Why does it get additional files during upload?

Since this is a big file, it may get uploaded in multiple parts (based on client in use). This is standard [S3 behaviour](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html) meant to ensure if there is a failure while uploading, you don't need to restart from beginning, you can instead resume from the last successfully uploaded part. 

Multipart directory holds these parts temporarily, until `CompleteMultipartUpload` is called by the client.

> I also see the disk writes happening twice. If I run iostat at the back end, I see 2x writes going to the disk.

Yes, once to the `/tmp` and then to the actual bucket.

**Comment by gadgilsanjeev** [comment]
Is this standard too? That every write is amplified twice?

Here is a screenshot showing the write amplification per second.


Minio client system:
Completed 6.2 GiB/24.4 GiB (140.5 MiB/s) with 1 file(s) remaining

Minio server system:
Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda           7666.00         0.00    490080.00          0     490080
sda           4736.00         0.00    303104.00          0     303104
sda           2242.00         0.00    139900.00          0     139900
sda           6237.00         0.00    396972.00          0     396972
sda           3292.00         4.00    210384.00          4     210384
sda           4608.00         0.00    294912.00          0     294912
sda           6802.00         0.00    435048.00          0     435048
sda             58.00         0.00       232.00          0        232
sda           4864.00         0.00    311296.00          0     311296

**Comment by nitisht** [comment]
> Is this standard too? That every write is amplified twice?

As I said before the data is first written to /tmp amd moved to the bucket once upload is complete.

**Comment by harshavardhana** [comment]
This is true only in case of FS mode, erasure coding mode doesn't write twice. 

In FS we need to do this because we cannot keep parts as is i.e we want a single contigous file. We concatenate in background preemptively as the parts come in.

Design principal of FS mode is to keep the namespace human readable, so in future, if Minio is to be uninstalled - you can start using the files on the backend disk as is without the requirement of specialized tools to handle it.

So what you found is correct there is twice the write during Multipart upload when using FS mode. Erasure coding has a custom backend format which doesn't incur this additional cost.

**Comment by harshavardhana** [comment]
Closing this as answered
