### ISSUE TITLE
Build errors on darwin with go1.12.beta1 due to vendored rjeczalik/notify lib

### ISSUE THREAD

**Issue by mirtchovski** [minio/minio#7039]
Similar to #6315, but this time with go 1.12. 

I have created an issue in the original project and will update this one once it is fixed there https://github.com/rjeczalik/notify/issues/169

**Comment by harshavardhana** [comment]
you should build with `go get -tags kqueue` @mirtchovski

**Comment by mirtchovski** [comment]
rjeczalik/notify#169 was closed as it has been fixed upstream, this means that minio may want to update its vendored dependency before 1.12 is out. 

@harshavardhana thanks, we will do that in our CI, but in general one would prefer the default target for 'go get' to work off the bat :)

**Comment by harshavardhana** [comment]
Yeah since we avoid cgo based deps, we never test with fsevents.

With go 1.11 you can also set 

```
GOFLAGS="-tags kqueue" go get github.com/minio/minio
```

**Comment by kannappanr** [comment]
@mirtchovski Looks like rjeczalik/notify#169 has been re-opened. We can either close this issue and re-open when rjeczalik/notify#169 is closed, or we can keep this issue blocked on  rjeczalik/notify#169 and you can let us know once it closed, then we can vendorize the latest version of ` rjeczalik/notify` library.

If that issue is going to be open for a while, then I prefer closing this issue and re-opening again.

**Comment by mirtchovski** [comment]
I'm fine with closing this issue until the other one is resolved. for now we're sidestepping it by building with the kqueue tag.

**Comment by kannappanr** [comment]
Closing this issue based on the above comment. Will vendorize the library in minio once rjeczalik/notify#169 is fixed.
