### ISSUE TITLE
Distributed storage one host multiple drives

### ISSUE THREAD

**Issue by kolyadin** [minio/minio#7061]
Hi folks,

I want to build private cloud storage on one host with multiple ceph drives.
So i don't need any data protection and i want to use every GB of drives to create distributed cloud storage with maximum capacity.

In docs, i see only one solution for multiple drives in one host and it's erasure strategy, which is required too much drives (in my situation) to protect failures.

Any ideas how to deal with it?

**Comment by kannappanr** [comment]
@kolyadin you can setup `Software Raid 0` and use it in `fs` mode.

**Comment by fwessels** [comment]
The alternative way would be to run multiple minio gateway in front of each of the drives (but you would have multiple ports).

Minio's erasure code always compute parity, you can use STORAGE_CLASS=RSS to limit the parity overhead to just two disks (instead of N/2). But you would still some overhead.

**Comment by kolyadin** [comment]
Thanks for your advices.
For now is good solution for me is using LVM over CEPH volumes because LVM is native to shrink/enlarge logical volumes in comparison to RAID 0.
