### ISSUE TITLE
[faq] file and directory cannot have the same name, why?

### ISSUE THREAD

**Issue by xuancong84** [minio/minio#7335]
There exists a fundamental design flaw in the file-path naming convention for the storage.
In Linux file system, a file and a directory cannot have the same name. However, for AWS S3 bucket and S3rver (another S3 bucket emulator), this is possible.

The following operation will work in AWS-S3 and S3rver but fail in Minio due to this issue:

```
import boto3
conn = boto3.client('s3', ...)
conn.create_bucket(Bucket='test-bucket')
conn.put_object(Bucket='test-bucket', Key='test-key', Body='test-body1')
conn.put_object(Bucket='test-bucket', Key='test-key/file1', Body='test-body2') # this will fail for Minio
```

The last line of code will fail for Minio because under the directory _test-bucket_, it has already created the file _test-key_ as a file to store the key _test-key_, thus, it can no longer create a folder with the same name _test-key_. S3rver has a more elegant solution by creating the folder _test-key_ and store Body in a rare-named hidden file. Maybe you can think of alternative ways to work around.

**Comment by harshavardhana** [comment]
This is not a design flaw, it is by design. Will explain in detail why we took this design decision.

**Comment by xuancong84** [comment]
I apologize for my harsh comments. But my use case does indeed make a point. I am using Beiwe platform for a study (https://github.com/onnela-lab/beiwe-backend/wiki). For small scale testing, we do not want to use AWS S3 bucket to save cost, Minio does not work, S3rver works like a charm.

I mean you can keep your design decision in the current way, but you have to make sure the code I posted above can run without generating any filesystem error because it works on AWS S3 bucket.

**Comment by harshavardhana** [comment]
@xuancong84 

Lets take an example of ListObjects with prefix dir1/ (where dir1/ is empty directory on object store) does not list on minio is because minio is using the file system hierarchy for storing objects whereas s3 uses a flat namespace. On s3, the prefix "dir1/" in entirety is itself just a key to the blob location, so s3 lists it as a result. From minio's perspective, ListObjects with "dir1/" as prefix is listing objects in the filesystem's dir1 directory, hence it returns nothing because the directory is empty.

We could, of course, any day make changes to our implementation to list empty directory as well when you query ListObjects with "dir1/" as prefix. We discourage creating empty directory as an object, because it would pose issues if you were to sync the data back to filesystem or to an object store other than s3 which doesn't support such semantics.

Let's say you want to store objects grouped by prefix "dir1" under a bucket, conceptually similar to storing files in a folder. s3 will allow creating an object with key "dir1/"(representing empty directory), "dir1" (representing a file in filesystem lingo), and also prefixed by dir1 such as "dir1/a/b" (similar to subdirectories). Look at the example listing below showing the actual object names and the result of aws cli command to sync the data in your bucket back to the file system.

aws cli silently fails to create a dir1/ object or the object named dir2 if dir2/ directory already exists.So storing objects to connote empty directory on s3 can actually pose consistency issues if you were to move the data out of s3. Instead, it is recommended to put objects into the object store with keys in the form "parent_dir/object" would automatically group objects by the prefix "parent_dir" without the overhead of an extra object to represent empty directory, and syncing issues. 

```
➜ mc ls --r s3/dir1
[2018-06-28 18:26:52 PDT]    24B dir1/
[2018-06-28 18:27:35 PDT]    24B dir1/issue
[2018-06-28 18:32:44 PDT]     0B dir2
[2018-06-28 18:32:04 PDT]     0B dir2/
[2018-06-28 18:28:09 PDT]    24B dir2/issue

➜  aws s3 sync s3://bucket1 /tmp/t
download failed: s3://bucket1/dir1/ to ../../../../../../../tmp/t/dir1/ [Errno 20] Not a directory
download failed: s3://bucket1/dir2 to ../../../../../../../tmp/t/dir2 [Errno 21] Is a directory
download: s3://bucket1/dir2/issue to ../../../../../../../tmp/t/dir2/issue
download: s3://bucket1/dir1/issue to ../../../../../../../tmp/t/dir1/issue
```

The problem if you see now you cannot copy files out of the storage, either you will lose the top level file or you will lose the objects inside the dir1 prefix.  Since the inception of Minio this is what we have followed strictly because adding features like above have serious consequences on data and it is non-standard unexpected behavior. If AWS tools itself cannot handle it - your application using this feature is creating trouble for your users in the future when they really want to use some tools to get the data out.

So if you see its not a design flaw, it is a carefully designed approach to avoid problems for our users in future and avoid vendor lock-in like features which AWS S3 already implements. It is in our interest to actively discourage these specialized features. 

We can provide better suggestions on how to avoid using these features so that your application is more portable in future.

**Comment by xuancong84** [comment]
Thank you very much @harshavardhana for your very detailed explanation! I really appreciate your effort!
I completely understand your design rationale, however, now I do need to:
```
conn.put_object(Bucket='test-bucket', Key='test-key', Body='test-body1')
conn.put_object(Bucket='test-bucket', Key='test-key/file1', Body='test-body2')
```
and
```
conn.put_object(Bucket='test-bucket', Key='test-key/file1', Body='test-body2')
conn.put_object(Bucket='test-bucket', Key='test-key', Body='test-body1')
```
But because of your design architecture, this does not work. What is even worse is that it causes Minio to stuck for several seconds before popping out the access-denied exception. Thus, I cannot use Minio on this project. Hopefully, I can still use Minio on other projects.
