### ISSUE TITLE
[Proposal] Improve/reduce volume of potentially conflictual dependencies 

### ISSUE THREAD

**Issue by ymartin59** [minio/minio#7639]
I am cross-compiling Minio for Synology and I find build process really really long and identify Minio collects multiple versions for same dependencies - here are just an exerpt I extracted from output:
```
go: finding google.golang.org/grpc v1.19.0
go: finding google.golang.org/grpc v1.19.1
go: finding google.golang.org/grpc v1.14.0
go: finding google.golang.org/grpc v1.17.0
go: finding google.golang.org/grpc v1.16.0
go: finding google.golang.org/grpc v1.18.0
go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: finding golang.org/x/net v0.0.0-20190424112056-4829fb13d2c6
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/net v0.0.0-20190324223953-e3b2ff56ed87
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
```

Even if resulting binary "works as expected", I guess we can consider following points:
- old versions may have security vulnerabilities
- binary may be lighter if only one version was included (and compilation would be faster)

Isn't there any way to improve project dependencies management to avoid so many duplicates?

**Comment by ymartin59** [comment]
Moreover, some dependencies are declared as "latest" which may prevent "reproduceable build" from a release/tag
```
go: finding github.com/modern-go/concurrent latest
go: finding github.com/hashicorp/hcl/hcl/ast latest
go: finding github.com/hashicorp/hcl/hcl latest
```

**Comment by harshavardhana** [comment]
> Moreover, some dependencies are declared as "latest" which may prevent "reproduceable build" from a release/tag

Those are upstream issues @ymartin59 which needs to be addressed by upstream libraries. We have no control over them. We do not directly depend on them - these are some of the shortcomings of go module system.

> Isn't there any way to improve project dependencies management to avoid so many duplicates?

This is up to `go mod` to avoid these duplicates, we do not manually add them ourselves. `go mod tidy` should simply fix them appropriately but most part it doesn't because the sub dependent packages have not moved to fully `go mod` style dependencies or have some other cross-dependencies on them.

It will be a while before all of this is sorted out since `go mod` is a fairly new introduction. If you think it can be fixed we are happy to accept PRs AFAIK even with multiple deps mentioned `go mod` only uses the right version in `go.mod`

**Comment by harshavardhana** [comment]
Also what you are assuming is incorrect it is `go.mod` which defines the right dependencies for MinIO included in the build whereas the other versions are mentioned in `go.sum` which are perhaps needed for dependent libraries.  

So thinking that MinIO will link to older is actually not correct and go build will ensure that `go.mod` is honored above all for MinIO

**Comment by kannappanr** [comment]
@ymartin59 closing this based on the above comment. please feel free to re-open the issue if you feel otherwise.

**Comment by ymartin59** [comment]
Thanks for answer and details. I would say it confirms my opinion Go is still not mature enough...
