### ISSUE TITLE
Letsencrypt ecc key doesn't work with MinIO

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#7698]
OK, so I just wasted a couple of days trying to get a Let's Encrypt ECC key generated using acme.sh to work with Minio, but I kept getting the message "ERROR Unable to load the TLS configuration: The private key contains additional data. Please check your certificate.".

Turns out that for some reason I need to translate the private key by adapting the latter part of the call described above, i.e. if I call "openssl -in .acme.sh/domain/private.key -out .minio/certs/private.key" it'll work.

Now, is there any logic behind the fact that I can use a 4096 bit RSA key straight off, but I need to do some kind of translation in order to use a prime256v1 ECC key? What am I missing here...?

_Originally posted by @mhjartstrom in https://github.com/minio/minio/pull/5245#issuecomment-496303478_

**Comment by harshavardhana** [comment]
@mhjartstrom please add other details like the command used to generate the keys, operating system, MinIO release being used etc.

**Comment by mhjartstrom** [comment]
For reference, I initially created https://github.com/Neilpang/acme.sh/issues/2295 regarding this problem.

I'm setting up a MinIO server (currently on Windows 7) for hosting backups created by CloudBerry. CloudBerry is also running on a Windows 7 machine (with .NET Framework 4.8 for updated Schannel TLS support) and it seems that I cannot (?) bypass the fact that it requires an ECDSA certificate for setting up TLS communication (on Windows 7). I tried using Nartac Software "IIS Crypto 3.0" for setting up "Best Practices" to see if that'd enable using RSA, but that doesn't seem to work. Please help me out if that ought to work...?

The MinIO server is secured by a Let's Encrypt certificate generated with the help of https://github.com/Neilpang/acme.sh. I call the Bash script with some parameters, of which --keylength is probably of most importance here, and let it install the certificates in .minio/certs/. Then I launch the stand-alone Windows executable version of MinIO, typically:
`minio.exe server --address :9000 --certs-dir ".minio\certs" --config-dir ".minio" "C:\MinIO"`

When I issue a new certificate using `acme.sh <params> --keylength 4096` it'll create a 4096 bit RSA Let's Encrypt certificate that'll work perfectly with MinIO (rated class A on https://www.ssllabs.com/ssltest/), but as I previously stated I'm forced to use an ECC certificate in order for CloudBerry to be able to connect to it while running on Windows 7. So I would prefer to use EC-521, but that's not supported by Let's Encrypt yet. And EC-384 isn't supported by MinIO (yet?)... Instead I have to use `--keylength ec-256` (or `--keylength prime256v1`, same thing...).

My problem is that the certificate generated using this method is not compatible with MinIO, I get the error message mentioned in the initial comment pasted by @harshavardhana above. But if I use the very same ECC private key that I get from acme.sh and use the following command (please note that the command copied by @harshavardhana above was "misspelled") it'll work:
`openssl ec -in .acme.sh/<domain>/<domain>.key -out .minio/certs/private.key`

I'm sorry for commenting an old issue instead of creating a new one, but I found the comment by @aead in #5245 and since that was also included in the documentation I figured I'd try to mess around with "openssl ec" and see what it did.

I was happy to find that the above call worked, but I haven't found a valid explanantion for why this "translation" is required? That's why I'm asking you; why doesn't this work straight off?

**Comment by aead** [comment]
Hi @mhjartstrom - thanks for opening this issue.
> So I would prefer to use EC-521, but that's not supported by Let's Encrypt yet. And EC-384 isn't supported by MinIO (yet?)... Instead I have to use --keylength ec-256 (or --keylength prime256v1, same thing...).

The problem here is that the go standard lib only provides constant time implementations for P-224 and P-256 but not for P-384 and P-521. Also note that it only supports the NIST curves mentioned [here](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf) for ECDSA.
So given that, using P-256 curve is better (and sufficient) than using e.g. P-521.

>I was happy to find that the above call worked, but I haven't found a valid explanantion for why this "translation" is required? That's why I'm asking you; why doesn't this work straight off?

The reason is that the TLS parsing logic does not handle all types of keys. We have actually a PR that fixes this as a side-effect. See: https://github.com/minio/minio/pull/7139/files#diff-1094222d3259d85ad53cc70f8bcc0816R221

I'm sorry that you had to time to get your setup to work.

**Comment by mhjartstrom** [comment]
Do you think P-384 and/or P-521 will be implemented in the go standard lib in the future?

OK, so is that pull request about to be accepted or what is the status of that?

**Comment by aead** [comment]
> Do you think P-384 and/or P-521 will be implemented in the go standard lib in the future?

There are implementations, but they use generic, non-constant-time implementations. I suspect that the Go security team won't introduce assembler code for those curves without very good reason (maintainability). Also observe that (IIRC) for the key exchange (ECDHE) the TLS stack uses Curve25519 (X25519) by default - which is a curve over the prime field determined by `2^255 - 19` - and therefore achieves 128 bit security anyway. Regardless whether the signature scheme (ECDSA) uses P-256, P-384 or P-512 (or another curve that claims >= 128 bit security). Therefore, there is no/very little benefit in using e.g. P-384 or P-521. 
Also, if you achieve 128 bit security (the best an adversary can do is to mount an attack that requires `2^128 * some_operation`) there will be no real-world adversary in the foreseeable future / ever.

 > OK, so is that pull request about to be accepted or what is the status of that?

I'm working on that. Got deferred b/c of priories. However, maybe I can break it in parts and refactor / fix the parsing issues separate from the `auto-tls` feature...

**Comment by mhjartstrom** [comment]
Breaking out and refactoring the ECC certificate parse routines sound like a good idea to me!

BTW, do you happen to know if there is any way to configure Windows 7 and TLS cipher suites available with Schannel, for instance like I tried with Nartac Software "IIS Crypto 3.0"? I thought that'd allow Windows 7 to use something other than ECDSA, but it appears as if that did not work as I had hoped.

**Comment by aead** [comment]
> BTW, do you happen to know if there is any way to configure Windows 7 and TLS cipher suites available with Schannel, for instance like I tried with Nartac Software "IIS Crypto 3.0"? I thought that'd allow Windows 7 to use something other than ECDSA, but it appears as if that did not work as I had hoped.

AFAIK Win7 supports e.g. `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256`
This a cipher suite supported by the MinIO server. The problem with the RSA cipher suites is that they either do not preserve (perfect) forward security or us CBC. The issue with CBC is that the Go TLS stack (and many other TLS stacks) don't even try to mitigate all types of side-channels. Therefore, CBC ciphers are also disabled.

So you would need a cipher suite that provides PFS (i.e. ECDHE) and an AEAD cipher (i.e. AES-GCM or ChaCha20-Poly1305). Therefore, AFAICS you would need a ECDSA suite on Win7...

**Comment by candlerb** [comment]
FYI, when using [dehydrated](https://github.com/dehydrated-io/dehydrated) to fetch the certificate, the config `KEY_ALGO=prime256v1` fixes this.
