### ISSUE TITLE
Are files pushed to MiniIO stored as it is and not as chunks?

### ISSUE THREAD

**Issue by mygithub-praveen** [minio/minio#7700]
I pushed 5 lakh images (200+ GB) in to a bucket of Ubuntu distributed MinIO with 4 servers, which has 4x8TB HDD. I noticed that after this the MinIO web is taking too much time to load. All images are stored in a folder named with bucket name, Is this the default MinIO storage mechanism?

**Comment by harshavardhana** [comment]
@mygithub-praveen can you please join our https://slack.min.io for your questions - we can have a more real-time conversation? 

Storing images at the top level is not a good idea, it is better to store them in a hierarchy. So you have to choose them appropriately while uploading. 

Now getting back to the issue itself,  to help you further you need to state more clearly your setup and what you are testing. This issue is currently incomplete and we have no clue whatsoever what you are trying to achieve. 

Here are the basic details required

- MinIO server version? 
- What operating system?
- What is your backend filesystem?
- What are the type of objects uploaded, what is the average size of each object?
- What is the program used? if it's a custom code, please provide us a sample of this code?

**Comment by mygithub-praveen** [comment]
- minio-3.0.7
- Ubuntu 18.04
- ext4
- jpeg images (3.5 MB)
- Python 3.4 
`import traceback
import os
import time

from minio import Minio
from minio.error import (ResponseError, BucketAlreadyOwnedByYou, BucketAlreadyExists)
minio_client = Minio('localhost:9000', access_key='', secret_key='', secure=False)
if minio_client.bucket_exists('image1'):
        print("bucket existing....")
else:
        print("No such bucket found...")

while True:
        files = []
        path = "/home/minio/img/"
        for r, d, f in os.walk(path):
                for file in f:
                        files.append(file)
        for f in files:
                name = "{0}".format(time.time())
                name = name.replace(".","AXDF")
                try:
                        minio_client.fput_object('image1', name, "{0}{1}".format(path, file))
                        print(name)
                except ResponseError as err:
                        print(err)`

**Comment by harshavardhana** [comment]
what is the MinIO server version @mygithub-praveen ? I see that you shared the client SDK version.

**Comment by mygithub-praveen** [comment]
VERSION
2019-05-23T00:29:34Z
MEMORY
Used: 6.2 MB | Allocated: 42 MB | Used-Heap: 6.2 MB | Allocated-Heap: 66 MB
PLATFORM
Host: localhost | OS: linux | Arch: amd64
RUNTIME
Version: go1.12.4 | CPUs: 4

**Comment by kannappanr** [comment]
@mygithub-praveen How much time does it take to load on the browser UI? Also, how much time does it take to list the objects under the same bucket using `mc`?

**Comment by nitisht** [comment]
closing this for now @mygithub-praveen due to no response. Feel free to join us on Slack or reopen this when you have more info.
