### ISSUE TITLE
[gateway-s3] Gateway to S3 using permission without ListBucket and HeadBucket permission

### ISSUE THREAD

**Issue by shernshiou** [minio/minio#7709]
**Is your feature request related to a problem? Please describe.**
I try to gateway to S3 but the IAM inside my EC2 does not have ListBucket or HeadBucket permission. It causes a timeout and `minio gateway s3` spews out the following error:
```
ERROR Unable to initialize gateway backend: Get https://s3.amazonaws.com/probe-bucket-sign-randomstring/?location=: dial tcp **REDACTED_IP**:443: i/o timeout
```

**Describe the solution you'd like**
I hope there is a feature that let minio to gateway to specific bucket. Or maybe bypass the HeadBucket at `/cmd/gateway/s3/gateway-s3.go`

**Comment by harshavardhana** [comment]
> ```
> ERROR Unable to initialize gateway backend: Get https://s3.amazonaws.com/probe-bucket-sign-randomstring/?location=: dial tcp **REDACTED_IP**:443: i/o timeout
> ```

This looks like you have a network timeout @shernshiou

**Comment by thefiddler** [comment]
(I am working with @shernshiou on this issue)

@harshavardhana the timeout is happening precisely because ListBucket and HeadBucket permissions are not available in the IAM role:
```bash
$ aws s3api list-buckets

Connect timeout on endpoint URL: "https://s3.amazonaws.com"
```

The IAM role has GetObject, PutObject and ListObjects. Ideally it should be possible to use minio with a specific bucket (with a known ARN), even if the IAM is locked down to not be able to list all buckets for security reasons.

**Comment by harshavardhana** [comment]
That doesn't seem right @thefiddler timeout means a network issue if you don't have permission we should get 403 Access Denied error.

**Comment by thefiddler** [comment]
@harshavardhana we are working in a highly-constrained 3rd party environment on Amazon AWS. In this environment, disallowed calls fail either with AccessDenied or a Timeout error. List-buckets happens to fail with a Timeout error.

The network is otherwise working correctly and we have verified that put-object, get-object and list-objects work as expected.

What we are trying to do is the following:
1. We have read/write to a single, known S3 bucket (we cannot access any other bucket for security reasons).
2. We wish to use minio (gateway + sdk) to read/write to that S3 bucket and only that S3 bucket (i.e. without using list-buckets).

So far we haven't managed to figure out how to setup minio correctly in this configuration, because it fails trying to call list-buckets, which is not supported in this environment. Since we know exactly which bucket to use, is there a way to configure minio to use that bucket without trying to list or access any other bucket?

**Comment by vadmeste** [comment]
@thefiddler, I think you are wrong with disabling s3:ListBucket in the first place, you probably want to disable s3:ListAllMyBuckets

s3:ListBucket is needed to list objects in a bucket

**Comment by thefiddler** [comment]
@vadmeste you are right, we can list objects in that specific bucket, but we cannot list buckets, i.e. we have s3:ListBucket but not s3:ListAllMyBuckets.

Is there a way to point minio gateway to a specific known bucket and avoid s3:ListAllMyBuckets?

**Comment by vadmeste** [comment]
@thefiddler are you saying that you have  s3:ListBucket enabled but you still have the i/o timeout error ?

**Comment by thefiddler** [comment]
```bash
$ minio gateway s3
ERROR Unable to initialize gateway backend: Get https://s3.amazonaws.com/probe-bucket-sign-.../?location=: dial tcp **IP REDACTED**:443 i/o timeout
```

Trying something similar to what was mentioned at https://github.com/minio/minio/issues/7696#issuecomment-496947701 gives:
```bash
$ minio gateway s3 https://[bucket name].s3.eu-west-1.amazonaws.com
ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'

$ MINIO_REGION=eu-west-1 _MINIO_REGION=eu-west-1 minio gateway s3 https://[bucket name].s3.eu-west-1.amazonaws.com
ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
```

If I try with the (incorrect) region us-east-1 as a test:
```bash
$ minio gateway s3 https://[bucket name].s3.us-east-1.amazonaws.com
ERROR Unable to initialize gateway backend: Get https://[bucket name].s3.us-east-1.s3.amazonaws.com/probe-bucket-sign-.../?location=: dial tcp **IP REDACTED**:443 i/o timeout
```

Edit:
Using `mc config host add` gives the same issues as above.

Edit 2:
@vadmeste regarding your permissions question:
```bash
$ aws s3api list-objects --bucket [bucket name]
# json list of objects returned as expected, i.e. we have s3:ListBucket permission

$ aws s3api list-buckets
# timeout, i.e. we don't have s3:ListAllMyBuckets permission
```

**Comment by vadmeste** [comment]
@thefiddler, can you double check that you have s3:ListBucket permitted for that specific user ? no reason for it to fails

**Comment by thefiddler** [comment]
@vadmeste regarding your permissions question (copying pasting from my edit above):
```bash
$ aws s3api list-objects --bucket [bucket name]
# json list of objects returned as expected, i.e. we have s3:ListBucket permission

$ aws s3api list-buckets
# timeout, i.e. we don't have s3:ListAllMyBuckets permission
```

Edit:
What is the right way to use minio gateway in bucket mode, as suggested by @harshavardhana here https://github.com/minio/minio/issues/7696#issuecomment-496282459?

The following doesn't seem to be working:
```bash
$ minio gateway s3 https://[bucket name].s3.eu-west-1.amazonaws.com
ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
```

**Comment by vadmeste** [comment]
@thefiddler can you also enable s3:GetBucketLocation for now, this is also seem needed

**Comment by thefiddler** [comment]
@vadmeste unfortunately this is a 3rd-party environment where we cannot enable/disable permissions. Is there any possible workaround?

I will request s3:GetBucketLocation to be enabled, but this request may or may not be granted.

**Comment by shernshiou** [comment]
Closing this issue. Reducing the scope of this problem by looking for another workaround: https://github.com/minio/minio/issues/7737
