### ISSUE TITLE
MinIO Concurrency Test - Upload of multiple large files at the same time failing in reduced storage space

### ISSUE THREAD

**Issue by hmarsolla** [minio/minio#7714]
This issue might not be exactly a bug. I want to understand more about the MinIO behavior I had while making some stress/concurrency tests before deploying to production. Maybe there's some setup options I missed or some tuning that must be done or even someone who had experienced something similar and can share some knowledge.

## Context
My team is developing a service that utilizes MinIO as its means of storage.
I am responsible for deploying MinIO on our servers and also develop the Node.js API that communicates with it.

The API works by piping the readstream of the upload to the containerized MinIO server, essentially being a bridge between the frontend and the storage, without saving anything on the backend file system. This streaming technique seemed to work fine and I started making tests as we expect that large files might be uploaded concurrently on our service.

## Behavior
On an homolog server, with very limited disk capacity (40GB of Free Space), I tried to send seven ~4GB files concurrently. Theoretically, I could still send almost 30GB of data, but the API received an error: **read ECONNRESET** (**connection reset by peer** on the clientside).

I tested in different ways, trying to change some code on the API, and I got a different error eventually: **S3Error: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed.**

That was a hint and I started to watch the /data folder to see how  MinIO was receiving the files. As I could understand, MinIO saves each file part inside the multipart folder in blocks of ~526MB, and merging a copy of them inside /tmp folder on a single file. When the file is complete, /multipart and /tmp are cleaned and the whole file is sent to the bucket folder.

## Conclusion of the tests
I cleaned the disk and, with more free space, I could send concurrently all of the files without any problem. Essentially it seems I need double the file size I'll be receiving concurrently as free space to be able to save the files sucessfully.

## Questions
1 - Can I change or tune anything on the server (host or docker container) to make this concurrent upload better? I am currently following the network configuration suggested [here](https://github.com/minio/minio/tree/master/docs/deployment/kernel-tuning).
2 -  Is there any way to avoid the ECONNRESET error? They seem related to the OS dropping connections because they would not be able to complete, but I'm not so sure exactly of why I got them.
3 - Should I always keep "double the expected concurrent upload size" of free space to guarantee that uploads work properly?
4 - Could there be a way that MinIO rejects an upload by checking available space, including /multipart and /tmp storages that would be used?

## Your Environment
* Minio Version used: minio/minio and minio/minio:edge docker images
* Deployed as a service inside a Docker Swarm
* Host OS Version: Linux Ubuntu 16.04.3 LTS Xenial

**Comment by kannappanr** [comment]
@hmarsolla Here is the response
1 - Can I change or tune anything on the server (host or docker container) to make this concurrent upload better? I am currently following the network configuration suggested here.
`No`
2 - Is there any way to avoid the ECONNRESET error? They seem related to the OS dropping connections because they would not be able to complete, but I'm not so sure exactly of why I got them.
`we don't send ECONNRESET, it must be networking related issue in docker swarm
can you try to reproduce the issue without docker?`
3 - Should I always keep "double the expected concurrent upload size" of free space to guarantee that uploads work properly?
`Yes and just a little more for metadata`
4 - Could there be a way that MinIO rejects an upload by checking available space, including /multipart and /tmp storages that would be used?
`No, it cannot, as the user can choose to not use all the multiparts uploaded. The user can just choose certain parts.`

**Comment by hmarsolla** [comment]
Hi @kannappanr, thanks for your reply.

As suggested out on the second question's response, I tested on the same environment using MinIO server without Docker. The results were the same: as soon as the disk hit 100%, the API started to received ECONNRESET error. I believe that is possibly related to the way **_minio.js_** behaves when the OS decides to drop connections because they could not complete. I'm not really sure why I don't always receive the S3 Error - Disk Full.

Anyway, I'll keep in mind the best setup conditions that I've been learning both with my tests and with your reply to use in my production environment.
