### ISSUE TITLE
SSE-KMS support for S3 gateway

### ISSUE THREAD

**Issue by thefiddler** [minio/minio#7753]
**Is your feature request related to a problem? Please describe.**
According to https://github.com/minio/minio/issues/7636#issuecomment-491521065 SSE-KMS is currently not supported for the S3 gateway. This is a blocking issue in one of our deployments.

**Describe the solution you'd like**
We would like to sponsor the development of this feature, either as a monetary or development contribution. For the latter, we would need some guidance about the design of the implementation. In either case, we would like to understand a bit better the amount of effort involved.

**Describe alternatives you've considered**
We have not been able to find a satisfactory workaround as of yet.

**Comment by shernshiou** [comment]
:+1:

**Comment by kannappanr** [comment]
@thefiddler Will check internally and get back to you.

**Comment by aead** [comment]
> We have not been able to find a satisfactory workaround as of yet.

@thefiddler Hi, can you describe why e.g. SSE-S3 does not work for you? I would be really interested in an S3 use case that *requires* SSE-KMS and cannot be implemented with SSE-S3.

**Comment by shernshiou** [comment]
@aead we faced a situation where we need to deploy minio as a gateway to an S3 that is configured to be using only SSE-KMS. It is purely architecture design provided by vendor, we are not sure what is the use case.

**Comment by aead** [comment]
@shernshiou See [this](https://aws.amazon.com/blogs/security/how-to-prevent-uploads-of-unencrypted-objects-to-amazon-s3/) AWS S3 doc. Adding a policy entry ` "s3:x-amz-server-side-encryption": "AES256"` would solve that problem.  

### Background information

I've objections to add `SSE-KMS` support since it adds quite some (configuration) complexity - in particular it requires sync. between the MinIO server/gateway, the clients and the KMS. Further, we would need to add an AWS-KMS integration as well. On the other side, there is no use case (AFAIK) that cannot be implemented with SSE-S3. Furthermore, using SSE-S3 instead of SSE-KMS is much simpler for the clients and simplifies configuration for the gateway/KMS operator.

**Comment by kannappanr** [comment]
ping @shernshiou Please let us know if you think this issue can be closed?

**Comment by shernshiou** [comment]
@kannappanr I will get back to you after my discussion with @thefiddler

**Comment by aead** [comment]
@shernshiou You can also ping me in our [slack channel](https://slack.min.io/) and we discuss your use case in detail (more privately).

**Comment by aead** [comment]
So, we will relax the SSE-KMS restriction in S3 Gateway mode. The Gateway will not reject the SSE-KMS but forward it to AWS S3 (and respond with whatever AWS S3 returns).

**Comment by shernshiou** [comment]
Thanks. I will try it out once it is ready.
