### ISSUE TITLE
MongoDB backend for users

### ISSUE THREAD

**Issue by hongkongkiwi** [minio/minio#7810]
Hi there,

I would like to store Minio Users & Access Control in a MongoDB. This makes it super simple to implement Minio as part of another more complex system.

Is there plans for supporting external authorisation mechanisms in future? I guess everybody has different requirements here, so a plugin architecture for backend credential storage would be awesome.

I could imagine some people want their users stored in flat files, some people would like in mysql, postgres or mongo and some might want to pass it off to an external REST api or script or ldap.

**Comment by kannappanr** [comment]
@hongkongkiwi Thanks for the request. We will talk internally and get back to you.

**Comment by hongkongkiwi** [comment]
Awesome! Excited to hear back.

**Comment by harshavardhana** [comment]
This was decided that we won't do instead we will be re-purposing MinIO backend as etcd replacement to store our users, DNS service records etc. 

Closing this issue as won't fix.

**Comment by chilicat** [comment]
Hallo. I Just wanted to ask if it is still planned to use the MinIO backend as etcd replacement?

I see when I start minio:

```
./minio  gateway nas $(pwd)/tmp
...
Attempting encryption of all config, IAM users and policies on MinIO backend
...
```
but I cannot create a user:
`
./mc admin user add minio myuser mypasswor123
mc: <ERROR> Cannot add new user. This 'admin' API is not supported by server in 'mode-gateway-nas'.
`


Minio ad MC build from master branch

**Comment by harshavardhana** [comment]
> but I cannot create a user:
> `./mc admin user add minio myuser mypasswor123 mc: <ERROR> Cannot add new user. This 'admin' API is not supported by server in 'mode-gateway-nas'.`
> 
> Minio ad MC build from master branch

NAS gateway requires etcd for multi-user support @chilicat

**Comment by chilicat** [comment]
@hackintoshrao I was hoping there is also another backend option. For our deployments would also be Mongo the best option since we have already a couple of deployments for it.

Of course, it would be possible to use the Etcd from Kubernetes but that, in my opinion, mixes the infrastructure with application/deployment too much.

From what I see it is also not possible to define the "root key" for Etcd? That would, for example, make it possible to use one Etcd cluster for multiple Minio deployments - or is that already possible?
