### ISSUE TITLE
[Gateway] b2: Failed to initialize gateway with error x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by LittlegrassSky** [minio/minio#7862]
## Expected Behavior
List all buckets of Backblaze cloud storage from Minio browser

## Current Behavior
When the command `minio gateway b2` executed, the following error message shown:
7[41m[37m[1mERROR[0m[0m[0m 8[6C[31mUnable to initialize gateway backend: [1mb2 error: x509: certificate signed by unknown authority.[0m[0m

## Possible Solution
No solution has been founded yet.

I have tried to place the Blackblaze wildcard SSL certificate (*.blackblazeb2.com) under the path .minio/certs/CAs, but the issue is still persisted.

## Steps to Reproduce (for bugs)
1. SET MINIO_ACCESS_KEY=xxxxx
2. SET MINIO_SECRET_KEY=xxxxx
3. minio gateway b2

## Context
I just need to start a gateway to Backblaze storage,

## Regression
No

## Your Environment

* Version used (`minio version`): 2019-06-27T21:13:50Z
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: N/A
* Operating System and version (`uname -a`): Window Server 2016 Standard Version 1607
* Link to your project: N/A

**Comment by kannappanr** [comment]
@Littlegrass98 We will take a look at the issue and get back to you.

**Comment by aead** [comment]
Hi @Littlegrass98 the error indicates the the gateway is trying to talk to the endpoint but cannot establish a connection since the endpoint presents a X509 TLS certificate that cannot be verified using any of CA certificates in the gateway's trust store (`minio/certs/CAs`, OS trust store, ...).

To solve that we need to know the endpoint URL (it should be `https://api.backblazeb2.com/`) and see what certificate is delivered by this endpoint (It should be issued by `Go Daddy Secure Certificate Authority - G2` with the SHA-256 fingerprint `5B:47:4F:1E:07:FC:F3:80:EB:97:32:1C:80:3E:19:63:1C:CF:07:4C:71:C9:E5:24:CD:F1:3F:E5:FF:BE:76:B3`)

If this (or a parent) CA certificate is not in your "list" of trusted CAs (e.g. you have removed / disabled the system certificates) than you need to put that certificate into the minio config directory under `certs/CA/`.

**Comment by LittlegrassSky** [comment]
Hi @aead , your solution works and many thanks to your quick response!

Just a summary of the solution:

1. Export the SSL certificate of `https://api.backblazeb2.com/` by `openssl s_client -showcerts -connect api.backblazeb2.com:443 > b2.crt`
2. Place the CA certificate under the path `.minio/certs/CAs`
3. Problem Solved!
