### ISSUE TITLE
MinIO Browser - Create Folder

### ISSUE THREAD

**Issue by tinohager** [minio/minio#7883]
If a folder not already exists, it is not possible over the `MinIO Browser` to create one.
I think one problem is on `MinIO` it is not possible to have a empty folder.

![image](https://user-images.githubusercontent.com/8215186/60706842-a2b87e00-9f0a-11e9-9240-2a7fb4ab3f3c.png) Add a button to create a new folder or allow on upload to set a destination.
 
![image](https://user-images.githubusercontent.com/8215186/60706728-65ec8700-9f0a-11e9-8e84-163248557ff5.png) Amazon have this option in the S3 Web Browser

**Comment by kannappanr** [comment]
@tinohager Thanks for your suggestion. Will check internally and get back to you on this.

**Comment by kaankabalak** [comment]
Upon further discussion, due to the object browser nature of MinIO Browser, we have decided to make the directory path located on the header editable so that the users can navigate to their desired locations. We will keep you updated with further details in the future, please feel free to ask any questions.

<img width="1280" alt="Screen Shot 2019-07-08 at 10 57 47 AM" src="https://user-images.githubusercontent.com/27314853/60832534-fb895000-a170-11e9-8482-d9b20e5cf185.png">

**Comment by deekoder** [comment]
thanks @nitisht & @kaankabalak I am swapping assignees.

**Comment by akshayuppal3** [comment]
I think now we have to type in the URL and then the folder is created automatically in minio. It doesn't seem to be editable anymore.

![image](https://user-images.githubusercontent.com/25509837/90574620-09d0da80-e17f-11ea-8380-f54892528369.png)


`
VERSION
2018-02-09T22:40:05Z
MEMORY
Used: 4.5 MB | Allocated: 11 GB | Used-Heap: 4.5 MB | Allocated-Heap: 27 MB
PLATFORM
Host: minio-6b67f98977-2rdxx | OS: linux | Arch: amd64
RUNTIME
Version: go1.9.4 | CPUs: 64
`

**Comment by harshavardhana** [comment]
> `VERSION 2018-02-09T22:40:05Z MEMORY Used: 4.5 MB | Allocated: 11 GB | Used-Heap: 4.5 MB | Allocated-Heap: 27 MB PLATFORM Host: minio-6b67f98977-2rdxx | OS: linux | Arch: amd64 RUNTIME Version: go1.9.4 | CPUs: 64`

Your version is like 2yrs old @akshayuppal3 please upgrade to 2020
