### ISSUE TITLE
Bucket Objects stored in one folder in filesystem

### ISSUE THREAD

**Issue by vanzhiganov** [minio/minio#7889]
Hello,

I see on my server that all files in a bucket stored in one folder on filesystem, this is bad for production environment.
It is big performance problem with big number of object in bucket.

```
root@minio:~# tree /usr/local/share/minio
/usr/local/share/minio
└── example
    ├── IPMIView_2.15.0_build.190109_bundleJRE_Linux_x64.tar.gz
    ├── mysql-workbench-community-8.0.16-1.fc30.x86_64.rpm
    └── Wikipedia_GNU_General_Public_License.eps
```

For solve this problem you can see how Squid store the cache.

**Comment by harshavardhana** [comment]
This is application requirement, you need to store the heirarchy in the right format and not dump objects at top level.

The reason we store in this fashion is a feature, because to expose your existing files as objects on your existing filesystems.

**Comment by vanzhiganov** [comment]
This is a big problem for minio. =(

**Comment by vanzhiganov** [comment]
This solution not production ready for large systems, because with large number files linux server may catch problems with a lack of inodes.

**Comment by harshavardhana** [comment]
I disagree @vanzhiganov we deploy in multiples of petabytes already. Linux filesystems have scaled really well since many years now.

Calling this not production ready is not only incorrect, also shows that there is lack of testing here and are based on anecdotal observations, either historical or are factually incorrect.

Please do join our https://slack.min.io we would love to help change your opinion, with real world deployment examples.

**Comment by vanzhiganov** [comment]
In my test case, on my server located ~1Tb of 5 Kb-2Mb files. And I have two problems: inodes and performance. Because my application does not provide any nesting in the file system structure.
