### ISSUE TITLE
Delay in policy visibility causing user add error "The canned policy does not exist"

### ISSUE THREAD

**Issue by ghost** [minio/minio#7988]
When creating a new user on a minio distributed cluster (without etcd) we perform to steps:

mc admin policy add
mc admin user add

However if we perform the two steps too quickly after each other <60 we get the following error:

<ERROR> Cannot set user policy for new user. The canned policy does not exist.

After waiting a period of time and re-running the "mc admin user add" command we get the following

Added user `username` successfully.

## Expected Behavior

Either there is an unexpected delay or the first "mc admin policy add " should not complete until it is fully sync'd?

## Current Behavior

see above

see above
## Steps to Reproduce (for bugs)

do the following right after each other in a cluster (we're using 4 machines no etcd)

1. mc admin policy add ///add///other///bits
2.mc admin user add ///add///other///bits
3.
4.

## Context

stops us from scripting the command unless we add a "wait" command

## Your Environment

* Version used (`minio version`): 2019-07-24T02:02:23Z
* Environment name and version (e.g. nginx 1.9.1): n/a
* Server type and version: 4x i9/32GB/8TB
* Operating System and version (`uname -a`):4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by kannappanr** [comment]
@hassbabaie Will take a look and get back to you.

**Comment by harshavardhana** [comment]
I think this is already fixed @donatello ??

**Comment by harshavardhana** [comment]
@hassbabaie can you upgrade to latest release and let us know if this is fixed..

**Comment by vsfalexanderpilch** [comment]
I'm encountering the same issue with policies and users on windows in version 2019-08-21T19:40:07Z as well. I'm running some batch scripts in order to create users, groups, policies and buckets automatically. They're basically deleting the existing resources first and then recreate them. Those issues do only appear during the 1st run, when the objects don't exist. As soon as they've been created once, the scripts run fine. 

It's also getting worse in docker swarm, if you're accessing minio via some lb/haproxy as the replication is taking longer. So when you create a policy and add users after that (via lb public url), some nodes might not even have received the latest policies when they receive the add users call. The http requests do endup on random nodes in thos case. There seems to be some race condition in there. 

Here're the errors, when the policy/user is removed before it has been created yet:

API: RemoveCannedPolicy()
Time: 12:40:57 CEST 08/28/2019
DeploymentID: 323e4bf8-8f67-4963-9747-198c2b4cf9ad
RequestID: 15BF101055F15CD0
RemoteHost: 127.0.0.1
Host: localhost:8080
UserAgent: MinIO (windows; amd64) madmin-go/0.0.1 mc/2019-08-21T19:59:10Z
Error: [31m[1mconfig file not found[0m[0m
       5: cmd\api-errors.go:1694:cmd.toAPIErrorCode()
       4: cmd\admin-handlers.go:999:cmd.toAdminAPIErrCode()
       3: cmd\admin-handlers.go:1004:cmd.toAdminAPIErr()
       2: cmd\admin-handlers.go:1361:cmd.adminAPIHandlers.RemoveCannedPolicy()
       1: net\http\server.go:1995:http.HandlerFunc.ServeHTTP()
       
API: RemoveUser()
Time: 12:47:16 CEST 08/28/2019
DeploymentID: e9d91469-1bda-4152-baf2-e9667972c2d9
RequestID: 15BF1068833AF20C
RemoteHost: 127.0.0.1
Host: localhost:8080
UserAgent: MinIO (windows; amd64) madmin-go/0.0.1 mc/2019-08-21T19:59:10Z
Error: [31m[1mconfig file not found[0m[0m
       5: cmd\api-errors.go:1694:cmd.toAPIErrorCode()
       4: cmd\admin-handlers.go:999:cmd.toAdminAPIErrCode()
       3: cmd\admin-handlers.go:1004:cmd.toAdminAPIErr()
       2: cmd\admin-handlers.go:1026:cmd.adminAPIHandlers.RemoveUser()
       1: net\http\server.go:1995:http.HandlerFunc.ServeHTTP()

**Comment by harshavardhana** [comment]
Thanks for reproducing @vsfalexanderpilch

**Comment by ghost** [comment]
@harshavardhana sorry for the delay, I will also retest this today using mc
