### ISSUE TITLE
Recommend S3 compatibility by default

### ISSUE THREAD

**Issue by SCDealy** [minio/minio#8012]
**Is your feature request related to a problem? Please describe.**
The default configuration of a program should be the one which causes the least problems for most users, particularly new users. As MinIO is put forward as: "compatible with Amazon S3 APIs", I believe this should be its default behavior to avoid confusion. Currently you must give the "--compat" option to get full S3 compatibility.

I don't know the history of the --compat option, but as the only documentation I have seen for it is "trade off performance for S3 compatibility", it seems to me that the logic is backwards as the default is what would normally be considered an advanced/power user's mode of operation. A new user will have no idea whether or not they need this and from the description, it should work for all users in "--compat" mode though it may be slower, but it clearly does not work for all users without "--compat"

**Describe the solution you'd like**
Ideally I would make "--compat" the default mode of operation and replace its command line option with an option like "--performance" which does the opposite of the current "--compat" option and is documented as breaking compatibility, in what ways it breaks compatibility (so people recognize the problem when they see it) and giving some use-cases where you would or would not use it.

**Describe alternatives you've considered**
An alternative is to simply have clear documentation of the "--compat" option in prominent locations in the documentation. I have already submitted a pull request for a quick but non-comprehensive update to the quick start guide. The problem with this approach is that it is documented in only one place (assuming my pull request is implemented) and since a quick start guide is by definition for people new to the project (who may simply jump to the relevant section of the document), ideally every single command line example in the documentation should include the "--compat" option as that is what is most likely to get them up and running without problems. It is better if the code offers the expected behavior by default rather than putting in this option everywhere in the documentation.

**Additional context**
None

**Comment by harshavardhana** [comment]
This is already fixed in #8006 `--compat` is only meant for applications which rely on ETag being md5sum hex.

ETag is hex of md5sum if client sets content-md5 appropriately. If client didn't set then it is assumed that client is not interested in the integrity based on md5sum. AWS already recommends using x-amz-content-sha256 for such verification of content integrity.

It is infact the best interest of the clients to use newer techniques to validate content during upload. 

Our decision to relax this was because by default it's not needed almost all Enterprise applications used out there such as Hadoop S3A ecosystem, Spark, Splunk.

Applications behaving on legacy requirements will just use `--compat`. Note this is only when client didn't set content-md5 and you still want server to calculate md5sum for the ETag.

Closing this issue.
