### ISSUE TITLE
Using ellipses uses two sets in 16 disks config

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#8034]
## Expected Behavior
Having two nodes and 16 disks should create one erasure set

## Current Behavior
Using ellipses in server arguments can give two erasure sets with 16 total disks

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
1. minio server /tmp/xl/foo/{1...8} /tmp/xl/bar/{1...8}
2. Check format.json for number of earsure sets

## Context
An issue found while investigating a user issue

## Regression
Looks like an old issue

## Your Environment
All

**Comment by harshavardhana** [comment]
This is part of the design @vadmeste not a bug, it is implemented to provide rack isolation.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/blob/master/docs/distributed/DESIGN.md#advanced-use-cases-with-multiple-ellipses

Distributed erasure coded configuration with no rack level redundancy but redundancy with in the rack we split the arguments, 32 sets in total, 16 disks per set.

```
minio server http://rack1-host{1...8}.example.net/export{1...16} http://rack2-host{1...8}.example.net/export{1...16} http://rack3-host{1...8}.example.net/export{1...16} http://rack4-host{1...8}.example.net/export{1...16}
```

v/s

Distributed erasure coded configuration with rack level redundancy 32 sets in total, 16 disks per set.
```
minio server http://rack{1...4}-host{1...8}.example.net/export{1...16}
```

This style support is necessary when top of the rack switch is not capable of handling the traffic to provide across rack redundancy.

**Comment by harshavardhana** [comment]
Each argument if split means that user wants to isolate disks, and nodes. Server currently complains if all disks are local that user has deployed in a sub-optimal order. Such that successive disks are local on the command line, so user would have simply ignored this message.

This happens generally because users didn't try to enumerate either their IPs or work on providing proper DNS names to allow ellipses to work. The splitting of argument happens when users have disks enumerated but not IPs. It is in our intention to educate them to keep it simple enumerate your IPs as hostnames, such that the deployment becomes easier.

**Comment by vadmeste** [comment]
yes, understood, closing this issue.
