### ISSUE TITLE
Minio B2 Gateway - error on CompleteMultipartUpload

### ISSUE THREAD

**Issue by stevesbrain** [minio/minio#8080]
## Expected Behavior
Minio acting as B2 gateway; allows uploading files

## Current Behavior
File upload fails (when used as the storage backend for Nextcloud) with the following error:

```
minio_1      | API: CompleteMultipartUpload(bucket=nextcloud, object=urn:oid:21)
minio_1      | Time: 01:52:35 UTC 08/15/2019
minio_1      | RequestID: Censored
minio_1      | RemoteHost: 192.168.128.4
minio_1      | Host: minio:9000
minio_1      | UserAgent: aws-sdk-php/3.62.10 GuzzleHttp/6.3.3 curl/7.65.1 PHP/7.3.6
minio_1      | Error: b2_finish_large_file: 400: large files must have at least 2 parts
minio_1      |        3: /go/minio/cmd/gateway/b2/gateway-b2.go:771:b2.(*b2Objects).CompleteMultipartUpload()
minio_1      |        2: /go/minio/cmd/object-handlers.go:2270:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
minio_1      |        1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

```

Tried on version 2019-08-14T20:37:41Z and 2019-08-15T00:14:57Z

## Steps to Reproduce (for bugs)
1. Set up instance of Nextcloud configured for S3 object storage (doesn't matter if you implement this from the start or after it's set up)
2. Have minio running b2 gateway
3. Watch it fail with above error

## Your Environment
* Version as per above, official minio docker images
* Docker running Docker version 19.03.1-ce, build 74b1e89e8a

Not sure if this is a Minio issue or a Nextcloud implementation issue, but figured it was Minio given the error comes from the b2 gateway component?

**Comment by kannappanr** [comment]
@stevesbrain Looking at the issue, it says that you are using `multipart` upload, but B2 is complaining that you have used only one part
https://github.com/minio/minio/blob/master/cmd/gateway/b2/gateway-b2.go#L770 The error is given by the B2 SDK and since the operation failed, Gateway is returning that error.

**Comment by stevesbrain** [comment]
@kannappanr Thanks - so just to confirm, you are saying this is a fault of the way the product is interacting with Minio, rather than an issue with Minio itself?

**Comment by kannappanr** [comment]
@stevesbrain This issue might give you a better picture. Gateway is more or less like a pass-through mechanism. So, the issue here is that `aws-sdk-php` uses `multi-part upload` against `B2`. The client uses `single` part but `B2` requires two parts. Either you should change your application to use explicit single put as explained here https://docs.aws.amazon.com/AmazonS3/latest/dev/UploadObjSingleOpPHP.html

another option is to raise an issue with B2.

There is nothing to be done as far as Minio is concerned. Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions.
