### ISSUE TITLE
Support Drag&Drop of folders in Web GUI

### ISSUE THREAD

**Issue by ghost** [minio/minio#8094]
**Is your feature request related to a problem? Please describe.**

Currently Minio supports the dragging and dropping of files into Minio's web GUI along with now creating folders. But then there are a few things a user intuitively thinks they can do (and wants to do) but they can't that

**Describe the solution you'd like**

1) Dragging and dropping of folders (and their contents) into (PUT) the web GUI
2) Dragging and dropping of folders/files from the Web GUI back to a desktop.

**Describe alternatives you've considered**

Right now users need to use a command line tool or another S3 client however they add additional complexities

**Additional context**

**Comment by darkdragon-001** [comment]
> 1. Dragging and dropping of folders (and their contents) into (PUT) the web GUI

Fixed in #9627

> 2. Dragging and dropping of folders/files from the Web GUI back to a desktop.

This needs to be implemented in your file explorer if I know correctly. Thus I have not seen any website implementing this.
@ghost If you can find any example implementing this, please link it here.

3. Dragging files into prefixes (both Web UI)

This is tracked in https://github.com/minio/minio/issues/9654#issuecomment-643171251.

---

@kaankabalak I guess this issue can be closed.

**Comment by harshavardhana** [comment]
> @kaankabalak I guess this issue can be closed.
