### ISSUE TITLE
MinIO won't clean up temporary files

### ISSUE THREAD

**Issue by mhjartstrom** [minio/minio#8129]
## Expected Behavior

MinIO should clean up its mess that it leaves behind in the object storage "tmp" folder.

## Current Behavior

Currently I have two different servers serving different object storages and they both have a massive load of junk left behind in their "tmp" folders. One of them contain 271 GB of data created between July 2nd and August 8th, another one 276 GB, a third one 124 GB and a fourth one 73 GB of data. These were created while running all from version "2019-06-27T21:13:50Z" to current version "2019-08-21T19:40:07Z"). MinIO is showing no intention of cleaning up any of these temporary files.

## Possible Solution

Make MinIO clean up its mess.

## Steps to Reproduce (for bugs)

1. Use MinIO on Windows in stand-alone executable mode, serving a single object storage directory.
2. Watch MinIO waste space for nothing.

## Context

It's wasting huge amounts of server space for no reason whatsoever.

## Regression

I don't know if this has ever worked.

## Your Environment

* Version used (`minio version`): 2019-08-21T19:40:07Z
* Environment name and version (e.g. nginx 1.9.1): Windows 7 Pro SP1
* Server type and version: PC
* Operating System and version (`uname -a`): Windows 7 Pro SP1
* Link to your project: N/A

**Comment by harshavardhana** [comment]
Thanks @mhjartstrom we will take a look

**Comment by vadmeste** [comment]
> These were created while running all from version "2019-06-27T21:13:50Z" to current version "2019-08-21T19:40:07Z"). MinIO is showing no intention of cleaning up any of these temporary files.

Just for clarification, are you saying here that both 2019-06-27T21:13:50Z and 2019-08-21T19:40:07Z do not clean tmp folders ?

**Comment by vadmeste** [comment]
It doesn't look there is any periodic tmp cleaning in FS mode, I think we can periodically remove all temporary files created/last-accessed at least 24 hours ago

**Comment by mhjartstrom** [comment]
I'm saying neither of those versions, or any of the ones released in between, will clean the tmp directory or else these files would have been deleted by now.

**Comment by mhjartstrom** [comment]
Any progress or updates on this issue?

**Comment by vadmeste** [comment]
> Any progress or updates on this issue?

Sorry for the delay.

~I found a possible cause of this, which requires that you are uploading large files to the same destination path, does that happen sometimes in your use case @mhjartstrom ?~

I found the cause of this, this happens when a client interrupts an upload of a large file after some time..

**Comment by stevekm** [comment]
hi, just wondering how to enable this behavior? And how to set the time interval for when MinIO server does these checks for old tmp files and removes them?

**Comment by harshavardhana** [comment]
> hi, just wondering how to enable this behavior? And how to set the time interval for when MinIO server does these checks for old tmp files and removes them?

every 24hrs - 24hrs and older are cleaned automatically. there is no reason to tune this @stevekm

**Comment by stevekm** [comment]
I need to be able to initiate the cleaning more frequently, and initiate it manually as well. 

For example, I have hundreds of GB of files in `.minio.sys/tmp` and `.minio.sys/multipart` that are filling up the volume and need to be cleared out immediately or risk destabilizing the server. Having to restart `minio server` to remove  files in`.minio.sys/tmp` and having to manually `rm -rf` files in `.minio.sys/multipart` is not a good solution. There should be a way to set the time interval that is appropriate for your own use case. Is that not available?

**Comment by dboc** [comment]
Hi,

I am facing the same problem wit MinIO NAS, recently we were out of storage then we list all files and discovery that there is very old files in ```.minio.sys/tmp```
We've been using MinIO(mode NAS) since 2018, we always update MinIO - using now RELEASE.2021-01-30T00-20-58Z. In that particular MinIO it has files old than 2 yeas in ```.minio-sys/tmp```.

Also, we recently make a new MinIO NAS instance, and the same behavior, those files in ```.minio-sys/tmp``` are not been deleted.

My question is that is safe to delete these files? 
and if it is happing with someoneelse using MinIO(mode NAS)?

Ty

**Comment by harshavardhana** [comment]
> I am facing the same problem wit MinIO NAS, recently we were out of storage then we list all files and discovery that there is very old files in `.minio.sys/tmp`
> We've been using MinIO(mode NAS) since 2018, we always update MinIO - using now RELEASE.2021-01-30T00-20-58Z. In that particular MinIO it has files old than 2 yeas in `.minio-sys/tmp`.
> 
> Also, we recently make a new MinIO NAS instance, and the same behavior, those files in `.minio-sys/tmp` are not been deleted.
> 
> My question is that is safe to delete these files?
> and if it is happing with someoneelse using MinIO(mode NAS)?
> 
> Ty

@dboc you can manually delete them since they are really old - we always cleanup if there is a failure - this looks like you have seen bugs that existed in the past and have been fixed.

**Comment by dboc** [comment]
@harshavardhana Thanks for the quick answer.

It is happing with new MinIO(mode NAS) RELEASE, i know that this issue is old but maybe this it was solved only on MinIO in mode Server.

I did a test with new RELEASE and it happened, for now i will delete theses files and monitoring if it will happen again.
