### ISSUE TITLE
How to use CoreDNS and ETCD to support minio cluster?

### ISSUE THREAD

**Issue by wlwcjl** [minio/minio#8289]
How to use CoreDNS and ETCD to support minio cluster? please help me,thank you!

**Comment by harshavardhana** [comment]
Are you not able to follow this article https://docs.min.io/docs/minio-federation-quickstart-guide.html ?

While we encourage GitHub issues,  it is generally beneficial to follow our issue template so that we can address the issues more thoroughly.

This issue ignores most of the required etiquette that we would like. It would give us immense pleasure if you follow our issue templates or better yet reach out to us at https://slack.min.io we will be more than happy to answer all your questions.

**Comment by kannappanr** [comment]
@wlwcjl Closing this issue. Please feel free to open another issue with detailed description or reach out to us at https://slack.min.io.
