### ISSUE TITLE
Whitespace in the access key supported by the web interface, but not by signature v4

### ISSUE THREAD

**Issue by awesterb** [minio/minio#8300]
## Expected Behavior

I would expect that either whitespaces in access keys are prohibited, or that access keys can contain whitespace without issues.

## Current Behavior

While running
```
MINIO_ACCESS_KEY="access key" MINIO_SECRET_KEY="secretkey" minio server data/
```
I can login to the web interface without issues, but the command
```
mc config host add myminio localhost:9000 "access key" secretkey
```
fails with the error
```
mc: <ERROR> Unable to initialize new config from the provided credentials. The access key ID you provided does not exist in our records.
```

## Possible Solutions

1. Ban whitespaces in access key, perhaps by adding a check in [IsAccessKeyValid from auth/credential.go](https://github.com/minio/minio/blob/d759a7ce99d1d03774ac005178480bcd717d299a/pkg/auth/credentials.go#L61); or
2. preserve whitespace in the access key by, for example, not removing _all_ spaces from the "Authorization" header [here](https://github.com/minio/minio/blob/e6d8e272ced8b54872c6df1ef2ad556092280224/cmd/signature-v4-parser.go#L256).

I think option 1 would be least error prone.

## Steps to Reproduce (for bugs)

See ["Current Behaviour"](#Current%20Behaviour).

## Context

We're using minio in our unit tests.

## Regression

No

## Your Environment

* Version used (`minio version`):
```
Version: 2019-09-18T21:55:05Z
Release-Tag: RELEASE.2019-09-18T21-55-05Z
Commit-ID: 456ce4cc92b6a24cc6087bebacd22f3d810d5de7
```

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:

not applicable?

* Operating System and version (`uname -a`):

```
Darwin ip-145-116-145-184.wlan-int.ru.nl 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

* Link to your project:

https://pep.cs.ru.nl

**Comment by kannappanr** [comment]
@awesterb Thanks for filing this issue. We will take a look and make the appropriate fix.

**Comment by sinhaashish** [comment]
Since the server console prints the access key and secret key . They must be used by web interface and the sdk. Right now the request from sdk hits `parseSignV4`  where all the white space are removed.  Example : Access key passed by sdk is `minio object` . This on server side gets converted to `minioobject`  This leads to the error `Unable to initialize new config from the provided credentials. The access key ID you provided does not exist in our records.`  Solution to this is fetching the access key before removing the spaces to keep the access key intact.
