### ISSUE TITLE
Minio monitoring with prometheus in K8s - authentication

### ISSUE THREAD

**Issue by Reamer** [minio/minio#8323]
Hi,
I'm setuped a prometheus and a minio cluster in K8s. I'm using the well known [prometheus-operator](https://github.com/coreos/prometheus-operator) to configure my prometheus scrape configuration. I'm able to add a [bearerTokenFile](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint) with the provided API from prometheus-operator. In general this is always the token from the serviceaccount running prometheus (`/var/run/secrets/kubernetes.io/serviceaccount/token`).

## Expected Behavior
Be able to monitor minio with a k8s serviceaccount token

## Current Behavior
After updating to [RELEASE.2019-09-25T18-25-51Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-09-25T18-25-51Z) I'm not able to monitor my minio cluster anymore. (403 Forbidden). I think generating the token via [mc tool](https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md#2-generate-the-prometheus-config-with-mc) is wrong in a k8s setup.

## Possible Solutions
1. Use k8s authentication service to secure metric endpoint
2. Give a option with environment variable to disable authentication
3. Give a option with environment variable to set a bearer token

## Steps to Reproduce (for bugs)
1. Setup K8s
2. Setup prometheus with prometheus-operator
3. Setup Minio with RELEASE.2019-09-25T18-25-51Z

## Regression
Yes,
[Minio version RELEASE.2019-09-25T18-25-51Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-09-25T18-25-51Z)
[Commit-Id](https://github.com/minio/minio/pull/7640/commits/8575c028161dbdcf014de915cad8b043eba27067)

## Your Environment
* Version used (`minio version`): RELEASE.2019-09-25T18-25-51Z
* Kubernetes: kubernetes v1.11.0+d4cacc0
* Openshift: openshift v3.11.0+1f48d99-299

**Comment by harshavardhana** [comment]
@Reamer it is not wrong it is a one-time activity and you should be able to use the token with the prometheus-operator 

all you need to do is migrate to the new style enable the bearer_token which never expires

```yml
bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ3MjMxNjY0OTIsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiJtaW5pbyJ9.kCfivtsc-Ea7M7g5SRhE43dsCcGfSbyqKUF9yYOnLse19uqVN9CKt_bkxAgEV5jkCLwyfXyZFNdTksSj7WVu5A
```

**Comment by harshavardhana** [comment]
> 1. Use k8s authentication service to secure metric endpoint

You can use this already generate the token as mentioned using `mc` and use that token.

> 2. Give a option with environment variable to disable authentication

No there is one way to do it, anonymous will not be allowed.

> 3. Give a option with environment variable to set a bearer token

This is not useful as there is already a known technique using the first method.

**Comment by Reamer** [comment]
Hi @harshavardhana,
I think it's not practicable to create a custom minio token and a custom scrape config for each minio installation. The prometheus server in K8s has already a token. Minio should be able to validate and accept this Token. This validation is often done in openshift via an [oauth-application-proxy](https://github.com/openshift/oauth-proxy).

**Comment by harshavardhana** [comment]
The token here to authorize the incoming client request. This token is also for per MinIO cluster not per node. So same token is used for all the nodes in the cluster? Are you thinking each node gets a separate token?

**Comment by Reamer** [comment]
No, I know that one token is for each minio cluster (installation).

**Comment by harshavardhana** [comment]
@Reamer why is it a bad idea to have each cluster do it's own authentication ?  If you don't wish to change the token you should keep the same admin credentials for all new clusters.. 

It is fine grained to avoid using same token for all clusters, it's hard to not see why isn't it beneficial. 

Are you saying that trusted pods shouldn't require such authentication ?

**Comment by Reamer** [comment]
Hi @harshavardhana 
It's good, that each cluster does it's own user authentication and maybe also prometheus authentication . I would be better, if I can set the prometheus token via  environment variable as like `MINIO_ACCESS_KEY` or `MINIO_SECRET_KEY`.

> It is fine grained to avoid using same token for all clusters, it's hard to not see why isn't it beneficial.

Prometheus should be able to discover with kubernetes-api all minio endpoints with potential multiple clusters and scrape all endpoints without adding a new scrape config for each cluster.

> Are you saying that trusted pods shouldn't require such authentication ?

No

**Comment by IsNull** [comment]
Sorry to hijack this issue, but I think what @Reamer  is after is a special case of my request here #7786.

The point is that we need to be able to bring up a complete minio cluster with all configuration, security and monitoring in place WITHOUT any manual configuration api calls. 

Think about it this way: A single `docker-compose up` should be enough to bring up minio, monitoring and any sort of event bus integration all configured properly. This means all the configuration including security must be specified in the initial configuration.

**Comment by harshavardhana** [comment]
You are right @IsNull once the config changes come in that is indeed possible

**Comment by bzakhar** [comment]
Actually, adding bearer token authentication over a clear text channel (HTTP) doesn't add anything to the cluster security and just complicates things beyond necessity. So please
a) make this authentication optional and configurable, off by default; and
b) disable it on HTTP endpoints as it's simply insecure and may in fact help compromise the cluster.

**Comment by IsNull** [comment]
For security reasons, endpoints exposed in public are limited using ingress / proxy rules.
Often, HTTPS is terminated at the ingress level so cluster internal communication is open. Exposing metrics on a separate port would probably simplify configuration and enhance security.

Also, your change in requiring authentication broke our monitoring and there is no easy fix. We cant even disable security on it. And all this in a non major version change ...

**Comment by thomasf** [comment]
> b) disable it on HTTP endpoints as it's simply insecure and may in fact help compromise the cluster.

Not that though, because some people put their security rules and authentication in a proxy/load balancer and never expose the http listener by itself.

This change has caused a bit of problem for us, we cannot currently deploy new minio instances (which we some times might do tens of times each day).  We are note using k8s, just a bunch of containers running on a bunch of hosts being set up by a CI there will be a lot to change unless setting it with environment variables start working..  We usually use one authentication for all Prometheus metrics end points so this. The fact that the `mc admin prometheus` was even imlemented without support for setting or even just getting a key (?) boggles the mind.

This was IMHO a really bad feature roll out since it breaks usage for a bunch of use cases without even providing an easy opt out.

I'm not sure exactly what to do about this, maybe keep using an old version of minio for now.

**Comment by harshavardhana** [comment]
We are going to allow an env to disable Prometheus auth. For people who want authentication `mc admin prometheus` does the job.

**Comment by thomasf** [comment]
Will this be happen within weeks? I am considering just disabling monitoring of minio until the change arrives if it's not too far off into the future

**Comment by harshavardhana** [comment]
Think of this as next week. Adding support for such a thing is fairly simple anyways

**Comment by bzakhar** [comment]
>> b) disable it on HTTP endpoints as it's simply insecure and may in fact help compromise the cluster.
>
>Not that though, because some people put their security rules and authentication in a proxy/load balancer and never expose the http listener by itself.

Bearer token is a shared secret, transmitting it over a clear text channel where it can be easily intercepted doesn't make much sense, it was never supposed to be used that way. Do not assume that since you're behind a firewall then your internal traffic is protected from eavesdropping...

**Comment by thomasf** [comment]
Also don't assume what other people assume.  If this was a general discussion about network infrastructure your point would maybe be valid but it isn't

**Comment by bzakhar** [comment]
It is my sincere belief that if you create an opportunity to do something wrong, inevitably someone will. Supporting bearer token authentication over clear text transport is just such an opportunity. It's one of those things you never do even if you see some immediate benefit and no apparent harm. Bearer and Basic authentication require secure transport, clear text transport shouldn't be even optionally allowable. It's like installing a lock on your front door and then leaving the key under the mat. You either don't put locks where they are not needed or you protect your keys if you did.

**Comment by thomasf** [comment]
Well, since the network between the proxy and minio in this case is only visible between those two services in a closed off virtual network on a single machine an attacker would have to root the machine first or hack the proxy and then we have a lot worse problems than someone being able to read our minio metrics which is fairly low down on the threat level scale to begin with.

 > It is my sincere belief that if you create an opportunity to do something wrong, inevitably someone will.

Yes, given an opportunity to do something wrong someone will but then we can just scrap the whole idea of networked computing and we are also much safer. 

> It's like installing a lock on your front door and then leaving the key under the mat. You either don't put locks where they are not needed or you protect your keys if you did.

It's usually still easy to just axe up the door if you need to get in fast because many doors are just made of wood, most locks are quite easy to pick if you are in to that or just break a window instead.   It's still all about threat assessment and design of the system as a whole that will bring you real security. A single component enforcing one thing or the other doesn't bring security either, you have to have a systematic understanding of the whole when designing for security. 

I am not going to respond further because this discussion has literally nothing to do with what this issue is about which was the reason I 👎 'd your previous comment. I'm all for discussing general security conerns but there is a place for that which isn't here.
