### ISSUE TITLE
[resolved] Why are there three nodes with high utilization of hard disk IO, and the other node is normal?

### ISSUE THREAD

**Issue by Jacky2** [minio/minio#8468]
## Current Behavior
Why are there three nodes with high utilization of hard disk IO, and the other node is normal?

My cluster consists of 4 nodes, one node and two disks, but it is actually a disk, but the directory is different.

Normal node
![2](https://user-images.githubusercontent.com/23411395/67844674-23922a00-fb39-11e9-8873-d133b108bd33.png)

Abnormal node
![1](https://user-images.githubusercontent.com/23411395/67844808-5f2cf400-fb39-11e9-903c-b8bfab88b923.png)

## Environment

* Version used (`minio/minio:RELEASE.2019-09-18T21-55-05Z`):

**Comment by kannappanr** [comment]
@Jacky2 Thanks for reporting this issue. Are you seeing any performance drop or anything else when this happens? What are the symptoms when this happens?

**Comment by Jacky2** [comment]
@kannappanr  

We are going to deploy MinIO to production, and then carry out the pressure test through the application developed by Java, 500 concurrent, TPS is only more than 100. It was found that the server Io was full. Then we stopped the pressure test and found that the IO utilization rate could not be lower. Then I restarted the MinIO service and found that the IO utilization rate of three machines was still very high.

**Comment by wlan0** [comment]
@Jacky2 The problem here is that ioutil is not a good measurement of IO utilization. ioutil measures the amount of CPU time utilized to issue IO requests to a particular device. It does not indicate how much of IO bandwidth is being utilized.  

Please refer to this blog for more info: https://brooker.co.za/blog/2014/07/04/iostat-pct.html

A better way to measure utilization is to measure total node IO throughput using iozone, and then looking at iostat for aggregate read or write bytes/seconds.

**Comment by kannappanr** [comment]
@Jacky2 Regarding why only three nodes have high utilization, you probably have restarted only one node. Once you restart all the nodes, you will see similar numbers.

**Comment by Jacky2** [comment]
@wlan0 @kannappanr  OK , thanks. I will try it.

**Comment by xianshun163** [comment]
After the client uploads the file and receives the correct return, will the server have a lot of synchronization or calculation work in the background?    Do you know the principle?  thanks.

**Comment by harshavardhana** [comment]
@xianshun163 there is no such thing in MinIO, MinIO writes in O_direct avoiding page cache. And MinIO is also strictly consistent.. all writes hit the disk as they are uploaded by the client.

This issue is about auto heal and disk usage thread, unrelated to your question. Let's talk in more detail on https://slack.min.io 

Let's leave this issue to assigned people to debug.

**Comment by harshavardhana** [comment]
@Jacky2 please test the latest release and let us know.

**Comment by harshavardhana** [comment]
> @Jacky2 please test the latest release and let us know.

Closing this issue as stale - crawling has been sufficiently optimized using bloom filters etc.
