### ISSUE TITLE
Is it possible to decrypt a file outside of minio server?

### ISSUE THREAD

**Issue by nreynis** [minio/minio#8527]
I have files encrypted using minio SSE-C. I wan't to be able to decrypt them without using minio server.

As far as I understand this isn't possible using OpenSSL because minio use either AES-256-GCM or ChaCha20-Poly1305.
Is it possible to decrypt the files using ncrypt (https://github.com/minio/sio#applications) and the 32 bits key ?

**Comment by aead** [comment]
> I have files encrypted using minio SSE-C. I wan't to be able to decrypt them without using minio server.

In theory, yes - but you would have to basically re-implement how MinIO derives various key material (object-encryption-key, key-encryption-key, ...). Also it depends whether the objects have been uploaded as single-PUT or [multipart PUT](https://docs.aws.amazon.com/en_en/AmazonS3/latest/dev/mpuAndPermissions.html).
Also it depends whether you used MinIO in FS mode or with erasure coding since you would need to erasure-decode the objects first and than decrypt them in the later case.

> As far as I understand this isn't possible using OpenSSL because minio use either AES-256-GCM or ChaCha20-Poly1305.

OpenSSL implements AES-256-GCM and ChaCha20-Poly1305 - both are [AEADs](https://en.wikipedia.org/wiki/Authenticated_encryption#Authenticated_encryption_with_associated_data_(AEAD)) and used in TLS - that is not the issue here.

In general, you would have to look at the object metadata and depending on the information found there (and the SSE-C key used of the particular object), do the same key-derivation and use https://github.com/minio/sio to decrypt the object.

So, yes it possible but it's non-trivial and there is no ready-to-use solution for this.
You may want to look at https://github.com/minio/minio/blob/master/docs/security/README.md fror more information.

**Comment by kannappanr** [comment]
@nreynis Closing this as answered, please feel free to reach out to us at https://slack.min.io for such questions

**Comment by nreynis** [comment]
Thanks @aead !
