### ISSUE TITLE
log: log output should not include full paths or domain names

### ISSUE THREAD

**Issue by aead** [minio/minio#8576]
## Expected Behavior
```
API: PutObject(bucket=system, object=732358.txt)
Time: 10/01/2019, 3:16:41 PM
DeploymentID: 6faeded5-5cf3-4133-8a37-07c5d500207c
RemoteHost: play.minio.io:9000
Error: no space left on device
2: cmd/xl-v1-metadata.go:441:cmd.writeXLMetadata()
1: cmd/xl-v1-metadata.go:474:cmd.writeUniqueXLMetadata.func1()
```

## Current Behavior
```
API: PutObject(bucket=system, object=732358.txt)
Time: 10/01/2019, 3:16:41 PM
DeploymentID: 6faeded5-5cf3-4133-8a37-07c5d500207c
RemoteHost: play.minio.io:9000
Error: mkdir /home/play/data2/.minio.sys/tmp/79266ad3-f1b6-4012-941f-47e992d054d5: no space left on device
2: cmd/xl-v1-metadata.go:441:cmd.writeXLMetadata()
1: cmd/xl-v1-metadata.go:474:cmd.writeUniqueXLMetadata.func1()
```

## Possible Solution
Check possible errors in posix.go a.o. to ensure we don't print unnecessary information

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
I am not sure how you think we can remove the path, it's really not in our control @aead

**Comment by aead** [comment]
@harshavardhana Maybe I'm missing corner cases but if an operation like `os.Mkdir` fails we should get an `os.PathError`. We don't have to print `os.PathError.Path` right?!

**Comment by harshavardhana** [comment]
Correct but it requires quite a lot of custom code, because we can't guarantee that structs might say the same.

It is too much of a burden because we have no control over if error returned with os.PathError is always going to stay the same. As there is no guarantee on errors other than interface definitions in Go  and os package by itself is not an interface and doesn't provide guarantees on the error returned.

IMO we may be able to do it for some but not for all and things might easily leak out leaving with inconsistent behavior.
