### ISSUE TITLE
Can't create objects that end with slash and have content

### ISSUE THREAD

**Issue by felipeek** [minio/minio#8618]
## Expected Behavior
When trying to create an object whose name ends with a slash (i.e. `my/prefix/`), the operation should work even when the object have content.

## Current Behavior
The operation only works when the object has size 0 (which would be a directory)

## Context
We use minIO to mimic a S3-backend for our tests. In S3, this works, and we rely on this feature.

**Comment by harshavardhana** [comment]
This is expected behavior for MinIO, we are not going to address this issue and we consider it's a design bug in your application.

There are some historical issues which will give you an indication on why we do this and why we discourage this behavior.

https://github.com/minio/minio/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22won%27t+fix%22+directory

If you need this behavior you should just use AWS S3, as we are not going to address this issue.
