### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by jasoncox** [minio/minio#8706]
Minio in gateway mode crashes with error: `fatal error: concurrent map iteration and map write` indicating concurrent map misuse.

## Steps to Reproduce (for bugs)

1. run `minio gateway s3`

## Your Environment

* Version used (`minio version`):  Bug is introduced in RELEASE.2019-12-17T23-16-33Z and exists in `latest` build on DockerHub
* Environment name and version (e.g. nginx 1.9.1): Kubernetes
* Server type and version: 
* Operating System and version (`uname -a`): Ubuntu 18.04
* Link to your project:

Happy to provide more information, just wanted to get this filed asap and don't have much on hand right now.

**Comment by harshavardhana** [comment]
Please provide more information such as the full crash logs etc. Right now we have no idea what to look at.

S3 gateway is working fine in our CI/CD tests, so we would need a reproducer.

Also we made a release this week as well, so would be worth to upgrade and test again.

**Comment by jasoncox** [comment]
Here is a full crash log from RELEASE.2019-12-24T23-04-45Z:
[https://gist.github.com/jasoncox/8ac4287919e98d07c337c2cb1a4e3a8c](https://gist.github.com/jasoncox/8ac4287919e98d07c337c2cb1a4e3a8c)

Minio runs for around 10 minutes under full load before crashing. Prometheus is also actively scraping against the metrics endpoint.

**Comment by harshavardhana** [comment]
Looks like you are also using disk cache, can you provide the configuration for that as well ?

**Comment by jasoncox** [comment]
Sure, I have the following env vars set:
MINIO_CACHE_MAXUSE=70
MINIO_CACHE_EXPIRY =30
MINIO_CACHE_DRIVES=/cache

**Comment by jasoncox** [comment]
Have you been able to reproduce the failure?

**Comment by harshavardhana** [comment]
Nope we have not @jasoncox

**Comment by klauspost** [comment]
ok, spent an hour chasing this down:

Seems the culprit is [filterObjectLockMetadata](https://github.com/minio/minio/blob/f931fc7bfbfee25ea3f7c95d855d41e689bc0611/cmd/object-lock.go#L597) modifying the metadata while another goroutine is reading it.

In `GetObjectHandler` the object info [is requested](https://github.com/minio/minio/blob/669c9da85d229755a33217b4834cdd3a311a6495/cmd/object-handlers.go#L346). This hits the disk cache which [spins up a goroutine](https://github.com/minio/minio/blob/80558e839d222010d688623811f3d679dee078be/cmd/disk-cache.go#L302) which as one part calls `getMetadata`, which [reads the metadata](https://github.com/minio/minio/blob/80558e839d222010d688623811f3d679dee078be/cmd/disk-cache.go#L178). This leads to the race with `filterObjectLockMetadata` which is modifying it.

It seems like similar functions like [CleanMinioInternalMetadataKeys](https://github.com/minio/minio/blob/555969ee425818fecd471b3e7d21925c1f900d48/cmd/object-api-utils.go#L802) copies rather than modifies the metadata.

I would propose to change `filterObjectLockMetadata` to copy the metadata when modifying. It will be fairly small and the size is known beforehand. Alternatively the two `getMetadata` calls could be moved outside the goroutines in `(*cacheObjects).GetObjectNInfo`, but other implementation may have similar sensibilities.

**Comment by harshavardhana** [comment]
> I would propose to change `filterObjectLockMetadata` to copy the metadata when modifying. It will be fairly small and the size is known beforehand. Alternatively the two `getMetadata` calls could be moved outside the goroutines in `(*cacheObjects).GetObjectNInfo`, but other implementation may have similar sensibilities.

@klauspost fixing `filterObjectLockMetadata` would actually fix this properly. The current behavior can cause quite a lot of map related races.

**Comment by klauspost** [comment]
I will do a PR tomorrow.
