### ISSUE TITLE
Does minio have performance limitations on object prefixes like AWS S3?

### ISSUE THREAD

**Issue by Meshkati** [minio/minio#8747]
Hi!

Does the minio have any performance limitations on object prefixes like S3? And if have, is there any difference between prefix delimiters on that?

As AWS documentation says, there is no hierarchical structure in s3, but in the minio we see `/` characters became into folders, so hierarchy appears. Also, the way that backend servers of AWS are behaving is not clear, but in minio we know how files are getting distributed, so is there any difference?

**Comment by harshavardhana** [comment]
MinIO uses filesystem for namespace, the heirarchy is needed to make sure to avoid overwhelming the backend filesystems. This is not a limitation an expected behavior.

For applications heirarchy provides a way to manage objects, dumping all objects flat will lead to overwhelming output for client applications.

So in MinIO if you use ext4 it will expose ext4 limits, if you use xfs it will expose xfs limits.

**Comment by Meshkati** [comment]
So we don't need to randomly distribute object prefixes in minio for more TPS?

**Comment by harshavardhana** [comment]
Whatever works best, test for your hardware and backend filesystem.

Note: *heirarchy is important for management objects and avoid overwhelming the client.*

**Comment by harshavardhana** [comment]
I will close this issue, let's discuss on slack https://slack.min.io
