### ISSUE TITLE
Failed to upload object 

### ISSUE THREAD

**Issue by ronh123** [minio/minio#8857]
Please Help! 

Failed to put object in Minio from python client
**Error in Minio backend**:
/storage/.minio.sys/buckets/mybucket/file.zip: file too large

**Environment**:
Running docker image version 2019-6 in kuberentes, storage on NetApp 

Try to delete old files with mc.exe cli, but is not help

Someone know about this issue?

**Comment by harshavardhana** [comment]
This looks like backend is returning an error @ronh123 how are you deleting files ?

**Comment by ronh123** [comment]
Run on Ubuntu Linux:
mc rm myminio/mybucket -r --force --older-than 1 
 
It is a right way?

Thanks,Ron.

**Comment by kannappanr** [comment]
@ronh123 If I understand your issue correctly, looks like `PutObject` is failing and you are trying to get more space by issuing `mc rm` command. I do not know the version of `mc` that you are running

`mc rm myminio/mybucket -r --force --older-than 1d`
if you want to delete files that are older than a day, seems correct.

What is the size of the file that you are trying to upload ? Can you try the same with `mc` ?

**Comment by ronh123** [comment]
My files size is between 100KB - 10MB.
Is there a limit on the amount of files in bucket or in Minio server?

**Comment by kannappanr** [comment]
@ronh123 There is no limitation from Minio Server, it depends on the backend. Can you give us the exact version of Minio that you are using, the actual error that you are seeing in the backend and the command that you used to start MinIO

**Comment by ronh123** [comment]
Thank you for the quick response.
**Update**:
My error occurring because of Netapp storage max folders limitation.

I have one more question:
Can I disable the metadata folder for all files (the hidden folder the Minio created per file)? 

Thanks, Ron.

**Comment by harshavardhana** [comment]
You cannot avoid @ronh123 for now, how many files did you create? what is the top-level limitation here? - This looks like you have ran out of single-tenant limits. You should be deploying a new NetApp volume and start putting new data into this volume.

You will reach this limit anyways with or without the `metadata` folder eventually because there is a top-level limit.

**Comment by ronh123** [comment]
I created 1000 files per second (=~ 90,000,000 per day), retention will be 24 hours.
My Netapp has a limitation in max folders in volume. Can I deployment the Minio cluster use multi-mount?

And I have another issue and i will be happy to your help: 
Because of the many files, The delete files process (using mc) takes a long time.
There is a faster way to delete files?

Thank you!

**Comment by harshavardhana** [comment]
There is no faster way, we are deleting as fast as your backend is able to delete.

**Comment by ronh123** [comment]
If I will delete files not using mc (metadata + file), It would be bad? 
I can delete an entire bucket

**Comment by harshavardhana** [comment]
> If I will delete files not using mc (metadata + file), It would be bad?
> I can delete an entire bucket

@ronh123 the point is you are testing the limitations of NetApp as they would recommend to not do that instead create multiple volumes for multiple tenants this would scale well and be isolated from any large scale performance issues.

So it is not suitable for the use case you are trying to address. I will go ahead and close this issue since there is nothing actionable for us.
