### ISSUE TITLE
MinIO takes long time to start for high bucket count

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#8994]
One of the customers' cluster had large number of buckets. I think this was causing the long bootup time for MinIO. We need to investigate and see how the bootup time can be fixed.

**Comment by harshavardhana** [comment]
@krishnasrinivas bootup time is already fast in latest releases, but due to the fact the all subsystems need to read all the buckets serially to look for 

- lifecycle
- policy
- encryption
- object/locking/legal-hold
- notification 

It requires significant amount of time if there are lots of buckets.

**Comment by harshavardhana** [comment]
After the PR #9031 can be it be validated again @vadmeste ?

**Comment by kannappanr** [comment]
ping @vadmeste

**Comment by vadmeste** [comment]
> After the PR #9031 can be it be validated again @vadmeste ?

Currently running a 4 nodes (1 disk per node) deployment in my local machine with 5000 buckets led a one minute startup delay for each node. This is probably considered acceptable since we already do not recommend having too many buckets.

**Comment by harshavardhana** [comment]
Most of this has been already optimized @vadmeste , so this issue is perhaps fixed.

**Comment by harshavardhana** [comment]
Closing this as fixed for now
