### ISSUE TITLE
Add cache garbage collection to Prometheus exposed metrics

### ISSUE THREAD

**Issue by muzomer** [minio/minio#9072]
We are happily using MinIO in our production environment to manage the caching between our in-house application and AWS S3. It really has a great performance. 

Thanks for your efforts!

**Background**
We have an in-house developed application, which uses MinIO as file caching layer between the application processes and AWS S3. Monitoring of cache usage is crucial for the application. Currently, we are basically using the disk space usage as the main monitoring metric. We need to monitor the cache Garbage Collection (eviction) frequency as well, to have better visibility of cache state.

**Suggestion**

It would be great to expose a Prometheus `counter` metric  to track the number of executed cache garbage collection cycles.

**Links**
* How to monitor MinIO server with Prometheus (https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md)
* Metrics exposed by MinIO server (https://play.min.io:9000/minio/prometheus/metrics)
* The only available external Prometheus metrics exporter (https://github.com/joe-pll/minio-exporter)

Thanks

**Comment by nitisht** [comment]
We'll discuss this internally and get back @muzaffar-omer

**Comment by muzomer** [comment]
Your follow up and feedback is appreciated @nitisht. Thanks !

**Comment by aledegano** [comment]
Hello, I am part of @muzaffar-omer team.
@nitisht did you have a chance to discuss this issue with your team? Do you have any update?

Thank you!

**Comment by harshavardhana** [comment]
> It would be great to expose a Prometheus `counter` metric to track the number of executed cache garbage collection cycles.

What is the requirement here? what decision is done based on watching this in prometheus?

**Comment by aledegano** [comment]
> > It would be great to expose a Prometheus `counter` metric to track the number of executed cache garbage collection cycles.
> 
> What is the requirement here? what decision is done based on watching this in prometheus?

My team uses Minio as an on-premise pull through cache for AWS S3 (and by the way it works great!!!).
Because of the way it works, though, it's hard to judge if our local storage dedicated to the cache is sufficiently sized for our customers.
Given enough time the cache always fills up to 100%, which is desired, however we would like to monitor if the cache is pruned too frequently (which would mean that the storage is too small) or not so much.
Thus the decision based on the Prometheus data is to see if larger storage is needed, and since our usage of Minio as cache will continue to expand, this decision will be probably taken multiple times.

Thanks!

**Comment by muzomer** [comment]
Thank you @harshavardhana for your follow up on the issue. Much appreciated

**Comment by harshavardhana** [comment]
It is more comprehensive PTAL #9815

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/9815 is merged which can be used here, we will make a release in another couple of weeks.
