### ISSUE TITLE
[working as intended] You can remove a policy from a cluster when its still applied to users/groups

### ISSUE THREAD

**Issue by khumps** [minio/minio#9127]
## Expected Behavior
An error message if I try to remove a policy from a cluster that is applied somewhere
## Current Behavior
Policy is removed from the cluster and silently removed from all users/groups

## Possible Solution
Prevent removal of the policy from the cluster, require a `--force` to remove it or wait until its actually gone from everywhere

## Context
If I accidentally delete a policy and it was in use, there is no easy way to recover the connections of the policy. This should not be so easily allowed if the policy is in use

**Comment by harshavardhana** [comment]
@khumps this is as per the behavior of AWS S3, policies are not really tied to anyone. So if you remove it while they are being referenced by some users it is expected because you may want to revoke their access.

It makes sense to remove users from their group association but not policies. If we restrict policy removal it becomes tricky, you cannot update then either after once set. This is unexpected from the actual desired behavior.

It is perhaps okay to add --force flag to warn the user.

**Comment by harshavardhana** [comment]
> @khumps this is as per the behavior of AWS S3, policies are not really tied to anyone. So if you remove it while they are being referenced by some users it is expected because you may want to revoke their access.
> 
> It makes sense to remove users from their group association but not policies. If we restrict policy removal it becomes tricky, you cannot update then either after once set. This is unexpected from the actual desired behavior.
> 
> It is perhaps okay to add --force flag to warn the user.

Closing as per this comment.
