### ISSUE TITLE
Set bucket policy server side 

### ISSUE THREAD

**Issue by augnustin** [minio/minio#9443]
**Is your feature request related to a problem? Please describe.**

So I set up minio in my `docker-compose.yml`, it works like a charm, I love it, this project is amazing.

Since it is part of my stack, I need it to be easily deployable and replicable among environments.

Everything is plugged, upload works well, but the last thing I need it to set the bucket I use some policy, in my case "download". 

Reading [the docs](https://docs.min.io/docs/minio-client-complete-guide#policy), it seems like this can only be done using the client command line. I checked inside my server container if it were there, but it doesn't seem to be anywhere.

But it feels lame to have to set up another docker instance simply to run a couple commands.

**Describe the solution you'd like**

What I'd expect instead, is to being able to build my config from the server side.

It could be by having `mc` in the server, but IMHO a cleaner solution would be to simply share a file within the docker that would host the config. Environment variables could work also.

Thanks for getting back

**Comment by augnustin** [comment]
Does my issue make sense? Ain't there a workaround other than installing the client? Thanks

**Comment by harshavardhana** [comment]
> Does my issue make sense? Ain't there a workaround other than installing the client? Thanks

It's not a priority for us @augnustin we may do it in future.

**Comment by anthu** [comment]
The bucket policy would need to be applied to a bucket, so we are talking about creating a bucket AND applying a policy.

My gut feeling is due to the rather individual nature of use-cases this should be a task for the developer to create a docker image and do whatever needs to be done to the instance.

Maybe we could provide a docker image including server and client so one could just customize the `docker-entrypoint.sh` .
