### ISSUE TITLE
s3:ListAllMyBuckets is allowed on single bucket

### ISSUE THREAD

**Issue by ghost** [minio/minio#9475]
AFAIK the s3:ListAllMyBuckets Action can be only assigned on Resource `arn:aws:s3:::*`. 
I tested assigning it on a test bucket `arn:aws:s3:::foo` and it worked. It should not.

## Context

I was trying to set a per-user visibility to just the buckets owned by the user. By reading various threads such as following it became clear that S3 allows listing only all or none buckets and what I'm trying to accomplish is not going to work.
https://acloud.guru/forums/s3-masterclass/discussion/-L6X96Lo37ZnG_g6wiEg/ListBucket%20vs%20ListAllMyBuckets
Nevertheless, by using the sample policy I was able to make it work in Minio but not in Wasabi S3 for example.

## Steps to Reproduce (for bugs)
1. add the following policy with `mc admin policy add my-minio foo foo.json`
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListAllMyBuckets",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads"
      ],
      "Resource": "arn:aws:s3:::foo"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "s3:AbortMultipartUpload",
        "s3:DeleteObject",
        "s3:GetObject",
        "s3:ListMultipartUploadParts",
        "s3:PutObject"
      ],
      "Resource": "arn:aws:s3:::foo/*"
    }
  ]
}
```
2. create a bucket `mc mb my-minio/foo`
3. create a user `mc admin user add my-minio foo 123123123123`
4. attach the policy to the user `mc admin policy set my-minio foo user=foo`
5. I tested with it listing the bucket/buckets using Rclone as it's the main client tool I use. Use the following `~/.config/rclone/rclone.conf` snippet:
```
[foo]
type = s3
provider = Minio
access_key_id = foo
secret_access_key = 123123123123
endpoint = <url.to.minio>
```
6. Run 
```
rclone lsd foo:
          -1 2020-04-28 13:21:26        -1 foo
```
(I have many other buckets in `my-minio` so it seems to work.)

## Expected Behavior
steps 1-4. Created the same kind of user/policy/bucket setting on Wasabi S3 (the policy json was identical)
5. Similar Rclone config, but pointing to Wasabi S3
6. 
```
rclone lsd tempfoo123:
2020/04/28 13:35:09 ERROR : : error listing: AccessDenied: User: arn:aws:iam::<redacted>:user/tempfoo123 is not authorized to perform: s3:ListAllMyBuckets on resource: arn:aws:s3:::
	status code: 403, request id: F8EB8A6AC373EC68, host id: 8PHq/QgwaLr........
2020/04/28 13:35:09 Failed to lsd with 2 errors: last error was: AccessDenied: User: arn:aws:iam::<redacted>:user/tempfoo123 is not authorized to perform: s3:ListAllMyBuckets on resource: arn:aws:s3:::
	status code: 403, request id: F8EB8A6AC373EC68, host id: 8PHq/QgwaLr......
```

## Your Environment

* Version used (`minio version`):  2020-04-15T19:42:18Z

**Comment by harshavardhana** [comment]
First, this is a MinIO feature @markkutikkanen what is happening here is that ListBuckets() lists the buckets that you have access to based on `s3:ListBucket` policy. 

It is not that following call honors resources, it is actually ignored for this action.

>         "s3:ListAllMyBuckets",

The resource is honored because you have access set for this

>         "s3:ListBucket",

It is in our interest to keep this behavior such that users can discover which buckets they have access to using `mc ls` - it allows discoverability of access to buckets rather than mentally remembering such details. 

It is also what we think is wrong in AWS S3 implementation that policy evaluation should have filtered out the right set of buckets that the user has clearly access to. Treating `s3:ListAllMyBuckets` as a special call was not necessary and it simply complicates the usage of the S3 system. 

We deviated here on purpose because it didn't make sense to us what AWS S3 expects @markkutikkanen . So what you saw is expected we are not going to change.
