### ISSUE TITLE
[faq][wontfix] Special behavior around slashes

### ISSUE THREAD

**Issue by pauldraper** [minio/minio#9567]
## Expected Behavior

I can use any non-empty Unicode string of a few hundred characters for a key.

## Current Behavior

Creating an object beginning with / yields the error "Object name contains a leading slash."

Creating an object ending in / has the error "The specified key does not exists."

Creating an object with adjacent repeated / in the middle creates an object whose key has the slashes collapsed into a single /.

## Possible Solution

I infer that minio is using key names as file paths, though file paths have different semantics than arbitrary keys.

It should use a character escaping algorithm, such as percent encoding % and / (at least in cases when / would be incompatible with the file system).

## Steps to Reproduce (for bugs)

1. curl -X PUT http://minio:9000/minio/upload//example --data-binary @/dev/null
2. curl -X PUT http://minio:9000/minio/upload/example/ --data-binary @/dev/null
3. curl -X PUT http://minio:9000/minio/upload/exa//mple --data-binary @/dev/null

## Context

I am using minio as a replacement for AWS S3. However, some S3 tools create objects ending with / (to represent a "directory"), and these failing to work with minio.

I have not tried more compatibility, but the existence of so basic a difference with S3 currently suggests that minio is not a drop-in replacement for object storage.

## Regression

No

## Your Environment

https://hub.docker.com/layers/minio/minio/latest/images/sha256-ead26f33ad60678e7c303e692915cda2cd71bc15df8240a589db988211e7527d?context=explore

**Comment by pauldraper** [comment]
Alternatively, if minio decides not to support arbitrary keys, this difference should be documented, at it otherwise it is surprising to users migrating from S3.

**Comment by harshavardhana** [comment]
> I am using minio as a replacement for AWS S3. However, some S3 tools create objects ending with / (to represent a "directory"), and these failing to work with minio.

MinIO uses the backend filesystem for its namespace, it is trying to reserve keys such as `//`, unlike AWS S3 which we think is rather meaningless. They did, not by design it just exists because of the nature of its implementation, i.e using some form of a KV store for storing the flat keys which MinIO does not with its own design reasons.

Now, this was misused by client applications is another question, which is the case you are talking about.

> I have not tried more compatibility, but the existence of so basic a difference with S3 currently suggests that minio is not a drop-in replacement for object storage.

MinIO is widely used across almost all known large scale S3 applications such as Splunk, Hadoop, Druid and you name it. Deployed also at the scale of 100PiB+ deployments.  To suggest that it is not drop-in is a bit of a stretch, supporting `//` is not a cornerstone of S3 compatibility.  

File systems exist and will always exist the way they are `//` has no special meaning on FS it is quite simply doesn't exist or preserved - MinIO is designed to not introduce anything special which ends up creating vendor lock-in like scenarios which you are experiencing with AWS S3. MinIO generally takes the approach of doing what makes sense most of the time, in this scenario it took a simpler approach by keeping your namespace easy to understand. 

Bringing database entities inside object storage brings its own complexities just to satisfy AWS S3 for niche scenarios, while MinIO is on-prem deployment - increases the burden to maintain such an infrastructure which has many components that can fail, this is easily seen with most object storage on-prem deployments struggling to scale and meet the needs.

So the bottom line is better-written applications such as Splunk Smart store, Hadoop S3A do not behave this way and are more widely used at scale. I do not know what application you are talking about if it's open-source it can be fixed if it's proprietary you are out of luck. The fix here is ideally in the application you are using. 

@pauldraper

**Comment by harshavardhana** [comment]
> Alternatively, if minio decides not to support arbitrary keys, this difference should be documented, at it otherwise it is surprising to users migrating from S3.

All other keys are supported, its naturally not possible because of using filesystem as the namespace.

We shall not be compromising our design principles here for niche usecases, if support for `//` is a hard requirement then you should look for alternatives to MinIO.

**Comment by pauldraper** [comment]
> To suggest that it is not drop-in is a bit of a stretch

Apologies for the overstatement. 

> MinIO is designed to not introduce anything special

On the contrary, I am seeing special handling of the "/" characters in my key-object store.

If had I desired portable file system semantics, I would likely use a file system interface.

> better-written applications

The AWS web console and [s3fs](https://github.com/s3fs-fuse/s3fs-fuse) are two "poorly written"(?) applications that create objects ending in "/".

With some effort I can avoid copying these into minio, or using my own encoding on top of it.

> if support for // is a hard requirement then you should look for alternatives to MinIO.

Support for trailing slash is actually the more important one to me, but I assume the answer is the same.

I at least suggest documenting special semantics regarding forward slashes in what is described as an "object store."

**Comment by harshavardhana** [comment]
> > To suggest that it is not drop-in is a bit of a stretch
> 
> Apologies for the overstatement.
> 
> > MinIO is designed to not introduce anything special
> 
> On the contrary, I am seeing special handling of the "/" characters in my key-object store.
> 
> If had I desired portable file system semantics, I would likely use a file system interface.
> 
> > better-written applications
> 
> The AWS web console and [s3fs](https://github.com/s3fs-fuse/s3fs-fuse) are two "poorly written"(?) applications that create objects ending in "/".
> 

Yes most definitely, if they are relying on these semantics. Personally I don't wish to argue about such naunces as our standing is already explained on why we don't need to do it. 

If there is a big enough usecase in future we may entertain it but right now we shall rest this case for now.

> With some effort I can avoid copying these into minio, or using my own encoding on top of it.
> 
> > if support for // is a hard requirement then you should look for alternatives to MinIO.
> 
> Support for trailing slash is actually the more important one to me, but I assume the answer is the same.
> 
> I at least suggest documenting special semantics regarding forward slashes in what is described as an "object store."

I don't think this needs such special attention, as these are not really at scale applications which require this. 

I know you beg to differ, but we agree to disagree here unfortunately.
