### ISSUE TITLE
Browser "shareObject": missing policy check for auth/anon user

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#9590]
While reviewing the code, I noticed there are no policy checks for authorized users.

#### For authorized user:
We should only allow the authorized (logged in with valid credentials) user to share an object in a bucket, if his/her **user policy** (not bucket policy) has `"GetObject"` action. Otherwise, sharing should be rejected.
#### For anonymous user:
We should allow anonymous user to share object if and only if the involved bucket's policy has `"GetObject"` action. Otherwise, sharing should be rejected.

## Current Behavior
We don't check the user/bucket policies if an authorized/anonymous user is qualified to share an object. Because of that, we don't catch the permission problem until the generated URL is shared and URL fails with `"AccessDenied"`"
```
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied.</Message>
    <Key>frog5.1MB.png</Key>
    <BucketName>ersan</BucketName>
    <Resource>/ersan/frog5.1MB.png</Resource>
    <Region>us-east-1</Region>
    <RequestId>160E89685DC413A7</RequestId>
    <HostId>4c2e1c3d-fcab-414a-8414-0a164015471d</HostId>
</Error>
```

## Possible Solution
Add proper policy checks in the code for shareObject(../browser/app/js/objects/action.js:223) functionality.

## Steps to Reproduce (for bugs)
1. Start MinIO server (fs) and create a bucket with `public`
2. Create a user with a policy which doesn't have `"GetObject"` action
3. Login as the created user and choose share object option from the ellipsis menu
4. Copy the successfully created URL
5. Paste it on a browser in incognito 
6. "AccessDenied" will be returned instead of the shared object.

## Regression
No

## Your Environment
MinIO server (fs), built from the top of the tree

**Comment by harshavardhana** [comment]
Sharing an object doesn't need further validation of policies, sharing an object inherits the permission of the bucket from which the content is being shared.

If it fails, so be it we don't need to disallow creating share object. Because there is no clear way to tell what is the current state of policies on a server by making disconnected calls from the browser as proposed here.

It may be possible to add a check to verify if sharing is allowed to report error and fail appropriately rather than sharing the URL and failing later.

This needs to be done on the call where the presigned URL is being generated.
