### ISSUE TITLE
Explore alternatives to file concatenation on fs backend

### ISSUE THREAD

**Issue by darkdragon-001** [minio/minio#9657]
**Is your feature request related to a problem? Please describe.**
Chunks are concatenated after all of them are received. Since disk speed is often the bottleneck, this doubles transfer times.

**Describe the solution you'd like**
Explore solutions which require the data to be written to disk only once.

**Describe alternatives you've considered**
Use distributed storage which stores the chunks as is and thus does not need to concatenate them.

**Additional context**
The following ideas came into my mind:
- `fallocate` + `fseek`: Allocate the whole file on disk and create handles at the corresponding offset for each chunk for write operations on supported file systems (e.g. `ext4`, `xfs`, `btrfs`).
- Search for _move append_ operation: Hardlinks and CoW behavior allows a single data block to be referenced to by many files, so it should be somehow possible to create a new file which references the existing data of the chunk files. Afterwards the chunks files (references) can be removed.

**Comment by harshavardhana** [comment]
> Use distributed storage that stores the chunks as-is and thus does not need to concatenate them.

FS model is kept as is to support importantly two important fundamental requirements 

- files/folders are kept as is i.e any future day MinIO can be removed files are still accessible in the backend without any custom migration
- support existing files

> * `fallocate` + `fseek`: Allocate the whole file on disk and create handles at the corresponding offset for each chunk for write operations on supported file systems (e.g. `ext4`, `xfs`, `btrfs`).

This is not possible because multipart sizes can vary i.e each part can be of different sizes according to AWS S3 spec. To keep a generalized approach concatenation is preferred.

> * Search for _move append_ operation: Hardlinks and CoW behavior allows a single data block to be referenced to by many files, so it should be somehow possible to create a new file that references the existing data of the chunk files. Afterward, the chunks files (references) can be removed.

- Custom formats such as COW are not possible defeats our fundamental design principle for FS mode. 
- Hardlinks are not cleanly implemented with most common requirement for FS mode to be run against NAS (NFS) mounts.
  Hardlinks are generally considered insecure and cause bunch of traversal issues that are hard to track down. 

We have explored all these options already, what we have today is the best possible implementation while keeping the compatibility etc in place.

**Comment by darkdragon-001** [comment]
@harshavardhana Thanks for your detailed explanation!

---

> Search for _move append_ operation: Hardlinks and CoW behavior allows a single data block to be referenced to by many files, so it should be somehow possible to create a new file that references the existing data of the chunk files. Afterward, the chunks files (references) can be removed.

If anyone finds such an option in any file system or the kernel in general, please ping me!
