### ISSUE TITLE
manage share links in browser

### ISSUE THREAD

**Issue by ynqjwsm** [minio/minio#9916]
need to manage share links in web-ui ,just like revoke or renew the share link etc.

**Comment by harshavardhana** [comment]
You cannot revoke shared links.

Note: please use the issue template, we painstakingly write code and try to resolve all the issues reported. All we ask is use the issue template and fill with proper details. This entire issue reporting is a classic example of how not to report issues. 

I shall close this now as this issue is incomplete..
