### ISSUE TITLE
[not our bug] Minio should be able to run on a configurable context path

### ISSUE THREAD

**Issue by sumeetchhetri** [minio/minio#9946]
Currently it is not possible to run minio (standalone or behind proxy) on a different context path other than / (/minio).
This is required in multiple situations, for eg behind a single public facing ip address (behind a firewall) and a proxy server routing traffic to several applications using different context paths where routing to minio on / would not be possible, also adding multiple bucket routes in the proxy also is just a hack, so why not handle it in minio itself.

**Comment by vadmeste** [comment]
@sumeetchhetri do you want to route S3 requests ? that's not possible because it will break S3 signature calculation

**Comment by sumeetchhetri** [comment]
Nope, not s3, generally minio should be able to run on configurable context paths instead of the current /minio.

**Comment by harshavardhana** [comment]
That is a design choice for us, we cannot allow such configuration. 

We have explained why this is not necessary for us and why it creates confusion, complications in terms of documentation and overall expected behavior in past issues.

/minio is a reserved endpoint by design and cannot be allowed to be configurable. It is a niche usecase we are not interested in. 

You may fork MinIO and make these changes in your fork.
