### ISSUE TITLE
Security vulnerability which disclose users with valid Access Key

### ISSUE THREAD

**Issue by MortusKill** [minio/minio#9973]
Hello Minio team,
I want to inform you about vulnerability in Minio, which I discovered during an internal pentest.

**Description:**
A remote unauthenticated attacker can use brute force to identify users with valid Access Key without knowing Secret Key.

**Step to reproduce**
1. Enter valid Access Key + wrong Security Key, you will see message - Authentication failed, check your access credentials.
![Valid_Access_Key](https://user-images.githubusercontent.com/41238315/86519681-c24bf480-be45-11ea-8386-26d1be581a27.PNG)

2. Enter invalid Access Key + any Security Key, you will see message - The access key ID you provided does not exist in our records.
![InValid_Access_Key](https://user-images.githubusercontent.com/41238315/86519682-ca0b9900-be45-11ea-9a61-2403acee68f8.PNG)

**Impact**
Attacker can first enumerate a valid users with brute force Access Key and after that start to brute force Secret Key for found users. This vulnerability makes brute force attack much easier for the attacker and is a threat to Minio user accounts.

**Mitigation**
If the user entered the wrong Access Key, show him a message similar to entering the correct Access Key + wrong Security Key (Authentication failed, check your access credentials). 
No need to show the user different error messages when entering the wrong Access Key.

**Comment by harshavardhana** [comment]
This is a default access secret key, you need to change it @MortusKill - this is not a vulnerability.

**Comment by harshavardhana** [comment]
Default access key / secret key i.e `minioadmin/minioadmin` needs to be changed @MortusKill the message printed on the screen

> Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'"

Also access key is public information there is no point in hiding it, its the secret key that is used for signature calculation. So I don't see what point you are trying to make here.

For me, it looks like not a security issue from any angle. Brute force can be applied to anything, in reality, all you can do is choose sufficient entropy for your access / secret key - these are the best practices you need to follow for anything in reality that requires authentication.

**Comment by harshavardhana** [comment]
> 2\. Enter invalid Access Key + any Security Key, you will see the message - The access key ID you provided does not exist in our records.

This doesn't mean that your secret key is correct @MortusKill it only shows that access key id doesn't exist. You cannot deduce the secret key from this. 

> 1. Enter valid Access Key + wrong Security Key, you will see the message - Authentication failed, check your access credentials.

This means that the secret key is wrong doesn't mean either that you can decide the secret key from this. 

> Attacker can first enumerate a valid users with brute force Access Key and after that start to brute force Secret Key for found users. This vulnerability makes brute force attack much easier for the attacker and is a threat to Minio user accounts.

It is not possible with high entropy if you choose a character length of 20+ with different combinations of ASCII characters

20 characters’ long access/secret made up of ASCII symbols (lower case, upper case, digits, special characters) is as strong as today’s encryption keys. Which means, it is “cryptographically secure” and it doesn’t make sense to go any further.

https://en.m.wikipedia.org/wiki/Password_strength

So brute-force is a bit of a far stretched claim here because they are as good as your password length. 

> In December, 2012, William Cheswick wrote an article published in ACM magazine that included the mathematical possibilities of how easy or difficult it would be to break passwords that are constructed using the commonly recommended, and sometimes followed, standards of today. In his article, William showed that a standard eight character alpha-numeric password could withstand a brute force attack of ten million attempts per second, and remain unbroken for 252 days. Ten million attempts each second is the acceptable rate of attempts using a multi-core system that most users would have access to. A much greater degree of attempts, at the rate of 7 billion per second, could also be achieved when using modern GPUs. At this rate, the same 8 character full alpha-numeric password could be broken in approximately 0.36 days (i.e. 9 hours). Increasing the password complexity to a 13 character full alpha-numeric password increases the time needed to crack it to more than 900,000 years at 7 billion attempts per second. This is, of course, assuming the password does not use a common word that a dictionary attack could break much sooner. Using a password of this strength reduces the obligation to change it as often as many organizations require, including the U.S. Government, as it could not be reasonably broken in such a short period of time.

You can see that choosing higher values will take a really really long time, each bit adds a power of 2 complexity to attack surface. With sufficient best practices, all of this can be handled which you need to do as a user of the software. 

The security vulnerability is only when we are exposing something sensitive which leads to either a DOS attack on the server or some form of information stealing. You have not demonstrated anything of this nature so this issue should be closed.

**Comment by kannappanr** [comment]
Also, AWS s3 returns

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>Correct_Access_Key_Id</AWSAccessKeyId><StringToSign>
``` 
if Access Key is correct but secret key is wrong.

It returns
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>abcde</AWSAccessKeyId><RequestId>9JEV1H6G</RequestId><HostId>YLcB3wyvUuxcc=</HostId></Error>
```
